/*
 Adform.RMB.js, version 2.1.75223

 Copyright Adform
 http://www.adform.com

 Date: 2014-05-20
*/
(function(a,d,c){function l(w,g){w.super_=g;o.prototype=g.prototype;w.prototype=new o;w.prototype.constructor=w}function o(){}function q(w,g){for(var b in g)g.hasOwnProperty(b)&&(w[b]=g[b]);return w}function j(w,g){return(g=g||c)&&g.getElementById&&g.getElementById(w)}function t(w,g){var b=!g?c:w.substr?j(w):w;return b?b.getElementsByTagName(g||w):[]}function s(w,g){return~(" "+w.className+" ").indexOf(" "+g+" ")}function b(w,g){s(w,g)&&(w.className=(" "+w.className+" ").replace(" "+g+" "," ").slice(1,
-1),b(w,g))}function h(w){var g=w.offsetTop,b=w.offsetLeft,i,a=k.curCSS,n="static"!=a(w,"position");g||(g=(parseFloat(a(w,"marginTop"))||0)+(n?parseFloat(a(w,"top"))||0:0));b||(b=(parseFloat(a(w,"marginLeft"))||0)+(n?parseFloat(a(w,"left"))||0:0));n&&w.getBoundingClientRect&&(i=k.offset(w,!0));!g&&i&&(g=i.top);!b&&i&&(b=i.left);return{top:g,left:b}}function e(w){var g={relativeX:w[A[0]],relativeY:w[A[1]]};if(null==w.pageX&&null!=w.clientX){var b=c.documentElement,i=c.body;g.pageX=w.clientX+(b&&b.scrollLeft||
i.scrollLeft||0);g.pageY=w.clientY+(b&&b.scrollTop||i.scrollTop||0)}else g.pageX=w.pageX,g.pageY=w.pageY;return g}function f(w,g){if(!(w=w.parentNode))return!1;var b=w.ownerDocument,i=b.body,a=k.curCSS,n;g&&(g+=1);if(d.$sf)return!0;if(k.isIE&&(8>b.documentMode||"BackCompat"==b.compatMode))return!1;for(;w&&w!=i;){if("hidden"==a(w,"overflow"))return!1;if("fixed"==a(w,"position"))break;else if(g&&(n=parseInt(a(w,"z-index"),10))&&n<g)return!1;w=w.parentNode}return!0}function m(){for(var w=0,b=[];w<R.length;w++)"complete"!=
R[w].document.readyState&&b.push(R[w]);if(!(R=b).length||3E4<(new Date).getTime()-U){aa=clearInterval(aa);for(w=0;w<g.length;w++)g[w]();g=[];R=[]}}function v(w,g){var b=w.x+w.width,i=w.y+w.height,a=g.x+g.width,n=g.y+g.height,h=Math.max(w.x,g.x),J=Math.max(w.y,g.y),b=Math.min(b,a)-h,i=Math.min(i,n)-J;return 0<b&&0<i?{x:h,y:J,width:b,height:i}:{x:0,y:0,width:0,height:0}}function C(w,g,b,a){var n=function(g){a&&a.apply(g,arguments)},h=t(b,"head"),h=h&&h[0];if(!h)try{throw Error("Can't find head tag.");
}catch(J){n(J)}var e=g.src||g.href,r=e.replace(/[^\da-z_-]/gi,"_"),aa=b.adformId||k.gid("doc_"),c=aa+"|"+r,F=i[c],r=k.byTag(b,w),p=0,f=r.length;b.adformId=b.adformId||aa;if(F)F.loaded?n():F.callbacks.push(n);else{for(;p<f;++p)if(r[p].src==e||r[p].href==e){n();return}i[c]=F={doc:b,src:e,callbacks:[n]};var D=b.createElement(w),d;q(D,g);a&&(d=function(g){D.onload=D.onreadystatechange=D.onerror=null;g?i[c]=null:F.loaded=1;var w=F.callbacks;p=0;for(f=w.length;p<f;++p)w[p](g)},D.onload=function(){d()},
D.onreadystatechange=function(){"complete"==D.readyState&&d()},D.onerror=function(){try{throw Error("Failed to load script: "+e);}catch(g){d(g)}});setTimeout(function(){h.insertBefore(D,h.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var z=a.RMB,k=z.lib||(z.lib={});a.lib||(a.lib=k);k.inherit=l;k.define=function(g,b,i){i&&l(g,b);i(g,g.prototype)};k.gid=function(g){var b=+new Date;return(g||
"")+(b+b*~~(Math.random()*1E4)).toString(36)};k.byId=j;k.byTag=t;k.bind=function(g,b){return function(){return b.apply(g,arguments)}};k.extend=q;k.isMouseLeave=function(g,b){if(!g||g.type!="mouseout")return true;for(var i=g.relatedTarget||g.toElement,a,n=b.length;i;){for(a=0;a<n;a++)if(b[a]==i)return false;i=i.parentNode}return true};k.singleCall=function(g){function b(){h=false;var g=a,w=i,J=n;i=a=n=null;g&&g.apply(w,J)}var i,a,n,h;return function(J,e){i=J;a=e;n=O.call(arguments,2);if(e&&!h)h=setTimeout(b,
g);else if(!e&&h){clearTimeout(h);h=false}}};k.onload=function(w,b){try{do{if(w[J])break;w[J]=true;if(w.document.readyState!="complete"){R.push(w);if(!aa){U=(new Date).getTime();aa=setInterval(m,200)}}}while(w!=w.parent&&(w=w.parent))}catch(i){}aa?g.push(b):setTimeout(b,0)};k.overlap=v;k.overlapElem=function(g,b){var i=k.offset(g),a=k.offset(b);return v({x:i.left,y:i.top,width:g.offsetWidth,height:g.offsetHeight},{x:a.left,y:a.top,width:b.offsetWidth,height:b.offsetHeight})};k.hasClass=s;k.addClass=
function(g,b){if(!s(g,b))g.className=g.className+(" "+b)};k.removeClass=b;k.loadScript=function(g,b,i){C("script",{src:b,type:"text/javascript"},g,i)};k.loadCSS=function(g,b){C("link",{href:b,type:"text/css",rel:"stylesheet"},g)};k.navigator=d.navigator;k.isTMX=function(g){try{var b=g.document,i=b&&b.body;return i&&s(i,"tmx")}catch(a){}return false};k.isolate=function(g,b){var i=g.__adform_isolate;if(!i){var a=g.document,i=t(a,"head")[0],a=a.createElement("script");a.type="text/javascript";a.text=
'function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';i.insertBefore(a,i.firstChild);i.removeChild(a);i=g.__adform_isolate}i?i(b):(new Function("window","("+b+")(window)"))(g)};var O=Array.prototype.slice;k.addEvent=function(g,b,i){return g[K]?g[K](b,i,false):g[G]?g[G]("on"+b,i):false};k.removeEvent=function(g,b,i){return g[M]?g[M](b,i,false):g[H]?g[H]("on"+b,i):false};var K="addEventListener",M="removeEventListener",G="attachEvent",H="detachEvent",x=/([A-Z])/g,N=/^-?\d+(?:px)?$/i,
V=/^-?\d/,a=c.defaultView;k.curCSS=a&&a.getComputedStyle?function(g,b){var i=g.ownerDocument.defaultView;if(i&&(i=i.getComputedStyle(g,null)))return i.getPropertyValue(b.replace(x,"-$1").toLowerCase())||g.style[b]}:c.documentElement.currentStyle&&function(g,b){var i,a,n,h=g.currentStyle&&g.currentStyle[b];if(!N.test(h)&&V.test(h)){i=(n=g.style).left;if(a=g.runtimeStyle&&g.runtimeStyle.left)g.runtimeStyle.left=g.currentStyle.left;n.left=b==="fontSize"?"1em":h||0;h=n.pixelLeft+"px";n.left=i;if(a)g.runtimeStyle.left=
a}return h===""?"auto":h};var Y=function(){function g(){return g}var b=c.body,i=c.createElement("div"),a;a=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();i.innerHTML='<div style="'+a+'visibility:hidden"><div style="'+a+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+a+'"><div style="'+a+'position:fixed;top:20px;"></div></div><div style="'+a+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+
a+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';b.insertBefore(i=i.firstChild,b.firstChild);a=i.childNodes;g.dnab=a[0].firstChild.offsetTop!==5;g.sfp=a[1].firstChild.offsetTop===20;g.sbfonv=a[2].firstChild.offsetTop===-5;g.dabftac=t(i,"td").offsetTop===5;b.removeChild(i);b=i=a=null;return Y=g},S=/^t(?:able|d|h)$/i;k.offsetFromWindow=function(g){var b,i,a,n;i=g&&g.ownerDocument;if(!i)return null;a=i.documentElement;if("getBoundingClientRect"in a){try{b=g.getBoundingClientRect();
n=a.getBoundingClientRect()}catch(J){}if(!b)return{top:0,left:0};if(n.left>0||n.top>0){b.top=b.top-n.top;b.left=b.left-n.left}return{top:b.top,left:b.left}}b=i.defaultView||i.parentWindow;n=i.body;if(g===i.body)return h(g);g=k.offset(g);i=b&&b.pageYOffset||a.scrollTop||n.scrollTop;a=b&&b.pageXOffset||a.scrollLeft||n.scrollLeft;g.top=g.top-i;g.left=g.left-a;return g};k.offset="getBoundingClientRect"in c.documentElement?function(g,b){var i,a=g&&g.ownerDocument;if(!a)return null;if(!b&&g===a.body)return h(g);
try{i=g.getBoundingClientRect()}catch(n){}if(!i)return{top:0,left:0};var J=a.body,a=a.documentElement;return{top:i.top+(a.scrollTop||J.scrollTop)-(a.clientTop||J.clientTop||0),left:i.left+(a.scrollLeft||J.scrollLeft)-(a.clientLeft||J.clientLeft||0)}}:function(g){var b=g&&g.ownerDocument;if(!b)return null;if(g===b.body)return h(g);var i,a=g.offsetParent,n=b.documentElement,J=b.body;i=(b=b.defaultView)?b.getComputedStyle(g,null):g.currentStyle;for(var e=g.offsetTop,r=g.offsetLeft,c=Y();(g=g.parentNode)&&
g!==J&&g!==n;){if(c.sfp&&i.position==="fixed")break;i=b?b.getComputedStyle(g,null):g.currentStyle;e=e-g.scrollTop;r=r-g.scrollLeft;if(g===a){e=e+g.offsetTop;r=r+g.offsetLeft;if(c.dnab&&(!c.dabftac||!S.test(g.nodeName))){e=e+(parseFloat(i.borderTopWidth)||0);r=r+(parseFloat(i.borderLeftWidth)||0)}a=g.offsetParent}if(c.sbfonv&&i.overflow!=="visible"){e=e+(parseFloat(i.borderTopWidth)||0);r=r+(parseFloat(i.borderLeftWidth)||0)}}if(i.position==="relative"||i.position==="static"){e=e+J.offsetTop;r=r+J.offsetLeft}if(c.sfp&&
i.position==="fixed"){e=e+Math.max(n.scrollTop,J.scrollTop);r=r+Math.max(n.scrollLeft,J.scrollLeft)}return{top:e,left:r}};k.client=function(g){var b,i,a,n,g=g.ownerDocument||g;i=g.defaultView||g.parentWindow;a=g.documentElement;n=g.body;if(i.innerWidth){g=i.innerWidth;b=i.innerHeight}else if(a){g=a.clientWidth;b=a.clientHeight;if(!g||n.clientHeight!=n.offsetHeight){g=Math.min(g||123456789,n.clientWidth||123456789);b=Math.min(b||123456789,n.clientHeight||123456789)}}else{g=n.clientWidth;b=n.clientHeight}return{left:i&&
i.pageXOffset||a&&a.scrollLeft||n&&n.scrollLeft||0,top:i&&i.pageYOffset||a&&a.scrollTop||n&&n.scrollTop||0,width:g,height:b}};k.isArray=Array.isArray||function(g){return Object.prototype.toString.call(g)=="[object Array]"};var A=[["offsetX","offsetY"],["layerX","layerY"]];k.getMousePos=function(g){for(var b;b=A.shift();)if(typeof g[b[0]]!="undefined"){A=b;break}b||(A=["x","y"]);k.getMousePos=e;return e(g)};var T=c.createElement("div");k.html=function(g,b){var i=!b&&T||b.createElement("div");i.innerHTML=
g;return i.firstChild&&i.removeChild(i.firstChild)};var a=k.navigator,X=a.vendor,a=a.userAgent,P=/Apple Computer/i.test(X),z=/Google/i.test(X),F=k.isIPad=/iPad/i.test(a),y=k.isIPhone=/iPhone/i.test(a),D=k.isIOS=F||y,E=k.isTouch="ontouchstart"in c.documentElement||"ontouchstart"in d,F=k.isOrientation="orientation"in d,y=k.isAndroid=!D&&(/Android/i.test(a)||E&&!/series60|symbian|windows ce|blackberry/i.test(a));k.isAndroidApp=y&&!/^(?:Opera|Mozilla)/i.test(a);var n;k.isIOSF=D&&(n=/\sos\s(\d+)_\d+/i.exec(a))&&
(n=4<n[1]>>0);var r=k.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||E;n=k.isIE=/msie|Trident/i.test(a);E=k.isFF=/Firefox[\/.]+[^\s]/i.test(a);k.isMACOS=/Mac OS X/i.test(a);k.isWinPhone=n&&r&&/Phone/gi.test(a);var r=k.isOpera=/Opera/i.test(a),p=k.isOperaMobile=/Opera\s(?!Mini)/i.test(a),B=k.isOperaMini=/Opera\sMini/i.test(a),X=k.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(X),D=k.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(D?P:z),P=k.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&
P,z=k.isInternet=y&&!D&&F&&/Safari\/[\.\d]+$/i.test(a)&&z;k.isAfmaSDK=/afma-sdk/i.test(a);var I=n?"msie":E?"firefox":p?"operaMobile":B?"operaMini":r?"opera":X?"operaWebKit":D?"chrome":P?"safari":z?"internet":!1;k.browser=function(){return I};if(k.isIE&&("Microsoft Internet Explorer"==k.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a)))k.ieVersion=parseFloat(RegExp.$1);k.testPlace=k.isIE&&8>k.ieVersion?function(){return false}:f;k.isSafari&&(k.safariVersion=parseFloat(/Version.([\d.]+)/.exec(a)[1]));
var R=[],g=[],J="__adform_onload",aa,U,i={}})(Adform=window.Adform||{},window,document);
(function(a){function d(){var c=a.Data;if(c&&(delete a.Data,c.videoSources&&c.streamingVideo&&!(0>c.clicktags.indexOf("&detectBW=true")))){for(var d=c.videoSources,o=d[0].file.replace(/^[^:]+:\/\/[^\/]+|[^\/]+$/g,""),q={},j,t=0,s=d.length,b,h,e;t<s;t++)if(d[t]&&(b=d[t].file)&&0<=b.indexOf(o)&&(h=b.match(/([^\/]+?)(\d+)\.f[l4]v$/))){e=q[h[1]]||[];e.push(h[2]);if(!j||q[j].length<=e.length)j=h[1];q[h[1]]=e}j&&(q[j].sort(function(b,a){return b-a}),c.clicktags+="&streamBaseName="+encodeURIComponent(j)+
"&streamBitrates="+q[j].join(","))}}a.BWDetect=d;d()})(Adform=window.Adform||{},window,document);
(function(a){function d(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=d;var c=Array.prototype.slice,a=d.prototype;a.emit=function(a){var d=this._events,q=!1,j=arguments;if(d&&(d=d[a]))if("function"==typeof d){switch(j.length){case 1:d.call(this);break;case 2:d.call(this,j[1]);break;case 3:d.call(this,j[1],j[2]);break;case 4:d.call(this,j[1],j[2],j[3]);break;default:d.apply(this,c.call(j,1))}q=!0}else if(d.length){for(var j=c.call(j,1),d=d.slice(),q=0,t=d.length;q<t;q++)d[q].apply(this,j);q=!0}else delete this._events[a];
return q};a.on=function(a,c){this._events||(this._events={});this.emit("newListener",a,c);var d=this._events;d[a]?"function"==typeof d[a]?d[a]=[d[a],c]:d[a].push(c):d[a]=c;return this};a.once=function(a,c){var d=c._once;d?d._times++:(d=c._once=function(){this.off(a,d);1>--d._times&&delete c._once;return c.apply(this,arguments)},d._times=1);return this.on(a,d)};a.off=function(a,c){if(!this._events||!this._events[a])return this;var d=this._events,j=d[a];if(j==c)return delete d[a],this;c&&c._once&&this.off(c._once);
if("function"==typeof j)return this;if(2>j.length&&j[0]==c)return delete d[a],this;for(var t=0,s=j.length,b=[];t<s;t++)j[t]!=c&&b.push(j[t]);b.length!=s&&(b.length?d[a]=b:delete d[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var c=this._events;c[a]?"function"==typeof c[a]&&(c[a]=[c[a]]):c[a]=[];return c[a]}})(Adform=window.Adform||{});
(function(a,d){function c(){c.super_.call(this);this._previous={};this._attributes={};this._sets=[]}a.RMB=a.RMB||{};var l=a.RMB,o=l.lib;l.StateEmitter=c;o.inherit(c,l.EventEmitter);l=c.prototype;l.set=function(a,c){var d=this._sets,s=this._attributes;if("object"==typeof a)for(var b in a)a.hasOwnProperty(b)&&(s[b]=a[b],d.push(b));else s[a]=c,d.push(a);return this.commit()};l.get=function(a){var c=this._attributes;return a?c[a]:c};l.attr=function(a,c){return"object"==typeof a||1<arguments.length?this.set(a,
c):this.get(a)};l.previous=function(a){var c=this._previous;return a?c[a]:c};l.changes=function(a){var c=this._attributes,l=this._previous,s=this._sets;if(a)return c[a]!==l[a]?c[a]:d;for(var b={},h=0;a=s[h];h++)c[a]!==l[a]&&(b[a]=c[a]);return b};l.commit=function(){var a=this._sets;if(this._commit||!a.length)return this;this._commit=!0;for(var c=this._attributes,d=this._previous,s=!1,b=this._changes||(this._changes={}),h=0,e;e=a[h];h++)c[e]!==d[e]&&c[e]!==b[e]&&(b[e]=c[e],s=!0,this.emit("change:"+
e,c[e],d[e],e));if(s){b={};s=!1;for(e in c)c[e]!==d[e]&&(b[e]=c[e],s=!0);s&&this.emit("change",b)}this._commit=!1;a.splice(0,h);if(a.length)return this.commit();this._changes=null;for(e in c)c.hasOwnProperty(e)&&(d[e]=c[e]);return this};l.onchange=function(a,c){return c?this.on("change:"+a,c):this.on("change",a)}})(Adform=window.Adform||{});
(function(a){function d(a){j.push(this);this._doc=a;this._events={};this.dispatchHover=q.bind(this,c)}function c(){for(var a=d._hoverTarget,c=[],e=d._hoverChain,f=s+"hover-",m;a&&"undefined"!=(m=typeof a.className);)"string"==m&&0<=a.className.indexOf(f)&&c.unshift(a),a=a.parentNode;var v=Math.max(c.length,e.length),a=RegExp(f+"\\S+","g");m=[];for(v-=1;0<=v&&e[v]!=c[v];v--){if(e[v])for(var j=l(e[v].className,f,a),o=0;o<j.length;o++)j[o].call(e[v],"hoverout",e[v]);if(c[v]){j=l(c[v].className,f,a);
for(o=0;o<j.length;o++)m.push([j[o],c[v]])}}if(m.length)for(v=0;v<m.length;v++)m[v][0].call(m[v][1],"hoverin",m[v][1]);d._hoverChain=c}function l(a,c,e){a=a.match(e);e=[];if(a){a=("x|"+a.join("|")).split("|"+c).slice(1);for(c=0;c<a.length;c++)t[a[c]]&&e.push(t[a[c]])}return e}function o(a){for(var c=0;c<j.length;c++)if(j[c]._doc==a)return j[c]}a.RMB=a.RMB||{};var a=a.RMB,q=a.lib;a.DOMEvents=d;var j=[],t={},s="adform-domevents-";d.destroy=function(a){var c;if(a)(c=o(a))&&c.destroy();else for(;j.length;)j[0].destroy()};
d.on=function(a,c,e){var f=a.ownerDocument;(d.find(f)||new d(f)).on(a,c,e);return this};d.off=function(a,c,e){var f=d.find(a.ownerDocument);f&&f.off(a,c,e);return this};d.find=o;d.dispatchHover=c;d.dispatchClick=function(a,c){for(var e=s+"click-",d=[],m;a&&"undefined"!=(m=typeof a.className);)"string"==m&&0<=a.className.indexOf(e)&&d.unshift(a),a=a.parentNode;m=RegExp(e+"\\S+","g");for(var j=d.length-1;0<=j;j--)for(var o=l(d[j].className,e,m),q=0;q<o.length;q++)o[q].call(d[j],"click",d[j],c)};d._hoverChain=
[];d._hoverTarget=null;a=d.prototype;a.on=function(a,c,e){var d=e._adform_dom_key;d||(d=e._adform_dom_key=q.gid());d in t||(t[d]=e);e=s+c+"-"+d;0>a.className.indexOf(e)&&(a.className+=" "+e,this.setup(c))};a.off=function(a,c,e){if(e=e._adform_dom_key)a.className=a.className.replace(s+c+"-"+e,"")};a.destroy=function(){var a=this._events,c,e,f,m=this._doc;for(c in a)for(e in f=a[c],f)q.removeEvent(m,e,f[e]);for(a=j.length;0<a--;)if(j[a]==this){j.splice(a,1);break}a=d._hoverChain;a[0]&&a[0].ownerDocument==
m&&(d._hoverChain=[],d._hoverTarget=null);this._doc=this._events=null};a.setup=function(a){if(!this._events[a]){this._events[a]={};var c=this._doc,e=c.defaultView||c.parentWindow,f,m;"hover"==a?(c.addEventListener?(f=function(a){d._hoverTarget!=a.target&&(d._hoverTarget=a.target,d.dispatchHover())},m=function(a){d._hoverTarget!=a.relatedTarget&&(d._hoverTarget=a.relatedTarget,d.dispatchHover())}):(f=function(){e=c.defaultView||c.parentWindow;d._hoverTarget!=e.event.srcElement&&(d._hoverTarget=e.event.srcElement,
d.dispatchHover())},m=function(){e=c.defaultView||c.parentWindow;d._hoverTarget!=e.event.toElement&&(d._hoverTarget=e.event.toElement,d.dispatchHover())}),q.addEvent(c,"mouseover",this._events[a].mouseover=f),q.addEvent(c,"mouseout",this._events[a].mouseout=m),q.addEvent(c,"mousemove",this._events[a].mousemove=f),d._hoverChain=[]):"click"==a&&(f=c.addEventListener?function(a){d.dispatchClick(a.target,a)}:function(a){e=c.defaultView||c.parentWindow;a=e.event;d.dispatchClick(a.srcElement,a)},q.addEvent(c,
"mousedown",this._events[a].mousedown=f))}}})(Adform=window.Adform||{},window,document);
(function(a,d,c){function l(a,b){"string"!=typeof a&&(b=a,a="default");if(this instanceof l)this._id="adfrom-styleSheet-"+a,this._doc=b||c;else return new l(a,b)}a.RMB=a.RMB||{};a=a.RMB;a.StyleSheet=l;var o=a.lib,q,j,t,a=l.prototype;a.node=function(){var a=this._doc,b=this._id,c=o.byId(b,a);c||(c=a.createElement("style"),c.type="text/css",c.id=b,c._rules={},o.byTag(a,"head")[0].appendChild(c));if(!q&&(j=c.sheet?"sheet":"styleSheet",a=c[j]))t=a.insertRule?function(a,b,c,d){a.insertRule(b+" {"+c+"}",
d)}:function(a,b,c,d){a.addRule(b,c,d)},q=a&&a.cssRules?"cssRules":"rules";return c};a.set=function(a,b){var c=this.node(),d=c[j],f,m;try{f=c._rules,m=f[a]}catch(o){}var l=a.split(/\s*,\s*/),z,k;try{if(1<l.length)for(z=l.length-1;0<=z;--z)this.set(l[z],b);else if(m)m.style.cssText+=";"+b;else if(!d||!d[q])c.appendChild(this._doc.createTextNode(a+"{"+b+"}"));else if(b){k=d[q].length;try{t(d,a,b,k)}catch(O){setTimeout(function(){t(d,a,b,k)},0)}f&&(f[a]=d[q][k])}}catch(K){}return this};a.destroy=function(){var a=
o.byId(this._id,this._doc);a&&a.parentNode.removeChild(a);this._doc=null}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(){var a=x.bind;c.super_.call(this);this.cssQueue=[];this.id=x.gid(A);this.set({showing:!1,visible:!0}).onchange("visible",M).onchange("element",M).onchange("zIndex",o).onchange(K);this._contents={};this._pos={};this.findElement=a(this,q);this.repositionPage=a(this,z);this.repositionFloated=a(this,O);this.repositionSticky=a(this,C)}function l(a){var b,c;if(b=this._hub)c=this._hubName,b.emit("element",this,c,a)}function o(a){this.style({zIndex:a})}function q(){this._findCalls||
(this._findCalls=(new Date).getTime()+c.fTimeout);var g=x.byId(this.id,this._doc),b=this.get("frame");if(g)this.handleHover=x.bind(this,j),this.handleClick=x.bind(this,t),V.on(b||g,"hover",this.handleHover),x.addEvent(g,"mousedown",this.handleClick),g.innerHTML="",this.set("element",g),this.css(""),this.style();else if(this._findCalls>(new Date).getTime())setTimeout(this.findElement,0);else throw g=this.content(),a.Log.pushMessage(["Adbox"],"Adbox element not found",{bn:g&&g.options.bn}),Error("Adbox element not found");
}function j(a){var b=this.hovered="hoverin"==a;this.emit("hover",b,this);this.emit(a,b,this)}function t(a){this.emit("click",a||this._win.event)}function s(a){var c=this._doc;var n=this.get(),d=n.element;if(d)for(var n=d.className.match(RegExp(A+n.postype+"(-\\w+)?","g")),i=0;i<n.length;i++){var r=n[i];x.hasClass(d,r)&&x.removeClass(d,r)}d=a.from;c=a.type||(!d?"static":d.window==d?"fixed":d===c?"page":"floated");i=a.position||"";n=R.exec(i);i=I.exec(i);n=n?n[0]:X;i=i?i[0]:E;r=this.get();r.vpos=i;
r.hpos=n;r.postype=c;r.frompos=d;this.resetPosition&&this.resetPosition();b.apply(this,[c,r,a])}function b(a,b,c){var p=this,i=p._win,w=p._doc,D=b.element;D&&(x.addClass(D,A+a+"-"+b.vpos),x.addClass(D,A+a+"-"+b.hpos),x.addClass(D,A+a));p.positionType=a;if("static"==a)this.onchange("x",m).onchange("y",m).onchange("showing",m),this.resetPosition=function(){p.off("change:x",m).off("change:y",m).off("change:showing",m);p.resetPosition=null};else if("fixed"==a){var f=w.documentElement,B=w.body,y=!1,j=
!1,l=function(){if(b.fixedBounding!==false){var a=f.clientWidth||B.clientWidth,g=f.clientHeight||B.clientHeight,i=b.element,c=i.offsetWidth-b.x,i=i.offsetHeight-b.y;if(j!=a<c){a=(j=a<c)?0:"";p.style({left:a,marginLeft:a,marginRight:a})}if(y!=g<i){a=(y=g<i)?0:"";p.style({top:a,marginTop:a,marginBottom:a})}}};this.onchange("showing",l);x.addEvent(i,"resize",l);this.onchange(v);this.onchange("fixedBounding",function(a){if(a===false){a="";p.style({left:a,marginLeft:a,marginRight:a,top:a,marginTop:a,marginBottom:a})}else l()});
S&&(this.iOSFixed=function(){var a={},g=f.scrollLeft||B.scrollLeft,i=f.scrollTop||B.scrollTop,b=f.clientWidth||B.clientWidth,c=f.clientHeight||B.clientHeight;if(I=="L")a.left=g+"px";if(I=="C")a.left=g+Math.round(b/2)+"px";if(I=="R")a.right=-g+"px";if(u=="T")a.top=i+"px";if(u=="M")a.top=i+Math.round(c/2)+"px";if(u=="B")a.bottom=-i+"px";p.style(a)},x.addEvent(i,"scroll",this.iOSFixed));this.resetPosition=function(){p.off("change:showing",l).off(v);l&&x.removeEvent(i,"resize",l);p.iOSFixed&&x.removeEvent(i,
"scroll",p.iOSFixed);p.css("margin:0;left:auto;top:auto;");p.resetPosition=null}}else if("sticky"==a)this.onchange(C),this.handleResize=x.bind(this,e),x.addEvent(i,"resize",this.handleResize),x.addEvent(i,"scroll",this.handleResize),x.addEvent(i,"load",this.handleResize),this.handleResize(),setTimeout(this.handleResize,50),this.resetPosition=function(){p.off(C);if(p.handleResize){x.removeEvent(i,"resize",p.handleResize);x.removeEvent(i,"scroll",p.handleResize);x.removeEvent(i,"load",p.handleResize)}};
else if("page"==a){this.onchange(z);this.resizeDelay=x.singleCall(100);this.handleResize=x.bind(this,h);x.addEvent(i,"resize",this.handleResize);x.addEvent(i,"scroll",this.handleResize);x.addEvent(i,"load",this.handleResize);this.handleResize();var o=setInterval(this.handleResize,100);setTimeout(function(){clearInterval(o)},3E3);this.resetPosition=function(){p.off(z);if(p.handleResize){x.removeEvent(i,"resize",p.handleResize);x.removeEvent(i,"scroll",p.handleResize);x.removeEvent(i,"load",p.handleResize)}clearInterval(o)}}else if("floated"==
a)this.onchange(O),c.container!=c.from?(this.resizeDelay=x.singleCall(10),this.handleResize=x.bind(this,k),x.addEvent(i,"resize",this.handleResize),this._fromInt=setInterval(this.handleResize,500),x.onload(d,this.handleResize),setTimeout(this.handleResize,50)):setTimeout(function(){O.call(p)},0),this.resetPosition=function(){p.handleResize&&x.removeEvent(i,"resize",p.handleResize);clearInterval(p._fromInt)};else if("mobile"==a){var u=b.vpos,I=b.hpos,s,G,q,H=i.innerWidth,t=i.innerHeight,Y=H>=t,T=!1,
a=function(){p.pos.width=p.pos.height=0},R=function(){if(b.showing&&!T){s=D.getBoundingClientRect();H=i.innerWidth;t=i.innerHeight;if(Y&&H<t||!Y&&H>=t){Y=H>=t;T=true;setTimeout(function(){T=false},500)}else{Y=H>=t;var a=b.width,g=b.height,c=p._vp,d=p.pos||{},a=p._hp?H*parseFloat(a)/100:a,g=c?t*parseFloat(g)/100:g;G=(parseFloat(d.left)||0)-s.left;q=(parseFloat(d.top)||0)-s.top;var e,w;I==P?e=Math.round(G+(H-a)/2):I==X?e=Math.floor(G):I==F&&(e=Math.ceil(G+(H-a)));u==n?w=Math.round(q+(t-g)/2):u==E?w=
Math.floor(q):u==r&&(w=Math.ceil(q+(t-g)));p.setPosition(w,e,0,0,0,0,a,g)}}},N=setInterval(R,100);x.addEvent(i,"resize",R);x.addEvent(i,"scroll",R);p.onchange("showing",R).onchange("width",a).onchange("height",a);R();this.resetPosition=function(){x.removeEvent(i,"resize",R);x.removeEvent(i,"scroll",R);p.resetPosition=null;clearInterval(N)}}}function h(){this.repositionPage({showing:1})}function e(){this.repositionSticky({showing:1})}function f(a){var b=a.defaultView||a.parentWindow;b.self||(b=d);
var c=a.documentElement||a.body;this._doc=a;this._win=b;this.sheet=N("adbox",a);if(!b.__adform_adbox_init){var n=N("adbox-static",a);n.set("."+A+"hidden","visibility:hidden").set("."+A+"mobile","position:absolute").set("."+A+"static","position:relative").set("."+A+"static-L","margin:0 auto 0 0").set("."+A+"static-C","margin:0 auto").set("."+A+"static-R","margin:0 0 0 auto").set("."+A+"static-I","display:inline-block;*display:inline;zoom:1").set("."+A+"floated","position:absolute;display:block!important").set("."+
A+"page,."+A+"fixed,."+A+"sticky","position:fixed;display:block!important").set("."+A+"page-L,."+A+"fixed-L","left:0").set("."+A+"page-C,."+A+"fixed-C","left:50%").set("."+A+"page-R,."+A+"fixed-R","right:0").set("."+A+"page-T,."+A+"fixed-T","top:0").set("."+A+"page-M,."+A+"fixed-M","top:50%").set("."+A+"page-B,."+A+"fixed-B","bottom:0").set("."+A+"overlay","position:fixed;right:0;bottom:0;width:300%;height:300%").set("."+A+"overlay iframe","display:none;position:absolute;top:0;right:0;width:100%;height:100%").set("* html ."+
A+"page,* html ."+A+"fixed","position:absolute").set("* html ."+A+"fixed-L","left:expression(eval(__adform_adbox_fixedLeft(this)))").set("* html ."+A+"fixed-C","left:expression(eval(__adform_adbox_fixedCenter(this)))").set("* html ."+A+"fixed-R","left:expression(eval(__adform_adbox_fixedRight(this)))").set("* html ."+A+"fixed-T","top:expression(eval(__adform_adbox_fixedTop(this)))").set("* html ."+A+"fixed-M","top:expression(eval(__adform_adbox_fixedMiddle(this)))").set("* html ."+A+"fixed-B","top:expression(eval(__adform_adbox_fixedBottom(this)))").set("* html ."+
A+"overlay","position:absolute;top:expression(eval(__adform_adbox_fixedTop(this)));left:expression(eval(__adform_adbox_fixedLeft(this)));width:100%;height:100%");Y&&"BackCompat"==a.compatMode&&n.set("."+A+"page","position:absolute");b.__adform_adbox_fixedLeft=function(){return c.scrollLeft};b.__adform_adbox_fixedCenter=function(){return c.scrollLeft+Math.round(c.clientWidth/2)};b.__adform_adbox_fixedRight=function(a){return c.scrollLeft+c.clientWidth-a.offsetWidth};b.__adform_adbox_fixedTop=function(){return c.scrollTop};
b.__adform_adbox_fixedMiddle=function(){return c.scrollTop+Math.round(c.clientHeight/2)};b.__adform_adbox_fixedBottom=function(a){return c.scrollTop+c.clientHeight-a.offsetHeight};b.__adform_adbox_init=0}b.__adform_adbox_init++}function m(){var a=this.get();a.showing&&this.style({left:a.x+"px",top:a.y+"px"})}function v(a){var b=this.get();if(b.showing&&(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a)){var a=b.vpos,c=b.width,d=b.height,i="",r=b.y,p=b.x;b.hpos==P&&(this._hp?i+="left:"+
(50-parseFloat(c)/2)+"%;":p-=c/2);a==n&&(this._vp?i+="top:"+(50-parseFloat(d)/2)+"%;":r-=d/2);this.css(i+"margin:"+r+"px "+-p+"px "+-r+"px "+p+"px")}}function C(a){var b=this.get();if(b.showing&&(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a||"stickyOffset"in a)){var c=this._win,d=this._doc,i=b.element,e=this.from(),h=x.offsetFromWindow(e),a=b.stickyOffset||0;!0===a&&(h.top=x.offset(e).top,a=h.top);var f=this._hp,B=this._vp,k=b.x,j=b.y,m=f?i.offsetWidth:b.width||0,l=B?i.offsetHeight:
b.height||0,i=h.left,u=h.top,h=e.offsetWidth,e=e.offsetHeight,I=c.innerWidth||d.body.clientWidth,o=c.innerHeight||d.body.clientHeight,E=b.vpos,s=b.hpos,c=s==T,d=s==P,G=s==F,s=s==y,H=E==D,q=E==n,A=E==r,E=E==p;f&&(m=I*parseFloat(b.width)/100,this.style({width:m+"px"}));B&&(l=o*parseFloat(b.height)/100,this.style({height:l+"px"}));b=j+u+(H?-l:q?(e-l)/2:A?e-l:E?e:0);this.setPosition(b>a?b:a,k+i+(c?-m:d?(h-m)/2:G?h-m:s?h:0),0,0)}}function z(a){var b=this.get();if(b.showing&&(!a||"x"in a||"y"in a||"width"in
a||"height"in a||"showing"in a)){var c=this._win,d=b.vpos,i=b.hpos,e=b.x,h=b.y,f=b.element,B=this._hp,a=B?f.offsetWidth:b.width,f=this._vp?f.offsetHeight:b.height,k=i==T,m=i==P,j=i==F,l=i==y,E=d==D,I=d==n,o=d==r,s=d==p;if(this._absolute||"absolute"==x.curCSS(b.element,"position"))this._absolute||(x.removeEvent(c,"resize",this.handleResize),x.removeEvent(c,"scroll",this.handleResize)),this._absolute=!0,h=Math.round(d==n?-(f/2):0)+h,b=Math.round(i==P?-(a/2):0)+e,this.setPosition(null,null,o?0:h,j?0:
b,o?-h:0,j?-b:0);else{var i=this._doc,c=i.documentElement,G=i.body;Math.max(c&&c.clientWidth||0,G&&G.clientWidth||0);var i=c&&c.clientHeight||G&&G.clientHeight,d=Math.max(c&&c.scrollWidth||0,G&&G.scrollWidth||0),H=Math.max(c&&c.scrollLeft||0,G&&G.scrollLeft||0),c=Math.max(c&&c.scrollTop||0,G&&G.scrollTop||0);B&&this.style({width:(a=Math.round(d*parseFloat(b.width)/100))+"px"});b=-H+(k?-a:m?(d-a)/2:j?d-a:l?d:0)+e;h=-c+(E?-f:I?(i-f)/2:o?i-f:s?i:0)+h;e=this._pp||(this._pp={t:0,l:0});(e.t>-f&&e.l>-a||
h>-f&&b>-a)&&this.setPosition(h,b,0,0);e.t=h;e.l=b}}}function k(){if(this.get().showing){var a=this.from();if(a){var b=x.offset(a);b.w=a.offsetWidth;b.h=a.offsetHeight;a=this._lastFromPos;if(!a||a.left!=b.left||a.top!=b.top||a.w!=b.w||a.h!=b.h)this._lastFromPos=b,O.call(this)}}}function O(a){if(!a||"x"in a||"y"in a||"width"in a||"height"in a||"showing"in a){var b=this.get();if(b.showing){var c=this.from();if(c){var d=b.vpos,a=b.hpos,i={},e=this._hp,h=this._vp;e&&(i.width=Math.round(c.offsetWidth*
parseFloat(b.width)/100)+"px");h&&(i.height=Math.round(c.offsetHeight*parseFloat(b.height)/100)+"px");(e||h)&&this.style(i);var f=b.element,i=b.x,B=b.y,e=e?f.offsetWidth:b.width,h=h?f.offsetHeight:b.height,f=x.offset(c),b=b.element.parentNode;"static"!=x.curCSS(b,"position")&&(b=x.offset(b),f.top-=b.top,f.left-=b.left);var b=c.offsetWidth,c=c.offsetHeight,k=a==P,m=a==F,j=a==y,l=d==n,E=d==r,I=d==p,b=f.left+(a==T?-e:k?b/2:m?b-e:j?b:0),f=f.top+(d==D?-h:l?c/2:E?c-h:I?c:0),d=Math.round(d==n?-(h/2):0)+
B,a=Math.round(a==P?-(e/2):0)+i;this.setPosition(f,b,d,a)}}else this.setPosition(-3E3,-3E3,0,0)}}function K(a){if(("width"in a||"height"in a)&&"mobile"!=this.positionType){var b=this.get(),a=b.width,b=b.height,c=this._hp="string"==typeof a&&0<a.indexOf("%"),n=this._vp="string"==typeof b&&0<b.indexOf("%");this.style({width:"auto"===a?a:c?a:a+"px",height:"auto"===b?b:n?b:b+"px"})}}function M(){var a=this.get(),b=a.visible,c=this,n=a.element;if(n){var i=this._visibilityTimer;i&&(i=clearTimeout(i));var d=
function(){c._visibilityTimer=!1;var a=n.className,g=~a.indexOf(" adform-adbox-hidden");g&&b?n.className=a.replace(" adform-adbox-hidden",""):!g&&!b&&(n.className=a+" adform-adbox-hidden")};n.addEventListener?Y?d():i=setTimeout(d,b?10:100):d();this._visibilityTimer=i}this.set("showing",b&&!!a.element)}function G(a){this.emit("content:"+(a?"show":"hide"),this.get("element"),this);this.emit(a?"show":"hide")}a.RMB=a.RMB||{};var H=a.RMB,x=H.lib,N=H.StyleSheet,V=H.DOMEvents,Y=x.isIOS,S=Y&&!x.isIOSF,A=
"adform-adbox-",T="K",X="L",P="C",F="R",y="E",D="Y",E="T",n="M",r="B",p="N",B=[T,X,P,F,y,"I"],I=RegExp([D,E,n,r,p].join("|")),R=RegExp(B.join("|"));H.AdBox=c;c.LEFT_OUT=T;c.LEFT=X;c.CENTER=P;c.RIGHT=F;c.RIGHT_OUT=y;c.TOP_OUT=D;c.TOP=E;c.MIDDLE=n;c.BOTTOM=r;c.BOTTOM_OUT=p;c.INLINE="I";c.CLASS="adform-adbox";c.PREFIX=A;c.hPosRegExp=R;c.vPosRegExp=I;c.fTimeout=1E4;x.inherit(c,H.StateEmitter);c.toCustom=function(a,b,c){var d=R.exec(c),c=I.exec(c),d=d?d[0]:X,c=c?c[0]:E,i=b.width,e=b.height,h=a.width,a=
a.height,f=d==P,B=d==F,k=d==y,m=c==n,j=c==r,l=c==p;return{x:(d==T?-i:f?(h-i)/2:B?h-i:k?h:0)+b.x,y:(c==D?-e:m?(a-e)/2:j?a-e:l?a:0)+b.y}};H=c.prototype;H.css=function(a,b){if(this.sheet){if(this.cssQueue){var c=this.cssQueue,n=0,i=c.length;for(this.cssQueue=null;n<i;n+=2)this.css(c[n],c[n+1])}this.sheet.set("#"+this.id+(b?" "+a:""),b||a)}else this.cssQueue.push(a,b);return this};H.content=function(a,b,c){!c&&"string"==typeof b&&(c=b,b=!1);c=c||"main";a&&(this._contents[c]=a,a.bind(this),b&&(a=a.data,
this.set({width:a.width,height:a.height})));return this._contents[c]};H.setPosition=function(a,b,c,n,i,d,e,r){if(this.get("element")){var a={top:a,left:b,marginTop:c,marginRight:d,marginBottom:i,marginLeft:n,width:e,height:r},b=this.pos||{},c=!1,n={},p;for(p in a)a[p]!=b[p]&&(c=!0,n[p]=a[p]+"px");c&&(this.pos=a,this.style(n))}};H.from=function(){var a=this.get("frompos");if("string"==typeof a&&(a=x.byId(a,this._doc))){if("OBJECT"==a.nodeName&&30>a.offsetHeight){var b=x.byTag(a,"embed")[0];b&&20<b.offsetHeight&&
(a=b)}this.set("frompos",a)}return!a||a.attr&&!(a=a.get("element"))?void 0:a};H.style=function(a){var b=this.get("element");b?(this._styles&&(x.extend(b.style,this._styles),this._styles=null),a&&x.extend(b.style,a)):this._styles=x.extend(this._styles||{},a);return this};H.reset=s;H.destroy=function(){var a=this.get("element"),b=this.get("frame");if(a){this.emit("content:destroy",a,this);this.clear();this._contents=null;var c=this._win,n=this._doc;V.off(b||a,"hover",this.handleHover);x.removeEvent(a,
"mousedown",this.handleClick);this.resetPosition&&this.resetPosition();var i,d;(i=this.handleResize)&&x.removeEvent(c,"resize",i);(d=this._fromInt)&&clearInterval(d);--c.__adform_adbox_init||(N("adbox-static",n).destroy(),this.sheet.destroy(),c.__adform_adbox_fixedLeft=c.__adform_adbox_fixedCenter=c.__adform_adbox_fixedRight=c.__adform_adbox_fixedTop=c.__adform_adbox_fixedMiddle=c.__adform_adbox_fixedBottom=null);this.sheet=null;this._changes={};this._previous={};this._attributes={};a.parentNode&&
a.parentNode.removeChild(a)}};H.draw=function(a,b){var c,n,i,b=b||{};if(c=this._hub)n=this._hubName,c.emit("draw",this,n,b);this.set("frame",b.frame);c=b.container;n=b.before;i=b.from;a=c&&c.ownerDocument||n&&n.ownerDocument||i&&(i.ownerDocument||i._doc||(i.defaultView||i.parentWindow||i).document)||a;f.call(this,a);s.call(this,b);c=b;n=c.from;i=c.container;var d=c.before,e=this.get(),p=e.postype,r=this._doc,p='<div id="'+this.id+'" class="adform-adbox '+(e.visible?"":A+"hidden ")+A+p+" "+A+p+"-"+
e.vpos+" "+A+p+"-"+e.hpos+'">AdBox</div>';if(!n&&!d&&!i)r.write(p);else{try{r.body||r.write("<html><body></body></html>")}catch(h){}if(r.body.insertAdjacentHTML&&x.isIE){var F="afterBegin";n?(i||(i=r.body),"end"==d&&(F="beforeEnd")):d&&(F="beforeBegin",i=d);try{i.insertAdjacentHTML(F,p)}catch(D){r.write(p)}}else n?(i||(i=r.body),d=null):d&&(i=d.parentNode),i.insertBefore(x.html(p,r),d||i.firstChild)}this.set({x:c.x||e.x||0,y:c.y||e.y||0});this.onchange("showing",G);this.findElement();return this};
H.pull=function(a,b){var c=this.get();if(a in c)b.call(this,c[a]);else this.once("change:"+a,b);return this};H.publish=function(a,b){this._hubName=a;this._hub=b;this.pull("element",l);return this}})(Adform=window.Adform||{},window,document);
(function(a){var d,c;function l(a){var h=q?d:j?c:{},e;for(e in a)a.hasOwnProperty(e)&&h[e]&&(s[h[e]]=a[e])}if(!a.IframeApiWrapper){var o=new a.RMB.EventEmitter,q,j,t,s;t={over:!1,pushdown:!1};d={width:"width",height:"height",left:"offsetLeft",right:"offsetRight",top:"offsetTop",bottom:"offsetBottom"};c={width:"width",height:"height",left:"l",right:"r",top:"t",bottom:"b",pushdown:"push"};s={};o.support=t;o.init=function(a){j=a.$sf&&a.$sf.ext;if(a.inDapMgrIf||a.inDapIF||a.inFIF)try{q=a.$WLXRmAd||a.parent.$WLXRmAd}catch(c){}o.msAPI=
q;o.sfAPI=j;o.hasAPI=!(!q&&!j);q?(t.over=!0,t.pushdown=!1):j&&(a=j.supports(),t.over="1"===a["exp-ovr"],t.pushdown="1"===a["exp-push"])};o.register=function(a){l(a);q?q.init(s):j&&j.register(a.width,a.height,function(a){o.emit(a)})};o.update=l;o.expand=function(a){if(a)o.once("expanded",a);q?(q.expand(),o.emit("expanded")):j&&j.expand(s)};o.collapse=function(a){if(a)o.once("collapsed",a);q?(q.collapse(),o.emit("collapsed")):j.collapse()};a.IframeApiWrapper=o}})(Adform=window.Adform||{});
(function(a,d,c){function l(i){var g=v.extend({},r),F=v.extend({},r),f=v.extend({},p),m=v.extend({},p),y=v.extend({},B),l=v.extend({},I),E=v.extend({},I),o={},u=v.extend({},R),P;try{P=d.MESSENGER||-1<location.host.toLowerCase().indexOf("rad.msn.com")}catch(aa){}u.messenger=P;u.iab=d.inDapMgrIf||d.inDapIF||d.inFIF;u.iframeAPI=a.IframeApiWrapper;u.iframeAPI.init(d);var J=!i.flashvars;u.backCompat=!J;var U=i.clicktags=h(i.clicktags),ha=U.backupClickUrl,Bb=[0,"MC","TC","TL","TR","BL","BR","ML","MR","BC"],
oa,ea,ia;for(ia in i){var Q=n[ia]||ia,L=i[ia],Fa;switch(Q){case "bsrc":!y.poster&&(y.poster=L);case "src":var ua=b(L,U);oa=L.match(X)?g:L.match(T)?l:f;oa.src=L;oa.assetId=ua;!y.assetId&&(y.assetId=ua);break;case "besrc":y.poster=L;case "esrc":ua=b(L,U);oa=L.match(X)?F:L.match(T)?E:m;oa.src=L;(oa.assetId=ua)&&(y.assetId=ua);break;case "width":case "height":g[Q]=f[Q]=o[Q]=l[Q]=L>>0;!y[Q]&&(y[Q]=L>>0);break;case "ewidth":case "eheight":Q=Q.slice(1);F[Q]=m[Q]=y[Q]=E[Q]=L>>0;break;case "wmode":P&&"window"==
L&&(L="opaque");case "version":case "quality":g[Q]=F[Q]=l[Q]=E[Q]=L;break;case "flashvars":ea=g[Q]=F[Q]=l[Q]=E[Q]=L;break;case "link":ha=J?e(encodeURIComponent(L)):L;break;case "css":Fa=L.split("/assets/css/"),u.scriptsBase=a.scriptBase||Fa[0]+"/",L=u.scriptsBase+"assets/css/"+Fa[1];case "sources":u[Q]=y[Q]=L;break;case "ADFPoliteSrc":o.src=L;o.assetId=b(L,U);break;case "showType":u[Q]=0==L?1:2==L?2:0;break;case "hideType":u[Q]=1==L?0:1;break;case "floatPosition":u[Q]=Bb[L];break;case "behavior":u[Q]=
{"0":"default",1:"pushdown",2:"sidekick",3:"floating",takeOver:"takeover",4:"slider"}[L];break;case "zIndex":var ab=parseInt(L,10);u[Q]=isNaN(ab)?u.zIndex:ab;break;default:u[Q]=L}}var Cb=u.bn=U.bn,Db=u.userParams=u.userParams||{},ja=t(),Z=ja&&ja.banners&&ja.banners[u.xId];if(Z){var ka=Z.clickEvent;if(ka&&(ka=ka.match(S))&&(ka=ka[1]))Z.compoundSeqNo=u.seqNo=ea.seqNo=ka&&+ka;!1===Z.stubFileExists&&(u.forceBackup=!0);Z.cookieID&&(ea.icid=Z.cookieID);var bb=ja.getPropByBn&&ja.getPropByBn("animURL",Cb);
bb&&(Db.animURL=bb);var cb=ja.getRotSeed&&ja.getRotSeed().id;cb&&(ea.hash=cb);var db=Z.rotseqno;db&&(ea.rotseqno=db);var eb=Z.smid;eb&&(ea.smid=eb);var fb=Z.timeDiff;fb&&(ea.timeDiff=fb);if(Z.isDSPTag&&d!=d.parent)try{d.parent.document.getElementById,d.inFIF=u.iab=!0}catch(Rb){a.ADFIframe=1}var gb=Z.unloadScriptVersion;gb&&(u.unloadVersion="v"+gb);Z.sendUnloadData&&(u.sendUnload=!0)}"takeover"==u.behavior&&(u.autoShow=O,u.autoHide=K);P&&(u.showDelay=Math.max(u.showDelay,k),u.restartAnimation=1);u.iframeAPI.msAPI&&
!u.showType&&(u.showType=1);ea.wmode=g.wmode;var hb=d.ADFDomainCDN;hb&&(ea.hvfdomain=hb);var ga=u.type;ga==M&&"slider"==u.behavior&&(ga=u.type=Y);if(ga==H||ga==V)ha=U.clickTAG;if(ha){if(J)for(var ib,ba=3;ba--&&(2>(ib=ha.indexOf("://"))||8<ib);)try{ha=decodeURIComponent(ha)}catch(Sb){ba=0}l.link=E.link=f.link=m.link=y.link=o.link=ha}ga==G&&(u.behavior=G);var Ga=s(),Ha;if(a.ADFIframe)Ha=location.search;else{for(var Eb=RegExp("[?;]bn="+u.bn+"\\b"),jb=u.seqNo&&RegExp("[?;]compoundSeqNo="+u.seqNo+"\\b"),
va,Ia=v.byTag(c,"script"),Ja=Ia.length;Ja--;){var Aa=Ia[Ja].src;if(Aa&&0<Aa.indexOf("adfscript")&&Aa.match(Eb)&&(!jb||Aa.match(jb))){va=Ia[Ja];break}}if(v.isIE){for(var wa=va,kb=c.body;wa&&wa!=kb;)wa=wa.parentNode;wa==kb&&(u.$tag=va)}Ha=va&&va.src}var lb=Ha,Ka=lb&&lb.match(A);Ka&&Ka[1]&&(u.obaId=Ka[1],u.adNotice=1,Ga.link=D);if(Z&&Z.adNotice||u.adNotice)l.adNotice=g.adNotice=f.adNotice=Ga,ga!=M&&(y.adNotice=Ga),u.adNotice=1;if(ga==H&&(u.restartAnimation=1,Z)){Z.floatFrom&&(u.position=Z.floatPosition>>
0,u.floatFrom=Z.floatFrom);var mb=parseInt(Z.showFloat,10);u.showFloat=isNaN(mb)||1<=mb?1:0}ga==N&&(F.src=g.src,E.src=l.src,"sidekick"!=u.behavior&&(u.sideKickAnim=1),!u.sideKickAnim&&(ea.useAsMask=!1));var la=l.flashvars,nb=d.ADFDynamicDomain;la.staticDomain=la.domain;d.ADFDomain&&nb&&(la.domain=encodeURIComponent(nb));var La={};for(ia in la){L=la[ia];try{L=decodeURIComponent(L)}catch(Tb){}La[ia]=L}var ma=i.videoSources,Ma=[],ob=ma,Fb=decodeURIComponent(la.staticDomain),Gb=decodeURIComponent(la.hvfdomain),
pb;for(pb in ob){var pa=ob[pb];pa&&pa.file&&!~pa.file.indexOf("://")&&(pa.file=("true"==pa.isStreaming+""&&Gb||Fb)+pa.file)}if(ma){var qb=ma,Na,Oa,Pa,Ba,Ca,fa,Qa,qa,Ra,Sa,rb,sb,tb;Na=[];Oa=a.ENV&&a.ENV.akamaiHost;sb=/avc1\.(..)(..)(..)/;tb=/mp4a\.40\.(?:2|5)/;for(Pa=qb.length;Pa--;)if(Ba=qb[Pa])if(Ca=Ba.codecs,fa=Ba.file,Ca&&fa&&(fa.indexOf(Oa)||!~fa.indexOf("/master.m3u8")))Ra=(qa=Ca.match(sb))&&qa[1].toLowerCase(),Sa=qa&&parseInt(qa[3],16),qa="42"===Ra&&30>=Sa||"4d"===Ra&&31>=Sa,rb=Ca.match(tb),
qa&&rb&&(Qa=fa.indexOf("/Stream/"),~Qa&&(fa=fa.substr(Qa,fa.length-1),Na.unshift({file:Oa+fa+"/master.m3u8",mime:"application/x-mpegURL",codecs:Ba.codecs})));for(var ma=Na.concat(ma),ba=0,ub,Hb=ma.length;ba<Hb;ba++)(ub=ma[ba])&&Ma.push(ub);Ma.length&&(La.videoSources=y.sources=Ma)}l.flashvars=E.flashvars=La;var xa=u.AdformBgImage&&u,vb=t(),wb=vb&&vb.banners,xb;for(xb in wb){var Ta=wb[xb];if(Ta.bn==u.bn&&Ta.AdformBgImage){xa=Ta;break}}if(xa){var Ua='url("'+xa.AdformBgImage+'")',yb={Color:"",Repeat:"",
Scroll:"",HorizontalPosition:"center",VerticalPosition:"top"},Va;for(Va in yb)Ua+=" "+(xa["AdformBg"+Va]||yb[Va]);u.wallpaper={link:xa.AdformBgLink,background:Ua}}var ra=u.position,Wa=u.expPosition;switch(u.type){case x:var Xa={left:"L",center:"C",right:"R"};u.position=Xa[ra]||(u.backCompat?"I":"C");break;case V:u.fixed=1;var ya=(u.y?"T":"M")+(u.x?"L":"C");u.position=ya;u.x>>=0;u.y>>=0;break;case H:var Ya=u.floatFrom,Ib={1:"M",2:"T",3:"T",4:"T",5:"B",6:"B",7:"M",8:"M",9:"B"},Jb={1:"C",2:"C",3:"L",
4:"R",5:"L",6:"R",7:"L",8:"R",9:"C"},Kb={1:"M",2:"Y",3:"Y",4:"Y",5:"N",6:"N",7:"M",8:"M",9:"N"},Lb={1:"C",2:"C",3:"K",4:"E",5:"K",6:"E",7:"K",8:"E",9:"C"},Mb=Ya?Kb:Ib,Nb=Ya?Lb:Jb;u.x>>=0;u.y>>=0;if(!Ya&&(0>u.x&&(u.x=0),0>u.y))u.y=0;var Ob=Mb[ra]||"M",Pb=Nb[ra]||"C",ya=(u.y?"T":Ob)+(u.x?"L":Pb);u.position=ya;break;case M:case N:Xa={left:"L",center:"C",right:"R"};u.position=u.colPosition=Xa[ra]||ra;u.expPosition={custom:"TL","left-up":"BR",takeOver:"BR",left:"TR","left-down":"TR",up:"BL","right-up":"BL",
down:"TL",right:"TL","right-down":"TL"}[Wa]||Wa;"custom"!=Wa&&(u.expX=u.expY=0);break;case G:ya="2"==""+ra?"TR":"TL",u.position=u.colPosition=u.expPosition=ya}u.disturber=new C;var W={};W.flash=W.colFlash=g;W.expFlash=F;W.image=W.colImage=f;W.expImage=m;W.video=y;W.html=W.colHtml=l;W.expHtml=E;W.polite=o;W.options=u;W.events=new C;var ca=W.options,za={zIndex:ca.zIndex-1};ca.overlayOpacity&&(za.opacity=(ca.overlayOpacity>>0)/100);ca.overlayColor&&(za.background=ca.overlayColor);var Za={bn:ca.bn,closeOnClick:ca.overlayCloseOnClick||
1,style:za},Da=(ca.iab?parent:d).ADFORM_OVERLAY||d.ADFORM_OVERLAY,da;if(ca.type==H&&Da){for(var Ea=0,Qb=Da.length;Ea<Qb;Ea++)if(ca.bn==Da[Ea].bn){da=Da[Ea];break}if(da&&(typeof da.callFrom!=z&&(Za.callFrom=da.callFrom),typeof da.closeOnClick!=z&&(Za.closeOnClick=da.closeOnClick),da.color&&(za.background=da.color),da.opacity))za.opacity=da.opacity}if(da||ca.overlayOpacity)W.overlay=Za;var $={};for(ba in W)if(W[ba].src||W[ba].sources)$[ba]=W[ba];$.options=u;$.events=W.events;W.overlay&&($.overlay=W.overlay);
"window"!=g.wmode&&q($);y.sources&&(y.loop="true"==""+U.loopVideo,y.muted="true"!=""+U.soundOn,y.autoplay="true"==""+U.autoPlay,j(u,y));if(v.isSafari&&6.1<=v.safariVersion&&($.image||$.html||$.expImage||$.expHtml))delete $.flash,delete $.colFlash,delete $.expFlash;return $}function o(a,b){for(var c in b)b.hasOwnProperty(c)&&("object"==typeof b[c]?("object"!=typeof a[c]&&(a[c]={}),o(a[c],b[c])):a[c]=b[c])}function q(a){var b=a.options,c=b.socializeURL;if(c){var c={linkBack:c,css:b.css,position:"BL"},
b=b.type,n=b!=N&&a.expFlash||a.flash,g=b!=N&&a.expHtml||a.html,d=a.expImage||n==a.flash&&a.image,e=a.video;n&&(n.social=v.extend({width:(b==N?a.expFlash:n).width},c));d&&(d.social=v.extend({width:d.width},c));g&&(g.social=v.extend({width:g.ewidth},c));e&&(e.social=v.extend({width:e.width},c),e.social.position="TL"==e.closeButtonAlign?"TLV":"TL")}}function j(a,b){switch(a.type){case M:case N:b.closeButtonAlign={BR:"TL",TR:"BL",BL:"TR",TL:"BR"}[a.expPosition]||b.closeButtonAlign;"TR"==b.closeButtonAlign&&
b.adNotice&&(b.closeButtonAlign="TL");break;case G:b.closeButtonAlign="TL"==a.position?"BR":"BL";break;case H:b.closeButtonAlign=b.adNotice?"TL":"TR"}}function t(){var b=a.ADFBannerUtils;if(b&&b.getInstance)return b.getInstance()}function s(){return{title:P,linkText:E,text:F,link:y}}function b(a,b){return a&&~a.indexOf(aa)&&a.match(U)[1]||b&&b[J]||0}function h(a){if("string"!=typeof a)return a||{};for(var b={},a=a.split("&"),c=0,n=a.length,g;c<n;c++)g=a[c].split("="),b[g.shift()]=e(g.join("="));return b}
function e(a){if(!a)return a;a=decodeURIComponent(a);0<=a.indexOf("&")||!a.indexOf("http")?a=encodeURIComponent(a):0<=a.indexOf(";CREFURL=")&&(a=a.split(";CREFURL="),a=a.concat(a.pop().split(";C=")),a=a[0]+";CREFURL="+encodeURIComponent(a[1])+(a[2]?";C="+a[2]:""));return a}a.RMB=a.RMB||{};var f=a.RMB,m=f.DataParser||(f.DataParser={}),v=f.lib,C=f.EventEmitter,z="undefined",k=0.5,O=0.01,K=8,M=m.EXPANDING="expanding",G=m.TEARBACK="tearback",H=m.FLOATING="floating",x=m.STANDARD="standard",N=m.SINGLE_EXPANDING=
"singleExpanding",V=m.INTERSTITIAL="interstitial",Y=m.SLIDER="slider",S=/compoundSeqNo=(\d+)/,A=/;obaId=([^;]+)/,T=/\.js(\?|$)/i,X=/\.swf(\?|$)/i,P="Adform.com",F="Would you like to know more about why you are seeing this ad?",y="http://site.adform.com/privacy/adchoices/",D="http://site.adform.com/privacy/adchoices/",E="Read more";m.getData=function(){if(a.IFrameManager&&a.IFrameManager.bannerData){var b=l(a.IFrameManager.bannerData);b.options.iframeManager=!0;var c=b.options.userParams;if("string"==
typeof c){for(var c=c.split("|||"),n,g={},d=0,e=c.length;d<e;d++)n=c[d].split("="),g[decodeURIComponent(n.shift())]=decodeURIComponent(n.join("="));b.options.userParams=g}if(b.video&&(c=b.video,"string"==typeof c.sources)){n=c.sources.split("|||");for(var g=0,d=n.length,p=[],r,h;g<d;g++)if(n[g])if(0<n[g].indexOf("|")){p.push(r={});h=n[g].split("|");for(e=0;e<h.length;e+=2)r[h[e]]=h[e+1]}else"false"!=n[g]&&p.push({file:n[g]});c.sources=p}return b}b=a.RMBData;a.BannerList&&a.BannerList.length&&(b=a.BannerList.shift());
if(b)return l(b)};m.parseFlashvars=h;m.fixFlashvarsValue=e;m.applyHooks=function(a,b){var c=a.options,n=c.bn,e=t(),p=((c.iab?parent:d)._adform||[]).slice(0);c.iab&&p.push.apply(p,d._adform||[]);e&&e.getPropByBn&&(e=e.getPropByBn("multiPanel",n))&&p.push.apply(p,e);if(v.isArray(p)&&p.length){for(var c=b||["",n,"#"+c.seqNo,n+"#"+c.seqNo,c.xId],n={},r=c.length,h=p.length,e=0;e<r;e++)n[c[e]]={};for(var F=/(?:(\d+x|\d+#\d+|#[-_0-9a-z]+|\d+))?\.?(.*)/i,f,D,y,B,k,e=0;e<h;e++)if(f=p[e][0].match(F),D=n[f[1]||
""]){y=p[e][1];if(f[2]){f=f[2].split(".");for(k=B={};1<f.length;)B=B[f.shift()]={};B[f[0]]=y;y=k}if(f=y.on)for(var m in f){if("function"==typeof f[m])a.events.on(m,f[m])}else if(y.init)a.events.on("init",y.init);f={};for(B in y)g[B]&&(f[B]=y[B]);o(D,f)}p=n[c[0]];for(e=1;e<r;e++)o(p,n[c[e]]);for(e in g)if(e in p){f=g[e].split(".");for(k=B={};1<f.length;)B=B[f.shift()]={};B[f[0]]=p[e];o(a,k)}}B=(a.html||a.flash||a.image||a.video||{}).adNotice||s();if(p=a.options._adNotice){for(var l in p)p.hasOwnProperty(l)&&
(B[l]=p[l]);delete a.options._adNotice}(!a.flash||"window"!=a.flash.wmode)&&q(a);a.video&&j(a.options,a.video);return a};var n={ADFInitFlash:"src",ADFFlash:"src",ADFTearFlash:"esrc",tearWidth:"ewidth",tearHeight:"eheight",fVer:"version",ADFVer:"version",clicktags:"flashvars",ADFBuckup:"bsrc",bclickUrl:"link",backupClickURL:"link",ADFBuckupClickURL:"link",videoSources:"sources",bannerAlign:"position",expandsTo:"expPosition",adfxid:"xId",ADFid:"xId",expandDelay:"showDelay",expandTime:"showTime",collapseTime:"hideTime",
autoShowAfter:"autoShow",showTimeout:"autoShow",autoCloseAfter:"autoHide",closeTimeout:"autoHide",showOnRollOut:"showType",closeOnRollOut:"hideType",keepCollapsed:"keepCollapsed",politeTimeout:"loadDelay",expandedX:"expX",expandedY:"expY","":""},r={src:"",width:0,height:0,version:7,play:!0,menu:!1,loop:!0,quality:"autohigh",wmode:"opaque",bgcolor:null,allowScriptAccess:"always",allowFullScreen:!0,flashvars:{}},p={src:"",width:0,height:0,link:""},B={width:0,height:0,poster:"",css:null,closeButtonAlign:null,
loop:"false",muted:"true",autoplay:"false",link:null,assetId:0},I={src:"",width:0,height:0,flashvars:{}},R={position:"L",colPosition:"C",expPosition:"TL",x:0,y:0,expX:0,expY:0,xId:"1x",zIndex:1E5,fixed:0,restartAnimation:0,clickEvent:"",showDelay:0,showType:0,hideType:0,autoShow:0,autoHide:0,behavior:"default",frameRate:0,showTime:0,hideTime:0,loadDelay:0,type:"none",keepCollapsed:0,sideKickAnim:1,landingPageTarget:"_blank",showFloat:1},g={useClose:"expImage.useClose",overlay:"overlay",wallpaper:"options.wallpaper",
x:"options.x",y:"options.y",hidden:"options.hidden",position:"options.position",adNotice:"options._adNotice",fixedBounding:"options.fixedBounding",panel:"panel"},J="ADFassetID",aa=J+"=",U=RegExp(aa+"(\\d*)")})(Adform=window.Adform||{},window,document);
(function(a,d){function c(a,b,c){for(var a=a.replace(/[\r\n]+/g,b),d={},a=a.split(b),e=a.length,f,h,b=0;b<e;b++){h=a[b].split(c);f=h.shift();var k=d;h=h.join(c);k[f]=!h?null:"true"===h||"false"===h?"true"===h:1*h==h?1*h:h}return d}function l(a){var b=a.options,c=a.panel.from,e;!{standard:1,expanding:1,singleExpanding:1}[b.type]||"floating"==b.behavior?f.AdConstructor.initialize(a):("number"==typeof c?b=o(a):"string"==typeof c?(b=m.byId(a.panel.from,(a.options.iab?d.parent:d).document))?(j(a,{container:b},
!0),b=void 0):b=!0:(j(a,{before:a.options.iab&&d.frameElement},!0),b=void 0),e=b);e?(z.push(a),k||(k=setTimeout(q,100))):z.length&&l(z.shift())}function o(a){var b=O[a.options.bn+"#"+a.panel.from];if(!b||!b.box)return!0;var c=a.panel,d=h(c.position,!0),e=b.settings,f=e.image||e.html||e.video||e.flash,e=(e=e.panel)&&e.space,k;if(e&&f&&"C"!=d&&(k=e.width>>0))k=0.5*(k-f.width),c.x=(c.x||0)+("L"==d?-1:1)*k;b.box.pull("element",function(){j(a,{from:b.box})})}function q(){k=0;z.length&&l(z.shift())}function j(a,
b,c){function e(d){var f=B?"stickyBox":"box";p=y[f]=(new C).publish("panel-"+f,a.events);R&&p.set("zIndex",q.zIndex=R);p.set({width:g,height:D?J:"auto",x:!B&&v.x||0,y:!B&&v.y||0,visible:!v.hidden}).set(E?{stickyOffset:v.sticky}:{}).pull("element",k).draw(F,{type:E&&"sticky",position:B?"":h(v.position,c),container:n,before:r,from:d||b.from})}function k(b){b.innerHTML="<span></span>";q.iab=!1;q.window=z;q.$tag=b.firstChild;b={item:y,settings:a,content:o};q.panel=b.exports={set:m.bind(b,t),get:m.bind(b,
s)};b.constructor=I=f.AdConstructor.initialize(a);I._panel_show=I.show;I._panel_hide=I.hide;I.show=l;I.hide=j}function l(){var a=b.from;a&&a.pull&&!a.get("visible")?setTimeout(l,100):(B&&B.set("visible",!0),p.set("visible",!0),I._panel_show())}function j(){I._panel_hide();p.set("visible",!1);B&&B.set("visible",!1)}var o=a.image||a.html||a.flash,q=a.options,v=a.panel,z=q.iab?d.parent:d,F=z.document,y=O[q.bn+"#"+q.seqNo],D=!!b.from,E="sticky"in v&&!1!==v.sticky,n=b.container,r=b.before,p,B,I,R="z"in
v?v.z:E||D?1E4:null,g=o.width,J=o.height;q.hidden?v.hidden=q.hidden:v.hidden&&(q.hidden=v.hidden);E&&!D?(n=r=null,(B=y.box=new C).publish("panel-box",a.events).set({width:g,height:J,visible:!v.hidden,x:v.x||0,y:v.y||0}).pull("element",e).draw(F,{position:h(v.position,c),before:b.before,container:b.container})):e()}function t(a,b){var c=this.item,d=c.box,c=c.stickyBox,a=M[a]||a;if("string"!==typeof a)for(b in a)t.call(this,b,a[b]);else"zIndex"==a?((c||d).set(a,b),this.constructor.setZIndex(b)):c&&
"stickyOffset"==a?c.set(a,b):d.set(a,b);c&&c.repositionSticky()}function s(a){var b=this.item,c=b.box,a=M[a]||a;if("width"==a||"height"==a)a=this.content[a];else{if("zIndex"==a||"stickyOffset"==a)c=b.stickyBox||c;a=c.get(a)}return a}function b(a,b){var c=b.options,d=b.panel,e={options:{iab:c.iab},events:b.events};v.applyHooks(e,["#"+a,c.bn+"#"+a]);e.panel&&(d?m.extend(d,e.panel):b.panel=e.panel)}function h(a,b){var a=(a||"").toLowerCase(),c,d={r:"E",ri:"R",l:"K",li:"L"}[(c=a.match(/[rl]i?/))&&c[0]]||
"C",e={t:"Y",ti:"T",b:"N",bi:"B"}[(c=a.match(/[tb]i?/))&&c[0]]||"M";return b?{E:"R",K:"L"}[d]||d:d+e}function e(){}if(!a._panels){a._panels=!0;var f=a.RMB,m=f.lib,v=f.DataParser,C=f.AdBox,z=[],k,O={},K={},M={z:"zIndex",sticky:"stickyOffset"};(_adform=d._adform||[]).push(["on.setup",function(h){var f=a.ADFUtilInstance,k=h.options,j=k.bn;if(f&&f.getPropByBn){var o=h.panel,q=h.events,s=k.seqNo,v=1==s,t;t=K[j];if(!t)for(var z=m.byTag("script"),C=z.length,F,y;0<C--;)if(F=z[C],(y=F.getAttribute("data-panels"))&&
F.src&&~F.src.indexOf("?bn="+j)){var z=c(y,";","="),C={length:0},D=y=F=void 0,E={w:"width",h:"height",pos:"position",p:"position",f:"from",s:"sticky"},n=void 0;for(n in z)if(n){F=z[n]?c(z[n],",",":"):{};y={};for(var r in F)r&&(D=E[r]||r,y[D]="hidden"==D||null===F[r]||F[r]);C["#"+n]=y;C.length++}y=C;y.length&&(t=K[j]=y);break}if(t&&(v&&!f.getPropByBn("syncMembersCount",j)&&f.addBannerAttribute(k.xId,"syncMembersCount",t.length),t=t["#"+s]))o=h.panel=m.extend(o||{},t);o&&(k.iab&&(d.frameElement.style.display=
"none"),O[j+"#"+s]={settings:h},v&&(o.id=o.id||"top"),o.id&&(q.clear("setup"),b(o.id,h),q.emit("setup",h)),h.preventInitialization=!0,l(h));if(v&&f.getPropByBn("singleTag",j)){f=a.ADFUtilInstance;h=h.options;k=f.getPropByBn("syncMembersCount",h.bn);j={options:{iab:h.iab,bn:h.bn},events:{on:e}};for(o=1;o++<(k||10);){if(!k){b(o,j);if(!j.panel)break;delete j.panel}f.copyBanner(h.xId,{compoundSeqNo:o,compoundImpr:0})}}}}])}})(Adform=window.Adform||{},window,document);
(function(a){function d(a,d,o){this._dur=o;this._int=d||25;this._fn=a;this._pos=0;var q=this;this.frame=function(a){q._frame(a)}}a.RMB=a.RMB||{};a.RMB.Tween=d;a=d.prototype;a.duration=function(a){this._dur=a;return this};a.forward=function(a){this.start(a)};a.backward=function(a){this.start(a,!0)};a.frame=function(a){a=!0===a?0:this._dur?(new Date-this._time)/this._dur:1;1<=a&&(a=1,this.stop());this._fn(this._back?1-a:a,this._back);this._pos=a};a._frame=a.frame;a.start=function(a,d){this.stop();"undefined"!=
typeof a?this._pos=a:a=this._pos;this._back!=d&&(a=1-a);this._back=!!d;this._time=new Date-this._dur*a;this._timer=setInterval(this.frame,this._int);this.frame(!a)};a.stop=function(){clearInterval(this._timer)}})(Adform=window.Adform||{});
(function(a,d,c){function l(b){if(!z)if(z=a.ADFEventsInstance){if(!z.getItem)return z=null;z.on("destroy",s);z.subscribe(t);t()}else b&&!C&&(C=1,m=a.scriptBase+m+a.cache,e.loadScript(c,m.split("{version}").join(f)));return z}function o(a){var b=l();return b&&b.getItem(a)}function q(a){if(this instanceof q)throw Error('This function cannot be used with operator "new".');return v[a]||(v[a]=new b(a))}function j(a){a&&(f=a)}function t(){for(var a in v)v[a].refresh()}function s(){for(var a in v)v[a].emit("destroy")}
function b(a){this.xId=a;this._queue=[];this._attributes={};this.set("visible",!1);this.set("loaded",!1);this.set("percent",0);this.set("clicksCount",0);this.refresh();this._changes=null;if(!l())this.once("newListener",h)}function h(){l(!0)}a.RMB=a.RMB||{};d=a.RMB;if(!d.EngagementAPI){d.EngagementAPI=q;var e=d.lib,d=d.EventEmitter,f="v13",m="unload/EngagementTracker.{version}.js?",v={},C,z,k;l()||(k=a._etCallback,a._etCallback=function(){l();(a._etCallback=k)&&k()});q.version=j;q.load=function(a){j(a);
l(true)};e.inherit(b,d);d=b.prototype;d.set=function(a,b){var c=o(this.xId),d=this.get(a),e=this._changes;if(c)c.attr(a,b);else{this._attributes[a]=b;this._queue.push([a,b])}if(d!==b){if(!e)e=this._changes={};e[a]=b;this.emit("change:"+a,b,d)}return this};d.get=function(a){if(this["get_"+a])return this["get_"+a]();var b=o(this.xId);return b?b.attr(a):this._attributes[a]};d.get_visibleTime=function(){var a=o(this.xId);return a&&a.visibility.time};d.refresh=function(){var a;a=o(this.xId);var b=0,c=
this._queue,d=c.length;if(a){if(d){for(;b<d;b++)a.attr(c[b][0],c[b][1]);c.length=0}this.set("visible",a.visibility.active);this.set("percent",a.data.currentVisibleArea);this.set("clicksCount",a.clicks.length);if(a=this._changes){this._changes=null;this.emit("change",a)}}return this}}})(Adform=window.Adform||{},window,document);
(function(a,d,c){function l(c){var e=this.options=c.options;this.settings=c;e.BANNER_TYPE=this.BANNER_TYPE;var f=d;e.iab?(f=parent,e.iframe=d.frameElement):e.iframeManager?(f=parent.parent,e.iframe=q(f,parent)):e.window&&(f=e.window);this.win=f;k.isolate(f,s);a.adRegister=f.Adform.adRegister;t.call(this);(this._wallpaper=e.wallpaper&&e.wallpaper.background&&!k.isTMX(f))&&this.setupWallpaper();var m=c.events;this.on=function(){m.on.apply(m,arguments);return this};this.off=function(){m.off.apply(m,
arguments);return this};this.once=function(){m.once.apply(m,arguments);return this};this.emit=function(){var a=this._events;this._events=m._events;m.emit.apply(this,arguments);this._events=a;return this};this._clearEvents=function(a){m.clear(a)};k.isolate(f,b);d.ADFReload=f.ADFReload;d.ADFcall=d.ADFCall=f.ADFCall;c=k.bind(this,j);k.addEvent(d,"unload",c);if(f!=d&&(k.isolate(f,h),k.isOpera||9>k.ieVersion))(!f.Adform||!f.Adform.trackIframe)&&k.isolate(f,o),f.Adform.trackIframe(e.iframe,c)}function o(a){function b(){for(var a=
d.length;a--;)d[a][0].parentNode||(d[a][1](),d.splice(a,1));d.length||(c=clearInterval(c))}var c,d=[];(a.Adform=a.Adform||{}).trackIframe=function(a,e){d.push([a,e]);c||(c=setInterval(b,200))}}function q(a,b){for(var c=a.document.getElementsByTagName("iframe"),d=c.length;0<d--;)try{if(c[d].contentWindow==b)return c[d]}catch(e){}}function j(){var a=this.options.xId,b=this.getUtils();k.removeEvent(d,"unload",arguments.callee);this.emit("destroy");this.destroy&&this.destroy();O.destroy();t.call(this,
!0);this._clearEvents();this._wallpaper&&(this.toggleWallpaper(),delete this._wallpaper);b&&b.wipeOutBanner&&b.wipeOutBanner(a);this.options=null}function t(b){var c=this.options,d=c.bn,e=c.xId,c=c.seqNo,c=d+(c?"#"+c:""),n=a.adRegister,f=this.win.Adform.adRegister;b?(delete n[c],delete n[d],delete n[e],delete f[c],delete f[d],delete f[e]):n[c]=n[d]=n[e]=f[c]=f[d]=f[e]=this}function s(a){a=a.Adform=a.Adform||{};a.adRegister=a.adRegister||{}}function b(a){function b(c,d){var e=[].slice,f=a.Adform.adRegister;
if(f[c]){var p=[f[c]];if(!/x|#/.test(c))for(var h in f)p[0]!=f[h]&&!h.indexOf(c)&&p.push(f[h]);f=arguments;f=2<f.length?e.call(f,2):!1;for(e=0;e<p.length;e++){h=p[e];var k="string"==typeof d?h[d]:d;"function"==typeof k&&(f?k.apply(h,f):k.call(h))}}}a.ADFReload=function(a){setTimeout(function(){b(a||"1x","reload")},0)};a.ADFcall=a.ADFCall=b}function h(a){var b=a.Adform;b.Events=b.Events||{sendEvent:function(b,c,d,e,f){a.ADFCall(b,"sendEvent",c,d,e,f)}}}function e(a){return(new C.Type[A[a.options.type]](a)).emit("init",
a)}function f(b){var d=b;b||(b=G.shift());var f=b.options,h=f.type,n=A[h],r=C.Type[n],p=a.Log,k=f.bn;if(r&&!b._beforeScript){if(p&&(h===K.SLIDER&&(h=K.EXPANDING),p.pushMessage(["BannerType_"+h],"",{bn:k}),h===K.EXPANDING||h===K.SINGLE_EXPANDING))p.pushMessage(["ExpandingBehavior_"+f.behavior],"",{bn:k}),d=h.charAt(0).toUpperCase()+h.slice(1)+"_",f.showTime&&p.pushMessage([d+"expandTime"],"",{bn:k}),f.hideTime&&p.pushMessage([d+"collapseTime"],"",{bn:k});K.applyHooks(b);b.events.emit("setup",b);b.preventInitialization||
e(b)}else if(d)delete b._beforeScript,r&&(n="NextTick"),G.push(b),c.write('<script src="'+f.scriptsBase+"rmb/Adform."+n+".js?bv="+a.cache+'"><\/script>');else throw p&&p.pushMessage(["AdConstructor"],"Construct failed",{bn:k}),Error("Construct failed!");}function m(){var a=k.html('<iframe frameborder="0" allowtransparency="true" style="position:absolute;top:0;left:0;width:100%;height:100%"></iframe>'),b=c.body;k.isIE&&9>k.ieVersion?(b.appendChild(a),a=a.contentWindow,a.name=V,a.document.location.href=
N):(a.name=V,a.src=N,b.appendChild(a))}function v(a,b){if(this._hovered!=a){this._hovered=a;this.interacted=!0;if(a){var c=b.content().assetId;this._eventDelay(this,this.sendEvent,H,c,x)}else this._eventDelay();if(this.onEngage)this.onEngage()}}var C=a.RMB=a.RMB||{};C.Type=C.Type||{};if(!C.AdConstructor){C.AdConstructor=l;var z=C.EngagementAPI,k=C.lib,O=C.DOMEvents,K=C.DataParser,M=C.StyleSheet,G=[],H="141",x="Mouse Over on Banner",N,V,Y,S={Expanding:[K.EXPANDING,K.TEARBACK],Slider:[K.SLIDER],SingleExpanding:[K.SINGLE_EXPANDING],
Floating:[K.FLOATING],Standard:[K.STANDARD],Interstitial:[K.INTERSTITIAL]},A={},T,X,P;for(T in S)if((P=S[T]).push)for(X=P.length;0<X--;)A[P[X]]=T;l.build=function(){a.BWDetect&&a.BWDetect();var b=K.getData(),e=b&&b.options;if(e){var h=e.type,m;if(m=!e.forceBackup)if(m=a.ADFIframe){if(h=h==K.EXPANDING||h==K.SINGLE_EXPANDING||h==K.SLIDER)a:{h=a.RMBData;m=b.options;if(!m.messenger){var n=b.options.xId,r=a.ADFBannerUtils;n&&r&&r.getInstance&&(r=r.getInstance().banners[n]);if(r&&d!=d.parent&&(n=!m.iab&&
"stubFileURL"in r&&decodeURIComponent(r.stubFileURL))){n+=(n.match(/\?/)?"&":"?")+"version="+d.ADFBanVer;r=c.referrer;if(!/^[a-z]{3,}\:\/\/\w+/i.test(n)&&r&&(r=r.match(/^https?\:\/\/[^\/]+\//i)))n=n.replace(/^\/*/,r[0]);(r=location.search.match(/\bADFstubFileURL=([^&]+)/))&&r[1]&&(n=n.replace(/\/\/[^\/]+\//,"//"+r[1]+"/"));h=k.extend({},h);delete h.__parsed;h.host=a.CDNHost||a.host;m.adNotice&&(h.adNotice=1);m.obaId&&(h.obaId=m.obaId);h.bclickUrl&&(h.bclickUrl=K.fixFlashvarsValue(h.bclickUrl));r=
K.parseFlashvars(h.clicktags);delete h.clicktags;var p=h.clickEvent,B=p;p&&"string"==typeof p&&p.match(/\S/)?B=encodeURIComponent(p):p=B=!1;for(var j in r)B&&"string"==typeof r[j]&&(r[j]=r[j].replace(p,"#base#").replace(B,"#base#")),h["ct_"+j]=r[j];if(r=h.videoSources){p=[];j=0;for(B=r.length;j<B;j++){p[j]=[];for(var l in r[j])p[j].push(l,r[j][l]);p[j]=p[j].join("|")}h.videoSources=p.join("|||")}if(r=h.userParams){p=[];for(l in r)p.push(encodeURIComponent(l)+"="+encodeURIComponent(r[l]));h.userParams=
p.join("|||")}l=["format=expanding"];h.rmbPath=m.scriptsBase+"rmb/Adform.RMB.js?bv="+a.cache;for(j in h)l.push(encodeURIComponent(j)+"="+encodeURIComponent(h[j]));N=n;V=l.join("&");Y=b.options.css.replace(/\/assets\/.*/,"/assets/");c.write('<script src="'+Y+'cached.js"><\/script>');h=!0;break a}}h=void 0}m=h}m||(z[e.sendUnload?"load":"version"](e.unloadVersion),b._beforeScript=a._beforeScript,delete a._beforeScript,f(b),e.errorTimeout&&clearTimeout(e.errorTimeout))}};l.ibuild=f;l.checkCache=function(){if("b59c76df0ba3e60fad145628206b7a94"!=
d.CACHE){var a='<iframe src="'+Y+"recache.html?"+(new Date).getTime()+'" frameborder="0" style="position: absolute; left: -9999px;"></iframe>',a=k.html(a),b=0,e=0,h=function(){if(2===(e||b))a.onload=null,a.onreadystatechange=null,c.body.removeChild(a),m()};a.onload=function(){b++;h()};a.onreadystatechange=function(){"complete"===a.readyState&&(e++,h())};c.body.appendChild(a)}else m()};l.initialize=e;S=l.prototype;S.BANNER_TYPE="";S.setupUtils=function(a,b){var c=this.getUtils(),d=this.options.xId;
"string"==typeof a&&(a=[a]);c&&(c.addBannerAttribute(d,"relativeTargetSWFID",a[0]),c.addBannerAttribute(d,"trackElements",a),b&&c.addBannerAttribute(d,"trackHeatMap",b))};S.setupEngagement=function(a){var b=this,c=k.singleCall(0);b._eventDelay=k.singleCall(1E3);b._hovered=!1;a.length||(a=[a]);for(var d=0;d<a.length;d++)a[d].on("hover",function(a,d){c(b,v,a,d)})};S.sendEvent=function(b,c,d,e){return a.Events&&a.Events.sendEvent?(a.Events.sendEvent(this.options.xId,b,c,d,e||"",this.BANNER_TYPE),!0):
!1};S.getUtils=function(){var b=a.ADFBannerUtils;if(b&&b.getInstance)return b.getInstance()};S.setupWallpaper=function(){var a=this.options,b=a.wallpaper,c=this.win.document,d=b.cssClass="adform-wallpaper-"+a.bn,e=b.element||"",e="html"==e?"":!e.indexOf("#")?" "+e:c.documentElement?" body":"";b.target=a.landingPageTarget;M("adform-wallpaper",c).set("."+d+e,"background: "+b.background);("undefined"==typeof b.autoShow||b.autoShow)&&this.toggleWallpaper(!0)};S.toggleWallpaper=function(a){function b(a){a=
a||e.event;a=a.target||a.srcElement;return j&&a.id==j?!0:/^(html|body)$/i.test(a.nodeName)}function c(a){m.style.cursor=b(a)?"pointer":""}if(this._wallpaper){var a="string"==typeof a?"true"==""+a:a,d=this.options,e=this.win;try{var h=e.document,f,m=h.documentElement||h.body;if((f=e.__adform_wallpaper)&&(a||f.cssClass==d.wallpaper.cssClass))k.removeClass(m,f.cssClass),f.link&&(k.removeEvent(h,"mousemove",f._move),k.removeEvent(h,"mouseover",f._cursor),k.removeEvent(h,"click",f._click)),m.style.cursor=
"",e.__adform_wallpaper=null;if((f=d.wallpaper)&&a){k.addClass(m,f.cssClass);if(f.link){var j=f.element,j=j&&!j.indexOf("#")?j.slice(1):"";k.addEvent(h,"mousemove",f._move=function(a){k.removeEvent(h,"mousemove",arguments.callee);c(a)});k.addEvent(h,"mouseover",f._cursor=c);k.addEvent(h,"click",f._click=function(a){b(a)&&e.open(f.link,f.target)})}e.__adform_wallpaper=f}}catch(l){}}};S.setupGateway=function(b,c){if(b.get("element")){if(a.Wallpaper&&a.Wallpaper.setup&&!b.get("frompos")){var d=b.get("element"),
e=(e=this.getUtils())&&e.banners&&e.banners[this.options.xId];a.Wallpaper.setup({bn:this.options.bn,element:d,utils:e,width:b.get("width"),height:b.get("height"),callback:c})}}else{var n=this;b.onchange("element",function(){b.off("change:element",arguments.callee);n.setupGateway(b,c)})}};S.adDestroy=j;S.reload=function(){this.adBox&&this.adBox.emit("content:reload")};S.setZIndex=function(a){a=parseInt(a,10);if(!isNaN(a)){var b=this.options,c=A[b.type],d="adBox,collapsed,expanded,wallpaper,container,overlay".split(","),
e,h,f,k=d.length;for(this.zIndex=a;k--;)if((h=d[k])&&(e=this[h]))f=a,!("container"==h&&"floating"!=b.behavior)&&!("collapsed"==h&&"SingleExpanding"==c)&&("expanded"==h&&"Expanding"==c&&(f+=1),"overlay"==h&&(f-=1),e.set("zIndex",f))}}}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(b,h){function e(){f.emit(j)}var f=this;c.super_.call(f);f.created=0;f.options=b;f.data=h;f.container=t.bind(f,f.container);f.show=t.bind(f,f.show);f.hide=t.bind(f,f.hide);f.clear=t.bind(f,f.clear);f.reload=t.bind(f,f.reload);var m=b.loadDelay;if(m)setTimeout(e,1E3*m);else t.onload(d,e);f.on(q,function(){s(b.xId).set(q,!0)});h.social&&(f.setupExtra(f.social=new o.Socialize(b,h.social)),a.Log&&a.Log.pushMessage(["Socialize"],"",{bn:b.bn}));h.adNotice&&"window"!=h.wmode&&f.setupExtra(f.adNotice=
new o.AdNotice(b,h))}a.RMB=a.RMB||{};var l=a.RMB,o=l.Content=a.Content||{};l.AdContent=c;var q="loaded",j="pageLoadComplete";a.PAGE_LOAD_COMPLETE=j;var t=l.lib,s=l.EngagementAPI;t.inherit(c,l.EventEmitter);l=c.prototype;l.container=function(a){var c=this.doc=a.ownerDocument;this.win=c.defaultView||c.parentWindow;this._element=a};l.show=function(){};l.hide=function(){};l.reload=function(){var a=this instanceof o.AdNotice;!(this instanceof o.Socialize)&&!a&&(this.destroy(),this._adbox.get("showing")&&
this.show())};l.destroy=function(){};l.element=function(a,c){var d=this._elem;!1!==c?(d||(d=t.html('<div style="position:relative;width:100%;height:100%;overflow:hidden">',c&&c.ownerDocument)),d&&(c&&c.appendChild(d),"string"==typeof a&&(d.innerHTML=a))):d&&(d.parentNode&&d.parentNode.removeChild(d),d=null);return this._elem=d};l.bind=function(b){if(!this._adbox){var c=this.options,d,f;this._adbox=b;b.once("content:show",function(b){d=setTimeout(function(){for(var d=["img","object","embed","iframe"],
e,f;e=d.pop();){if((e=t.byTag(b,e)[0])&&0<e.offsetWidth&&0<e.offsetHeight)return;e&&(f=e)}a.Log.pushMessage(["AdContent"],"Banner did not render correctly",{bn:c.bn,node:f&&f.nodeName})},3E3)});b.once("content:hide",function(){clearTimeout(d)});b.once("content:destroy",function(){clearTimeout(d)});b.on("change:element",this.container);b.on("content:show",this.show);b.on("content:hide",this.hide);b.on("content:destroy",this.clear);b.on("content:reload",this.reload);(f=b.get("element"))&&this.container(f);
b.get("showing")&&this.show()}};l._clear=l.clear;l.clear=function(){var a=this._adbox;a&&(a.off("change:element",this.container),a.off("content:show",this.show),a.off("content:hide",this.hide),a.off("content:destroy",this.clear),a.off("content:reload",this.reload),this.destroy(),this._clear(),this._adbox=this.doc=this.win=this._element=null)};l.style=function(a){var c=this.element();c&&t.extend(c.style,a);return this};l.setupExtra=function(a){var c=this.bind,d=this.clear;this.bind=function(d){var e=
c.call(this,d);a.bind(d);return e};this.clear=function(){a.clear(this._adbox);return d.call(this)}}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(a,b){c.super_.call(this,a,b.adNotice);var d=this.data;d.width=b.width;d.height=b.height;this.id=o.gid(t+"button-");this.base=a.scriptsBase+"assets/images/OBA/"}a.RMB=a.RMB||{};var l=a.RMB;l.Content.AdNotice=c;var o=l.lib,q=l.DOMEvents,j=l.StyleSheet,t="adform-adnotice-",s={};o.inherit(c,l.AdContent);l=c.prototype;c.supported=function(){return!0};c.READY="ready";l.show=function(){this._element&&!this.created&&this.write()};l.write=function(){var a=this;a.created=(new Date).getTime();
var b=a._element,c=a.doc,m=a.win;m.self||(m=a.win=d);var l=a.statics=j("adbox-static",c);l.adNoticeStyles||(l.adNoticeStyles=!0,l.set(".adform-adnotice","z-index:1;position:absolute!important;top:0!important;right:0!important;left:auto!important;padding:0!important;margin:0!important"));a._elem=o.html('<div class="adform-adnotice" id="'+a.id+'">',c);var s=a.options,t=s.obaId;t?m.$ADP?a.setupAdPlayer(t,b):(l=s.scriptsBase+"adplayer/js/adplayer.min.js",o.loadCSS(c,s.scriptsBase+"adplayer/css/adplayer.min.css"),
o.loadScript(c,l,function(c){c||!m.$ADP?a.setupDefault(b):a.setupAdPlayer(t,b)})):a.setupDefault(b);q.on(a._elem,"hover",function(a){s.disturber.emit("hover",a=="hoverin")})};l.destroy=function(){this.element("",!1);this.created=0};l.getOBAImage=function(a){a=a.toLowerCase().match(/^(bg|cs|da|de-at|de-ch|de|el|es|fi|fr-be|fr-ch|fr|ga|hu|it-ch|it|nl-be|nl|no|pl|ro|sk|sv|uk|en)/);a=(a&&a[0]||"en")+".png";return this.base+a};l.setupAdPlayer=function(a,b){var c=this.win,d=c.$ADP.Registry,j=this.id,l=
this.data,o=this.options;this.element("",b);if(!s[a]){var k=[{title:l.title,text:l.text,url:l.link,linkText:l.linkText,usePopup:!!(c.Adform&&c.Adform.ADFIframe||o.iframeManager||o.iab)}];c.ADFCall(o.xId,function(){this.emit("setupADP",k)});if(k){c=0;for(l=k.length;c<l;++c)d.register(a,k[c])}s[a]=!0}d.createPlayer(a,{domId:j});this.emit("ready")};l.setupDefault=function(a){var c=this.data,d=this.id,j=this.statics,l=105<=c.width&&0.1>1575/(c.width*c.height);j.set(".adform-adnotice a","display:block;width:19px;height:15px;margin:0!important;padding:0!important;position:static!important;background:url("+
this.base+"oba.png) no-repeat;").set(".adform-adnotice img","display:none;border:none;margin:0!important;padding:0!important;position:static!important");l&&j.set("#"+d+" a:hover","width:auto;position:absolute;top:0;right:0;background-position:0 -100px").set("#"+d+" a:hover img","display:block;");this.element('<a href="'+c.link+'" target="_blank">'+(l?'<img src="'+this.getOBAImage(b)+'" alt="">':"")+"</a>",a);this.emit("ready")};var b=navigator.userLanguage||navigator.language||""})(Adform=window.Adform||
{},window,document);
(function(a,d){function c(a,d){c.super_.call(this,a,d);this.id=j.gid(s+"button-");this.on(b,function(){this.sendEvent(145,"Hide Social Bar")}).on(h,function(){this.sendEvent(140,"Facebook Like Button Press")})}function l(){this.emit(h);d.open(this.data.linkBack);return!1}function o(){this.emit(b);this.destroy()}a.RMB=a.RMB||{};var q=a.RMB;q.Content.Socialize=c;var j=q.lib,t=j.addEvent,s="adform-social-",b="collapsed",h="liked";j.inherit(c,q.AdContent);q=c.prototype;c.supported=function(){return!0};
c.READY="ready";c.COLLAPSED=b;c.LIKED=h;q.show=function(){this.destroyed||(this.created&&this.style({display:""}),this._element&&!this.created&&this.write())};q.hide=function(){this.style({display:"none"})};q.write=function(){this.created=(new Date).getTime();var a=this._element,b=this.doc,c=this.data,d=this.id;this._elem=j.html('<div id="'+d+'" class="'+[s+"container",s+"container-"+c.position].join(" ")+'" style="display:none;">',b);this.element('<div class="'+s+'bg"></div><div id="'+d+'-bar" class="'+
s+'bar"></div>',a);a=j.byId(d+"-bar",b);d=this.closeButton=j.html('<div class="'+s+'close">',b);this.close=j.bind(this,o);t(d,"click",this.close);var h=this.linkButton=j.html('<div class="'+s+'link">Like us on Facebook.</div>',b);this.like=j.bind(this,l);t(h,"click",this.like);a.appendChild(h);a.appendChild(d);j.loadCSS(b,c.css);123>c.width&&this.style({width:c.width-("TLV"==c.position?30:2)+"px",overflow:"hidden"});this.emit("ready")};q.destroy=function(){this.closeButton&&j.removeEvent(this.closeButton,
"click",this.close);this.linkButton&&j.removeEvent(this.linkButton,"click",this.like);this.bar=this.linkButton=this.like=this.closeButton=this.close=null;this.element("",!1);this.created=0;this.destroyed=!0};q.sendEvent=function(b,c){if(a.Events&&a.Events.sendEvent){var d=this.options;a.Events.sendEvent(d.xId,b,0,c,"",d.BANNER_TYPE);return!0}return!1}})(Adform=window.Adform||{},window,document);
(function(a,d){function c(b,d){c.super_.call(this,b,d);q.call(this);this.cube3D=this.video=!1;this.created=0;this.keepAlive=b.keepAlive;this.restartAnim=b.restartAnimation;var e=a.Log,f=b.bn;e&&(this.restartAnim&&e.pushMessage(["RestartAnimation"],"",{bn:f}),e.pushMessage(["AssetType_flash"],"",{bn:f}));e=m.gid("Adform");f=this.flashvars=d.flashvars;d=m.extend({},d);f.adId=e;f.expandTime=b.showTime||0;f.collapseTime=b.hideTime||0;f.behavior=b.behavior;f.landingPageTarget=b.landingPageTarget;var h=
[],k;for(k in f)f.hasOwnProperty(k)&&h.push(k+"="+f[k]);var g=b.userParams;if(g)for(k in g)if(g.hasOwnProperty(k)){var j=encodeURIComponent(k);j in f||h.push(j+"="+encodeURIComponent(g[k]+""))}d.flashvars=h.join("&");d.id=this.id="ad"+e;this.data=d;this.assetId=d.assetId||0;this._inScreenLast=0;this.on(T,l)}function l(){var a=v(this.options.xId);if(!this._lastInScreen)a.on("change",m.bind(this,o));a={visible:a.get("visible"),percent:a.get("percent"),loaded:a.get("loaded")};o.call(this,a)}function o(a){var b=
this,c=+new Date,d=b._inScreenTimer,e=b._lastInScreenChanges;e&&(a=m.extend(e,a));d&&(clearTimeout(d),b._inScreenTimer=0);b._lastInScreen>c-500?(b._lastInScreenChanges=a,b._inScreenTimer=setTimeout(function(){o.call(b,a)},b._lastInScreen+500-c)):(b._lastInScreen=c,b._lastInScreenChanges=null,b.callSwfMethod(X,a))}function q(){var a=!1,b=!1,c=this,d;c.on(M,function(){var e=+new Date;b=!0;a&&((!d||500<e-d)&&c.callSwfMethod(z),d=e)});c.on(z,function(){c.off(z,arguments.callee);a=!0;b&&c.callSwfMethod(z)})}
function j(b,c){function e(a,c,d,g,f){b.emit(a,{x:parseInt(c,10)+k.x,y:parseInt(d,10)+k.y,width:parseInt(g,10),height:parseInt(f,10)})}function f(a){b.emit(a);d.IABcloseAD&&d.IABcloseAD()}for(var h=b.win,k={x:0,y:0},g=b.emit,g=[["initPoliteMode",g,M],["initVideoMode",function(c){b.video=!0;a.Log&&a.Log.pushMessage(["VideoType_"+("undefined"===typeof c||c?"flash":"html")],"",{bn:b.options.bn})}],["initCube3D","cube3D",!0],["initExtender",g,P],["initInScreen",g,T],["startDrag",g,F],["endDrag",e,y],
["updateBox",e,Y],["expandComplete",g,S],["collapseComplete",g,A],["close",f,G],["superClose",f,x],["expand",g,H],["rollOutAd",g,N],["videoPlayStartHandler",g,"video:start"],["videoCompleteHandler",g,"video:end"]],j=g.length;0<j--;)(function(a,d,e){function g(){var a=D.call(arguments);"undefined"!==typeof e&&a.unshift(e);d.apply(b,a)}function f(){b[d]=e}c[a]="function"==typeof d?g:f}).apply(b,g[j]);c.initScroll=function(){var a=b.options.iab?h.parent:h;m.addEvent(a,"scroll",function(){m.removeEvent(a,
"scroll",arguments.callee);b.callSwfMethod("scroll")})};c.initSingleExpanding=function(a,c){b.emit("expandSettings",k={x:-parseInt(a,10),y:-parseInt(c,10)})};c.toggleFullScreen=function(a){b.emit(V,"true"==""+a)}}function t(a){var b=a.id,c,d,e="Handlers"+a.options.xId;d=a.win;m.isolate(d,s);c=d.Adform.swfCallbacks;d=d.Adform.VideoInterstitialHandlers;d=d[e]=c[b]=c[b]||{};j(a,d)}function s(a){function b(a,d){if(a&&(a=c["ad"+a])&&a[d])a[d]()}var c="swfCallbacks",d="VideoInterstitialHandlers",e=a.Adform=
a.Adform||{};if(!e[c]||!e[d])c=e[c]=e[c]||{},d=e[d]=e[d]||{},a.ADFClose=function(a){b(a,"close")},a.ADFSuperClose=function(a){b(a,"superClose")},a.ADFExpand=function(a){b(a,"expand")}}function b(a){var b=['classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"','codebase="'+location.protocol+"//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version="+a.version+',0,0,0"'],c=[],d=['type="'+C+'"','pluginspage="'+location.protocol+'//www.macromedia.com/go/getflashplayer"'],e;for(e in a)a.hasOwnProperty(e)&&
!~"object|undefined".indexOf(typeof a[e])&&("id"==e||"width"==e||"height"==e?b.push(e+'="'+a[e]+'"'):"src"==e?c.push('<param name="movie" value="'+a[e]+'" />'):c.push('<param name="'+e+'" value="'+a[e]+'" />'),"id"==e?d.push('name="'+a[e]+'"'):d.push(e+'="'+a[e]+'"'));return"<object "+b.join(" ")+">"+c.join("")+"<embed "+d.join(" ")+" /></object>"}function h(a,b){var c=m.byId(a,b);c&&"OBJECT"==c.nodeName&&("msie"==m.browser()?(c.style.display="none",function(){if(4==c.readyState){var d=m.byId(a,b);
if(d){try{for(var e in d)if("function"==typeof d[e])try{d[e]=null}catch(f){}}catch(g){}d.parentNode.removeChild(d)}}else setTimeout(arguments.callee,10)}()):c.parentNode.removeChild(c))}function e(a,b){var c=m.byId(a,b);return c&&m.byTag(c,"embed")[0]}a.RMB=a.RMB||{};var f=a.RMB;f.Content.FlashTag=c;var m=f.lib,v=f.EngagementAPI,C="application/x-shockwave-flash",z="pageLoadComplete",k="loaded",O="percentLoaded",K="canceled",M="politeReady",G="hide",H="show",x="close",N="rollOut",V="fullScreen",Y=
"updateBox",S="expandComplete",A="collapseComplete",T="initInScreen",X="updateInScreen",P="extender",F="startDrag",y="endDrag";m.inherit(c,f.AdContent);f=c.prototype;c.supported=function(a){return E>=(a||1)};c.observe=function(a){var b=c._timer,d=c._toObserve=c._toObserve||[];d.push(a);b||(b=setInterval(function(){for(var a=d.length;a--;)d[a]()&&d.splice(a,1);d.length||(clearInterval(b),delete c._timer)},500),c._timer=b)};c.READY="ready";c.PERCENT=O;c.LOADED=k;c.CANCELED=K;c.POLITE_READY=M;c.HIDE=
G;c.CLOSE=x;c.SHOW=H;c.ROLL_OUT=N;c.EXPAND_SETTINGS="expandSettings";c.EXPAND_UPDATE=Y;c.EXPAND_END=S;c.COLLAPSE_END=A;c.FULL_SCREEN=V;c.LOAD_COMPLETE=z;c.INSCREEN_INIT=T;c.INSCREEN_UPDATE=X;c.EXTENDER=P;c.START_DRAG=F;c.END_DRAG=y;c.setCallbacks=j;c.setupPolite=q;f.write=function(){var a=this,d=a._element,e=b(a.data);t(a);a.element(e,d);a.created=new Date;a.emit("ready");setTimeout(function(){function b(){var c=m.byId(a.id,a.doc),d=c&&m.byTag(c,"embed")[0];try{return c.PercentLoaded(),c}catch(e){try{return d.PercentLoaded(),
d}catch(g){}}}function d(){try{var b=e.PercentLoaded();a.emit(O,b);100==b&&(a.emit(k),g=clearInterval(g))}catch(c){a.emit(K),g=clearInterval(g)}}var e,g;(e=b())?g||(g=setInterval(d,100)):c.observe(function(){var c;if(!(c=!a.created))if(c=e=b())g||(g=setInterval(d,100)),c=!0;return c})},100)};f.destroy=function(){this.video&&this.callSwfMethod("pauseVideo");var a=this.id,b=this.win;(b=b&&b.Adform||d.Adform)&&b.swfCallbacks&&b.swfCallbacks[a]&&delete b.swfCallbacks[a];h(this.id,this.doc);this.element("");
this.created=0};f.callSwfMethod=function(a){function b(){if(!j[a]&&(!l||!l[a]))0<o--?setTimeout(b,100):c.emit("failed:"+a,i);else{try{"undefined"!=typeof j[a]?e.Adform_swfCallFix?e.Adform_swfCallFix(h,a,i):j[a].apply(j,i):"undefined"!=typeof l[a]&&l[a].apply(l,i)}catch(d){}c.emit("called:"+a,i)}}var c=this;if(c.created){var e=c.win,f=c.doc,h=c.id,g=c._elem;if(e!=d&&!f.addEventListener){var k=f.createElement("script");k.text="function Adform_swfCallFix(a,b,c){a=document.getElementById(a);return a[b].apply(a,c);}";
g.parentNode.insertBefore(k,g)}var j=m.byId(h,f),l=m.byTag(j,"embed")[0],i=D.call(arguments,1),o=20;c.emit("call:"+a,i);200>new Date-c.created?setTimeout(b,"safari"==m.browser()?100:0):b()}};f.show=function(){this._element&&!this.created&&(this.write(),this.forceRender())};f.hide=function(){if(this._element&&this.created){var a=e(this.id,this.doc);a&&a.blur&&a.blur();this.video&&!this.restartAnim?(this.callSwfMethod("pauseVideo"),this.cube3D&&this.callSwfMethod("resetCube3D"),this.forceRender()):
this.keepAlive?this.forceRender():this.destroy()}};f.forceRender=function(){if(!d.opera){var a=e(this.id,this.doc);if(a){var b=this.data.width;setTimeout(function(){a.width=b+1},0);setTimeout(function(){a.width=b},0)}}};var D=Array.prototype.slice,E=function(){var a=navigator.plugins,b=navigator.mimeTypes,c=d.ActiveXObject,e=16,f,a=a&&a["Shockwave Flash"]&&(!b||!b["application/x-shockwave-flash"]||b["application/x-shockwave-flash"].enabledPlugin)&&a["Shockwave Flash"].description||"";if(!a&&c)for(;6<=
e--;)try{f=new c("ShockwaveFlash.ShockwaveFlash."+e);6==e&&(f.AllowScriptAccess="always",a="WIN 6.0.21.0");try{a=f.GetVariable("$version").replace(/,/g,".")}catch(h){}break}catch(g){}return parseFloat(a.replace(/^.*?(\d+[\.,].*$)/,"$1"))||0}()})(Adform=window.Adform||{},window,document);
(function(a,d,c){function l(c,d){l.super_.call(this,c,d);this.assetId=d.assetId||0;this.xId=c.xId;this.restartAnim=c.restartAnimation;var e=a.Log,f=c.bn;e&&(e.pushMessage(["VideoType_html"],"",{bn:f}),e.pushMessage(["AssetType_video"],"",{bn:f}),this.restartAnim&&a.Log.pushMessage(["RestartAnimation"],"",{bn:f}));e=b.gid("Adform");d.id=this.id="ad"+e}function o(a){function c(){var a=m.currentTime,b=m.duration,e=+new Date,f=e-t,h=a-v;t=e;v=a;if(b){e=!1;if(h&&(h=f/(1E3*h)))e=2<Math.round(Math.abs(m.playbackRate/
h));a/=b;r!=a?(r=a,n=5,k.emit("timeupdate",r,e)):"playing"==o&&!--n&&0.9<r&&(d({type:"ended"}),n=5)}}function d(b){if("ended"==b.type&&a.loop)h(0),m.play();else if("ended"==b.type&&(h(0),m.pause()),b=m.paused||"ended"==b.type?!r||1===r?"stoped":"paused":"playing",b!=o)k.playbackState=o=b,k.emit("state",b)}function f(a){var b=a.total||m.duration;if(0<b)try{var c=(a.loaded||m.buffered&&m.buffered.end(0)||0)/b;c>p&&(p=c,k.emit("loadProgress",p))}catch(d){}}function h(a){try{m.currentTime=a*m.duration}catch(b){}}
var k=this,j=a.document;"undefined"==typeof N&&(N=j.createElement("video"));var l=s(a.sources);k.source=l;var m=b.html("<video "+q(a)+' preload="none" style="float:left"><source src="'+l.src+'"></video>',j);m.loop=!1;k.element=m;var o,n,r=-1,p=-1,t=0,v=0;e(m,"timeupdate",c);setInterval(function(){c()},500);j="play,pause,playing,seeking,seeked,stalled,ended,timeupdate".split(",");for(l=0;l<j.length;l++)e(m,j[l],d);d({});if(m.buffered)var z=setInterval(function(){f({});1<=p&&clearInterval(z)},500);
else e(m,"progress",f);k.setProgress=h;a.autoplay&&m.play()}function q(a){for(var b=[],c=0,d,e;c<V.length;c++)d=V[c],(e=a[d])&&(!0===e?b.push(d):b.push(d+'="'+e+'"'));return b.join(" ")}function j(a){function c(a){a=(b.getMousePos(a).pageX-s.pageX+s.relativeX)/n.offsetWidth;d(a)}function d(a){a=0>a?0:1<a?1:a;l(a);m.emit("seek",a)}function k(){f(o,"mousemove",c);f(o,"mouseup",k);f(o,"mouseout",j);m.emit("endSeek")}function j(a){for(a=a.relatedTarget;a&&a!=m;)a=a.parentNode;a!=m&&k()}function l(a){p.style.width=
100*a+"%"}var m=this;h.call(m);var o=a.container,s=null,q=b.html('<div class="'+v+'seek"><div class="'+v+'seek-border"><div class="'+v+'seek-background"><div class="'+v+'seek-loaded"></div><div class="'+v+'seek-played"></div></div></div></div>',o.ownerDocument),n=q.firstChild.firstChild,r=n.firstChild,p=r.nextSibling;p.style.width=0;m.element=q;e(q,"mousedown",function(a){m.emit("startSeek");a.preventDefault?a.preventDefault():a.returnValue=!1;s=b.getMousePos(a);d(s.relativeX/q.offsetWidth);e(o,"mousemove",
c);e(o,"mouseup",k);e(o,"mouseout",j)});m.setProgress=l;m.setLoadProgress=function(a){r.style.width=100*a+"%"}}function t(a){var c=this;h.call(c);var d=a.className,a=c.element=b.html('<div class="'+d+'"></div>',a.document);e(a,"click",function(a){a.preventDefault?a.preventDefault():a.returnValue=!1;c.emit("buttonClick",d)})}function s(a){if(a&&a.length)for(var b=N,c=0;c<a.length;c++){var d=a[c];if(d){var e=d.file;if(e){var f=!1;if(d.mime&&d.codecs)d=d.mime+'; codecs="'+d.codecs+'"';else{f=e.match(/\.(mp4|webm|mkv|ogv|ogg|avi)/i);
if(!f)continue;f=f[1].toLowerCase();d={mp4:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',avi:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',mkv:'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',webm:'video/webm; codecs="vp8, vorbis"',ogv:'video/ogg; codecs="theora, vorbis"',ogg:'video/ogg; codecs="theora, vorbis"'}[f]}if(d){var h;try{var k;if(!(k=b.canPlayType(d))){var j;if(j=f)j=M&&("mp4"==f||"m4v"==f)||K&&"m3u8"==f?"maybe":void 0;k=j}h=k}catch(l){}if("probably"==h||"maybe"==h)return{src:e,type:d}}}}}}a.RMB=
a.RMB||{};d=a.RMB;d.Content.VideoTag=l;var b=d.lib,h=d.EventEmitter,e=b.addEvent,f=b.removeEvent;b.inherit(l,d.AdContent);var d=l.prototype,m={progr0:{id:"25",name:"Video Play Start"},progr25:{id:"26",name:"Played 25% Of Video"},progr50:{id:"27",name:"Played 50% Of Video"},progr75:{id:"28",name:"Played 75% Of Video"},progr100:{id:"29",name:"Video Playback Complete"},play:{id:"30",name:"Play Button Press"},pause:{id:"31",name:"Pause Button Press"},stop:{id:"32",name:"Stop Button Press"},soundOn:{id:"33",
name:"Sound ON Button Press"},soundOff:{id:"34",name:"Sound OFF Button Press"},close:{id:"23",name:"Close Button Press"}},v="adform-video-",C=v+"state-",z=v+"sound-",k=b.isIPad,O=b.isIPhone,K=O||k,M=b.isAndroid,G=b.isWinPhone,H=O||G,x,N;l.supported=function(a){"undefined"==typeof x&&(N=c.createElement("video"),x=!!N.canPlayType);return!x?!1:!s(a)?!1:!0};l.READY="ready";l.LOADED="loaded";l.HIDE="hide";d.write=function(){function a(){p.play()}function c(a){var b=p.muted;d(!b);d(b);w=a;r.className=r.className.replace(zb,
" "+C+a)}function d(a){K||(p.muted=a,r.className=r.className.replace(Ab," "+z+(a?"off":"on")))}function h(a,b){if(na.length||ta){if(!b&&a!=sa){var c=100*sa,d=100*(0.5<sa-a?1.1:a);0>=c&&0<d?(ta=ta||s.list($a).length,s.emit($a)):100>=c&&100<d&&(ta=ta||s.list(u).length,s.emit(u));for(var e=0,f=na.length;e<f;e++)if(na[e]>=c&&na[e]<d){s.sendEvent(m["progr"+na[e]]);na.splice(e,1);break}}sa=a}}var s=this,q=s.data,x=s.options,y=s._element,D=q.document=s.doc,E=new o(q);b.loadCSS(D,q.css);var n=q.closeButtonAlign;
s.element('<div class="'+v+"container "+v+"device-"+(O?"iphone":k?"ipad":M?"android":"default")+'"></div>',y);var y=s._elem,r=y.firstChild,p=E.element;r.appendChild(p);var B,I=["width:"+q.width+"px","height:"+q.height+"px"];q.poster&&(I.push("background-image:url('"+q.poster+"')"),I.push("background-size:contain"));var G=b.html('<a class="adform-video-poster" style="'+I.join(";")+'"></a>');r.appendChild(G);var g,J,N,U;if(H){G.style.position="relative";p.style.position="absolute";p.style.top="-100000px";
var I=0.25*Math.min(q.width,q.height)/90,I="scale("+I+", "+I+");",i=b.html('<div style="'+["-ms-transform:"+I,"-webkit-transform:"+I,"-o-transform:"+I,"-moz-transform:"+I].join("")+'" class="adform-video-big-play"></div>');G.appendChild(i);e(G,"click",a);q.link&&q.poster&&(B=function(){f(G,"click",a);G.removeChild(i);G.href=q.link;G.target=x.landingPageTarget})}else g=v+"play-pause",J=v+"stop",N=v+"sound",g=new t({className:g,document:D}),J=new t({className:J,document:D}),N=new t({className:N,document:D}),
U=new j({container:r}),q.link?(G.href=q.link,G.target=x.landingPageTarget):G.style.cursor="auto",B=function(){G.style.opacity=0},r.appendChild(g.element),r.appendChild(J.element),r.appendChild(N.element),r.appendChild(U.element);if(B)E.on("state",function(a){if(a=="playing"){E.off("state",arguments.callee);B()}});n&&(I=new t({className:v+"close",document:D}),I.element.appendChild(b.html('<div><div class="adform-video-close-icon">&times;</div></div>',D)),r.className+=" "+v+"stopAlign-"+n,r.appendChild(I.element),
I.on("buttonClick",function(){p.pause();s.emit(l.HIDE);s.sendEvent(m.close)}));var w=E.playbackState,V=!1,zb=RegExp("\\s*"+C+"\\S+|$"),Ab=RegExp("\\s*"+z+"\\S+|$");d(s.data.muted);c("stoped");E.on("state",function(a){V||c(a)});var sa=0,na=[0,25,50,75,100],ta=!1,$a="video:start",u="video:end";H?(E.on("timeupdate",h),e(p,"ended",function(){sa=0.9;h(0)}),M&&e(p,"click",function(){p.play()})):(e(p,"volumechange",function(){d(p.muted)}),E.on("timeupdate",function(a){if(!V){h(a);U.setProgress(a)}}),E.on("loadProgress",
U.setLoadProgress),g.on("buttonClick",function(){if(w=="playing"){p.pause();s.sendEvent(m.pause)}else{p.play();s.sendEvent(m.play)}}),J.on("buttonClick",function(){w=="playing"&&p.pause();E.setProgress(0);s.sendEvent(m.stop)}),U.on("seek",function(a){E.setProgress(a);h(a,true)}),U.on("startSeek",function(){V=true;p.pause()}),U.on("endSeek",function(){V=false;w=="playing"&&p.play()}),N.on("buttonClick",function(){d(!p.muted);p.muted?s.sendEvent(m.soundOff):s.sendEvent(m.soundOn)}));s.pause=function(){p.pause()};
s.play=function(){if(!p.src){p.src=E.source.src;p.load()}p.play()};y.appendChild(r);s.created=!0;s.emit("ready");s.emit("loaded")};d.show=function(){this._element&&!this.created&&this.write()};d.hide=function(){this.created&&(this.restartAnim?this.destroy():this.pause())};d.destroy=function(){this.pause();this.element("",!1);this.created=0};d.sendEvent=function(b){b&&a.Events&&a.Events.sendEvent&&a.Events.sendEvent(this.xId,b.id,this.assetId,b.name,"")};b.inherit(o,h);var V="id,class,width,height,controls,autoplay,poster".split(",");
b.inherit(j,h);b.inherit(t,h)})(Adform=window.Adform||{},window,document);
(function(a){function d(c,j){d.super_.call(this,c,j);this.created=!1;this.data=j;this.adId=l.gid("Adform");this.data.id=this.id="ad"+this.adId;this.assetId=j.assetId||0;a.Log&&a.Log.pushMessage(["AssetType_image"],"",{bn:c.bn})}a.RMB=a.RMB||{};var c=a.RMB;c.Content.ImageTag=d;var l=c.lib,o=l.addEvent;l.inherit(d,c.AdContent);c=d.prototype;d.supported=function(){return!0};d.READY="ready";d.LOADED="loaded";d.HIDE="hide";c.show=function(){this._element&&!this.created&&this.write()};c.hide=function(){};
c.write=function(){var a=this,c=a.data,d=a._element,s=a.options,b=c.useClose,h='<img src="'+c.src+'" border="0" id="'+c.id+'" width="'+c.width+'" height="'+c.height+'" alt="" style="cursor:pointer" />';c.link&&(h='<a href="'+c.link+'" target="'+s.landingPageTarget+'">'+h+"</a>");b&&(h+='<img src="'+s.scriptsBase+'assets/images/close-sprite.png" style="width:50px!important;height:50px!important;position:absolute!important;top:0!important;right:0!important;padding:0!important;margin:0!important;cursor:pointer;">');
a.element(h,d);c=l.byTag(a._elem,"img");o(c[0],"load",function(){a.emit("loaded")});b&&o(c[1],"click",function(){a.emit("hide",!0)});a.created=!0;a.emit("ready")};c.destroy=function(){if(this._elem){var a=l.byTag(this._elem,"img")[0];a.src=a.src}this.element("",!1);this.created=!1}})(Adform=window.Adform||{},window,document);
(function(a){function d(c,b){var h=this;d.super_.call(h,c,b);h.id="ad"+o.gid("Adform");j.setupPolite.call(h);h.video=!1;j.setCallbacks(h,h.external={});h.external.resize=function(a,c){b.height=a;b.width=c;var d=h.element();if(d&&(d=o.byTag(d,"iframe")[0]))d.height=d.width="100%";h._adbox&&h._adbox.set({width:a,height:c})};h.external.setLayout=function(a){h.external.resize(a.width,a.height);var b=a.type&&o.isMobile&&(o.isIOS||o.isAndroid);h._adbox&&b&&h._adbox.reset(a)};h.sharedEvents=new q;var e=
h.flashvars=b.flashvars,b=o.extend({},b);e.expandTime=c.showTime||0;e.collapseTime=c.hideTime||0;e.behavior=c.behavior;var f=c.landingPageTarget;e.landingPageTarget="_self"==f?"_parent":f;if(f=c.userParams)for(var m in f)f.hasOwnProperty(m)&&!(m in e)&&(e[m]=f[m]);b.id=h.id;h.data=b;h.assetId=b.assetId||0;h.state(t);h.once(a.PAGE_LOAD_COMPLETE,h.write);a.Log&&a.Log.pushMessage(["AssetType_html"],"",{bn:c.bn});var v;h.on(j.INSCREEN_INIT,function(){var a=l(c.xId),b=j.INSCREEN_UPDATE;v||(v=!0,a.on("change",
function(a){h.callSwfMethod(b,a)}));a={visible:a.get("visible"),percent:a.get("percent"),loaded:a.get("loaded")};h.callSwfMethod(b,a)})}a.RMB=a.RMB||{};var c=a.RMB;c.Content.HTML=d;var l=c.EngagementAPI,o=c.lib,q=c.EventEmitter,j=c.Content.FlashTag,t="initial";o.inherit(d,c.AdContent);d.READY="ready";d.supported=function(){return!o.isIOS&&!o.isAfmaSDK&&(o.isAndroid||o.isMobile&&!o.isIE)?o.isSafari||o.isChrome||o.isOperaMobile||o.isFF||o.isInternet||o.isAndroidApp||o.isOperaWebKit:!0};c=d.prototype;
c.show=function(){var a=this._element;this.write();setTimeout(function(){a&&(a.style.background="")},100);this.element().style.width=this._width;this.state("visible")};c.hide=function(){var a=this._element;this.state("hidden");a&&this.created&&(this.callSwfMethod("pauseVideo"),a=this.element().style,this._width=a.width,a.width=0)};c.write=function(){var c=this,b=c._element;if(b&&!c.created){var d=c.options,e=c.data,f=c.win,j=o.gid("AdformWin"),l=e.src.replace(/[^\/]+$/,"");f[j]=function(b){function e(){f.close()}
c._contentWindow=b;var f=b.document,j=c.flashvars;b._Adform=a;b._AdformContent=c;var l=c.options.scriptsBase;b.API_URL=l+"rmb/Adform.DHTML.js?bv="+j.bv;var m='<script src="'+l+"rmb/Adform.WriteHelper.js?bv="+j.bv+'"><\/script>',q=[],t,v=function(a){f._write(a+"<script>document._finish();<\/script>")};f._write=f.write;f.write=o.isIE?function(a){var a=a+"",b;q.length?q.splice(-1,0,a):(b=a.match(/(<\!--[\s\S]*?--\>)|(<script(?:\s+[^>]*)?>[\s\S]*?<\/script>)/i))?(a=b[2],b=RegExp.leftContext+b[0],q.unshift(RegExp.rightContext),
a?f._write(b+(a.match(/^<script[^>]+?src/i)?m:"<script>document._continue();<\/script>")):(f._write(b),f._continue())):v(a)}:v;f._continue=function(){var a=q.join("");q.length=0;f.write(a)};f._writeln=f.writeln;f.writeln=function(a){f.write(a+"\r\n")};f._finish=function(){clearTimeout(t);t=setTimeout(e,10)};var C;o.addEvent(b,"load",function(){if(!C){C=!0;o.removeEvent(b,"load",arguments.callee);var e=a.ADFEventsInstance;if(e&&e.addElement){var k=f.documentElement.id=o.gid("adform-dhtml-");e.addElement(d.xId,
[k],b)}c.emit("loaded")}})};var q="t"+j;f[q]=function(a){var b=a.contentWindow.document;b.close();(!b||!o.byTag(b,"base")[0])&&setTimeout(function(){b.open();b.write('<!DOCTYPE html><base href="'+l+'"><script>parent.'+j+"&&parent."+j+'(window)<\/script><script src="'+e.src+'"><\/script>')},0)};b=c.element('<iframe onload="'+q+"&&"+q+'(this)" width="'+e.width+'" height="'+e.height+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>',
b).style;c._width=b.width;b.width=0;c.created=(new Date).getTime();c.emit("ready")}};c.destroy=function(){if(this._elem&&this.created){this.state("destroyed");var c=o.byTag(this._elem,"iframe")[0],b=c.contentWindow||this._contentWindow,d=a.ADFEventsInstance;d&&d.removeElement&&b.document&&d.removeElement(this.options.xId,[b.document.documentElement.id],b);this.docCloseTimer=clearTimeout(this.docCloseTimer);b.cleanupAdform&&b.cleanupAdform();b._AdformContent=b._Adform=null;this.sharedEvents.clear();
o.isIE&&(c.src="about:blank");this.element("",!1);this.created=0}};c.callSwfMethod=function(a){var b=this.sharedEvents;b.emit.apply(b,arguments);this.emit("call:"+a)};c.state=function(a){var b=this._state,c;a&&a!=b&&(this._state=a,(c=this.sharedEvents).emit("changed:state",a),"visible"==a?c.emit("show"):"visible"==b&&c.emit("hide"));return this._state}})(Adform=window.Adform||{},window,document);
(function(a,d,c){function l(a){var f=this;l.super_.call(f,a);var m,o=!1,C=a.flash,z=a.video,k=a.image,O=a.polite,K=a.html,a=a.options;if(C&&q.supported(C.version))m=new q(a,C),o=!0;else if(K&&s.supported())m=new s(a,K);else if(z&&j.supported(z.sources))m=new j(a,z);else if(k&&t.supported())m=new t(a,k),o=!C;else return;var M=f.adBox=(new b).publish("adBox",f);a.hidden&&f.hide();O&&t.supported()?(O=new t(a,O),O.style({position:"absolute",top:0,left:0,zIndex:1}),M.content(O,!0),O.on(h,function(){O.off(h,
arguments.callee);M.content(m);if(m instanceof q)m.on(q.LOADED,function(){O.clear()});else O.clear()})):M.content(m,!0);f.onEngage=function(){f.onEngage=null;M.content().emit(h)};f.setupEngagement(M);C=m.data;a.iab&&(z=d.frameElement.style,z.width=C.width+"px",z.height=C.height+"px");z=a.iframeAPI;z.hasAPI&&z.register(C);C={position:a.position};a.$tag&&(C.before=a.$tag);M.draw(c,C);f.setupUtils(M.id,o?M.id:null);f.setupGateway(M)}a.RMB=a.RMB||{};var o=a.RMB;o.Type.Standard=l;var q=o.Content.FlashTag,
j=o.Content.VideoTag,t=o.Content.ImageTag,s=o.Content.HTML,b=o.AdBox,h=a.PAGE_LOAD_COMPLETE;o.lib.inherit(l,o.AdConstructor);a=l.prototype;a.BANNER_TYPE="Standard Banner";a.destroy=function(){this.adBox&&this.adBox.destroy();this.adBox=null};a.show=function(){this._hidden&&(this._hidden=!1,this.adBox.set("visible",!0))};a.hide=function(){this._hidden||(this._hidden=!0,this.adBox.set("visible",!1),this.reload())}})(Adform=window.Adform||{},window,document);Adform.RMB.AdConstructor.build();