/* JS */ gapi.loaded_2(function(_){var window=this;
(0,_.E)("gapi.plusone.render",_.kv);(0,_.E)("gapi.plusone.go",_.lv);
_.Bh=(window.gapi||{}).load;
_.xn=(0,_.Ja)(_.Wa,"rw",(0,_.Ka)());
var yn=function(a,b){var c=_.xn[a];c&&c.state<b&&(c.state=b)};var zn=function(a){a=(a=_.xn[a])?a.oid:void 0;if(a){var b=_.Ga.getElementById(a);b&&b.parentNode.removeChild(b);delete _.xn[a];zn(a)}};_.An=function(a){a=a.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.Bn=function(a){var b=a.clientWidth;return"position:absolute;top:-10000px;width:"+(b?b+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.Cn=function(a,b){var c={},d=a.Xa(),e=b&&b.width,f=b&&b.height,g=b&&b.verticalAlign;g&&(c.verticalAlign=g);e||(e=d.width||a.width);f||(f=d.height||a.height);d.width=c.width=e;d.height=c.height=f;d=a.Ga();e=a.fa();yn(e,2);t:{e=a.La();c=c||{};if(_.Wa.oa){var k=d.id;if(k){f=(f=_.xn[k])?f.state:void 0;if(1===f||4===f)break t;zn(k)}}(f=e.nextSibling)&&f.getAttribute&&f.getAttribute("data-gapistub")&&(e.parentNode.removeChild(f),e.style.cssText="");var f=c.width,g=c.height,l=e.style;l.textIndent="0";l.margin=
"0";l.padding="0";l.background="transparent";l.borderStyle="none";l.cssFloat="none";l.styleFloat="none";l.lineHeight="normal";l.fontSize="1px";l.verticalAlign="baseline";e=e.style;e.display="inline-block";d=d.style;d.position="static";d.left=0;d.top=0;d.visibility="visible";f&&(e.width=d.width=f+"px");g&&(e.height=d.height=g+"px");c.verticalAlign&&(e.verticalAlign=c.verticalAlign);k&&yn(k,3)}(k=b?b.title:null)&&a.Ga().setAttribute("title",k)};_.Dn=function(a){var b=a.La();b&&b.removeChild(a.Ga())};
_.En=function(a){a.where=(0,_.An)(a);var b=a.messageHandlers=a.messageHandlers||{},c=function(a){(0,_.Cn)(this,a)};b._ready=c;b._renderstart=c;var d=a.onClose;a.onClose=function(a){d&&d.call(this,a);(0,_.Dn)(this)};a.onCreate=function(a){a=a.Ga();a.style.cssText=(0,_.Bn)(a)}};

_.rc=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(g){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Jb=function(b){a(2,b)};_.Hb=function(b){a(3,b)};_.qc=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

_.M=_.M||{};(function(){var a=[];_.M.kQ=function(b){a.push(b)};_.M.yQ=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
_.xc=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&(0,_.db)(a());return{register:function(a,c,d){d&&d((0,_.G)())},get:function(a){return(0,_.G)(a)},update:function(a,c){if(c)throw"Config replacement is not supported";(0,_.db)(a)},eb:function(){}}}();
(0,_.E)("gadgets.config.register",_.xc.register);(0,_.E)("gadgets.config.get",_.xc.get);(0,_.E)("gadgets.config.init",_.xc.eb);(0,_.E)("gadgets.config.update",_.xc.update);
var Lc;var Hc;Hc=function(){var a=_.Ga.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Jc=function(a){if(Hc())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Fa.addEventListener?(_.Fa.addEventListener("load",c,!1),_.Fa.addEventListener("DOMContentLoaded",c,!1)):_.Fa.attachEvent&&(_.Fa.attachEvent("onreadystatechange",function(){Hc()&&c.apply(this,arguments)}),_.Fa.attachEvent("onload",c))}};_.Kc=function(a,b){if(!Hc())try{a()}catch(c){}(0,_.Jc)(b)}; Lc=Lc||{};Lc.Kx=null;Lc.zw=null;Lc.rm=null;Lc.frameElement=null;
Lc=Lc||{};
Lc.Xr||(Lc.Xr=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.Gc)(a.data);if(b&&b.f){(0,_.qc)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.O.Mh(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?(0,_.Hb)("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{oj:function(){return"wpm"},A:function(){return!0},eb:function(f,g){_.xc.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=g;a(b);d("..",!0);return!0},kb:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.O.Mh(a),e=_.O.mt(a);d?window.setTimeout(function(){var a=(0,_.Fc)(c);(0,_.qc)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&(0,_.Hb)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
Lc=Lc||{};
Lc.Cl||(Lc.Cl=function(){function a(a,b){I[b]=I[b]||function(){a.apply({},arguments)}}function b(){if(null===x&&window.document.body&&m){var a=m+"?cb="+Math.random()+"&origin="+H+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+l+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;x=c.firstChild}++y;null!==w&&(null!==x||50<=y)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){z[".."]||(k(".."),C++,50<=C&&null!==F?(window.clearTimeout(F),F=null):F=window.setTimeout(c,100))}function d(){if(null!==x&&x.setup)for(;0<v.length;){var a=v.shift(),b=a.eI;x.setup(a.Ei,".."===b?_.O.Kn:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){z[".."]||null!==
F||(F=window.setTimeout(c,100))}function f(a,b,c){b=_.O.Mh(a);var d=_.O.lj(a);x["sendMessage_"+(".."===a?_.O.Kn:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(x,(0,_.Fc)(c),b);return!0}function g(a,b){var c=(0,_.Gc)(a),d=c._scr;d?(t(d,!0),z[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){p(c,b)},0)}function k(a,b){var c=_.O.Kn,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l="___xpcswf",m=null,n=!1,p=null,t=null,x=null,v=[],w=null,y=0,C=0,F=null,z={},H=window.location.protocol+"//"+window.location.host,
I;window.___jsl=window.___jsl||{};I=window.___jsl._fm={};_.xc.register("rpc",null,function(a){n&&(m=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(g,"receiveMessage");return{oj:function(){return"flash"},A:function(){return!0},eb:function(a,b){p=a;t=b;return n=!0},kb:function(a,c){v.push({Ei:c,eI:a});null===x&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,PB:g,D:d,F:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.O&&_.O||(_.O=window.gadgets.rpc,_.O.config=_.O.config,_.O.register=_.O.register,_.O.Yg=_.O.unregister,_.O.xx=_.O.registerDefault,_.O.cz=_.O.unregisterDefault,_.O.lu=_.O.forceParentVerifiable,_.O.call=_.O.call,_.O.wj=_.O.getRelayUrl,_.O.Qe=_.O.setRelayUrl,_.O.Zm=_.O.setAuthToken,_.O.nk=_.O.setupReceiver,_.O.lj=_.O.getAuthToken,_.O.Sq=_.O.removeReceiver,_.O.Ju=_.O.getRelayChannel,_.O.qi=_.O.receive,_.O.tx=_.O.receiveSameDomain,_.O.xa=_.O.getOrigin,
_.O.Mh=_.O.getTargetOrigin,_.O.mt=_.O._getTargetWin,_.O.OB=_.O._parseSiblingId);else{_.O=function(){function a(a,b){if(!P[a]){var c=wa;b||(c=ha);P[a]=c;for(var d=ca[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=F[a];c.call(a,f.f,f)}ca[a]=[]}}function b(){function a(){ra=!0}ua||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),ua=!0)}function c(a,c,d,e,f){F[c]&&F[c]===d||((0,_.Hb)("Invalid gadgets.rpc token. "+
F[c]+" vs "+d),La(c,2));f.onunload=function(){I[c]&&!ra&&(La(c,1),_.O.Sq(c))};b();e=(0,_.Gc)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(F[b.f]&&F[b.f]!==b.t&&((0,_.Hb)("Invalid gadgets.rpc token. "+F[b.f]+" vs "+b.t),La(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.O.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,g;try{g=
e(f)}catch(k){}f&&g==d||(f=c);b.referer=f}d=(w[b.s]||w[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.O.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==
a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function g(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&
b.contentWindow?b.contentWindow:null}function k(a,b){if(!0!==I[a]){"undefined"===typeof I[a]&&(I[a]=0);var c=g(a);".."!==a&&null==c||!0!==wa.kb(a,b)?!0!==I[a]&&10>I[a]++?window.setTimeout(function(){k(a,b)},500):(P[a]=ha,I[a]=!0):I[a]=!0}}function l(a){(a=y[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=
window.location.protocol+b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));y[a]=b;"undefined"!==typeof c&&(C[a]=!!c)}function n(a,b){b=b||"";F[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);Y=a[0]||"none";va=a[1]||"origin"}function t(b){"true"===String(b.useLegacyProtocol)&&(wa=Lc.rm||ha,wa.eb(d,a))}function x(a,b){function c(d){d=d&&d.rpc||{};p(d);var f=d.parentRelayUrl||"",f=e(T.parent||b)+
f;m("..",f,"true"===String(d.useLegacyProtocol));t(d);n("..",a)}!T.parent&&b?c({}):_.xc.register("rpc",null,c)}function v(a,b,c){if(".."===a)x(c||T.rpctoken||T.ifpctok||"",b);else t:{var d=null;if("/"!=a.charAt(0)){if(!_.M)break t;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.O.xa(d);m(a,b);b=_.M.tb(d);n(a,c||b.rpctoken)}}var w={},y={},C={},F={},z=0,H={},I={},T={},P={},ca={},Y=null,va=null,Q=window.top!==window.self,ja=window.name,La=function(){},Z=window.console,
da=Z&&Z.log&&function(a){Z.log(a)}||function(){},ha=function(){function a(b){return function(){da(b+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.M&&(T=_.M.tb());var ra=!1,ua=!1,wa=function(){if("flash"==T.rpctx)return Lc.Cl;if("rmr"==T.rpctx)return Lc.Kx;var a="function"===typeof window.postMessage?Lc.Xr:"object"===typeof window.postMessage?Lc.Xr:window.ActiveXObject?Lc.Cl?Lc.Cl:Lc.zw?Lc.zw:
Lc.rm:0<window.navigator.userAgent.indexOf("WebKit")?Lc.Kx:"Gecko"===window.navigator.product?Lc.frameElement:Lc.rm;a||(a=ha);return a}();w[""]=function(){da("Unknown RPC service: "+this.s)};w.__cb=function(a,b){var c=H[a];c&&(delete H[a],c.call(this,b))};return{config:function(a){"function"===typeof a.Qx&&(La=a.Qx)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");w[a]=b},Yg:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");
delete w[a]},xx:function(a){w[""]=a},cz:function(){delete w[""]},lu:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=ja:"/"==a.charAt(0)&&(e=_.O.xa(window.location.href),e="/"+ja+(e?"|"+e:""));++z;c&&(H[z]=c);var g={s:b,f:e,c:c?z:0,a:Array.prototype.slice.call(arguments,3),t:F[a],l:!!C[a]},k;t:if("bidir"===Y||"c2p"===Y&&".."===a||"p2c"===Y&&".."!==a){k=window.location.href;var l="?";if("query"===va)l="#";else if("hash"===va)break t;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,
l)}else k=null;k&&(g.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=P[a])||null===f(a)||(k=wa),0===b.indexOf("legacy__")&&(k=wa,g.s=b.substring(8),g.c=g.c?g.c:z),g.g=!0,g.r=e,k?(C[a]&&(k=Lc.rm),!1===k.call(a,e,g)&&(P[a]=ha,wa.call(a,e,g))):ca[a]?ca[a].push(g):ca[a]=[g]},wj:l,Qe:m,Zm:n,nk:v,lj:function(a){return F[a]},Sq:function(a){delete y[a];delete C[a];delete F[a];delete I[a];delete P[a]},Ju:function(){return wa.oj()},qi:function(a,b){4<a.length?wa.PB(a,d):c.apply(null,a.concat(b))},
tx:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},0)},xa:e,Mh:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:b=".."==a?T.parent:window.document.getElementById(a).src;return e(b)},eb:function(){!1===wa.eb(d,a)&&(wa=ha);Q?v(".."):_.xc.register("rpc",null,function(a){a=a.rpc||{};p(a);t(a)})},mt:g,OB:f,A:"__ack",Kn:ja||"..",D:0,C:1,B:2}}();_.O.eb()};
_.O.config({Qx:function(a){throw Error("h`"+a);}});_.qc=_.wc;(0,_.E)("gadgets.rpc.config",_.O.config);(0,_.E)("gadgets.rpc.register",_.O.register);(0,_.E)("gadgets.rpc.unregister",_.O.Yg);(0,_.E)("gadgets.rpc.registerDefault",_.O.xx);(0,_.E)("gadgets.rpc.unregisterDefault",_.O.cz);(0,_.E)("gadgets.rpc.forceParentVerifiable",_.O.lu);(0,_.E)("gadgets.rpc.call",_.O.call);(0,_.E)("gadgets.rpc.getRelayUrl",_.O.wj);(0,_.E)("gadgets.rpc.setRelayUrl",_.O.Qe);(0,_.E)("gadgets.rpc.setAuthToken",_.O.Zm);(0,_.E)("gadgets.rpc.setupReceiver",_.O.nk);
(0,_.E)("gadgets.rpc.getAuthToken",_.O.lj);(0,_.E)("gadgets.rpc.removeReceiver",_.O.Sq);(0,_.E)("gadgets.rpc.getRelayChannel",_.O.Ju);(0,_.E)("gadgets.rpc.receive",_.O.qi);(0,_.E)("gadgets.rpc.receiveSameDomain",_.O.tx);(0,_.E)("gadgets.rpc.getOrigin",_.O.xa);(0,_.E)("gadgets.rpc.getTargetOrigin",_.O.Mh);

_.El=(0,_.Ka)();
_.Hn=function(a){var b=window;a=(a||b.location.href).match(/.*(\?|#|&)usegapi=([^&#]+)/)||[];return"1"===(0,window.decodeURIComponent)(a[a.length-1]||"")};
var On;var Nn;var Mn;var Ln;_.In={callback:1,clientid:1,cookiepolicy:1,openidrealm:-1,includegrantedscopes:-1,requestvisibleactions:1,scope:1};_.Jn=!1;
_.Kn=function(){if(!_.Jn){for(var a=window.document.getElementsByTagName("meta"),b=0;b<a.length;++b){var c=a[b].name.toLowerCase();if((0,_.Ob)(c,"google-signin-")){var c=c.substring(14),d=a[b].content;_.In[c]&&d&&(_.El[c]=d)}}if(window.self!==window.top){var a=window.document.location.toString(),e;for(e in _.In)0<_.In[e]&&(b=(0,_.Ra)(a,e,""))&&(_.El[e]=b)}_.Jn=!0}e=(0,_.Ka)();(0,_.Bj)(_.El,e);return e};Ln=function(a){return function(b,c){return a?(0,_.fk)()[c]||a[c]||"":(0,_.fk)()[c]||""}}; Mn={button:!0,div:!0,span:!0};Nn=function(a){return(0,_.Ja)(_.Wa,"watt",(0,_.Ka)())[a]};On=function(a){var b=(0,_.Ja)(_.Wa,"sws",[]);return 0<=_.sc.call(b,a)};
var Pn;Pn=function(a){var b;a.match(/^https?%3A/i)&&(b=(0,window.decodeURIComponent)(a));return(0,_.Nj)(window.document,b?b:a)};_.Qn=function(a){a=a||"canonical";for(var b=window.document.getElementsByTagName("link"),c=0,d=b.length;c<d;c++){var e=b[c],f=e.getAttribute("rel");if(f&&f.toLowerCase()==a&&(e=e.getAttribute("href"))&&(e=Pn(e))&&null!=e.match(/^https?:\/\/[\w\-\_\.]+/i))return e}return window.location.href};_.Rn=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Sn=function(a,b,c,d){return(a="string"==typeof a?a:void 0)?Pn(a):(0,_.Qn)(d)};_.Tn=function(a,b,c){null==a&&c&&(a=c.db,null==a&&(a=c.gwidget&&c.gwidget.db));return a||void 0};_.Un=function(a,b,c){null==a&&c&&(a=c.ecp,null==a&&(a=c.gwidget&&c.gwidget.ecp));return a||void 0};
_.Vn=function(a,b){return(0,_.Sn)(a,0,0,b.action?void 0:"publisher")};var eo;var fo;var co;var bo;var ao;var $n;var Zn;var Yn;var Xn;var Wn;Wn={hB:"se"};Xn={hB:"ad"};Yn={ad:{"true":"1","false":"2"}};Zn={post:!0};$n={style:"position:absolute;top:-10000px;width:450px;margin:0px;border-style:none"};ao="onPlusOne _ready _close _open _resizeMe _renderstart oncircled drefresh erefresh".split(" ");bo=(0,_.Ja)(_.Wa,"WI",(0,_.Ka)());co=["style","data-gapiscan"];
fo=function(a){for(var b=(0,_.Ka)(),c=0!=a.nodeName.toLowerCase().indexOf("g:"),d=0,e=a.attributes.length;d<e;d++){var f=a.attributes[d],g=f.name,k=f.value;0<=_.sc.call(co,g)||c&&0!=g.indexOf("data-")||"null"===k||"specified"in f&&!f.specified||(c&&(g=g.substr(5)),b[g.toLowerCase()]=k)}a=a.style;(c=eo(a&&a.height))&&(b.height=String(c));(a=eo(a&&a.width))&&(b.width=String(a));return b};
_.ho=function(a,b,c,d,e,f){var g;c.rd?g=b:(g=window.document.createElement("div"),b.setAttribute("data-gapistub",!0),g.style.cssText="position:absolute;width:450px;left:-10000px;",b.parentNode.insertBefore(g,b));f.siteElement=g;g.id||(g.id=(0,_.go)(a));b=(0,_.Ka)();b[">type"]=a;(0,_.Bj)(c,b);a=(0,_.jk)(d,g,e);f.iframeNode=a;f.id=a.getAttribute("id")};_.go=function(a){(0,_.Ja)(bo,a,0);return"___"+a+"_"+bo[a]++}; eo=function(a){var b=void 0;"number"===typeof a?b=a:"string"===typeof a&&(b=(0,window.parseInt)(a,10));return b};
var io,jo,ko,lo,mo=/(?:^|\s)g-((\S)*)(?:$|\s)/,no={plusone:!0,autocomplete:!0,profile:!0,signin:!0};io=(0,_.Ja)(_.Wa,"SW",(0,_.Ka)());jo=(0,_.Ja)(_.Wa,"SA",(0,_.Ka)());ko=(0,_.Ja)(_.Wa,"SM",(0,_.Ka)());lo=(0,_.Ja)(_.Wa,"FW",[]);
var oo=function(a,b){var c;"string"===typeof a?c=window.document.getElementById(a):c=a;return c||b},ro=function(a,b){var c,d,e,f;(0,_.po)("ps0");var g=oo(a,_.Ga);d=_.Ga.documentMode;if(g.querySelectorAll&&(!d||8<d)){d=b?[b]:(0,_.nb)(io).concat((0,_.nb)(jo)).concat((0,_.nb)(ko));e=[];for(var k=0;k<d.length;k++){var l=d[k];e.push(".g-"+l,"g\\:"+l)}d=g.querySelectorAll(e.join(","))}else d=g.getElementsByTagName("*");g=(0,_.Ka)();for(e=0;e<d.length;e++){k=d[e];var m=k,l=b,n=m.nodeName.toLowerCase(),p=
void 0;m.getAttribute("data-gapiscan")?l=null:(0==n.indexOf("g:")?p=n.substr(2):(m=(m=String(m.className||m.getAttribute("class")))&&mo.exec(m))&&(p=m[1]),l=!p||!(io[p]||jo[p]||ko[p])||l&&p!==l?null:p);l&&(no[l]||0==k.nodeName.toLowerCase().indexOf("g:")||0!=(0,_.nb)(fo(k)).length)&&(k.setAttribute("data-gapiscan",!0),(0,_.Ja)(g,l,[]).push(k))}for(c in g)lo.push(c);(0,_.po)("ps1");if(c=lo.join(":"))try{_.Oa.load(c,void 0)}catch(t){(0,_.vc)(t);return}k=[];for(f in g)for(e=g[f],d=0,c=e.length;d<c;d++)l= e[d],qo(f,l,fo(l),k,c)};
var so=function(a,b){var c=Nn(a);b&&c?(c(b),(c=b.iframeNode)&&c.setAttribute("data-gapiattached",!0)):_.Oa.load(a,function(){var c=Nn(a),e=b&&b.iframeNode;e&&c?(c(b),e.setAttribute("data-gapiattached",!0)):(0,_.Oa[a].go)(e&&e.parentNode)})},qo=function(a,b,c,d,e,f){switch(to(b,a,f)){case 0:a=ko[a]?a+"_annotation":a;d={};d.iframeNode=b;d.userParams=c;so(a,d);break;case 1:if(b.parentNode){for(var g in c){if(f=(0,_.Ma)(c,g))f=c[g],f=!!f&&"object"===typeof f&&(!f.toString||f.toString===Object.prototype.toString||
f.toString===Array.prototype.toString);if(f)try{var k=(0,_.Fc)(c[g]);600>k.length?c[g]=k:delete c[g]}catch(l){delete c[g]}}g=!0;c.dontclear&&(g=!1);delete c.dontclear;var m,n,k={},p=f=a;"plus"==a&&c.action&&(f=a+"_"+c.action,p=a+"/"+c.action);(f=(0,_.G)("iframes/"+f+"/url"))||(f=":im_socialhost:/:session_prefix::im_prefix:_/widget/render/"+p+"?usegapi=1");for(n in Wn)if(p=Wn[n],c[p])k[p]=p+"/"+c[p]+"/";else{var t=Xn[n];t&&c[t]&&(k[p]=p+"/"+Yn[t][c[t]]+"/")}n=(0,_.Nj)(_.Ga,f.replace(_.ek,Ln(k)));f=
"iframes/"+a+"/params/";k={};(0,_.Bj)(c,k);(p=(0,_.G)("lang")||(0,_.G)("gwidget/lang"))&&(k.hl=p);Zn[a]||(k.origin=(0,_.Rn)());k.exp=(0,_.G)(f+"exp");if(f=(0,_.G)(f+"location"))for(p=0;p<f.length;p++)t=f[p],k[t]=_.Fa.location[t];switch(a){case "plus":case "follow":k.url=(0,_.Vn)(k.href,c);delete k.href;break;case "plusone":f=(f=c.href)?Pn(f):(0,_.Qn)();k.url=f;k.db=(0,_.Tn)(c.db,0,(0,_.G)());k.ecp=(0,_.Un)(c.ecp,0,(0,_.G)());delete k.href;break;case "signin":k.url=(0,_.Qn)()}_.Wa.ILI&&(k.iloader=
"1");delete k["data-onload"];delete k.rd;for(var x in Wn)f=Wn[x],k[f]&&delete k[f];k.gsrc=(0,_.G)("iframes/:source:");x=(0,_.G)("inline/css");"undefined"!==typeof x&&0<e&&x>=e&&(k.ic="1");x=/^#|^fr-/;e={};for(var v in k)(0,_.Ma)(k,v)&&x.test(v)&&(e[v.replace(x,"")]=k[v],delete k[v]);v="q"==(0,_.G)("iframes/"+a+"/params/si")?k:e;x=(0,_.Kn)();for(m in x)!(0,_.Ma)(x,m)||(0,_.Ma)(k,m)||(0,_.Ma)(e,m)||(v[m]=x[m]);m=[].concat(ao);v=(0,_.G)("iframes/"+a+"/methods");(0,_.ib)(v)&&(m=m.concat(v));for(var w in c)(0,_.Ma)(c,
w)&&/^on/.test(w)&&("plus"!=a||"onconnect"!=w)&&(m.push(w),delete k[w]);delete k.callback;e._methods=m.join(",");m=(0,_.Oj)(n,k,e);v={allowPost:1,attributes:$n};v.dontclear=!g;w={};w.userParams=c;w.url=m;w.type=a;(0,_.ho)(a,b,c,m,v,w);b=w.id;c=(0,_.Ka)();c.id=b;c.userParams=w.userParams;c.url=w.url;c.type=w.type;c.state=1;_.xn[b]=c;b=w}else b=null;b&&((c=b.id)&&d.push(c),so(a,b))}},to=function(a,b,c){if(a&&1===a.nodeType&&b){if(c)return 1;if(ko[b]){if(Mn[a.nodeName.toLowerCase()])return(a=a.innerHTML)&& a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?0:1}else{if(jo[b])return 0;if(io[b])return 1}}return null};
(0,_.Ja)(_.Oa,"platform",{}).go=function(a,b){ro(a,b)};var Eo;var Do;var Co;var Ao;var zo;var yo;var xo;var uo=(0,_.Ja)(_.Wa,"perf",(0,_.Ka)()),vo=(0,_.Ja)(uo,"g",(0,_.Ka)()),wo=(0,_.Ja)(uo,"i",(0,_.Ka)());(0,_.Ja)(uo,"r",[]);xo=(0,_.Ka)();yo=(0,_.Ka)();zo=function(a,b,c,d){xo[c]=xo[c]||!!d;(0,_.Ja)(yo,c,[]);yo[c].push([a,b])};Ao=function(a,b,c){var d=uo.r;"function"===typeof d?d(a,b,c):d.push([a,b,c])};_.po=function(a,b){vo[a]=b||(new Date).getTime();Ao(a)};Co=function(a,b,c,d){if("_p"==b)throw Error("w");(0,_.Bo)(a,b,c,d)};
_.Bo=function(a,b,c,d){Do(b,c)[a]=d||(new Date).getTime();Ao(a,b,c)};Do=function(a,b){var c=(0,_.Ja)(wo,a,(0,_.Ka)());return(0,_.Ja)(c,b,(0,_.Ka)())};Eo=function(a,b,c){var d=null;b&&c&&(d=Do(b,c)[a]);return d||vo[a]};_.Fo=function(a,b,c,d,e,f){Co("wrt0",a,b,c);Co("wrt1",a,b,d);Co("wrt2",a,b,e);Co("wrt3",a,b,f)};
(function(){function a(a){this.t={};this.tick=function(a,b,c){this.t[a]=[void 0!=c?c:(new Date).getTime(),b];if(void 0==c)try{window.console.timeStamp("CSI/"+a)}catch(d){}};this.tick("start",null,a)}var b;window.performance&&(b=window.performance.timing);var c=b?new a(b.responseStart):new a;window.__gapi_jstiming__={Timer:a,load:c};if(b){var d=b.navigationStart,e=b.responseStart;0<d&&e>=d&&(window.__gapi_jstiming__.srt=e-d)}if(b){var f=window.__gapi_jstiming__.load;0<d&&e>=d&&(f.tick("_wtsrt",void 0,
d),f.tick("wtsrt_","_wtsrt",e),f.tick("tbsd_","wtsrt_"))}try{b=null,window.chrome&&window.chrome.csi&&(b=Math.floor(window.chrome.csi().pageT),f&&0<d&&(f.tick("_tbnd",void 0,window.chrome.csi().startE),f.tick("tbnd_","_tbnd",d))),null==b&&window.gtbExternal&&(b=window.gtbExternal.pageT()),null==b&&window.external&&(b=window.external.pageT,f&&0<d&&(f.tick("_tbnd",void 0,window.external.startE),f.tick("tbnd_","_tbnd",d))),b&&(window.__gapi_jstiming__.pt=b)}catch(g){}})();
if(window.__gapi_jstiming__){window.__gapi_jstiming__.yt={};window.__gapi_jstiming__.PG=1;var Go=function(a,b,c){var d=a.t[b],e=a.t.start;if(d&&(e||c))return d=a.t[b][0],void 0!=c?e=c:e=e[0],d-e};window.__gapi_jstiming__.getTick=Go;window.__gapi_jstiming__.getLabels=function(a){var b=[],c;for(c in a.t)b.push(c);return b};var Ho=function(a,b,c){var d="";window.__gapi_jstiming__.srt&&(d+="&srt="+window.__gapi_jstiming__.srt);window.__gapi_jstiming__.pt&&(d+="&tbsrt="+window.__gapi_jstiming__.pt);try{window.external&&
window.external.tran?d+="&tran="+window.external.tran:window.gtbExternal&&window.gtbExternal.tran?d+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(d+="&tran="+window.chrome.csi().tran)}catch(e){}var f=window.chrome;if(f&&(f=f.loadTimes)){f().wasFetchedViaSpdy&&(d+="&p=s");if(f().wasNpnNegotiated){var d=d+"&npn=1",g=f().npnNegotiatedProtocol;g&&(d+="&npnv="+(window.encodeURIComponent||window.escape)(g))}f().wasAlternateProtocolAvailable&&(d+="&apa=1")}var k=a.t,l=k.start,f=
[],g=[],m;for(m in k)if("start"!=m&&0!=m.indexOf("_")){var n=k[m][1];n?k[n]&&g.push(m+"."+Go(a,m,k[n][0])):l&&f.push(m+"."+Go(a,m))}if(b)for(var p in b)d+="&"+p+"="+b[p];(b=c)||(b="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");return[b,"?v=3","&s="+(window.__gapi_jstiming__.sn||"")+"&action=",a.name,g.length?"&it="+g.join(","):"",d,"&rt=",f.join(",")].join("")},Io=function(a,b,c){a=Ho(a,b,c);if(!a)return"";b=new window.Image;var d=window.__gapi_jstiming__.PG++;
window.__gapi_jstiming__.yt[d]=b;b.onload=b.onerror=function(){window.__gapi_jstiming__&&delete window.__gapi_jstiming__.yt[d]};b.src=a;b=null;return a};window.__gapi_jstiming__.report=function(a,b,c){if("prerender"==window.document.webkitVisibilityState){var d=!1,e=function(){if(!d){b?b.prerender="1":b={prerender:"1"};var f;"prerender"==window.document.webkitVisibilityState?f=!1:(Io(a,b,c),f=!0);f&&(d=!0,window.document.removeEventListener("webkitvisibilitychange",e,!1))}};window.document.addEventListener("webkitvisibilitychange", e,!1);return""}return Io(a,b,c)}};
var Jo=[73,74,77,78],Ko={g:"gapi_global",m:"gapi_module",w:"gwidget"},Lo=function(a,b){this.type=a?"_p"==a?"m":"w":"g";this.name=a;this.A=b};Lo.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.A;case "w":return this.type+"."+this.name+this.A}};
var No=function(a){var b=[];b.push("l"+((0,_.G)("isPlusUser")?"1":"0"));var c="m"+(Mo?"1":"0");b.push(c);if("m"==a.type)b.push("p"+a.A);else if("w"==a.type){var d="n"+a.A;b.push(d);"0"==a.A&&b.push(c+d)}b.push("u"+((0,_.G)("isLoggedIn")?"1":"0"));return b},Oo=new Lo,Mo=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/),Po=(0,_.Ja)(uo,"_c",(0,_.Ka)()),Qo=Math.random()<((0,_.G)("csi/rate")||0),So=function(a,b,c){for(var d=new Lo(b,c),e=(0,_.Ja)(Po,d.key(),(0,_.Ka)()),f=yo[a]||
[],g=0;g<f.length;++g){var k=f[g],l=e,m=k[0],n=a,p=b,t=c,k=Eo(k[1],p,t),n=Eo(n,p,t);l[m]=k&&n?n-k:null}xo[a]&&Qo&&(Ro(Oo),Ro(d))},To=function(a,b){b=b||[];for(var c=[],d=0;d<b.length;d++)c.push(a+b[d]);return c},Ro=function(a){var b=_.Fa.__gapi_jstiming__;b.sn=Ko[a.type];var c=new b.Timer(0),d;t:{switch(a.type){case "g":d="global";break t;case "m":d=a.A;break t;case "w":d=a.name;break t}d=void 0}c.name=d;d=!1;var e=a.key(),f=Po[e];c.tick("_start",null,0);for(var g in f)c.tick(g,"_start",f[g]),d=!0;
Po[e]=(0,_.Ka)();if(d){g=[];d=(0,_.G)("lexps");g=g.concat(To("e",d));g=g.concat(To("",No(a)));for(e=0;e<Jo.length;e++)f=Jo[e],0<=_.sc.call(d,f)&&(g=g.concat(To(f?"e"+f:"",No(a))));g=To("abc_",g);b.report(c,{e:g.join(",")})}};zo("blt","bs0","bs1");zo("psi","ps0","ps1");zo("rpcqi","rqe","rqd");zo("bsprt","bsrt0","bsrt1");zo("bsrqt","bsrt1","bsrt2");zo("bsrst","bsrt2","bsrt3");zo("mli","ml0","ml1");zo("mei","me0","me1",!0);zo("wcdi","wrs","wcdi");zo("wci","wrs","wdc");zo("wdi","wrs","wrdi");
zo("wdt","bs0","wrdt");zo("wri","wrs","wrri",!0);zo("wrt","bs0","wrrt");zo("wji","wje0","wje1",!0);zo("wjli","wjl0","wjl1");zo("whi","wh0","wh1",!0);zo("wai","waaf0","waaf1",!0);zo("wadi","wrs","waaf1",!0);zo("wadt","bs0","waaf1",!0);zo("wprt","wrt0","wrt1");zo("wrqt","wrt1","wrt2");zo("wrst","wrt2","wrt3",!0);zo("fbprt","fsrt0","fsrt1");zo("fbrqt","fsrt1","fsrt2");zo("fbrst","fsrt2","fsrt3",!0);var Uo=uo.r;if("function"!==typeof Uo){for(var Vo;Vo=Uo.shift();)So.apply(null,Vo);uo.r=So};
var Cp;var Bp;var Ap;var zp;var rp;var yp;var sp;var qp;var xp;var wp;var vp;var up;var pp;var mp;var op;var lp;var kp;var jp;var ip;var hp;var gp;var fp;var Wo=["div"],Xo="onload",Yo=!0,Zo=!0,$o=function(a){return a},ap=null,bp=function(a){var b=(0,_.G)(a);return"undefined"!==typeof b?b:(0,_.G)("gwidget/"+a)},ap=(0,_.G)();(0,_.G)("gwidget");var cp=bp("parsetags"),Xo="explicit"===cp||"onload"===cp?cp:Xo,dp=bp("google_analytics");"undefined"!==typeof dp&&(Yo=!!dp);var ep=bp("data_layer");
"undefined"!==typeof ep&&(Zo=!!ep);fp=function(){var a=this&&this.fa();a&&(_.Wa.drw=a)};gp=function(){_.Wa.drw=null};hp=function(a){return function(b){var c=a;"number"===typeof b?c=b:"string"===typeof b&&(c=b.indexOf("px"),-1!=c&&(b=b.substring(0,c)),c=(0,window.parseInt)(b,10));return c}};ip=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:null};jp=function(){return bp("lang")||"en-US"};
kp=function(a){if(!_.J.ua("attach")){var b={},c=_.J.ua("inline"),d;for(d in c)c.hasOwnProperty(d)&&(b[d]=c[d]);b.open=function(a){var b=a.Xa().renderData.id,b=window.document.getElementById(b);if(!b)throw Error("x");return c.attach(a,b)};_.J.ob("attach",b)}a.style="attach"};lp=function(){var a={};a.width=[hp(450)];a.height=[hp(24)];a.onready=[ip];a.lang=[jp,"hl"];a.iloader=[function(){return _.Wa.ILI},"iloader"];return a}();
op=function(a){var b={};b.Sc=a[0];b.Ki=-1;b.RQ="___"+b.Sc+"_";b.yI="g:"+b.Sc;b.OP="g-"+b.Sc;b.Bx=[];b.config={};b.Zk=[];b.fz={};b.qn={};var c=function(a){for(var c in a)if((0,_.Ma)(a,c)){b.config[c]=[ip];b.Zk.push(c);var d=a[c],k=null,l=null,m=null;"function"===typeof d?k=d:d&&"object"===typeof d&&(k=d.DP,l=d.rn,m=d.Pr);m&&(b.Zk.push(m),b.config[m]=[ip],b.fz[c]=m);k&&(b.config[c]=[k]);l&&(b.qn[c]=l)}},d=function(a){for(var c={},d=0;d<a.length;++d)c[a[d].toLowerCase()]=1;c[b.yI]=1;b.SF=c};a[1]&&(b.Vw=
a[1]);(function(a){b.config=a;for(var c in lp)lp.hasOwnProperty(c)&&!b.config.hasOwnProperty(c)&&(b.config[c]=lp[c])})(a[2]||{});a[3]&&c(a[3]);a[4]&&d(a[4]);a[5]&&(b.Of=a[5]);b.KQ=!0===a[6];b.CG=a[7];b.qI=a[8];b.SF||d(Wo);b.yq=function(a){b.Ki++;Co("wrs",b.Sc,String(b.Ki));var c=[],d=a.element,k=a.config,l=":"+b.Sc;":plus"==l&&a.Nf&&a.Nf.action&&(l+="_"+a.Nf.action);var m=mp(b,k),n={};(0,_.Bj)((0,_.Kn)(),n);for(var p in a.Nf)null!=a.Nf[p]&&(n[p]=a.Nf[p]);p={container:d.id,renderData:a.NG,style:"inline",
height:k.height,width:k.width};kp(p);b.Of&&(c[2]=p,c[3]=n,c[4]=m,b.Of("i",c));l=_.J.open(l,p,n,m);(0,_.np)(b,l,k,d,a.vC);c[5]=l;b.Of&&b.Of("e",c)};return b};mp=function(a,b){for(var c={},d=a.Zk.length-1;0<=d;--d){var e=a.Zk[d],f=b[a.fz[e]||e]||b[e],g=b[e];g&&f!==g&&(f=function(a,b){return function(c){b.apply(this,arguments);a.apply(this,arguments)}}(f,g));f&&(c[e]=f)}for(var k in a.qn)a.qn.hasOwnProperty(k)&&(c[k]=pp(c[k]||function(){},a.qn[k]));c.drefresh=fp;c.erefresh=gp;return c};
pp=function(a,b){return function(c){var d=b(c);if(d){var e=c.href||null;if(Yo){if(window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",d,e):window._gaq&&window._gaq.push(["_trackSocial","Google",d,e])}catch(g){}if(window.ga&&window.ga.getAll)try{for(var k=window.ga.getAll(),f=0;f<k.length;f++)k[f].send("social","Google",d,e)}catch(l){}}if(Zo&&window.dataLayer)try{window.dataLayer.push({event:"social",socialNetwork:"Google",socialAction:d,
socialTarget:e})}catch(m){}}a.call(this,c)}};_.np=function(a,b,c,d,e){qp(b,c);rp(b,d);sp(a,b,e);tp(a.Sc,a.Ki.toString(),b)};up=function(a){return _.Qk&&a instanceof _.Qk};vp=function(a){return up(a)?"_renderstart":"renderstart"};wp=function(a){return up(a)?"_ready":"ready"};xp=function(){return!0};qp=function(a,b){if(b.onready){var c=!1,d=function(){c||(c=!0,b.onready.call(null))};a.register(wp(a),d,xp);a.register(vp(a),d,xp)}};
sp=function(a,b,c){var d=a.Sc,e=String(a.Ki),f=!1,g=function(){f||(f=!0,c&&Co("wrdt",d,e),Co("wrdi",d,e))};b.register(vp(b),g,xp);var k=!1;a=function(){k||(k=!0,g(),c&&Co("wrrt",d,e),Co("wrri",d,e))};b.register(wp(b),a,xp);up(b)?b.register("widget-interactive-"+b.id,a,xp):_.O.register("widget-interactive-"+b.id,a);_.O.register("widget-csi-tick-"+b.id,function(a,b,c){"wdc"===a?Co("wdc",d,e,c):"wje0"===a?Co("wje0",d,e,c):"wje1"===a?Co("wje1",d,e,c):"wh0"==a?(0,_.Bo)("wh0",d,e,c):"wh1"==a?(0,_.Bo)("wh1",
d,e,c):"wcdi"==a&&(0,_.Bo)("wcdi",d,e,c)})};yp=function(a){return"number"==typeof a?a+"px":"100%"==a?a:null};rp=function(a,b){var c=function(c){c=c||a;var e=yp(c.width);e&&b.style.width!=e&&(b.style.width=e);(c=yp(c.height))&&b.style.height!=c&&(b.style.height=c)};up(a)?a.xy("onRestyle",c):(a.register("ready",c,xp),a.register("renderstart",c,xp),a.register("resize",c,xp))};zp=function(a,b){for(var c in lp)if(lp.hasOwnProperty(c)){var d=lp[c][1];d&&!b.hasOwnProperty(d)&&(b[d]=a[d])}return b};
Ap=function(a,b){var c={},d;for(d in a)a.hasOwnProperty(d)&&(c[a[d][1]||d]=(a[d]&&a[d][0]||$o)(b[d.toLowerCase()],b,ap));return c};Bp=function(a){if(a=a.CG)for(var b=0;b<a.length;b++)(new window.Image).src=a[b]};Cp=function(a,b){var c=b.userParams,d=b.siteElement;d||(d=(d=b.iframeNode)&&d.parentNode);if(d&&1===d.nodeType){var e=Ap(a.config,c);a.Bx.push({element:d,config:e,Nf:zp(e,Ap(a.Vw,c)),pQ:3,vC:!!c["data-onload"],NG:b})}c=a.Bx;for(d=a.yq;0<c.length;)d(c.shift())};
_.Dp=function(a){var b=op(a);Bp(b);(0,_.tc)(b.Sc,function(a){Cp(b,a)});io[b.Sc]=!0;var c={Y:function(a,c){var f=c||{};f.type=b.Sc;var g=f.type;delete f.type;var k=oo(a);if(k){var l={},m;for(m in f)(0,_.Ma)(f,m)&&(l[m.toLowerCase()]=f[m]);l.rd=1;(f=!!l.ri)&&delete l.ri;qo(g,k,l,[],0,f)}else(0,_.vc)("string"==="gapi."+g+".render: missing element "+typeof a?a:"")},go:function(a){ro(a,b.Sc)},A:function(){var a=(0,_.Ja)(_.Wa,"WI",(0,_.Ka)()),b;for(b in a)delete a[b]}};a=function(){"onload"===Xo&&c.go()}; On(b.Sc)||(0,_.Kc)(a,a);(0,_.E)("gapi."+b.Sc+".go",c.go);(0,_.E)("gapi."+b.Sc+".render",c.Y);return c};
var Ep=Cp,Fp=function(a,b){a.Ki++;Co("wrs",a.Sc,String(a.Ki));var c=b.userParams,d=Ap(a.config,c),e=[],f=b.iframeNode,g=b.siteElement,k=mp(a,d),l=Ap(a.Vw,c);(0,_.Bj)((0,_.Kn)(),l);var l=zp(d,l),c=!!c["data-onload"],m=_.xk,n=(0,_.Ka)();n.renderData=b;n.height=d.height;n.width=d.width;n.id=b.id;n.url=b.url;n.iframeEl=f;n.where=n.container=g;n.apis=["_open"];n.messageHandlers=k;n.messageHandlersFilter=_.Ik;(0,_.En)(n);f=l;a.Of&&(e[2]=n,e[3]=f,e[4]=k,a.Of("i",e));k=m.kj(n);k.id=b.id;k.tr(k,n);(0,_.np)(a, k,d,g,c);e[5]=k;a.Of&&a.Of("e",e)},Cp=function(a,b){var c=b.url;a.qI||(0,_.Hn)(c)?_.Ok?Fp(a,b):(0,_.Bh)("gapi.iframes.impl",function(){Fp(a,b)}):_.J.open?Ep(a,b):(0,_.Bh)("iframes",function(){Ep(a,b)})};
var tp;_.Gp=function(a){return!!a.performance&&!!a.performance.getEntries};_.Hp=function(a){var b=a.indexOf("#");-1!=b&&(a=a.substring(0,b));a=window.performance.getEntriesByName(a);if(1>a.length)return null;a=a[0];return 0==a.responseStart?null:a};
tp=function(a,b,c){if((0,_.Gp)(window)){var d=function(){var a=!1;return function(){if(a)return!0;a=!0;return!1}}(),e=function(){d()||window.setTimeout(function(){var d=(0,_.Hp)(c.Ga().src);d&&(0,_.Fo)(a,b,Math.round(d.startTime),Math.round(d.requestStart),Math.round(d.responseStart),Math.round(d.responseEnd))},1E3)};c.register(vp(c),e,xp);c.register(wp(c),e,xp)}};
(0,_.E)("gapi.widget.make",_.Dp);
var Vw;var Tw;var Sw;var Rw;Rw=function(a,b){if("string"==typeof a){a=a.toLowerCase();var c;for(c=0;c<b.length;c++)if(b[c]==a)return a}};Sw="inline bubble none only pp vertical-bubble".split(" ");Tw=["left","right"];_.Uw=function(a){return Rw(a,Sw)};Vw=function(a){return Rw(a,Tw)};_.Ww=function(a){a.source=[null,"source"];a.expandTo=[null,"expandTo"];a.align=[Vw];a.annotation=[_.Uw];a.origin=[_.Rn]};

_.vx=function(a,b){b||(b={});var c=window,d="undefined"!=typeof a.href?a.href:String(a),e=b.target||a.target,f=[],g;for(g in b)switch(g){case "width":case "height":case "top":case "left":f.push(g+"="+b[g]);break;case "target":case "noreferrer":break;default:f.push(g+"="+(b[g]?1:0))}f=f.join(",");if(b.noreferrer){if(c=c.open("",e,f))_.S&&-1!=d.indexOf(";")&&(d="'"+d.replace(/'/g,"%27")+"'"),c.opener=null,d=(0,_.ec)(d),c.document.write('<META HTTP-EQUIV="refresh" content="0; url='+d+'">'),c.document.close()}else c= c.open(d,e,f);return c};

_.OI=function(){var a=_.Kd;return!!a&&0<=a.indexOf("CriOS")};_.PI=function(){var a=_.Kd;return!!a&&0<=a.indexOf("iPhone")&&0<=a.indexOf("Safari")&&-1==a.indexOf("CriOS")};_.QI=function(a,b){var c=/^https:\/\/([^\/]+\.google\.com)\//.exec(a);c&&-1!=["plus.google.com","plus.sandbox.google.com"].indexOf(c[1])&&(c=b||{},c.noreferrer=!0,(c=(0,_.vx)(a,c))&&c.focus())};

var RI,SI;
(function(){var a=null,b=null,c={0:"comments"};c[1]={href:[_.Sn],view_type:[null],query:[null],width:[null],pinned_comment:[null],owner_id:[null],first_party_property:[null],legacy_comment_moderation_url:[null]};var d=function(a,c,d){var e=(0,_.km)((0,_.Vl)(b)).y;c&&(0,_.PI)()&&(e-=60);var f=(0,_.Pl)().height,p=(0,_.Kl)(window.document).y;a=e+a;if(a<p||a>p+f||d)d=a,c&&(d-=f),(0,_.Hl)(window.document).scrollTop=d};c[3]={onfirsttimeplusonepromo:!0,onallcommentsclicked:!0,onfirsttimecommenter:!0,onhidefirsttimecommenterpromo:!0,
ontimestampclicked:!0,onshownotification:!0,onthumbsup:!0,onupgradeaccount:!0,scroll:function(){return d},openwindow:function(){return(0,_.OI)()?_.QI:void 0}};var e=function(){if(b){var a=window.document.getElementById(b);a&&a.parentNode&&a.parentNode.parentNode&&(a.style.width=a.parentNode.parentNode.offsetWidth+"px")}},f=function(){a&&(a.ea&&a.ea(),b=a=null,window.removeEventListener?window.removeEventListener("resize",e):window.detachEvent&&window.detachEvent("onresize",e))};c[5]=function(c,d){"e"==
c&&(f(),a=d[5],b=a.fa(),window.addEventListener?window.addEventListener("resize",e):window.attachEvent&&window.attachEvent("onresize",e))};(0,_.Dp)(c);RI=f;SI=function(b){a.send("createComment",{content:b},null,_.Ik)}})();(0,_.E)("gapi.comments.createComment",SI);(0,_.E)("gapi.comments.dispose",RI);

var Mc=_.Kb=_.Kb||{};window.___jsl=window.___jsl||{};Mc.eo={A:function(){return window.___jsl.bsh},Au:function(){return window.___jsl.h},kr:function(a){window.___jsl.bsh=a},HH:function(a){window.___jsl.h=a}};
_.Sc=function(a){var b;if(b=(0,_.G)("enableMultilogin"))if(b=a("cookie_policy"))b=String(a("immediate")||""),a=String(a("prompt")||""),b=!("true"===b.toLowerCase()||"none"===a.toLowerCase());return b?!0:!1};
_.Tc=function(a,b,c){a=String(a);if(null!=((0,_.Ra)(a,"authuser")||null)||null!=((0,_.Ra)(a,"hd")||null))return a;b=(0,_.Pc)(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],g=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(g||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));
return d}}null==b?(0,_.Sc)(function(b){return(0,_.Ra)(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l), c[0]=d.join(""));return d=c.join("#")};_.google.gQ=_.Tc;_.google.wp=_.Pc;_.google.AP=_.Qc;_.google.BP=_.Rc;

_.M=_.M||{};_.M.Gm=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.M.Xj=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

_.M=_.M||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.M.escape=function(a,b){if(a){if("string"===typeof a)return _.M.yl(a);if("Array"===typeof a)for(var e=0,f=a.length;e<f;++e)a[e]=_.M.escape(a[e]);else if("object"===typeof a&&b){e={};for(f in a)a.hasOwnProperty(f)&&(e[_.M.yl(f)]=_.M.escape(a[f],!0));return e}}return a};_.M.yl=function(a){if(!a)return a;for(var d=[],e,f,g=0,k= a.length;g<k;++g)e=a.charCodeAt(g),f=b[e],!0===f?d.push("&#",e,";"):!1!==f&&d.push(a.charAt(g));return d.join("")};_.M.NQ=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

_.M=_.M||{};_.M.Sk=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):(0,_.Jb)("cannot attachBrowserEvent: "+b)};_.M.KG=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):(0,_.Jb)("cannot removeBrowserEvent: mousemove")};

_.Nb=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,J:d,sf:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};

_.Ad=function(){function a(a){var b=(0,_.Nb)();b.update(a);return b.sf()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=(0,_.G)("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,g=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%
1E6*b;f=f*b%g;0<c&&++d==c&&_.M.KG(k)};0!=c&&_.M.Sk(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(g+Math.pow(16,20))}}();
(0,_.E)("shindig.random",_.Ad);
var hn;var Mm=function(){_.J.Rv++;return["I",_.J.Rv,"_",(new Date).getTime()].join("")};var Nm=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.Fc)(a):a};var Om=function(){};var Pm=function(a){a&&a.match(Qm)&&(0,_.db)("googleapis.config/gcv",a)};var Rm=function(a){_.Kb.eo.HH(a)};var Sm=function(a){_.Kb.eo.kr(a)};_.Tm=function(a,b){var c=b||{},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};
_.Um=function(a,b,c,d,e){var f=[],g;for(g in a)if(a.hasOwnProperty(g)){var k=b,l=c,m=a[g],n=d,p=Vm(g);p[k]=p[k]||{};n=_.M.Gm(n,m);m._iframe_wrapped_rpc_&&(n._iframe_wrapped_rpc_=!0);p[k][l]=n;f.push(g)}if(e)for(g in _.J.Nh)_.J.Nh.hasOwnProperty(g)&&f.push(g);return f.join(",")};var Wm=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=Xm(f,b,c)}}return d};
var Ym=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.Qb)if(b=_.Qb._open)if(b="inline"!=a.style)if(b=!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};
var Zm=function(a,b){var c={},d=b.params||{},e;for(e in a)"#"==e.charAt(0)&&(c[e.substring(1)]=a[e]),0==e.indexOf("fr-")&&(c[e.substring(3)]=a[e]),"#"==d[e]&&(c[e]=a[e]);for(var f in c)delete a["fr-"+f],delete a["#"+f],delete a[f];return c};var $m=function(a){if(":"==a.charAt(0)){var b=(0,_.G)("iframes/"+a.substring(1));a={};(0,_.Bj)(b,a);(b=a.url)&&(a.url=(0,_.hk)(b));a.params||(a.params={});return a}return{url:(0,_.hk)(a)}};var an=function(a){function b(){}b.prototype=bn.prototype;a.prototype=new b};
var cn=function(a){return _.J.rk[a]};var dn=function(a,b){_.J.rk[a]=b};var en=function(a){a=a||{};"auto"===a.height&&(a.height=_.qj.Jb());var b=window&&fn&&fn.ja();b?b.Hx(a.width||0,a.height||0):_.Qb&&_.Qb._resizeMe&&_.Qb._resizeMe(a)};var gn=function(a){Pm(a)};hn=function(a){var b=(0,_.Ra)(a.location.href,"urlindex");if(b=(0,_.Ja)(_.Wa,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};
_.jn=function(){return _.Fa.location.origin||_.Fa.location.protocol+"//"+_.Fa.location.host};
if(window.ToolbarApi)fn=window.ToolbarApi,fn.ja=window.ToolbarApi.getInstance,fn.prototype=window.ToolbarApi.prototype,_.h=fn.prototype,_.h.Sw=fn.prototype.openWindow,_.h.Lt=fn.prototype.closeWindow,_.h.vy=fn.prototype.setOnCloseHandler,_.h.Ct=fn.prototype.canClosePopup,_.h.Hx=fn.prototype.resizeWindow;else{var fn=function(){},kn=null;fn.ja=function(){!kn&&window.external&&window.external.GTB_IsToolbar&&(kn=new fn);return kn};_.h=fn.prototype;_.h.Sw=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.h.Lt=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.h.vy=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.h.Ct=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.h.Hx=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=fn;window.ToolbarApi.getInstance=fn.ja};
var ln=function(){_.O.register("_noop_echo",function(){this.callback(_.J.BD(_.J.If[this.f]))})},mn=function(){window.setTimeout(function(){_.O.call("..","_noop_echo",_.J.sG)},0)},Xm=function(a,b,c){var d=function(d){var f=Array.prototype.slice.call(arguments,0),g=f[f.length-1];if("function"===typeof g){var k=g;f.pop()}f.unshift(b,a,k,c);_.O.call.apply(_.O,f)};d._iframe_wrapped_rpc_=!0;return d},Vm=function(a){_.J.Wm[a]||(_.J.Wm[a]={},_.O.register(a,function(b,c){var d=this.f;if("string"==typeof b&&
!(b in{}||d in{})){var e=this.callback,f=_.J.Wm[a][d],g;f&&Object.hasOwnProperty.call(f,b)?g=f[b]:Object.hasOwnProperty.call(_.J.Nh,a)&&(g=_.J.Nh[a]);if(g)return d=Array.prototype.slice.call(arguments,1),g._iframe_wrapped_rpc_&&e&&d.push(e),g.apply({},d)}(0,_.Hb)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.J.Wm[a]};
_.J.fC=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.J.Gu(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.O.call.apply(_.O,d))})};_.J.HG=function(a,b){_.O.register(a,b)};
var Qm=/^[-_.0-9A-Za-z]+$/,nn={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},on={onBeforeParentOpen:"beforeparentopen"},pn={onOpen:function(a){var b=a.Xa();a.wd(b.container||b.element);return a},onClose:function(a){a.remove()}};_.J.tj=function(a){var b=(0,_.Ka)();(0,_.Bj)(_.Vj,b);(0,_.Bj)(a,b);return b};
var bn=function(a,b,c,d,e,f,g,k){this.config=$m(a);this.openParams=this.$j=b||{};this.params=c||{};this.Mb=d;this.jn=!1;qn(this,b.style);this.cj={};rn(this,function(){var a;(a=this.$j.style)&&_.J.rk[a]?a=_.J.rk[a]:a?((0,_.Jb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=pn;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.M.Gm(a,d,this):d}b=c}for(var g in e)a=b[g],"function"===typeof a&&sn(this,
e[g],_.M.Gm(b,a))}f&&sn(this,"close",f)});this.nf=this.ac=g;this.Bq=(k||[]).slice();g&&this.Bq.unshift(g.fa())};bn.prototype.Xa=function(){return this.$j};bn.prototype.Bf=function(){return this.params};bn.prototype.Nl=function(){return this.Mb};bn.prototype.Eb=function(){return this.nf};var qn=function(a,b){if(!a.jn){var c=b&&!_.J.rk[b]&&_.J.uo[b];c?(a.to=[],c(function(){a.jn=!0;for(var b=0,c=a.to.length;b<c;++b)a.to[b].call(a)})):a.jn=!0}},rn=function(a,b){a.jn?b.call(a):a.to.push(b)};
bn.prototype.Tb=function(a,b){rn(this,function(){sn(this,a,b)})};var sn=function(a,b,c){a.cj[b]=a.cj[b]||[];a.cj[b].push(c)};bn.prototype.Og=function(a,b){rn(this,function(){var c=this.cj[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
bn.prototype.ee=function(a,b){var c,d=this.cj[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,g=d.length;f<g;++f)try{c=d[f].apply({},e)}catch(k){(0,_.Hb)(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var tn=function(a){return"number"==typeof a?{value:a,Xo:a+"px"}:"100%"==a?{value:100,Xo:"100%",jw:!0}:null},un=function(a,b,c,d,e,f,g){bn.call(this,a,b,c,d,nn,e,f,g);this.id=b.id||Mm();this.B=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.Ad)());this.D=Zm(this.params,this.config);this.So={};rn(this,function(){this.ee("open");(0,_.Tm)(this.So,this)})};an(un);_.h=un.prototype;
_.h.wd=function(a,b){if(!this.config.url)return(0,_.Hb)("Cannot open iframe, empty URL."),this;var c=this.id;_.J.If[c]=this;var d=(0,_.Tm)(this.Mb);d._ready=this.Nm;d._close=this.close;d._open=this.Bs;d._resizeMe=this.Cs;d._renderstart=this.Nw;var e=this.D;this.B&&(e.rpctoken=this.B);e._methods=(0,_.Um)(d,c,"",this,!0);this.C=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var g;if(f){g=[];for(var f=f.split(";"),k=0,
l=f.length;k<l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?g.push(m.join(":")):(0,_.Hb)(['Iframe style "',f[k],'" not allowed.'].join(""))}g=g.join(";")}else g="";b.style=g}}this.Xa().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=Nm;this.A=(0,_.jk)(this.config.url,a,d);e=this.A.getAttribute("data-postorigin")||this.A.src;_.J.If[c]=this;_.O.Zm(this.id,this.B);_.O.Qe(this.id,
e);return this};_.h.Ec=function(a,b){this.So[a]=b};_.h.fa=function(){return this.id};_.h.Ga=function(){return this.A};_.h.La=function(){return this.C};_.h.Md=function(a){this.C=a};_.h.Nm=function(a){var b=Wm(a,this.id,"");this.nf&&"function"==typeof this.Mb._ready&&(a._methods=(0,_.Um)(b,this.nf.fa(),this.id,this,!1),this.Mb._ready(a));(0,_.Tm)(a,this);(0,_.Tm)(b,this);this.ee("ready",a)};_.h.Nw=function(a){this.ee("renderstart",a)};
_.h.close=function(a){a=this.ee("close",a);delete _.J.If[this.id];return a};_.h.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.h.Bs=function(a){var b=Wm(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.C);if(Ym(a.openParams))new vn(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new un(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;rn(c,function(){var a={childId:c.fa()},f=c.So;f._toclose=c.close;a._methods=(0,_.Um)(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.h.Cs=function(a){if(void 0===this.ee("resize",a)&&this.A){var b=tn(a.width);null!=b&&(this.A.style.width=b.Xo);a=tn(a.height);null!=a&&(this.A.style.height=a.Xo);this.A.parentElement&&(null!=b&&b.jw||null!=a&&a.jw)&&(this.A.parentElement.style.display="block")}};
var vn=function(a,b,c,d,e,f,g){bn.call(this,a,b,c,d,on,e,f,g);this.url=a;this.A=null;this.Lq=Mm();rn(this,function(){var a;this.ee("beforeparentopen");var b=(0,_.Tm)(this.Mb);b._onopen=this.nG;b._ready=this.Nm;b._onclose=this.mG;this.params._methods=(0,_.Um)(b,"..",this.Lq,this,!0);b={};for(a in this.params)b[a]=Nm(this.params[a]);var c=this.config.url;if(this.$j.hideUrlFromParent){a=window.name;var d=c,c=(0,_.Oj)(this.config.url,this.params,{},Nm),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=(0,_.Ja)(_.Wa,"fUrl",[]),e=d.length,d[e]=c,_.Wa.rUrl=hn,b["#opener"]=a,b["#urlindex"]=e,a=_.Kb.xa(_.Fa.location.href),c=(0,_.G)("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a=a+c);c=a}_.Qb._open({url:c,openParams:this.$j,params:b,proxyId:this.Lq,openedByProxyChain:this.Bq})})};an(vn);vn.prototype.B=function(){return this.A};
vn.prototype.nG=function(a){this.A=a.childId;var b=Wm(a,"..",this.A);(0,_.Tm)(b,this);this.close=b._toclose;_.J.If[this.A]=this;this.nf&&this.Mb._onopen&&(a._methods=(0,_.Um)(b,this.nf.fa(),this.A,this,!1),this.Mb._onopen(a))};vn.prototype.Nm=function(a){var b=String(this.A),c=Wm(a,"..",b);(0,_.Tm)(a,this);(0,_.Tm)(c,this);this.ee("ready",a);this.nf&&this.Mb._ready&&(a._methods=(0,_.Um)(c,this.nf.fa(),b,this,!1),this.Mb._ready(a))};
vn.prototype.mG=function(a){if(this.nf&&this.Mb._onclose)this.Mb._onclose(a);else return a=this.ee("close",a),delete _.J.If[this.A],a};
var wn=function(a,b,c,d,e,f,g){bn.call(this,a,b,c,d,on,f,g);this.id=b.id||Mm();this.B=e;d._close=this.close;this.onClosed=this.A;this.lz=0;rn(this,function(){this.ee("beforeparentopen");var b=(0,_.Tm)(this.Mb);this.params._methods=(0,_.Um)(b,"..",this.Lq,this,!0);b={};b.queryParams=this.params;a=(0,_.ak)(_.Ga,this.config.url,this.id,b);var c=e.Sw(a);this.canAutoClose=function(a){a(e.Ct(c))};e.vy(c,this);this.lz=c})};an(wn);wn.prototype.close=function(a){a=this.ee("close",a);this.B.Lt(this.lz);return a};
wn.prototype.A=function(){this.ee("close")};
(function(){_.J.If={};_.J.rk={};_.J.uo={};_.J.Rv=0;_.J.Wm={};_.J.Nh={};_.J.Pm=null;_.J.Om=[];_.J.sG=function(a){var b=!1;try{if(null!=a)var e=window.parent.frames[a.id],b=e.iframer.id==a.id&&e.iframes.openedId_(_.Qb.id)}catch(f){}try{_.J.Pm={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.J.Om.length;++a)_.J.Om[a](_.J.Pm);_.J.Om=[]}catch(g){}};_.J.BD=function(a){var b=a&&a.nf,e=null;b&&(e={},e.id=b.fa(),e.proxyChain=
a.Bq);return e};ln();if(window.parent!=window){var a=_.M.tb();a.gcv&&Pm(a.gcv);var b=a.jsh;b&&Rm(b);(0,_.Tm)(Wm(a,"..",""),_.Qb);(0,_.Tm)(a,_.Qb);mn()}_.J.ua=cn;_.J.ob=dn;_.J.GH=gn;_.J.resize=en;_.J.iD=function(a){return _.J.uo[a]};_.J.nr=function(a,b){_.J.uo[a]=b};_.J.Gx=en;_.J.QH=gn;_.J.om={};_.J.om.get=cn;_.J.om.set=dn;_.J.UB=function(a,b){Vm(a);_.J.Nh[a]=b||window[a]};_.J.iP=function(a){delete _.J.Nh[a]};_.J.open=function(a,b,e,f,g,k){3==arguments.length?f={}:4==arguments.length&&"function"===
typeof f&&(g=f,f={});var l="bubble"===b.style&&fn?fn.ja():null;return l?new wn(a,b,e,f,l,g,k):Ym(b)?new vn(a,b,e,f,g,k):new un(a,b,e,f,g,k)};_.J.close=function(a,b){_.Qb&&_.Qb._close&&_.Qb._close(a,b)};_.J.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var f=a||{};"height"in f||(f.height=_.qj.Jb());f._methods=(0,_.Um)(b||{},"..","",_.Qb,!0);_.Qb&&_.Qb._ready&&_.Qb._ready(f,e)};_.J.Gu=function(a){_.J.Pm?a(_.J.Pm):_.J.Om.push(a)};_.J.pG=function(a){return!!_.J.If[a]};_.J.nD=
function(){return["https://ssl.gstatic.com/gb/js/",(0,_.G)("googleapis.config/gcv")].join("")};_.J.px=function(a){var b={mouseover:1,mouseout:1};if(_.Qb._event)for(var e=0;e<a.length;e++){var f=a[e];f in b&&_.M.Sk(window.document,f,function(a){_.Qb._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.J.IH=Rm;_.J.kr=Sm;_.J.sw=Om;_.J.Xv=_.Qb})();
(0,_.E)("iframes.allow",_.J.UB);(0,_.E)("iframes.callSiblingOpener",_.J.fC);(0,_.E)("iframes.registerForOpenedSibling",_.J.HG);(0,_.E)("iframes.close",_.J.close);(0,_.E)("iframes.getGoogleConnectJsUri",_.J.nD);(0,_.E)("iframes.getHandler",_.J.ua);(0,_.E)("iframes.getDeferredHandler",_.J.iD);(0,_.E)("iframes.getParentInfo",_.J.Gu);(0,_.E)("iframes.iframer",_.J.Xv);(0,_.E)("iframes.open",_.J.open);(0,_.E)("iframes.openedId_",_.J.pG);(0,_.E)("iframes.propagate",_.J.px);(0,_.E)("iframes.ready",_.J.ready);
(0,_.E)("iframes.resize",_.J.resize);(0,_.E)("iframes.setGoogleConnectJsVersion",_.J.GH);(0,_.E)("iframes.setBootstrapHint",_.J.kr);(0,_.E)("iframes.setJsHint",_.J.IH);(0,_.E)("iframes.setHandler",_.J.ob);(0,_.E)("iframes.setDeferredHandler",_.J.nr);(0,_.E)("IframeBase",bn);(0,_.E)("IframeBase.prototype.addCallback",bn.prototype.Tb);(0,_.E)("IframeBase.prototype.getMethods",bn.prototype.Nl);(0,_.E)("IframeBase.prototype.getOpenerIframe",bn.prototype.Eb);
(0,_.E)("IframeBase.prototype.getOpenParams",bn.prototype.Xa);(0,_.E)("IframeBase.prototype.getParams",bn.prototype.Bf);(0,_.E)("IframeBase.prototype.removeCallback",bn.prototype.Og);(0,_.E)("Iframe",un);(0,_.E)("Iframe.prototype.close",un.prototype.close);(0,_.E)("Iframe.prototype.exposeMethod",un.prototype.Ec);(0,_.E)("Iframe.prototype.getId",un.prototype.fa);(0,_.E)("Iframe.prototype.getIframeEl",un.prototype.Ga);(0,_.E)("Iframe.prototype.getSiteEl",un.prototype.La);
(0,_.E)("Iframe.prototype.openInto",un.prototype.wd);(0,_.E)("Iframe.prototype.remove",un.prototype.remove);(0,_.E)("Iframe.prototype.setSiteEl",un.prototype.Md);(0,_.E)("Iframe.prototype.addCallback",un.prototype.Tb);(0,_.E)("Iframe.prototype.getMethods",un.prototype.Nl);(0,_.E)("Iframe.prototype.getOpenerIframe",un.prototype.Eb);(0,_.E)("Iframe.prototype.getOpenParams",un.prototype.Xa);(0,_.E)("Iframe.prototype.getParams",un.prototype.Bf);(0,_.E)("Iframe.prototype.removeCallback",un.prototype.Og);
(0,_.E)("IframeProxy",vn);(0,_.E)("IframeProxy.prototype.getTargetIframeId",vn.prototype.B);(0,_.E)("IframeProxy.prototype.addCallback",vn.prototype.Tb);(0,_.E)("IframeProxy.prototype.getMethods",vn.prototype.Nl);(0,_.E)("IframeProxy.prototype.getOpenerIframe",vn.prototype.Eb);(0,_.E)("IframeProxy.prototype.getOpenParams",vn.prototype.Xa);(0,_.E)("IframeProxy.prototype.getParams",vn.prototype.Bf);(0,_.E)("IframeProxy.prototype.removeCallback",vn.prototype.Og);(0,_.E)("IframeWindow",wn);
(0,_.E)("IframeWindow.prototype.close",wn.prototype.close);(0,_.E)("IframeWindow.prototype.onClosed",wn.prototype.A);(0,_.E)("iframes.util.getTopMostAccessibleWindow",_.J.qa.Ru);(0,_.E)("iframes.handlers.get",_.J.om.get);(0,_.E)("iframes.handlers.set",_.J.om.set);(0,_.E)("iframes.resizeMe",_.J.Gx);(0,_.E)("iframes.setVersionOverride",_.J.QH);
bn.prototype.send=function(a,b,c){_.J.Wx(this,a,b,c)};_.Qb.send=function(a,b,c){_.J.Wx(_.Qb,a,b,c)};bn.prototype.register=function(a,b){var c=this;c.Tb(a,function(a){b.call(c,a)})};_.J.Wx=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.J.qf=function(){return!0};(0,_.E)("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.J.qf);(0,_.E)("IframeBase.prototype.send",bn.prototype.send);(0,_.E)("IframeBase.prototype.register",bn.prototype.register);
(0,_.E)("Iframe.prototype.send",un.prototype.send);(0,_.E)("Iframe.prototype.register",un.prototype.register);(0,_.E)("IframeProxy.prototype.send",vn.prototype.send);(0,_.E)("IframeProxy.prototype.register",vn.prototype.register);(0,_.E)("IframeWindow.prototype.send",wn.prototype.send);(0,_.E)("IframeWindow.prototype.register",wn.prototype.register);(0,_.E)("iframes.iframer.send",_.J.Xv.send);

});
// Google Inc.
