/* JS */ gapi.loaded_0(function(_){var window=this;
_.m=function(a){throw a;};_.p=void 0;_.q=!0;_.s=null;_.t=!1;_.aa=function(){return function(a){return a}};_.v=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.y=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.C=function(a){return a!==_.p};_.ea=function(a){return"array"==(0,_.da)(a)};_.fa=function(a){var c=(0,_.da)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.ga=function(a){return"string"==typeof a};_.ha=function(a){return"function"==(0,_.da)(a)};_.ia=function(a){var c=typeof a;return"object"==c&&a!=_.s||"function"==c};_.ja=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.ka=function(a,c,f){a||(0,_.m)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.D=function(a,c,f){_.D=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ja:_.ka;return _.D.apply(_.s,arguments)};
_.ma=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.E=function(a,c){function f(){}f.prototype=c.prototype;a.u=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.m)(a)};_.oa=_.oa||{};_.F=this;_.pa="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.qa=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.D.apply(_.s,f)}return(0,_.D)(this,a)};
_.sa=window.gapi||{};_.ta=window.gadgets||{};_.H=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.t},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.q,"pos.plusones.list":_.q,"pos.plusones.get":_.q,"chili.people.get":_.q,"pos.plusones.insert":_.q,"chili.activities.list":_.q,"pos.plusones.delete":_.q,"chili.activities.get":_.q,
"chili.activities.search":_.q,"pos.plusones.getSignupState":_.q},requestCache:{enabled:_.q},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.q},transport:{isProxyShared:_.q},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.t}},drive_saver:{driveUrl:"https://drive.google.com"}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"}});
_.I=function(a,c,f){a=a.split(".");f=f||_.F;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.C)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};_.ua=function(a,c,f){return a[c]=a[c]||f};_.va=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.wa=function(a){return(0,window.String)(a).replace(_.xa,"&amp;").replace(_.ya,"&lt;").replace(_.za,"&gt;").replace(_.Aa,"&quot;").replace(_.Ba,"&#39;")};
_.Ca=function(){var a;if((a=window.Object.create)&&_.Da.test(a))a=a(_.s);else{a={};for(var c in a)a[c]=_.p}return a};_.Ea=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Fa=function(a,c){a=a||{};for(var f in a)(0,_.Ea)(a,f)&&(c[f]=a[f])};_.Ga=function(a,c){a||(0,_.m)((0,window.Error)(c||""))};_.Ha=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g");c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};
_.Ia=function(a){a=a.match(_.Ja);var c=(0,_.Ca)();c.tc=a[1];c.jb=a[3]?[a[3]]:[];c.Qf=a[5]?[a[5]]:[];return c};_.Ka=function(a){a=a?a.split("&"):[];for(var c=[],f=0;f<a.length;f++){var g=a[f].split("=",2);c.push([(0,window.decodeURIComponent)(g[0]),(0,window.decodeURIComponent)(g[1])])}return c};_.La=function(a){return a.tc+(0<a.jb.length?"?"+a.jb.join("&"):"")+(0<a.Qf.length?"#"+a.Qf.join("&"):"")};
_.Ma=function(a){var c=[];if(a)for(var f in a)(0,_.Ea)(a,f)&&a[f]!=_.s&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};_.Na=function(a,c,f){a=(0,_.Ia)(a);a.jb.push.apply(a.jb,(0,_.Ma)(c));a.Qf.push.apply(a.Qf,(0,_.Ma)(f));return(0,_.La)(a)};_.Oa=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.Pa=function(a){return!_.Qa.dpo?(0,_.Ha)(a,"jsh",_.Qa.h):_.Qa.h};_.Ra=function(a){return(0,_.Ha)(a,"_bsh",_.Qa.bsh)};
_.Sa=function(){return(0,_.ua)(_.Qa,"WI",(0,_.Ca)())};_.Ta=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};_.Ua=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};_.Va=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.Wa=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Va)(a[f])&&!(0,_.Va)(c[f])?(0,_.Wa)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Va)(c[f])?[]:{},(0,_.Wa)(a[f],c[f])):a[f]=c[f])};
_.Xa=function(a){(0,_.Ua)(_.q);var c=window.___gcfg,f=(0,_.Ta)("cu");if(c&&c!==window.___gu){var g={};(0,_.Wa)(g,c);f.push(g);window.___gu=c}var c=(0,_.Ta)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,(0,_.ua)(_.Qa,"us",[]));for(var n=0;n<h.length;++n)for(var r=h[n],u=0;u<l.length;++u)r.src&&0==r.src.indexOf(l[u])&&g.push(r);0==g.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)if(!g[h].getAttribute("gapi_processed")){g[h].setAttribute("gapi_processed",
_.q);(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.p;if(l){for(;0==l.charCodeAt(l.length-1);)l=l.substring(0,l.length-1);n=_.p;try{n=(new window.Function("return ("+l+"\n)"))()}catch(w){}if("object"===typeof n)l=n;else{try{n=(new window.Function("return ({"+l+"\n})"))()}catch(x){}l="object"===typeof n?n:{}}}else l=_.p;l&&c.push(l)}a&&(g={},(0,_.Wa)(g,a),f.push(g));g=(0,_.Ta)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Wa)((0,_.Ua)(),g[a]);g=(0,_.Ta)("ci");
a=0;for(c=g.length;a<c;++a)(0,_.Wa)((0,_.Ua)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Wa)((0,_.Ua)(),f[a])};_.M=function(a,c){if(!a)return(0,_.Ua)();for(var f=a.split("/"),g=(0,_.Ua)(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.p?g:c};_.Ya=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var r={},g=g[h[l]]=r;g[h[l]]=c}(0,_.Xa)(f)};
_.Za=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.ua)(_.Qa,"ci",[]).push(a),window.__GOOGLEAPIS=_.p)};_.N=function(a,c){c="function"==typeof _.$a&&(0,_.$a)(a,c)||c;(0,_.I)(a,c,_.p)};
_.ab=window;_.bb=window.document;_.Da=/\[native code\]/;_.xa=/&/g;_.ya=/</g;_.za=/>/g;_.Aa=/"/g;_.Ba=/'/g;_.cb=(0,_.ua)(_.ab,"gapi",{});_.Ja=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Qa=(0,_.ua)(_.ab,"___jsl",(0,_.Ca)());(0,_.ua)(_.Qa,"I",0);(0,_.ua)(_.Qa,"hel",10);_.Za&&(0,_.Za)();(0,_.Xa)();(0,_.N)("gapi.config.get",_.M);(0,_.N)("gapi.config.update",_.Ya);


_.il=window.googleapis&&window.googleapis.server||{};
if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.lb=function(a){return this[a]};_.mb=/___$/;_.O={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.t}},stringify:function(a){function c(a){return f.call(this,a,_.lb)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.mb.test(a)?c:_.p})}catch(h){return _.s}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.O=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,l,n;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){n=a.length;for(l=0;l<n;l+=1)h.push(c(a[l])||"null");return"["+h.join(",")+"]"}for(l in a)!/___$/.test(l)&&a.hasOwnProperty(l)&&"string"===typeof l&&(n=c(a[l]))&&h.push(c(l)+":"+n);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.t}}}();
_.O.Wj=function(a){var c={};if(a===_.s||a===_.p)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.s===g||_.p===g||(c[f]="string"===typeof g?g:_.O.stringify(g))}return c};(0,_.N)("gadgets.json.flatten",_.O.Wj);(0,_.N)("gadgets.json.parse",_.O.parse);(0,_.N)("gadgets.json.stringify",_.O.stringify);(0,_.N)("gadgets.json.flatten",_.O.Wj);(0,_.N)("gadgets.json.parse",_.O.parse);(0,_.N)("gadgets.json.stringify",_.O.stringify);


_.P=_.P||{};
_.sb=function(a,c){return window.String.fromCharCode(c)};_.P=_.P||{};_.tb={"0":_.t,10:_.q,13:_.q,34:_.q,39:_.q,60:_.q,62:_.q,92:_.q,8232:_.q,8233:_.q,65282:_.q,65287:_.q,65308:_.q,65310:_.q,65340:_.q};_.P.escape=function(a,c){if(a){if("string"===typeof a)return _.P.Nf(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.P.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.P.Nf(g)]=_.P.escape(a[g],_.q));return f}}return a}; _.P.Nf=function(a){if(!a)return a;for(var c=[],f,g,h=0,l=a.length;h<l;++h)f=a.charCodeAt(h),g=_.tb[f],g===_.q?c.push("&#",f,";"):g!==_.t&&c.push(a.charAt(h));return c.join("")};_.P.vt=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.sb)};

_.ml=function(a){var c="";if(3==a.nodeType||4==a.nodeType)c=a.nodeValue;else if(a.innerText)c=a.innerText;else if(a.innerHTML)c=a.innerHTML;else if(a.firstChild){c=[];for(a=a.firstChild;a;a=a.nextSibling)c.push((0,_.ml)(a));c=c.join("")}return c};_.P=_.P||{};_.P.createElement=function(a){var c;if(!window.document.body||window.document.body.namespaceURI)try{c=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(f){}return c||window.document.createElement(a)};
_.P.qh=function(a){var c=_.P.createElement("iframe");try{var f=["<","iframe"],g=a||{},h;for(h in g)g.hasOwnProperty(h)&&(f.push(" "),f.push(h),f.push('="'),f.push(_.P.Nf(g[h])),f.push('"'));f.push("></");f.push("iframe");f.push(">");var l=_.P.createElement(f.join(""));if(l&&(!c||l.tagName==c.tagName&&l.namespaceURI==c.namespaceURI))c=l}catch(n){}f=c;a=a||{};for(var r in a)a.hasOwnProperty(r)&&(f[r]=a[r]);return c};
_.P.$j=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml","body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.P.Xs=function(a){return(0,_.ml)(a)};

_.P=_.P||{};_.xb=[];_.P.jt=function(a){_.xb.push(a)};_.P.ot=function(){for(var a=0,c=_.xb.length;a<c;++a)_.xb[a]()};
_.P=_.P||{};_.ub=_.s;
_.P.pa=function(a){var c="undefined"===typeof a;if(_.ub!==_.s&&c)return _.ub;var f={};a=a||window.document.location.href;var g=a.indexOf("?"),h=a.indexOf("#");a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&");for(var g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,l=a.length;h<l;++h){var n=a[h].indexOf("=");if(-1!==n){var r=a[h].substring(0,n),n=a[h].substring(n+1),n=n.replace(/\+/g," ");try{f[r]=g(n)}catch(u){}}}c&&(_.ub=f);return f};_.P.pa();
(0,_.N)("gadgets.util.getUrlParameters",_.P.pa);
_.zb=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.zb&&(0,_.Ya)((0,_.zb)());_.yb={L:function(a,c,f){f&&f((0,_.M)())},get:function(a){return(0,_.M)(a)},update:function(a,c){c&&(0,_.m)("Config replacement is not supported");(0,_.Ya)(a)},ea:(0,_.v)()};
(0,_.N)("gadgets.config.register",_.yb.L);(0,_.N)("gadgets.config.get",_.yb.get);(0,_.N)("gadgets.config.init",_.yb.ea);(0,_.N)("gadgets.config.update",_.yb.update);
_.Ab=_.Ab||{};_.Ab.Tl=_.s;_.Ab.pl=_.s;_.Ab.kg=_.s;_.Ab.frameElement=_.s;_.Ab=_.Ab||{};
if(!_.Ab.pj){_.Eb=function(a){var c=_.O.parse(a.data);if(c&&c.f){var f=_.Q.Yd(c.f);(!_.Bb||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.Cb)(c,a.origin)}};_.Bb=_.q;_.Ab.pj={ak:(0,_.ca)("wpm"),b:(0,_.ca)(_.q),ea:function(a,c){_.yb.L("rpc",_.s,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.Bb=_.t});_.Cb=a;_.Fb=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.Eb,_.t):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.Eb);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.Eb);(0,_.Fb)("..",_.q);return _.q},$c:function(a){(0,_.Fb)(a,_.q);return _.q},call:function(a,c,f){var g=_.Q.Yd(a),h=_.Q.Aj(a);g?window.setTimeout(function(){h.postMessage(_.O.stringify(f),g)},0):".."!=a&&(0,_.ib)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.q}}};
_.Ab=_.Ab||{};
if(!_.Ab.Pf){_.Gb=_.Ab;_.Jb=function(a,c){function f(){a.apply({},arguments)}_.Hb[c]=_.Hb[c]||f;return _.Ib+"."+c};_.Qb=function(){if(_.Kb===_.s&&window.document.body&&_.Lb){var a=_.Lb+"?cb="+window.Math.random()+"&origin="+_.Mb+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.Nb+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.Kb=c.firstChild}++_.Ob;_.Pb!==_.s&&(_.Kb!==_.s||50<=_.Ob)?window.clearTimeout(_.Pb):_.Pb=window.setTimeout(_.Qb,100)};_.Xb=function(){_.Rb[".."]||((0,_.Sb)(".."),_.Vb++,50<=_.Vb&&_.Wb!==_.s?(window.clearTimeout(_.Wb),_.Wb=_.s):_.Wb=window.setTimeout(_.Xb,100))};_.Zb=function(){if(_.Kb!==_.s&&_.Kb.setup)for(;0<_.Yb.length;){var a=_.Yb.shift(),c=a.Ur;_.Kb.setup(a.se,".."===c?_.Q.$g:c,".."===c?"INNER":"OUTER")}_.Pb!==
_.s&&window.clearTimeout(_.Pb);_.Pb=_.s};_.$b=function(){!_.Rb[".."]&&_.Wb===_.s&&(_.Wb=window.setTimeout(_.Xb,100))};_.ac=function(a,c,f){c=_.Q.Yd(a);var g=_.Q.Ud(a);_.Kb["sendMessage_"+(".."===a?_.Q.$g:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.Kb,_.O.stringify(f),c);return _.q};_.dc=function(a,c){var f=_.O.parse(a),g=f._scr;g?((0,_.bc)(g,_.q),_.Rb[g]=_.q,".."!==g&&(0,_.Sb)(g,_.q)):window.setTimeout(function(){(0,_.cc)(f,c)},0)};_.Sb=function(a,c){var f=_.Q.$g,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.ac)(a,f,g)};_.Nb="___xpcswf";_.Lb=_.s;_.ec=_.t;_.cc=_.s;_.bc=_.s;_.Kb=_.s;_.Yb=[];_.Pb=_.s;_.Ob=0;_.Vb=0;_.Wb=_.s;_.Rb={};_.Mb=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.fc=window.___jsl._fm={};_.Ib="___jsl._fm";_.Hb=_.fc;_.yb.L("rpc",_.s,function(a){_.ec&&(_.Lb=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.Jb)(_.Zb,"ready");(0,_.Jb)(_.$b,"setupDone");(0,_.Jb)(_.dc,"receiveMessage");_.Gb.Pf={ak:(0,_.ca)("flash"),b:(0,_.ca)(_.q), ea:function(a,c){_.cc=a;_.bc=c;return _.ec=_.q},$c:function(a,c){_.Yb.push({se:c,Ur:a});_.Kb===_.s&&_.Pb===_.s&&(_.Pb=window.setTimeout(_.Qb,100));return _.q},call:_.ac,Xn:_.dc,d:_.Zb,i:_.$b}};
if(!window.gadgets||!window.gadgets.rpc){_.nc=function(a,c){if(!_.gc[a]){var f=_.hc;c||(f=_.ic);_.gc[a]=f;for(var g=_.jc[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=_.mc[a];f.call(a,l.f,l)}_.jc[a]=[]}};_.sc=function(a,c,f,g,h){function l(){_.oc=_.q}if(!_.mc[c]||_.mc[c]!==f)(0,_.ib)("Invalid gadgets.rpc token. "+_.mc[c]+" vs "+f),(0,_.pc)(c,2);h.onunload=function(){_.qc[c]&&!_.oc&&((0,_.pc)(c,1),_.Q.Vi(c))};_.rc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",l,_.t):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",l),_.rc=_.q);g=_.O.parse((0,window.decodeURIComponent)(g))};_.vc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.mc[a.f]&&_.mc[a.f]!==a.t&&((0,_.ib)("Invalid gadgets.rpc token. "+_.mc[a.f]+" vs "+a.t),(0,_.pc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.nc)(a.f,_.q)},0);else{a.c&&(a.callback=function(c){_.Q.call(a.f,(a.g?"legacy__":"")+"__cb",_.s,a.c,c)});if(c){var f=(0,_.tc)(c);
a.origin=c;var g=a.r;if(!g||(0,_.tc)(g)!=f)g=c;a.referer=g}f=(_.uc[a.s]||_.uc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.Q.call(a.f,"__cb",_.s,a.c,f)}};_.tc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=
c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.wc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.s}}return _.s};_.xc=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.wc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:
_.s};_.yc=function(a,c){if(_.qc[a]!==_.q){"undefined"===typeof _.qc[a]&&(_.qc[a]=0);var f=(0,_.xc)(a);(".."===a||f!=_.s)&&_.hc.$c(a,c)===_.q?_.qc[a]=_.q:_.qc[a]!==_.q&&10>_.qc[a]++?window.setTimeout(function(){(0,_.yc)(a,c)},500):(_.gc[a]=_.ic,_.qc[a]=_.q)}};_.Ac=function(a){(a=_.zc[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.Cc=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.zc[a]=c;"undefined"!==typeof f&&(_.Bc[a]=!!f)};_.Dc=function(a,c){c=c||"";_.mc[a]=(0,window.String)(c);(0,_.yc)(a,c)};_.Gc=function(a){a=(a.passReferrer||"").split(":",2);_.Ec=a[0]||"none";_.Fc=a[1]||"origin"};_.Hc=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.hc=_.Ab.kg||_.ic,_.hc.ea(_.vc,_.nc))};_.Jc=
function(a,c,f){if(".."===a){var g=f||_.Ic.rpctoken||_.Ic.ifpctok||"";a=function(a){a=a&&a.rpc||{};(0,_.Gc)(a);var f=a.parentRelayUrl||"",f=(0,_.tc)(_.Ic.parent||c)+f;(0,_.Cc)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.Hc)(a);(0,_.Dc)("..",g)};!_.Ic.parent&&c?a({}):_.yb.L("rpc",_.s,a)}else a:{var h=_.s;if("/"!=a.charAt(0)){if(!_.P)break a;(h=window.document.getElementById(a))||(0,_.m)((0,window.Error)("h`"+a))}var h=h&&h.src,l=c||_.Q.oa(h);(0,_.Cc)(a,l);h=_.P.pa(h);(0,_.Dc)(a,f||
h.rpctoken)}};_.uc={};_.zc={};_.Bc={};_.mc={};_.Kc=0;_.Lc={};_.qc={};_.Ic={};_.gc={};_.jc={};_.Ec=_.s;_.Fc=_.s;_.Mc=window.top!==window.self;_.Nc=window.name;_.pc=(0,_.v)();_.Oc=window.console;_.Pc=_.Oc&&_.Oc.log&&function(a){_.Oc.log(a)}||(0,_.v)();_.Qc=function(a){return function(){(0,_.Pc)(a+": call ignored")}};_.ic={getCode:(0,_.ca)("noop"),isParentVerifiable:(0,_.ca)(_.q),init:(0,_.Qc)("init"),setup:(0,_.Qc)("setup"),call:(0,_.Qc)("call")};_.P&&(_.Ic=_.P.pa());_.oc=_.t;_.rc=_.t;_.hc=function(){if("flash"==
_.Ic.rpctx)return _.Ab.Pf;if("rmr"==_.Ic.rpctx)return _.Ab.Tl;var a="function"===typeof window.postMessage?_.Ab.pj:"object"===typeof window.postMessage?_.Ab.pj:window.ActiveXObject?_.Ab.Pf?_.Ab.Pf:_.Ab.pl?_.Ab.pl:_.Ab.kg:0<window.navigator.userAgent.indexOf("WebKit")?_.Ab.Tl:"Gecko"===window.navigator.product?_.Ab.frameElement:_.Ab.kg;a||(a=_.ic);return a}();_.uc[""]=function(){(0,_.Pc)("Unknown RPC service: "+this.s)};_.uc.__cb=function(a,c){var f=_.Lc[a];f&&(delete _.Lc[a],f.call(this,c))};_.Q=
{Da:function(a){"function"===typeof a.mr&&(_.pc=a.mr)},L:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("i"));""===a&&(0,_.m)((0,window.Error)("j"));_.uc[a]=c},Tb:function(a){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("k"));""===a&&(0,_.m)((0,window.Error)("l"));delete _.uc[a]},Kl:function(a){_.uc[""]=a},um:function(){delete _.uc[""]},Zj:(0,_.v)(),call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=_.Nc:"/"==a.charAt(0)&&(h=_.Q.oa(window.location.href),h="/"+_.Nc+(h?
"|"+h:""));++_.Kc;f&&(_.Lc[_.Kc]=f);var l={s:c,f:h,c:f?_.Kc:0,a:window.Array.prototype.slice.call(arguments,3),t:_.mc[a],l:!!_.Bc[a]},n;a:if("bidir"===_.Ec||"c2p"===_.Ec&&".."===a||"p2c"===_.Ec&&".."!==a){n=window.location.href;var r="?";if("query"===_.Fc)r="#";else if("hash"===_.Fc)break a;r=n.lastIndexOf(r);r=-1===r?n.length:r;n=n.substring(0,r)}else n=_.s;n&&(l.r=n);".."!==a&&(0,_.wc)(a)==_.s&&!window.document.getElementById(a)||(n=_.gc[a],!n&&(0,_.wc)(a)!==_.s&&(n=_.hc),0===c.indexOf("legacy__")&&
(n=_.hc,l.s=c.substring(8),l.c=l.c?l.c:_.Kc),l.g=_.q,l.r=h,n?(_.Bc[a]&&(n=_.Ab.kg),n.call(a,h,l)===_.t&&(_.gc[a]=_.ic,_.hc.call(a,h,l))):_.jc[a]?_.jc[a].push(l):_.jc[a]=[l])},ek:_.Ac,Ng:_.Cc,Mg:_.Dc,pf:_.Jc,Ud:function(a){return _.mc[a]},Vi:function(a){delete _.zc[a];delete _.Bc[a];delete _.mc[a];delete _.qc[a];delete _.gc[a]},dk:function(){return _.hc.ak()},Il:function(a,c){4<a.length?_.hc.Xn(a,_.vc):_.sc.apply(_.s,a.concat(c))},Jl:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.vc)(a)},
0)},oa:_.tc,Yd:function(a){var c=_.s,c=(0,_.Ac)(a);c||(c=(c=(0,_.wc)(a))?c.origin:".."==a?_.Ic.parent:window.document.getElementById(a).src);return(0,_.tc)(c)},ea:function(){_.hc.ea(_.vc,_.nc)===_.t&&(_.hc=_.ic);_.Mc?(0,_.Jc)(".."):_.yb.L("rpc",_.s,function(a){a=a.rpc||{};(0,_.Gc)(a);(0,_.Hc)(a)})},Aj:_.xc,Wn:_.wc,b:"__ack",$g:_.Nc||"..",j:0,i:1,d:2};_.Q.ea()}else if("undefined"==typeof _.Q||!_.Q)_.Q=window.gadgets.rpc,_.Q.Da=_.Q.config,_.Q.L=_.Q.register,_.Q.Tb=_.Q.unregister,_.Q.Kl=_.Q.registerDefault,
_.Q.um=_.Q.unregisterDefault,_.Q.Zj=_.Q.forceParentVerifiable,_.Q.call=_.Q.call,_.Q.ek=_.Q.getRelayUrl,_.Q.Ng=_.Q.setRelayUrl,_.Q.Mg=_.Q.setAuthToken,_.Q.pf=_.Q.setupReceiver,_.Q.Ud=_.Q.getAuthToken,_.Q.Vi=_.Q.removeReceiver,_.Q.dk=_.Q.getRelayChannel,_.Q.Il=_.Q.receive,_.Q.Jl=_.Q.receiveSameDomain,_.Q.oa=_.Q.getOrigin,_.Q.Yd=_.Q.getTargetOrigin,_.Q.Aj=_.Q._getTargetWin,_.Q.Wn=_.Q._parseSiblingId;
(0,_.N)("gadgets.rpc.config",_.Q.Da);(0,_.N)("gadgets.rpc.register",_.Q.L);(0,_.N)("gadgets.rpc.unregister",_.Q.Tb);(0,_.N)("gadgets.rpc.registerDefault",_.Q.Kl);(0,_.N)("gadgets.rpc.unregisterDefault",_.Q.um);(0,_.N)("gadgets.rpc.forceParentVerifiable",_.Q.Zj);(0,_.N)("gadgets.rpc.call",_.Q.call);(0,_.N)("gadgets.rpc.getRelayUrl",_.Q.ek);(0,_.N)("gadgets.rpc.setRelayUrl",_.Q.Ng);(0,_.N)("gadgets.rpc.setAuthToken",_.Q.Mg);(0,_.N)("gadgets.rpc.setupReceiver",_.Q.pf);
(0,_.N)("gadgets.rpc.getAuthToken",_.Q.Ud);(0,_.N)("gadgets.rpc.removeReceiver",_.Q.Vi);(0,_.N)("gadgets.rpc.getRelayChannel",_.Q.dk);(0,_.N)("gadgets.rpc.receive",_.Q.Il);(0,_.N)("gadgets.rpc.receiveSameDomain",_.Q.Jl);(0,_.N)("gadgets.rpc.getOrigin",_.Q.oa);(0,_.N)("gadgets.rpc.getTargetOrigin",_.Q.Yd);


_.Rc=window.gapi&&window.gapi.util||{};
_.Sc=_.Rc=_.Rc||{};_.Tc={rj:"bsh",tj:"h"};window.___jsl=window.___jsl||{};_.Sc.jh={b:function(){return window.___jsl[_.Tc.rj]},bk:function(){return window.___jsl[_.Tc.tj]},Xi:function(a){window.___jsl[_.Tc.rj]=a},Cr:function(a){window.___jsl[_.Tc.tj]=a}};

_.hd=function(a){var c=(0,_.M)("googleapis.config/sessionIndex");c==_.s&&(c=window.__X_GOOG_AUTHUSER);if(c==_.s){var f=window.google;f&&(c=f.authuser)}c==_.s&&(a==_.s&&(a=window.location.href),c=a?(0,_.Ha)(a,"authuser")||_.s:_.s);return c==_.s?_.s:(0,window.String)(c)};
_.id=function(a,c,f){a=(0,window.String)(a);if(((0,_.Ha)(a,"authuser")||_.s)!=_.s||((0,_.Ha)(a,"hd")||_.s)!=_.s)return a;c=(0,_.hd)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],n=h[4],r=h[5];h[3]=="/"+f&&(g=(l||"")+(n||"/")+(r||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],r=h[6],c!=_.s&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(r||"")),g}f=c==_.s?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.jd=_.id;
_.bl=window.oauth2||{};_.cl=window.auth_firstparty||{};
_.dl=function(a,c){var f={};if(!a)return f;for(var g=a.split(c||"&"),h=0;h<g.length;h++){var l=g[h];l&&(l=l.split("="),f[(0,window.decodeURIComponent)(l[0])]=(0,window.decodeURIComponent)(l[1]))}return f};_.el=function(){if(!_.fl){var a={},c=(0,_.dl)(window.document.cookie,";"),f;for(f in c)0==f.indexOf("oauth2-")&&{}.hasOwnProperty.call(c,f)&&(a[f]=(0,_.dl)(c[f]));_.gl=a;_.fl=_.q}}; _.hl=function(a,c){(0,_.el)();var f=_.s;if(a)f=_.gl["oauth2-"+a]||_.s;else for(var g in _.gl)if({}.hasOwnProperty.call(_.gl,g)){f=_.gl[g]||_.s;break}f&&(f.error&&!c)&&(f=_.s);return f};_.gl={};_.fl=_.t;

_.Rc.oa=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};

_.kl=/\s*;\s*/;_.jl={get:function(a,c){for(var f=a+"=",g=(window.document.cookie||"").split(_.kl),h=0,l;l=g[h];++h)if(0==l.indexOf(f))return l.substr(f.length);return c}};
_.Vc=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;x=w=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],l=h[2],r=h[3],u=h[4],w,x,f=0;80>f;f++)40>f?20>f?(w=r^g&(l^r),x=1518500249):(w=g^l^r,x=1859775393):60>f?(w=g&l|r&(g|l),x=2400959708):(w=g^l^r,x=3395469782),w=((a<<5|a>>>27)&4294967295)+
w+u+x+c[f]&4294967295,u=r,r=l,l=(g<<30|g>>>2)&4294967295,g=a,a=w;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+r&4294967295;h[4]=h[4]+u&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==w)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64;for(;g<f;)if(l[w++]=a[g++],x++,64==w){w=0;for(c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64}}
function g(){var a=[],g=8*x;56>w?f(r,56-w):f(r,64-(w-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var u=24;0<=u;u-=8)a[g++]=h[n]>>u&255;return a}for(var h=[],l=[],n=[],r=[128],u=1;64>u;++u)r[u]=0;var w,x;a();return{reset:a,update:f,Ts:g,Lf:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.ll=function(){var a=window.__OVERRIDE_SID;a==_.s&&(a=_.jl.get("SID"));return!!a};
_.cl={bq:function(a){var c={SAPISIDHASH:_.q,APISIDHASH:_.q};return a&&(a.OriginToken||a.Authorization&&c[(0,window.String)(a.Authorization).split(" ")[0]])?_.q:_.t},lq:_.ll,jp:function(){var a=_.s;(0,_.ll)()&&(a=window.__PVT,a==_.s&&(a=_.jl.get("BEAT")));return a},Le:function(){var a=_.Rc.oa((0,window.String)(window.location.href));if((0,_.ll)()){var c=0==a.indexOf("https:")||0==a.indexOf("chrome-extension:"),f=c?"SAPISID":"APISID",g=c?window.__SAPISID:window.__APISID;g==_.s&&(g=_.jl.get(f));if(g)return c= c?"SAPISIDHASH":"APISIDHASH",f=(0,_.Vc)(),f.reset(),f.update([g,a].join(" ")),c+" "+f.Lf().toLowerCase()}return _.s}};

_.nb=function(a,c){if(!(a<_.pb)&&_._console$$inline_283)if(2===a&&_._console$$inline_283.warn)_._console$$inline_283.warn(c);else if(3===a&&_._console$$inline_283.error)try{_._console$$inline_283.error(c)}catch(f){}else _._console$$inline_283.log&&_._console$$inline_283.log(c)};_.qb=function(a){(0,_.nb)(1,a)};_.rb=function(a){(0,_.nb)(2,a)};_.ib=function(a){(0,_.nb)(3,a)};_.qb.INFO=1;_.qb.WARNING=2;_.qb.NONE=4;_.pb=1; _._console$$inline_283=window.console?window.console:window.opera?window.opera.postError:_.p;

_.P=_.P||{};_.P.Ae=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.rb)("cannot attachBrowserEvent: "+c)};_.P.Yq=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.rb)("cannot removeBrowserEvent: "+c)};

_.Wc=function(a){if("complete"===_.bb.readyState)a();else{var c=_.t,f=function(){if(!c)return c=_.q,a.apply(this,arguments)};_.ab.addEventListener?(_.ab.addEventListener("load",f,_.t),_.ab.addEventListener("DOMContentLoaded",f,_.t)):_.ab.attachEvent&&(_.ab.attachEvent("onreadystatechange",function(){"complete"===_.bb.readyState&&f.apply(this,arguments)}),_.ab.attachEvent("onload",f))}};_.Yc=function(a){var c=(0,_.Vc)();c.update(a);return c.Lf()};_.$c=window.crypto;
if(_.$c&&"function"==typeof _.$c.getRandomValues)_.Xc=function(){var a=new window.Uint32Array(1);_.$c.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.ad=(0,_.M)("random/maxObserveMousemove");_.ad==_.s&&(_.ad=-1);_.bd=0;_.cd=window.Math.random();_.dd=1;_.ed=1E6*(window.screen.width*window.screen.width+window.screen.height);_.fd=function(a){a=a||window.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.dd=_.dd*c%_.ed;0<_.ad&&++_.bd==_.ad&&
_.P.Yq(window,"mousemove",_.fd,_.t)};0!=_.ad&&_.P.Ae(window,"mousemove",_.fd,_.t);_.gd=(0,_.Yc)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.cd);_.Xc=function(){var a=_.dd,a=a+(0,window.parseInt)(_.gd.substr(0,20),16);_.gd=(0,_.Yc)(_.gd);return a/(_.ed+window.Math.pow(16,20))}};
(0,_.N)("shindig.random",_.Xc);
_.Nl=function(a,c,f,g){for(var h=0;h<_.Ol.length;h++){var l=_.Ol[h];window.setTimeout(function(){l(a,c,f,g)},1)}};
_.Pl=function(a,c,f,g){var h=(0,_.Ql)("proxy");if(f||!h)var h=(0,_.Ql)("root"),l=(0,_.Ql)("root-1p")||h,n=(0,_.Ql)("xd3"),h=(f||(0,window.String)(c?l:h))+n;(c=_.P.pa().jsh||_.Rc.jh.bk())&&(h+=(0<=h.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(c));(0,_.Ql)("push")&&(h+=(0<=h.indexOf("?")?"&":"?")+"p=1");h+="#parent="+(0,window.encodeURIComponent)(g!=_.s?(0,window.String)(g):_.Rc.oa(window.document.location.href));return h+="&rpctoken="+a};
_.Rl=function(a,c){var f=(0,_.Pl)("",a,c,""),g=_.Sl[f];g||(g=(0,_.Vc)(),g.update(f),g=g.Lf().toLowerCase(),g+=window.Math.random(),_.Sl[f]=g);return"apiproxy"+g};
_.Tl=function(a,c,f){function g(a){a&&(h=a.root||h,l=_.cl.bq(a.headers))}var h=_.s,l=_.t;if("makeRequest"===a||"listen"===a)g(c);else if("makeHttpRequests"===a&&c){for(var n=(0,_.M)("client/jsonpOverride"),r=0,u=c.length;r<u;++r){var w=c[r];w&&(w=w.params,g(w),n&&(0,_.Ul)(w,f))}if(n)return}n=(0,_.Rl)(l,h);if(!_.Vl[n]){var x=l,A=h,G=(0,window.String)(2147483647*(0,_.Xc)()|0),J=(0,_.Pl)(G,x,A);(0,_.Nl)("loading",(new window.Date).getTime(),x,A||_.s);(0,_.Wc)(function(){var a=(0,_.Rl)(x,A),c=_.P.qh({id:a,
name:a});c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.top="-100px";var f;if(window.navigator){f=window.navigator.userAgent||"";var g=window.navigator.product||"";f=0!=f.indexOf("Opera")&&-1==f.indexOf("WebKit")&&"Gecko"==g&&0<f.indexOf("rv:1.")}else f=_.t;c.src=f?"about:blank":J;window.document.body.appendChild(c);f&&(c.src=J);_.Q.L("ready:"+G,function(){_.Q.Tb("ready:"+G);if(!_.Wl[a]){_.Wl[a]=_.q;var c=_.Xl[a];_.Xl[a]=[];for(var f=0,g=c.length;f<g;++f){var h=c[f];
(0,_.Tl)(h.pe,h.br,h.Wa)}(0,_.Nl)("ready",(new window.Date).getTime(),x,A||_.s)}});_.Q.pf(a,J);_.Vl[a]=c})}_.Wl[n]?_.Q.call(n,a,function(c){var g=_.O.parse(c);if("makeRequest"==a&&g){for(var h={},l=0;l<g.length;l++)h[g[l].id]=g[l];f(h,c)}else f(g,c)},c):(_.Xl[n]||(_.Xl[n]=[]),_.Xl[n].push({pe:a,br:c,Wa:f}))};
_.Ul=function(a,c){"GET"!=a.httpMethod&&(0,_.m)("JSONP supports GET methods only.");var f="jpcb"+(0,window.String)(2147483647*(0,_.Xc)()|0),g=window.document.createElement("script"),h=window.document.getElementsByTagName("head")[0];window[f]=function(a){c(a);try{delete window[f]}catch(l){window[f]=_.p}window.setTimeout(function(){h.removeChild(g)},1)};var l=a.root||(0,_.Ql)("root"),l=l+a.url,n=a.urlParams;if(n)for(var r in n)window.Object.prototype.hasOwnProperty.call(n,r)&&(l=(0,_.Yl)(l,r,n[r]));
l=(0,_.Yl)(l,"callback",f);g.setAttribute("id",f);g.setAttribute("src",l);g.setAttribute("charset","utf-8");h.appendChild(g)};_.Yl=function(a,c,f){a+=0<a.indexOf("?")?"&":"?";return a+=(0,window.encodeURIComponent)(c)+"="+(0,window.encodeURIComponent)(f)};_.Ql=function(a){return(0,_.M)("googleapis.config/"+a)};_.Zl={};_.Sl={};_.Vl={};_.Wl={};_.Xl={};_.Ol=[];
_.$l={Kd:function(a,c){var f=a||{},g=_.Rc.oa((0,window.String)(window.location.href));f["X-Origin"]=g;var g=f.Authorization,h=f.OriginToken;if(g==_.s&&h==_.s){if(g==_.s){var l;_.bl&&_.Zl&&(l=(0,_.hl)());l&&l.access_token&&(g=(0,window.String)(l.token_type||"Bearer")+" "+l.access_token)}g==_.s&&((0,_.Ql)("auth/useFirstPartyAuth")&&_.cl.lq())&&(l=f["X-Goog-AuthUser"],l==_.s&&(l=(0,_.hd)(c)||"0"),(g=_.cl.Le())&&(f["X-Goog-AuthUser"]=l));g?f.Authorization=g:(0,_.Ql)("auth/useOriginToken")!==_.t&&(h=_.cl.jp())&& (f.OriginToken=h)}return f},Zn:function(a){_.Ol.push(a)},Zq:function(a){for(var c=0;c<_.Ol.length;c++)if(_.Ol[c]==a){_.Ol.splice(c,1);break}},Ed:_.Tl};

_.Um=window.tamings___||[];_.Vm=window.caja___;_.___=window.___;
_.Wm=function(a,c,f){this.method=a;this.transport=c;this.rpc=f};
_.H.Ci=function(){var a={},c=[];a.execute=function(a){function g(g){g.error&&(h.error=g.error);for(var l=0;l<c.length;l++){var r=c[l].key,u=g[r];u&&(h[r]=u.error?u:u.data||u.result)}n--;0===n&&a(h)}for(var h={},l={},n=0,r=[],u=0;u<c.length;u++){var w=c[u].request.transport;l[w.name]||(r.push(w),n++);l[w.name]=l[w.name]||[];var x=c[u],A={method:x.request.method,id:x.key};x.request.rpc&&(A.params=x.request.rpc);l[w.name].push(A)}for(u=0;u<r.length;u++)r[u].execute(l[r[u].name],g);0==n&&window.setTimeout(function(){a(h)}, 0)};a.add=function(f,g){g&&f&&c.push({key:f,request:g});return a};return a};
_.H.fh=function(a,c){if("newBatch"!==a){for(var f=a.split("."),g=window.osapi,h=0;h<f.length-1;h++)g[f[h]]=g[f[h]]||{},g=g[f[h]];var l=f[f.length-1];g[l]?(g.__dupwarn||(0,_.rb)("Skipping duplicate osapi method definition "+a+" on transport "+c.name+"; others may exist, but suppressing warnings"),g.__dupwarn=_.q):(g[l]=function(f){f=f||{};f.userId=f.userId||"@viewer";f.groupId=f.groupId||"@self";return new _.Wm(a,c,f)},"undefined"!==typeof _.Um&&_.Um.push(function(){_.Vm.markTameAsFunction(g[l],a)}))}};
_.Wm.prototype.execute=function(a){var c="undefined"!==typeof _.Vm&&_.Vm.getUseless&&_.Vm.getUseless(),f=c?_.Vm.getUseless():this,g=c?_.Vm.untame(a):a;a=_.H.Ci();a.add(this.method,this);a.execute(function(a){a.error?g.call(f,a.error):g.call(f,a[f.method])})};

_.Xm=function(a,c){for(var f=a.split("."),g=c||window,h;h=f.shift();)if(g[h]!=_.s)g=g[h];else return _.s;return g};_.Ym=function(a,c,f){a=a.split(".");f=f||window;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&c!==_.p?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.Zm=function(a,c){_.H.fh(a,{name:"googleapis",execute:_.$m,root:c});var f=(0,_.Xm)(a,window.osapi);(0,_.Ym)(a,f);if(0!=a.indexOf("googleapis.")){var g=a.substring(a.indexOf(".")+1),h=g,l=h.lastIndexOf(".delete");-1!=l&&l+7==h.length&&(g=g.replace(".delete",".remove"));(0,_.Ym)("googleapis."+g,f)}};_.an=function(a){for(var c in a)a.hasOwnProperty(c)&&(_.bn[c]=a[c])};_.cn=function(a){(0,_.dn)("key",a)};_.dn=function(a,c){c==_.s?(0,_.en)(a):(_.fn=_.fn||{},_.fn[a]=c)};_.en=function(a){_.fn&&delete _.fn[a]};
_.gn=function(a){a=a||{};if(window.navigator){for(var c=["appVersion","platform","userAgent"],f=[],g=0;g<c.length;g++)window.navigator[c[g]]&&f.push((0,window.encodeURIComponent)(c[g])+"="+(0,window.encodeURIComponent)(window.navigator[c[g]]));a["X-ClientDetails"]=f.join("&")}return a};
_.hn=function(a,c){for(var f=0;f<_.jn.length;f++)window.setTimeout(function(c){return function(){c(a)}}(_.jn[f]),1);return function(){var a=arguments;c.apply(_.s,a);for(var f=0;f<_.kn.length;f++)window.setTimeout(function(c){return function(){c.apply(_.s,a)}}(_.kn[f]),1)}};_.ln=function(a){a.applicationName=_.mn;a.clientVersion="1.0.0-alpha";_.fn&&(a.urlParams=_.fn,_.fn.key&&(a.developerKey=_.fn.key))};
_.$m=function(a,c){for(var f=this.root||_.s,g=0;g<a.length;g++){var h=a[g],l=h.method.substring(0,h.method.indexOf("."));h.jsonrpc="2.0";h.key=h.id;f=h.root||f;(l=_.bn[l]||"v1")&&!h.apiVersion&&(h.apiVersion=l)}g={};g=_.$l.Kd(g);g=(0,_.gn)(g);f={requests:a,headers:g,root:f};(0,_.ln)(f);g=(0,_.hn)(a,c);_.$l.Ed("makeRequest",f,g)};_.nn=function(a){_.jn.push(a)};_.on=function(a){_.kn.push(a)};_.pn=function(a){for(var c=0;c<_.jn.length;c++)if(_.jn[c]==a){_.jn.splice(c,1);break}};
_.qn=function(a){for(var c=0;c<_.kn.length;c++)if(_.kn[c]==a){_.kn.splice(c,1);break}};_.rn=function(a,c){for(var f=0,g=a.length;f<g;f++){var h=a[f];h.key=h.id;var l=h.params.headers||{},l=_.$l.Kd(l),l=(0,_.gn)(l);h.params.headers=l;(0,_.ln)(h.params)}f=(0,_.hn)(a,c);_.$l.Ed("makeHttpRequests",a,f)};
_.sn=function(){var a=_.P.pa(),c={debug:"googleapis.config/debug"},f;for(f in c)a[f]&&(0,_.Ya)(c[f],"true"==a[f]);for(var g in(0,_.M)("googleapis.config/methods"))(0,_.Zm)(g);(0,_.M)("googleapis.config/versions")&&(0,_.an)((0,_.M)("googleapis.config/versions"));(0,_.M)("googleapis.config/developerKey")&&(0,_.cn)((0,_.M)("googleapis.config/developerKey"));_.H.fh("googleapis.newHttpRequest",{name:"googleapis",execute:_.rn});(0,_.Ym)("googleapis.newHttpRequest",(0,_.Xm)("googleapis.newHttpRequest",window.osapi))}; _.tn=function(){this.d={};this.b=_.H.Ci()};
_.mn=_.s;_.bn={};_.jn=[];_.kn=[];(0,_.sn)();_.tn.prototype.add=function(a,c,f){this.d[a]=f;this.b.add(a,c);return this};_.tn.prototype.execute=function(a){var c=this;this.b.execute(function(f){var g={},h=_.t,l;for(l in f)if(f.hasOwnProperty(l)){var n=f[l],r=c.d[l];r?r(n):(g[l]=n,h=_.q)}h&&a&&a(g)})};
(0,_.N)("googleapis.ApiClient.register",_.Zm);(0,_.N)("googleapis.ApiClient.setVersions",_.an);(0,_.N)("googleapis.ApiClient.setDeveloperKey",_.cn);(0,_.N)("googleapis.ApiClient.setUrlParameter",_.dn);(0,_.N)("googleapis.ApiClient.removeUrlParameter",_.en);(0,_.N)("googleapis.ApiClient.addExecuteListener",_.nn);(0,_.N)("googleapis.ApiClient.addResponseListener",_.on);(0,_.N)("googleapis.ApiClient.removeExecuteListener",_.pn);(0,_.N)("googleapis.ApiClient.removeResponseListener",_.qn);
(0,_.N)("googleapis.ApiClient.init",_.sn);(0,_.N)("googleapis.Batch",_.tn);(0,_.N)("googleapis.Batch.prototype.add",_.tn.prototype.add);(0,_.N)("googleapis.Batch.prototype.execute",_.tn.prototype.execute);(0,_.N)("googleapis.init",function(){(0,_.sn)()});(0,_.N)("googleapis.newBatch",function(){return new _.tn});
(0,_.N)("googleapis.newRequest",function(a,c,f){c=c||{};var g={name:"googleapis",execute:_.$m,root:f},h=_.H.Ci(),l=this;f={};f.method=a;f.transport=g;f.rpc=c;f.execute=function(f){h.add(a,{method:a,rpc:c,transport:g});h.execute(function(c){c.error?f.call(l,c.error):f.call(l,c[a])})};return f});(0,_.N)("googleapis.register",function(a,c){(0,_.Zm)(a,c)});(0,_.N)("googleapis.setUrlParameter",function(a,c){(0,_.dn)(a,c)});(0,_.N)("googleapis.removeUrlParameter",function(a){(0,_.en)(a)});
(0,_.N)("googleapis.setDeveloperKey",function(a){(0,_.cn)(a)});(0,_.N)("googleapis.setApplicationName",function(a){_.mn=a});(0,_.N)("googleapis.setVersions",function(a){(0,_.an)(a)});(0,_.N)("googleapis.addExecuteListener",function(a){(0,_.nn)(a)});(0,_.N)("googleapis.removeExecuteListener",function(a){(0,_.pn)(a)});(0,_.N)("googleapis.addResponseListener",function(a){(0,_.on)(a)});(0,_.N)("googleapis.removeResponseListener",function(a){(0,_.qn)(a)}); (0,_.N)("googleapis.addTransportInitListener",function(a){_.$l.Zn(a)});(0,_.N)("googleapis.removeTransportInitListener",function(a){_.$l.Zq(a)});

_.P=_.P||{};_.P.vg=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.P.kf=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.vb=_.vb||{};_.vb.wp=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.wb=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.vb=_.vb||{};
_.vb.Lh=function(){var a=_.vb.wp().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.overflowY:_.s);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var l=h.offsetTop+h.offsetHeight+(0,_.wb)(h,"margin-bottom"),a=window.Math.max(a,l);c.push(h)}}return a+(0,_.wb)(window.document.body,"border-bottom")+(0,_.wb)(window.document.body,"margin-bottom")+(0,_.wb)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};

_.Uc=window.iframer=window.iframer||{};_.R=window.iframes=window.iframes||{};
_.R.ko=function(a,c,f){var g=window.Array.prototype.slice.call(arguments);_.R.ck(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.Q.call.apply(_.Q,g))})};_.R.Vq=function(a,c){_.Q.L(a,c)};

_.kd=function(a,c,f,g){var h=a.location.href,l=(0,_.Ca)(),n=(0,_.Ra)(h);n&&(l._bsh=n);(h=(0,_.Pa)(h))&&(l.jsh=h);var r,h=(0,_.Ca)();h.id=f;h.parent=a.location.protocol+"//"+a.location.host;f=(0,_.Ha)(a.location.href,"id","");a=(0,_.Ha)(a.location.href,"pfname","");(a=f?a+"/"+f:"")&&(h.pfname=a);g.hintInFragment?(0,_.Fa)(l,h):r=l;return(0,_.Na)(c,r,h)};
_.ld=function(a,c,f,g,h,l){var n;try{n=a.createElement('<iframe frameborder="'+(0,_.wa)(f.frameborder)+'" scrolling="'+(0,_.wa)(f.scrolling)+'" name="'+(0,_.wa)(f.name)+'"/>')}catch(r){n=a.createElement("iframe")}for(var u in f)a=f[u],"style"==u&&"object"===typeof a?(0,_.Fa)(a,n.style):n.setAttribute(u,f[u]);(!l||!l.dontClear)&&(0,_.Oa)(c);c.appendChild(n);f.allowtransparency&&(n.allowTransparency=_.q);return n};
_.md=function(a,c,f){f=f||{};var g=c.ownerDocument,h,l=0;do h=f.id||["I",_.nd++,"_",(new window.Date).getTime()].join("");while(g.getElementById(h)&&5>++l);(0,_.Ga)(5>l,"Error creating iframe id");a=(0,_.kd)(g,a,h,f);l=(0,_.Ca)();(0,_.Fa)(_.od,l);(0,_.Fa)(f.attributes,l);l.name=l.id=h;l.src=a;return(0,_.ld)(g,c,l,a,h,f)};
_.od={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.nd=0;_.pd=_.ld;
_.ld=function(a,c,f,g,h,l){if((l||{}).allowPost&&2E3<g.length){l=(0,_.Ia)(g);f.src="";f["data-postorigin"]=l.tc;f=(0,_.pd)(a,c,f,g,h);var n;if(-1!=window.navigator.userAgent.indexOf("WebKit")){n=c.firstChild.contentWindow.document;n.open();g=n.createElement("div");var r={},u=h+"_inner";r.name=u;r.src="";r.style="display:none";(0,_.pd)(a,g,r,"",u)}g=(0,_.Ka)(l.jb[0]);l.jb=[];r=(0,_.La)(l);l=a.createElement("form");l.action=r;l.method="POST";l.target=h;l.style.display="none";for(h=0;h<g.length;h++)r=a.createElement("input"), r.type="hidden",r.name=g[h][0],r.value=g[h][1],l.appendChild(r);c.appendChild(l);l.submit();l.parentNode.removeChild(l);n&&n.close();a=f}else a=(0,_.pd)(a,c,f,g,h);return a};

_.qd=function(a){_.R.Jg[a]||(_.R.Jg[a]={},_.Q.L(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,l=_.R.Jg[a][g],n;l&&window.Object.hasOwnProperty.call(l,c)?n=l[c]:window.Object.hasOwnProperty.call(_.R.Zd,a)&&(n=_.R.Zd[a]);if(n)return g=window.Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}(0,_.ib)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));
return _.s}));return _.R.Jg[a]};_.rd=function(a,c,f){function g(g){var l=window.Array.prototype.slice.call(arguments,0),n=l[l.length-1];if("function"===typeof n){var r=n;l.pop()}l.unshift(c,a,r,f);_.Q.call.apply(_.Q,l)}g._iframe_wrapped_rpc_=_.q;return g};_.sd=function(a,c){var f=(0,_.ua)(_.Qa,"watt",(0,_.Ca)());(0,_.ua)(f,a,c)};_.td=function(a){var c=(0,_.Ha)(a.location.href,"urlindex");if(c=(0,_.ua)(_.Qa,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};
_.ud=function(){_.R.Vk++;return["I",_.R.Vk,"_",(new window.Date).getTime()].join("")};_.vd=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname,f=c.lastIndexOf("/");return c.substring(0,f+1)+a};
_.wd=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.O.stringify(a):a};
_.xd=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.s,g.tc=a):(g.hash=a.substring(h+1),g.tc=a.substring(0,h));a=g.tc.indexOf("?");-1==a?g.jb=_.s:(g.jb=g.tc.substring(a+1),g.tc=g.tc.substring(0,a));a=f?g.hash?[g.hash]:[]:g.jb?[g.jb]:[];for(var l in c)c.hasOwnProperty(l)&&(h=(0,_.wd)(c[l]),a.push([(0,_.yd)(l),(0,_.yd)(h)].join("=")));f?g.hash=a.join("&"):g.jb=a.join("&");return g.tc+(g.jb?"?"+g.jb:"")+(g.hash?"#"+g.hash:"")};
_.zd=function(){var a=(0,_.hd)(_.p);return a!==_.p&&a!==_.s&&""!==a?"u/"+a+"/":""};_.Ad=function(a){a&&a.match(_.Bd)&&(0,_.Ya)("googleapis.config/gcv",a)};_.Cd=function(a){_.Rc.jh.Cr(a)};_.Dd=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};
_.Ed=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var r=c,u=f,w=a[n],x=g,A=(0,_.qd)(n);A[r]=A[r]||{};x=_.P.vg(x,w);w._iframe_wrapped_rpc_&&(x._iframe_wrapped_rpc_=_.q);A[r][u]=x;l.push(n)}if(h)for(n in _.R.Zd)_.R.Zd.hasOwnProperty(n)&&l.push(n);return l.join(",")};_.Fd=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=(0,_.rd)(l,c,f)}}return g};
_.Gd=function(a){return a&&a.disableMultiLevelParentRelay?_.t:_.Uc&&_.Uc._open&&"inline"!=a.style&&a.inline!==_.q&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.Hd=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
_.Id=function(a,c,f,g,h,l,n,r){if(":"==a.charAt(0)){a="iframes/"+a.substring(1);var u=a+"/params",w={},x=(0,_.M)(u);(0,_.Ya)(u,x||w);if(w=(0,_.M)(a+"/url"))u=a+"/url",w=w||"",w=w.replace(/:session_prefix:/g,(0,_.zd)()),w=w.replace(/:session_index:/g,(0,_.hd)(_.p)||"0"),w=w.replace(/:socialhost:/g,(0,_.M)("iframes/:socialhost:")),(0,_.Ya)(u,(0,_.vd)(w));a=(0,_.M)(a)}else a={url:(0,_.vd)(a)};this.Da=a;this.openParams=this.la=c;this.Va=f||{};this.Ua=g;this.j=_.t;c=c.style;if(!this.j)if(c=c&&!_.R.uf[c]&&
_.R.th[c]){this.k=[];var A=this;c(function(){A.j=_.q;for(var a=0,c=A.k.length;a<c;++a)A.k[a].call(A)})}else this.j=_.q;this.d={};(0,_.Jd)(this,function(){var a;(a=this.la.style)&&_.R.uf[a]?a=_.R.uf[a]:a?((0,_.rb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=_.s):a=_.Kd;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.P.vg(a,g,this):g}c=f}for(var n in h)a=c[n],"function"===typeof a&&(0,_.Ld)(this,
h[n],_.P.vg(c,a))}l&&(0,_.Ld)(this,"close",l)});this.xa=this.ac=n;this.Ni=(r||[]).slice();n&&this.Ni.unshift(n.$())};_.Jd=function(a,c){a.j?c.call(a):a.k.push(c)};_.Ld=function(a,c,f){a.d[c]=a.d[c]||[];a.d[c].push(f)};_.Md=function(a,c){return"number"==typeof c?{value:c,ld:c+"px"}:"100%"==c?{value:100,ld:"100%",el:_.q}:_.s};_.Nd=function(a){return(0,_.xd)(a.Da.url,a.Va,_.t)};
_.Od=function(a,c,f,g,h,l,n){_.Id.call(this,a,c,f,g,_.Pd,h,l,n);this.id=c.id||(0,_.ud)();this.i=c.rpcToken||window.Math.round(1E9*(0,_.Xc)());a=this.Va;c={};f=this.Da.params||{};for(var r in a)"#"==r.charAt(0)&&(c[r.substring(1)]=a[r]),0==r.indexOf("fr-")&&(c[r.substring(3)]=a[r]),"#"==f[r]&&(c[r]=a[r]);for(var u in c)delete a["fr-"+u],delete a["#"+u],delete a[u];this.Y=c;this.o={};(0,_.Jd)(this,function(){this.Lb("open");(0,_.Dd)(this.o,this)})};
_.Qd=function(a,c,f,g,h,l,n){_.Id.call(this,a,c,f,g,_.Rd,h,l,n);this.url=a;this.b=_.s;this.z=(0,_.ud)();(0,_.Jd)(this,function(){this.Lb("beforeparentopen");var a=(0,_.Dd)(this.Ua);a._onopen=this.da;a._ready=this.Bg;a._onclose=this.G;this.Va._methods=(0,_.Ed)(a,"..",this.z,this,_.q);var a={},c;for(c in this.Va)a[c]=(0,_.wd)(this.Va[c]);var f=this.Da.url;if(this.la.hideUrlFromParent){c=window.name;var g=f,f=(0,_.Nd)(this),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];
a["#opener"]&&h["#urlindex"]!=_.p?(a["#opener"]=c+","+a["#opener"],c={url:g,Va:a}):(g=(0,_.ua)(_.Qa,"fUrl",[]),h=g.length,g[h]=f,_.Qa.rUrl=_.td,a["#opener"]=c,a["#urlindex"]=h,c=_.Rc.oa(_.ab.location.href),f=(0,_.M)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Va:a});f=c.url;a=c.Va}_.Uc._open({url:f,openParams:this.la,params:a,proxyId:this.z,openedByProxyChain:this.Ni})})};
_.Sd=function(a,c,f,g,h,l,n){_.Id.call(this,a,c,f,g,_.Rd,l,n);this.id=c.id||(0,_.ud)();this.i=h;g._close=this.close;this.onClosed=this.b;this.C=0;(0,_.Jd)(this,function(){this.Lb("beforeparentopen");var a=(0,_.Dd)(this.Ua);this.Va._methods=(0,_.Ed)(a,"..",this.z,this,_.q);var a=(0,_.xd)(this.Da.url,this.Va,_.t),a=(0,_.kd)(_.bb,a,this.id,{}),c=h.Cl(a);this.canAutoClose=function(a){a(h.Lj(c))};h.am(c,this);this.C=c})};_.Td=function(a){return _.R.uf[a]};_.Ud=function(a,c){_.R.uf[a]=c}; _.Vd=function(a){a=a||{};"auto"===a.height&&(a.height=_.vb.Lh());var c=window&&_.Wd&&_.Wd.na();c?c.Pl(a.width||0,a.height||0):_.Uc&&_.Uc._resizeMe&&_.Uc._resizeMe(a)};_.Xd=function(a){(0,_.Ad)(a)};
_.R.H=_.R.H||{};_.R.H.lo=function(a){try{return!!a.document}catch(c){}return _.t};_.R.H.hk=function(a){var c=a.parent;return a!=c&&_.R.H.lo(c)?_.R.H.hk(c):a};_.R.H.Zs=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Wd=window.ToolbarApi,_.Wd.na=window.ToolbarApi.getInstance,_.Wd.prototype=window.ToolbarApi.prototype,_.B=_.Wd.prototype,_.B.Cl=_.Wd.prototype.openWindow,_.B.Nj=_.Wd.prototype.closeWindow,_.B.am=_.Wd.prototype.setOnCloseHandler,_.B.Lj=_.Wd.prototype.canClosePopup,_.B.Pl=_.Wd.prototype.resizeWindow;else{_.Yd=_.s;_.Wd=(0,_.v)();_.Wd.na=function(){!_.Yd&&(window.external&&window.external.GTB_IsToolbar)&&(_.Yd=new _.Wd);return _.Yd};_.B=_.Wd.prototype;_.B.Cl=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.B.Nj=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.B.am=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.B.Lj=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.B.Pl=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Wd;window.ToolbarApi.getInstance=_.Wd.na};
_.Bd=/^[-_.0-9A-Za-z]+$/;_.Pd={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Rd={onBeforeParentOpen:"beforeparentopen"};_.Kd={onOpen:function(a){var c=a.la;a.Ka(c.container||c.element);return a},onClose:function(a){a.remove()}};_.yd=window.encodeURIComponent||window.escape;_.R.Zo=function(a){var c=(0,_.Ca)();(0,_.Fa)(_.od,c);(0,_.Fa)(a,c);return c};_.B=_.Id.prototype;_.B.Nh=(0,_.y)("la");
_.B.od=(0,_.y)("Va");_.B.Mh=(0,_.y)("Ua");_.B.Oh=(0,_.y)("xa");_.B.ma=function(a,c){(0,_.Jd)(this,function(){(0,_.Ld)(this,a,c)})};_.B.Bd=function(a,c){(0,_.Jd)(this,function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};
_.B.Lb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),l=0,n=g.length;l<n;++l)try{f=g[l].apply({},h)}catch(r){(0,_.ib)(['Exception when calling callback "',a,'" with exception "',r.name,": ",r.message,'".'].join(""))}return f};(0,_.Hd)(_.Od,_.Id);_.B=_.Od.prototype;
_.B.Ka=function(a,c){if(!this.Da.url)return(0,_.ib)("Cannot open iframe, empty URL."),this;var f=this.id;_.R.Rc[f]=this;var g=(0,_.Dd)(this.Ua);g._ready=this.Bg;g._close=this.close;g._open=this.Dl;g._resizeMe=this.Ql;g._renderstart=this.yl;var h=this.Y;this.i&&(h.rpctoken=this.i);h._methods=(0,_.Ed)(g,f,"",this,_.q);g=(0,_.Nd)(this);(0,_.xd)(g,h,_.q);this.T=a="string"===typeof a?window.document.getElementById(a):a;g=(0,_.Nd)(this);g=(0,_.xd)(g,h,_.q);h={id:f};if(c){h.attributes=c;var l=c.style;if("string"===
typeof l){var n;if(l){n=[];for(var l=l.split(";"),r=0,u=l.length;r<u;++r){var w=l[r];0==w.length&&r+1==u||(w=w.split(":"),2==w.length&&w[0].match(/^[ a-zA-Z_-]+$/)&&w[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?n.push(w.join(":")):(0,_.ib)(['Iframe style "',l[r],'" not allowed.'].join("")))}n=n.join(";")}else n="";c.style=n}}this.la.allowPost&&(h.allowPost=_.q);this.b=(0,_.md)(g,a,h);_.R.Rc[f]=this;f=g;_.Q.Mg(this.id,this.i);_.Q.Ng(this.id,f);return this};_.B.Ha=function(a,c){this.o[a]=c};_.B.$=(0,_.y)("id");
_.B.ca=(0,_.y)("b");_.B.qp=(0,_.y)("T");_.B.Ic=(0,_.ba)("T");_.B.Bg=function(a){var c=(0,_.Fd)(a,this.id,"");this.xa&&"function"==typeof this.Ua._ready&&(a._methods=(0,_.Ed)(c,this.xa.$(),this.id,this,_.t),this.Ua._ready(a));(0,_.Dd)(a,this);(0,_.Dd)(c,this);this.Lb("ready",a)};_.B.yl=function(a){this.Lb("renderstart",a)};_.B.close=function(a){a=this.Lb("close",a);delete _.R.Rc[this.id];return a};_.B.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.B.Dl=function(a){var c=(0,_.Fd)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.T);if((0,_.Gd)(a.openParams))new _.Qd(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new _.Od(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;(0,_.Jd)(f,function(){var a={childId:f.$()},l=f.o;l._toclose=f.close;a._methods=(0,_.Ed)(l,g.id,f.id,f,_.t);c._onopen(a)})}};
_.B.Ql=function(a){if(this.Lb("resize",a)===_.p&&this.b){var c=(0,_.Md)(this,a.width);c!=_.s&&(this.b.style.width=c.ld);a=(0,_.Md)(this,a.height);a!=_.s&&(this.b.style.height=a.ld);if(this.b.parentElement&&(c!=_.s&&c.el||a!=_.s&&a.el))this.b.parentElement.style.display="block"}};(0,_.Hd)(_.Qd,_.Id);_.Qd.prototype.i=(0,_.y)("b");
_.Qd.prototype.da=function(a){this.b=a.childId;var c=(0,_.Fd)(a,"..",this.b);(0,_.Dd)(c,this);this.close=c._toclose;_.R.Rc[this.b]=this;this.xa&&this.Ua._onopen&&(a._methods=(0,_.Ed)(c,this.xa.$(),this.b,this,_.t),this.Ua._onopen(a))};_.Qd.prototype.Bg=function(a){var c=(0,window.String)(this.b),f=(0,_.Fd)(a,"..",c);(0,_.Dd)(a,this);(0,_.Dd)(f,this);this.Lb("ready",a);this.xa&&this.Ua._ready&&(a._methods=(0,_.Ed)(f,this.xa.$(),c,this,_.t),this.Ua._ready(a))};
_.Qd.prototype.G=function(a){if(this.xa&&this.Ua._onclose)this.Ua._onclose(a);else return a=this.Lb("close",a),delete _.R.Rc[this.b],a};(0,_.Hd)(_.Sd,_.Id);_.Sd.prototype.close=function(a){a=this.Lb("close",a);this.i.Nj(this.C);return a};_.Sd.prototype.b=function(){this.Lb("close")};_.R.Rc={};_.R.uf={};_.R.th={};_.R.Vk=0;_.R.Jg={};_.R.Zd={};_.R.Eg=_.s;_.R.Dg=[];
_.R.Oq=function(a){var c=_.t;try{if(a!=_.s)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.Uc.id)}catch(g){}try{_.R.Eg={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.R.Dg.length;++a)_.R.Dg[a](_.R.Eg);_.R.Dg=[]}catch(h){}};_.R.ip=function(a){var c=a&&a.xa,f=_.s;c&&(f={},f.id=c.$(),f.proxyChain=a.Ni);return f};_.Q.L("_noop_echo",function(){this.callback(_.R.ip(_.R.Rc[this.f]))});
if(window.parent!=window){_.Zd=_.P.pa();_.Zd.gcv&&(0,_.Ad)(_.Zd.gcv);_.$d=_.Zd.jsh;_.$d&&(0,_.Cd)(_.$d);(0,_.Dd)((0,_.Fd)(_.Zd,"..",""),_.Uc);(0,_.Dd)(_.Zd,_.Uc);window.setTimeout(function(){_.Q.call("..","_noop_echo",_.R.Oq)},0)}_.R.ka=_.Td;_.R.ia=_.Ud;_.R.Ar=_.Xd;_.R.Xc=_.Vd;_.R.To=function(a){return _.R.th[a]};_.R.Yi=function(a,c){_.R.th[a]=c};_.R.er=_.Vd;_.R.Hr=_.Xd;_.R.ig={};_.R.ig.get=_.Td;_.R.ig.set=_.Ud;_.R.ao=function(a,c){(0,_.qd)(a);_.R.Zd[a]=c||window[a]};_.R.Us=function(a){delete _.R.Zd[a]};
_.R.open=function(a,c,f,g,h,l){3==arguments.length?g={}:4==arguments.length&&"function"===typeof g&&(h=g,g={});var n="bubble"===c.style&&_.Wd&&_.Wd.na();return n?new _.Sd(a,c,f,g,n,h,l):(0,_.Gd)(c)?new _.Qd(a,c,f,g,h,l):new _.Od(a,c,f,g,h,l)};_.R.close=function(a,c){_.Uc&&_.Uc._close&&_.Uc._close(a,c)};
_.R.Pb=function(a,c,f){2==arguments.length&&"function"===typeof h&&(f=c,c={});var g=a||{};"height"in g||(g.height=_.vb.Lh());var h=c||{};g._methods=(0,_.Ed)(h,"..","",_.Uc,_.q);_.Uc&&_.Uc._ready&&_.Uc._ready(g,f)};_.R.ck=function(a){_.R.Eg?a(_.R.Eg):_.R.Dg.push(a)};_.R.Lq=function(a){return!!_.R.Rc[a]};_.R.Xo=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.M)("googleapis.config/gcv")].join("")};
_.R.Uq=function(a){var c={mouseover:1,mouseout:1};if(_.Uc._event)for(var f=0;f<a.length;f++){var g=a[f];g in c&&_.P.Ae(window.document,g,function(a){_.Uc._event({event:a.type,timestamp:(new window.Date).getTime()})},_.q)}};_.R.Dr=_.Cd;_.R.Xi=function(a){_.Rc.jh.Xi(a)};_.R.gt=(0,_.v)();_.R.hq=_.Uc;
(0,_.N)("iframes.allow",_.R.ao);(0,_.N)("iframes.callSiblingOpener",_.R.ko);(0,_.N)("iframes.registerForOpenedSibling",_.R.Vq);(0,_.N)("iframes.close",_.R.close);(0,_.N)("iframes.getGoogleConnectJsUri",_.R.Xo);(0,_.N)("iframes.getHandler",_.R.ka);(0,_.N)("iframes.getDeferredHandler",_.R.To);(0,_.N)("iframes.getParentInfo",_.R.ck);(0,_.N)("iframes.iframer",_.R.hq);(0,_.N)("iframes.open",_.R.open);(0,_.N)("iframes.openedId_",_.R.Lq);(0,_.N)("iframes.propagate",_.R.Uq);(0,_.N)("iframes.ready",_.R.Pb);
(0,_.N)("iframes.resize",_.R.Xc);(0,_.N)("iframes.setGoogleConnectJsVersion",_.R.Ar);(0,_.N)("iframes.setBootstrapHint",_.R.Xi);(0,_.N)("iframes.setJsHint",_.R.Dr);(0,_.N)("iframes.setHandler",_.R.ia);(0,_.N)("iframes.setDeferredHandler",_.R.Yi);(0,_.N)("IframeBase",_.Id);(0,_.N)("IframeBase.prototype.addCallback",_.Id.prototype.ma);(0,_.N)("IframeBase.prototype.getMethods",_.Id.prototype.Mh);(0,_.N)("IframeBase.prototype.getOpenerIframe",_.Id.prototype.Oh);
(0,_.N)("IframeBase.prototype.getOpenParams",_.Id.prototype.Nh);(0,_.N)("IframeBase.prototype.getParams",_.Id.prototype.od);(0,_.N)("IframeBase.prototype.removeCallback",_.Id.prototype.Bd);(0,_.N)("Iframe",_.Od);(0,_.N)("Iframe.prototype.close",_.Od.prototype.close);(0,_.N)("Iframe.prototype.exposeMethod",_.Od.prototype.Ha);(0,_.N)("Iframe.prototype.getId",_.Od.prototype.$);(0,_.N)("Iframe.prototype.getIframeEl",_.Od.prototype.ca);(0,_.N)("Iframe.prototype.getSiteEl",_.Od.prototype.qp);
(0,_.N)("Iframe.prototype.openInto",_.Od.prototype.Ka);(0,_.N)("Iframe.prototype.remove",_.Od.prototype.remove);(0,_.N)("Iframe.prototype.setSiteEl",_.Od.prototype.Ic);(0,_.N)("Iframe.prototype.addCallback",_.Od.prototype.ma);(0,_.N)("Iframe.prototype.getMethods",_.Od.prototype.Mh);(0,_.N)("Iframe.prototype.getOpenerIframe",_.Od.prototype.Oh);(0,_.N)("Iframe.prototype.getOpenParams",_.Od.prototype.Nh);(0,_.N)("Iframe.prototype.getParams",_.Od.prototype.od);
(0,_.N)("Iframe.prototype.removeCallback",_.Od.prototype.Bd);(0,_.N)("IframeProxy",_.Qd);(0,_.N)("IframeProxy.prototype.getTargetIframeId",_.Qd.prototype.i);(0,_.N)("IframeProxy.prototype.addCallback",_.Qd.prototype.ma);(0,_.N)("IframeProxy.prototype.getMethods",_.Qd.prototype.Mh);(0,_.N)("IframeProxy.prototype.getOpenerIframe",_.Qd.prototype.Oh);(0,_.N)("IframeProxy.prototype.getOpenParams",_.Qd.prototype.Nh);(0,_.N)("IframeProxy.prototype.getParams",_.Qd.prototype.od);
(0,_.N)("IframeProxy.prototype.removeCallback",_.Qd.prototype.Bd);(0,_.N)("IframeWindow",_.Sd);(0,_.N)("IframeWindow.prototype.close",_.Sd.prototype.close);(0,_.N)("IframeWindow.prototype.onClosed",_.Sd.prototype.b);(0,_.N)("iframes.util.getTopMostAccessibleWindow",_.R.H.hk);(0,_.N)("iframes.handlers.get",_.R.ig.get);(0,_.N)("iframes.handlers.set",_.R.ig.set);(0,_.N)("iframes.resizeMe",_.R.er);(0,_.N)("iframes.setVersionOverride",_.R.Hr);

_.kg=2147483648*window.Math.random()|0;
_.lg=function(a){return a[_.pa]||(a[_.pa]=++_.mg)};_.ng=function(a,c){return 0<=(0,_.qg)(a,c)};_.rg=function(a,c){var f=(0,_.qg)(a,c),g;(g=0<=f)&&_.sg.splice.call(a,f,1);return g};_.tg=function(a){var c=a.length;if(0<c){for(var f=(0,window.Array)(c),g=0;g<c;g++)f[g]=a[g];return f}return[]};_.ug=function(a,c,f){return 2>=arguments.length?_.sg.slice.call(a,c):_.sg.slice.call(a,c,f)};_.mg=0;
_.sg=window.Array.prototype;_.qg=_.sg.indexOf?function(a,c,f){return _.sg.indexOf.call(a,c,f)}:function(a,c,f){f=f==_.s?0:0>f?window.Math.max(0,a.length+f):f;if((0,_.ga)(a))return!(0,_.ga)(c)||1!=c.length?-1:a.indexOf(c,f);for(;f<a.length;f++)if(f in a&&a[f]===c)return f;return-1};_.vg=_.sg.forEach?function(a,c,f){_.sg.forEach.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.ga)(a)?a.split(""):a,l=0;l<g;l++)l in h&&c.call(f,h[l],l,a)};
_.wg=_.sg.filter?function(a,c,f){return _.sg.filter.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=[],l=0,n=(0,_.ga)(a)?a.split(""):a,r=0;r<g;r++)if(r in n){var u=n[r];c.call(f,u,r,a)&&(h[l++]=u)}return h};_.xg=_.sg.map?function(a,c,f){return _.sg.map.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,window.Array)(g),l=(0,_.ga)(a)?a.split(""):a,n=0;n<g;n++)n in l&&(h[n]=c.call(f,l[n],n,a));return h};
_.yg=_.sg.some?function(a,c,f){return _.sg.some.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.ga)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&c.call(f,h[l],l,a))return _.q;return _.t};_.zg=_.sg.every?function(a,c,f){return _.sg.every.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=(0,_.ga)(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&!c.call(f,h[l],l,a))return _.t;return _.q};

_.Ag=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.Bg=function(a,c){if(c)return a.replace(_.Cg,"&amp;").replace(_.Dg,"&lt;").replace(_.Eg,"&gt;").replace(_.Fg,"&quot;");if(!_.Gg.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(_.Cg,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(_.Dg,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(_.Eg,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(_.Fg,"&quot;"));return a};_.Hg=function(){return _.F.navigator?_.F.navigator.userAgent:_.s};_.Ig=function(){return _.F.navigator};
_.Jg=function(){var a=_.F.document;return a?a.documentMode:_.p};
_.Kg=function(a){var c;if(!(c=_.Lg[a])){c=0;for(var f=(0,_.Ag)((0,window.String)(_.Mg)).split("."),g=(0,_.Ag)((0,window.String)(a)).split("."),h=window.Math.max(f.length,g.length),l=0;0==c&&l<h;l++){var n=f[l]||"",r=g[l]||"",u=(0,window.RegExp)("(\\d*)(\\D*)","g"),w=(0,window.RegExp)("(\\d*)(\\D*)","g");do{var x=u.exec(n)||["","",""],A=w.exec(r)||["","",""];if(0==x[0].length&&0==A[0].length)break;c=((0==x[1].length?0:(0,window.parseInt)(x[1],10))<(0==A[1].length?0:(0,window.parseInt)(A[1],10))?-1:
(0==x[1].length?0:(0,window.parseInt)(x[1],10))>(0==A[1].length?0:(0,window.parseInt)(A[1],10))?1:0)||((0==x[2].length)<(0==A[2].length)?-1:(0==x[2].length)>(0==A[2].length)?1:0)||(x[2]<A[2]?-1:x[2]>A[2]?1:0)}while(0==c)}c=_.Lg[a]=0<=c}return c};_.Ng=function(a){return _.S&&_.Og>=a};_.Gg=/[&<>\"]/;_.Fg=/\"/g;_.Eg=/>/g;_.Dg=/</g;_.Cg=/&/g;_.Tg=_.Sg=_.Rg=_.Qg=_.Pg=_.t;
if(_.Vg=(0,_.Hg)()){_.Wg=(0,_.Ig)();_.Pg=0==_.Vg.indexOf("Opera");_.Qg=!_.Pg&&-1!=_.Vg.indexOf("MSIE");_.Sg=(_.Rg=!_.Pg&&-1!=_.Vg.indexOf("WebKit"))&&-1!=_.Vg.indexOf("Mobile");_.Tg=!_.Pg&&!_.Rg&&"Gecko"==_.Wg.product}_.Xg=_.Pg;_.S=_.Qg;_.Yg=_.Tg;_.Zg=_.Rg;_.$g=_.Sg;_.ah=(0,_.Ig)();_.bh=_.ah&&_.ah.platform||"";_.Ug=-1!=_.bh.indexOf("Mac");_.bh.indexOf("Win");_.bh.indexOf("Linux");_.ch=!!(0,_.Ig)()&&-1!=((0,_.Ig)().appVersion||"").indexOf("X11");
a:{_.eh="";if(_.Xg&&_.F.opera){_.gh=_.F.opera.version;_.eh="function"==typeof _.gh?(0,_.gh)():_.gh}else if(_.Yg?_.fh=/rv\:([^\);]+)(\)|;)/:_.S?_.fh=/MSIE\s+([^\);]+)(\)|;)/:_.Zg&&(_.fh=/WebKit\/(\S+)/),_.fh){_.hh=_.fh.exec((0,_.Hg)());_.eh=_.hh?_.hh[1]:""}if(_.S){_.ih=(0,_.Jg)();if(_.ih>(0,window.parseFloat)(_.eh)){_.dh=(0,window.String)(_.ih);break a}}_.dh=_.eh}_.Mg=_.dh;_.Lg={};_.jh=_.F.document;_.Og=!_.jh||!_.S?_.p:(0,_.Jg)()||("CSS1Compat"==_.jh.compatMode?(0,window.parseInt)(_.Mg,10):5);

_.kh=function(a,c,f){for(var g in a)c.call(f,a[g],g,a)};_.lh=function(a){var c={},f;for(f in a)c[f]=a[f];return c};_.mh=function(a,c){for(var f,g,h=1;h<arguments.length;h++){g=arguments[h];for(f in g)a[f]=g[f];for(var l=0;l<_.nh.length;l++)f=_.nh[l],window.Object.prototype.hasOwnProperty.call(g,f)&&(a[f]=g[f])}};_.nh="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");

_.oh=function(a){a=a.className;return(0,_.ga)(a)&&a.match(/\S+/g)||[]};_.ph=function(a,c){for(var f=(0,_.oh)(a),g=(0,_.ug)(arguments,1),h=f.length+g.length,l=f,n=0;n<g.length;n++)(0,_.ng)(l,g[n])||l.push(g[n]);a.className=f.join(" ");return f.length==h};_.qh=function(a,c){var f=(0,_.oh)(a),g=(0,_.ug)(arguments,1),h,l=g;h=(0,_.wg)(f,function(a){return!(0,_.ng)(l,a)});a.className=h.join(" ");return h.length==f.length-g.length};_.rh=function(a){return(0,_.ga)(a)?window.document.getElementById(a):a};
_.sh=function(a,c,f){return(0,_.th)(window.document,arguments)};
_.th=function(a,c){var f=c[0],g=c[1];if(!_.uh&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',(0,_.Bg)(g.name),'"');if(g.type){f.push(' type="',(0,_.Bg)(g.type),'"');var h={};(0,_.mh)(h,g);delete h.type;g=h}f.push(">");f=f.join("")}var l=a.createElement(f);g&&((0,_.ga)(g)?l.className=g:(0,_.ea)(g)?_.ph.apply(_.s,[l].concat(g)):(0,_.kh)(g,function(a,c){"style"==c?l.style.cssText=a:"class"==c?l.className=a:"for"==c?l.htmlFor=a:c in _.vh?l.setAttribute(_.vh[c],a):0==c.lastIndexOf("aria-",0)||
0==c.lastIndexOf("data-",0)?l.setAttribute(c,a):l[c]=a}));2<c.length&&(0,_.wh)(a,l,c,2);return l};_.wh=function(a,c,f,g){function h(f){f&&c.appendChild((0,_.ga)(f)?a.createTextNode(f):f)}for(;g<f.length;g++){var l=f[g];if((0,_.fa)(l)&&!((0,_.ia)(l)&&0<l.nodeType)){var n=_.vg,r;a:{if((r=l)&&"number"==typeof r.length){if((0,_.ia)(r)){r="function"==typeof r.item||"string"==typeof r.item;break a}if((0,_.ha)(r)){r="function"==typeof r.item;break a}}r=_.t}n(r?(0,_.tg)(l):l,h)}else h(l)}};
_.xh=function(a){for(var c;c=a.firstChild;)a.removeChild(c)};_.yh=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c)};_.zh=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c.nextSibling)};_.Ah=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):_.s};_.Bh=function(a){var c,f=a.parentNode;if(f&&11!=f.nodeType){if(a.removeNode)return a.removeNode(_.t);for(;c=a.firstChild;)f.insertBefore(c,a);return(0,_.Ah)(a)}};
_.Ch=function(a){return a.firstElementChild!=_.p?a.firstElementChild:(0,_.Dh)(a.firstChild,_.q)};_.Eh=function(a){return a.nextElementSibling!=_.p?a.nextElementSibling:(0,_.Dh)(a.nextSibling,_.q)};_.Dh=function(a,c){for(;a&&1!=a.nodeType;)a=c?a.nextSibling:a.previousSibling;return a};
_.Fh=function(a,c){if(a.contains&&1==c.nodeType)return a==c||a.contains(c);if("undefined"!=typeof a.compareDocumentPosition)return a==c||(0,window.Boolean)(a.compareDocumentPosition(c)&16);for(;c&&a!=c;)c=c.parentNode;return c==a};_.Gh=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};_.Hh=function(a,c){if("textContent"in a)a.textContent=c;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=c}else(0,_.xh)(a),a.appendChild((0,_.Gh)(a).createTextNode(c))};
_.Ih=function(a){if(_.Jh&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var c=[];(0,_.Kh)(a,c,_.q);a=c.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.Jh||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};_.Lh=function(a){var c=[];(0,_.Kh)(a,c,_.t);return c.join("")};
_.Kh=function(a,c,f){if(!(a.nodeName in _.Mh))if(3==a.nodeType)f?c.push((0,window.String)(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):c.push(a.nodeValue);else if(a.nodeName in _.Nh)c.push(_.Nh[a.nodeName]);else for(a=a.firstChild;a;)(0,_.Kh)(a,c,f),a=a.nextSibling};_.Oh=function(a){this.b=a||_.F.document||window.document};
_.uh=!_.S||(0,_.Ng)(9);!_.Yg&&!_.S||_.S&&(0,_.Ng)(9)||_.Yg&&(0,_.Kg)("1.9.1");_.Jh=_.S&&!(0,_.Kg)("9");_.vh={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};_.Mh={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};_.Nh={IMG:" ",BR:"\n"};_.B=_.Oh.prototype;_.B.p=function(a){return(0,_.ga)(a)?this.b.getElementById(a):a};_.B.F=function(a,c,f){return(0,_.th)(this.b,arguments)};_.B.createElement=function(a){return this.b.createElement(a)}; _.B.appendChild=function(a,c){a.appendChild(c)};_.B.al=_.yh;_.B.Xf=_.Ah;_.B.Io=_.Bh;_.B.Wd=_.Ch;_.B.gp=_.Eh;_.B.contains=_.Fh;

_.Ph=function(a){return"CSS1Compat"==a.compatMode};_.Qh=function(a){return!_.Zg&&(0,_.Ph)(a)?a.documentElement:a.body};_.Rh=function(a,c){this.width=a;this.height=c};_.Sh=function(a,c){this.x=(0,_.C)(a)?a:0;this.y=(0,_.C)(c)?c:0};_.Th=function(a){var c=(0,_.Qh)(a);a=a.parentWindow||a.defaultView;return new _.Sh(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop)};_.Uh=function(a){a=a.document;a=(0,_.Ph)(a)?a.documentElement:a.body;return new _.Rh(a.clientWidth,a.clientHeight)};_.Vh=function(a){return(0,_.Th)(a.b)};
_.Wh=function(a){return a.b.parentWindow||a.b.defaultView};_.Xh=function(a){return(0,_.Ph)(a.b)};_.Yh=function(a){return(0,_.Uh)(a||window)};_.Zh=function(a){return a?new _.Oh((0,_.Gh)(a)):_.$h||(_.$h=new _.Oh)};_.ai=function(a){return a?a.parentWindow||a.defaultView:window};_.bi=function(a,c){var f=(0,_.Gh)(a);return f.defaultView&&f.defaultView.getComputedStyle&&(f=f.defaultView.getComputedStyle(a,_.s))?f[c]||f.getPropertyValue(c)||"":""};
_.ci=function(a,c){return a.currentStyle?a.currentStyle[c]:_.s};_.di=function(a,c){return(0,_.bi)(a,c)||(0,_.ci)(a,c)||a.style&&a.style[c]};_.ei=function(a){return(0,_.di)(a,"position")};_.fi=function(a){a=a?(0,_.Gh)(a):window.document;return _.S&&!(0,_.Ng)(9)&&!(0,_.Xh)((0,_.Zh)(a))?a.body:a.documentElement};_.gi=function(a){var c=a.getBoundingClientRect();_.S&&(a=a.ownerDocument,c.left-=a.documentElement.clientLeft+a.body.clientLeft,c.top-=a.documentElement.clientTop+a.body.clientTop);return c};
_.hi=function(a){if(_.S&&!(0,_.Ng)(8))return a.offsetParent;var c=(0,_.Gh)(a),f=(0,_.di)(a,"position"),g="fixed"==f||"absolute"==f;for(a=a.parentNode;a&&a!=c;a=a.parentNode)if(f=(0,_.di)(a,"position"),g=g&&"static"==f&&a!=c.documentElement&&a!=c.body,!g&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==f||"absolute"==f||"relative"==f))return a;return _.s};
_.ii=function(a){var c,f=(0,_.Gh)(a),g=(0,_.di)(a,"position"),h=_.Yg&&f.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==g&&(c=f.getBoxObjectFor(a))&&(0>c.screenX||0>c.screenY),l=new _.Sh(0,0),n=(0,_.fi)(f);if(a==n)return l;if(a.getBoundingClientRect)c=(0,_.gi)(a),a=(0,_.Vh)((0,_.Zh)(f)),l.x=c.left+a.x,l.y=c.top+a.y;else if(f.getBoxObjectFor&&!h)c=f.getBoxObjectFor(a),a=f.getBoxObjectFor(n),l.x=c.screenX-a.screenX,l.y=c.screenY-a.screenY;else{c=a;do{l.x+=c.offsetLeft;l.y+=c.offsetTop;c!=a&&
(l.x+=c.clientLeft||0,l.y+=c.clientTop||0);if(_.Zg&&"fixed"==(0,_.ei)(c)){l.x+=f.body.scrollLeft;l.y+=f.body.scrollTop;break}c=c.offsetParent}while(c&&c!=a);if(_.Xg||_.Zg&&"absolute"==g)l.y-=f.body.offsetTop;for(c=a;(c=(0,_.hi)(c))&&c!=f.body&&c!=n;)if(l.x-=c.scrollLeft,!_.Xg||"TR"!=c.tagName)l.y-=c.scrollTop}return l};_.ji=function(a,c){var f=new _.Sh(0,0),g=(0,_.ai)((0,_.Gh)(a)),h=a;do{var l=g==c?(0,_.ii)(h):(0,_.ki)(h);f.x+=l.x;f.y+=l.y}while(g&&g!=c&&(h=g.frameElement)&&(g=g.parent));return f};
_.ki=function(a){var c=new _.Sh;if(1==a.nodeType){if(a.getBoundingClientRect){var f=(0,_.gi)(a);c.x=f.left;c.y=f.top}else{var f=(0,_.Vh)((0,_.Zh)(a)),g=(0,_.ii)(a);c.x=g.x-f.x;c.y=g.y-f.y}if(_.Yg&&!(0,_.Kg)(12)){var h;_.S?h="-ms-transform":_.Zg?h="-webkit-transform":_.Xg?h="-o-transform":_.Yg&&(h="-moz-transform");var l;h&&(l=(0,_.di)(a,h));l||(l=(0,_.di)(a,"transform"));l?(a=l.match(_.li),a=!a?new _.Sh(0,0):new _.Sh((0,window.parseFloat)(a[1]),(0,window.parseFloat)(a[2]))):a=new _.Sh(0,0);c=new _.Sh(c.x+
a.x,c.y+a.y)}}else h=(0,_.ha)(a.Po),l=a,a.targetTouches?l=a.targetTouches[0]:h&&a.Pa.targetTouches&&(l=a.Pa.targetTouches[0]),c.x=l.clientX,c.y=l.clientY;return c};_.mi=function(a){if("none"!=(0,_.di)(a,"display"))return(0,_.ni)(a);var c=a.style,f=c.display,g=c.visibility,h=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=(0,_.ni)(a);c.display=f;c.position=h;c.visibility=g;return a};
_.ni=function(a){var c=a.offsetWidth,f=a.offsetHeight,g=_.Zg&&!c&&!f;return(!(0,_.C)(c)||g)&&a.getBoundingClientRect?(a=(0,_.gi)(a),new _.Rh(a.right-a.left,a.bottom-a.top)):new _.Rh(c,f)};_.oi=function(a,c){var f=a.style;"opacity"in f?f.opacity=c:"MozOpacity"in f?f.MozOpacity=c:"filter"in f&&(f.filter=""===c?"":"alpha(opacity="+100*c+")")};_.Rh.prototype.Z=function(){return new _.Rh(this.width,this.height)};_.Rh.prototype.gb=function(){return!(this.width*this.height)};
_.Rh.prototype.floor=function(){this.width=window.Math.floor(this.width);this.height=window.Math.floor(this.height);return this};_.Rh.prototype.round=function(){this.width=window.Math.round(this.width);this.height=window.Math.round(this.height);return this};_.Sh.prototype.Z=function(){return new _.Sh(this.x,this.y)};
_.pi=_.Yg?"MozUserSelect":_.Zg?"WebkitUserSelect":_.s;_.li=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;
_.qi=function(a){return(0,window.String)(a).replace(/\-([a-z])/g,function(a,f){return f.toUpperCase()})};_.ri=function(a){return"rtl"==(0,_.di)(a,"direction")};
_.si=function(a,c){var f=(0,_.qi)(c);if(a.style[f]===_.p){var g=_.Zg?"Webkit":_.Yg?"Moz":_.S?"ms":_.Xg?"O":_.s,h;h=(h=(0,_.ga)(_.p)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s")?"|["+h+"]+":"";h=c.replace((0,window.RegExp)("(^"+h+")([a-z])","g"),function(a,c,f){return c+f.toUpperCase()});g=g+h;if(a.style[g]!==_.p)return g}return f};_.vi=function(a,c,f){(f=(0,_.si)(a,f))&&(a.style[f]=c)};
_.wi=function(a,c,f,g){this.left=a;this.top=c;this.width=f;this.height=g};_.T=function(a,c){a.style.display=c?"":"none"};_.xi=function(a){var c=(0,_.ii)(a);a=(0,_.mi)(a);return new _.wi(c.x,c.y,a.width,a.height)};_.yi=function(a,c,f){(0,_.ga)(c)?(0,_.vi)(a,f,c):(0,_.kh)(c,(0,_.ma)(_.vi,a))};_.wi.prototype.Z=function(){return new _.wi(this.left,this.top,this.width,this.height)};
_.wi.prototype.contains=function(a){return a instanceof _.wi?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};

_.zi=function(a,c,f,g){this.top=a;this.right=c;this.bottom=f;this.left=g};
_.Ai=function(a,c,f,g){a=g||a;c=c&&"*"!=c?c.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(c||f))return a.querySelectorAll(c+(f?"."+f:""));if(f&&a.getElementsByClassName){a=a.getElementsByClassName(f);if(c){g={};for(var h=0,l=0,n;n=a[l];l++)c==n.nodeName&&(g[h++]=n);g.length=h;return g}return a}a=a.getElementsByTagName(c||"*");if(f){g={};for(l=h=0;n=a[l];l++)c=n.className,"function"==typeof c.split&&(0,_.ng)(c.split(/\s+/),f)&&(g[h++]=n);g.length=h;return g}return a};
_.Bi=function(a,c,f,g){if(/^\d+px?$/.test(c))return(0,window.parseInt)(c,10);var h=a.style[f],l=a.runtimeStyle[f];a.runtimeStyle[f]=a.currentStyle[f];a.style[f]=c;c=a.style[g];a.style[f]=h;a.runtimeStyle[f]=l;return c};_.Ci=function(a,c){if("none"==(0,_.ci)(a,c+"Style"))return 0;var f=(0,_.ci)(a,c+"Width");return f in _.Di?_.Di[f]:(0,_.Bi)(a,f,"left","pixelLeft")};_.Ei=function(a,c){var f=(0,_.ci)(a,c);return f?(0,_.Bi)(a,f,"left","pixelLeft"):0};
_.Fi=function(a){if(_.S){var c=(0,_.Ci)(a,"borderLeft"),f=(0,_.Ci)(a,"borderRight"),g=(0,_.Ci)(a,"borderTop");a=(0,_.Ci)(a,"borderBottom");return new _.zi(g,f,a,c)}c=(0,_.bi)(a,"borderLeftWidth");f=(0,_.bi)(a,"borderRightWidth");g=(0,_.bi)(a,"borderTopWidth");a=(0,_.bi)(a,"borderBottomWidth");return new _.zi((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c))};_.Gi=function(a,c){"number"==typeof a&&(a=(c?window.Math.round(a):a)+"px");return a};
_.Hi=function(a){var c;if(_.S){c=(0,_.Ei)(a,"paddingLeft");var f=(0,_.Ei)(a,"paddingRight"),g=(0,_.Ei)(a,"paddingTop");a=(0,_.Ei)(a,"paddingBottom");c=new _.zi(g,f,a,c)}else c=(0,_.bi)(a,"paddingLeft"),f=(0,_.bi)(a,"paddingRight"),g=(0,_.bi)(a,"paddingTop"),a=(0,_.bi)(a,"paddingBottom"),c=new _.zi((0,window.parseFloat)(g),(0,window.parseFloat)(f),(0,window.parseFloat)(a),(0,window.parseFloat)(c));return c};_.Ii=function(a,c){return new _.Sh(a.x-c.x,a.y-c.y)};
_.Ji=function(a,c){var f=(0,_.Zh)(c),g=_.s;if(_.S)f=g=f.b.createStyleSheet(),_.S?f.cssText=a:f.innerHTML=a;else{var h=(0,_.Ai)(f.b,"head",_.p,_.p)[0];h||(g=(0,_.Ai)(f.b,"body",_.p,_.p)[0],h=f.F("head"),g.parentNode.insertBefore(h,g));var l=g=f.F("style");_.S?l.cssText=a:l.innerHTML=a;f.appendChild(h,g)}return g};_.Ki=function(a,c,f){c instanceof _.Rh?(f=c.height,c=c.width):f==_.p&&(0,_.m)((0,window.Error)("p"));a.style.width=(0,_.Gi)(c,_.q);a.style.height=(0,_.Gi)(f,_.q)};
_.Li=function(a){for(var c=new _.zi(0,window.Infinity,window.Infinity,0),f=(0,_.Zh)(a),g=f.b.body,h=f.b.documentElement,l=(0,_.Qh)(f.b);a=(0,_.hi)(a);)if((!_.S||0!=a.clientWidth)&&(!_.Zg||0!=a.clientHeight||a!=g)&&a!=g&&a!=h&&"visible"!=(0,_.di)(a,"overflow")){var n=(0,_.ii)(a),r;r=a;if(_.Yg&&!(0,_.Kg)("1.9")){var u=(0,window.parseFloat)((0,_.bi)(r,"borderLeftWidth"));if((0,_.ri)(r))var w=r.offsetWidth-r.clientWidth-u-(0,window.parseFloat)((0,_.bi)(r,"borderRightWidth")),u=u+w;r=new _.Sh(u,(0,window.parseFloat)((0,_.bi)(r,
"borderTopWidth")))}else r=new _.Sh(r.clientLeft,r.clientTop);n.x+=r.x;n.y+=r.y;c.top=window.Math.max(c.top,n.y);c.right=window.Math.min(c.right,n.x+a.clientWidth);c.bottom=window.Math.min(c.bottom,n.y+a.clientHeight);c.left=window.Math.max(c.left,n.x)}g=l.scrollLeft;l=l.scrollTop;c.left=window.Math.max(c.left,g);c.top=window.Math.max(c.top,l);f=(0,_.Yh)((0,_.Wh)(f));c.right=window.Math.min(c.right,g+f.width);c.bottom=window.Math.min(c.bottom,l+f.height);return 0<=c.top&&0<=c.left&&c.bottom>c.top&&
c.right>c.left?c:_.s};_.Mi=function(a,c,f){var g,h=_.Yg&&(_.Ug||_.ch)&&(0,_.Kg)("1.9");c instanceof _.Sh?(g=c.x,c=c.y):(g=c,c=f);a.style.left=(0,_.Gi)(g,h);a.style.top=(0,_.Gi)(c,h)};_.Ni=function(a,c){return(0,_.ng)((0,_.oh)(a),c)};
_.Oi=function(a,c,f,g,h,l,n,r,u){var w,x;if(w=f.offsetParent){var A="HTML"==w.tagName||"BODY"==w.tagName;if(!A||"static"!=(0,_.ei)(w))x=(0,_.ii)(w),A||(A=(A=(0,_.ri)(w))&&_.Yg?-w.scrollLeft:A&&(!_.S||!(0,_.Kg)("8"))?w.scrollWidth-w.clientWidth-w.scrollLeft:w.scrollLeft,x=(0,_.Ii)(x,new _.Sh(A,w.scrollTop)))}w=x||new _.Sh;x=(0,_.xi)(a);if(A=(0,_.Li)(a)){var G=new _.wi(A.left,A.top,A.right-A.left,A.bottom-A.top),A=window.Math.max(x.left,G.left),J=window.Math.min(x.left+x.width,G.left+G.width);if(A<=
J){var K=window.Math.max(x.top,G.top),G=window.Math.min(x.top+x.height,G.top+G.height);K<=G&&(x.left=A,x.top=K,x.width=J-A,x.height=G-K)}}A=(0,_.Zh)(a);K=(0,_.Zh)(f);A.b!=K.b&&(J=A.b.body,K=(0,_.ji)(J,(0,_.Wh)(K)),K=(0,_.Ii)(K,(0,_.ii)(J)),_.S&&!(0,_.Xh)(A)&&(K=(0,_.Ii)(K,(0,_.Vh)(A))),x.left+=K.x,x.top+=K.y);a=(c&4&&(0,_.ri)(a)?c^2:c)&-5;c=new _.Sh(a&2?x.left+x.width:x.left,a&1?x.top+x.height:x.top);c=(0,_.Ii)(c,w);h&&(c.x+=(a&2?-1:1)*h.x,c.y+=(a&1?-1:1)*h.y);var L;if(n)if(u)L=u;else if(L=(0,_.Li)(f))L.top-=
w.y,L.right-=w.x,L.bottom-=w.y,L.left-=w.x;return(0,_.Pi)(c,f,g,l,L,n,r)};
_.Pi=function(a,c,f,g,h,l,n){a=a.Z();var r=0,u=(f&4&&(0,_.ri)(c)?f^2:f)&-5;f=(0,_.mi)(c);n=n?n.Z():f.Z();if(g||0!=u)u&2?a.x-=n.width+(g?g.right:0):g&&(a.x+=g.left),u&1?a.y-=n.height+(g?g.bottom:0):g&&(a.y+=g.top);if(l){if(h){r=a;g=0;if(65==(l&65)&&(r.x<h.left||r.x>=h.right))l&=-2;if(132==(l&132)&&(r.y<h.top||r.y>=h.bottom))l&=-5;r.x<h.left&&l&1&&(r.x=h.left,g|=1);r.x<h.left&&(r.x+n.width>h.right&&l&16)&&(n.width=window.Math.max(n.width-(r.x+n.width-h.right),0),g|=4);r.x+n.width>h.right&&l&1&&(r.x=
window.Math.max(h.right-n.width,h.left),g|=1);l&2&&(g|=(r.x<h.left?16:0)|(r.x+n.width>h.right?32:0));r.y<h.top&&l&4&&(r.y=h.top,g|=2);r.y>=h.top&&(r.y+n.height>h.bottom&&l&32)&&(n.height=window.Math.max(n.height-(r.y+n.height-h.bottom),0),g|=8);r.y+n.height>h.bottom&&l&4&&(r.y=window.Math.max(h.bottom-n.height,h.top),g|=2);l&8&&(g|=(r.y<h.top?64:0)|(r.y+n.height>h.bottom?128:0));r=g}else r=256;if(r&496)return r}(0,_.Mi)(c,a);if(!(f==n||(!f||!n?0:f.width==n.width&&f.height==n.height)))h=(0,_.Xh)((0,_.Zh)((0,_.Gh)(c))),
_.S&&(!h||!(0,_.Kg)("8"))?(a=c.style,h?(h=(0,_.Hi)(c),c=(0,_.Fi)(c),a.pixelWidth=n.width-c.left-h.left-h.right-c.right,a.pixelHeight=n.height-c.top-h.top-h.bottom-c.bottom):(a.pixelWidth=n.width,a.pixelHeight=n.height)):(c=c.style,_.Yg?c.MozBoxSizing="border-box":_.Zg?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=window.Math.max(n.width,0)+"px",c.height=window.Math.max(n.height,0)+"px");return r};_.zi.prototype.Z=function(){return new _.zi(this.top,this.right,this.bottom,this.left)}; _.zi.prototype.contains=function(a){return!this||!a?_.t:a instanceof _.zi?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};_.Di={thin:2,medium:4,thick:6};

_.Qi=function(){};_.Ri=function(a){a&&"function"==typeof a.K&&a.K()};_.Si=function(a){for(var c=0,f=arguments.length;c<f;++c){var g=arguments[c];(0,_.fa)(g)?_.Si.apply(_.s,g):(0,_.Ri)(g)}};_.Qi.prototype.da=_.t;_.Qi.prototype.Ia=(0,_.y)("da");_.Qi.prototype.K=function(){this.da||(this.da=_.q,this.B())};_.Qi.prototype.B=function(){this.Y&&_.Si.apply(_.s,this.Y);if(this.Ub)for(;this.Ub.length;)this.Ub.shift()()};
_.Ti=function(a,c){for(var f=a.split("."),g=c||_.F,h;h=f.shift();)if(g[h]!=_.s)g=g[h];else return _.s;return g};_.Ui=function(){};_.Vi=function(a){_.Wi[_.Wi.length]=a;if(_.Xi)for(var c=0;c<_.Yi.length;c++)a((0,_.D)(_.Yi[c].b,_.Yi[c]))};_.Zi=function(a){_.Zi[" "](a);return a};_.$i=function(a,c){this.type=a;this.b=this.target=c};_.aj=function(a,c){a&&this.ea(a,c)};_.bj=function(){};
_.U=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.U)(a,c[l],f,g,h);return _.s}return(0,_.cj)(a,c,f,_.t,g,h)};
_.cj=function(a,c,f,g,h,l){c||(0,_.m)((0,window.Error)("s"));h=!!h;var n=_.dj;c in n||(n[c]={V:0,xb:0});n=n[c];h in n||(n[h]={V:0,xb:0},n.V++);var n=n[h],r=(0,_.lg)(a),u;n.xb++;if(n[r]){u=n[r];for(var w=0;w<u.length;w++)if(n=u[w],n.bc==f&&n.xd==l){if(n.Cd)break;g||(u[w].Ff=_.t);return u[w].key}}else u=n[r]=[],n.V++;var x=_.ej,A=_.fj?function(a){return x.call(A.src,A.key,a)}:function(a){a=x.call(A.src,A.key,a);if(!a)return a},w=A;w.src=a;n=new _.bj;n.ea(f,w,a,c,h,l);n.Ff=g;f=n.key;w.key=f;u.push(n);
_.gj[f]=n;_.hj[r]||(_.hj[r]=[]);_.hj[r].push(n);a.addEventListener?(a==_.F||!a.Rj)&&a.addEventListener(c,w,h):a.attachEvent(c in _.ij?_.ij[c]:_.ij[c]="on"+c,w);return f};
_.jj=function(a){if(!_.gj[a])return _.t;var c=_.gj[a];if(c.Cd)return _.t;var f=c.src,g=c.type,h=c.d,l=c.capture;f.removeEventListener?(f==_.F||!f.Rj)&&f.removeEventListener(g,h,l):f.detachEvent&&f.detachEvent(g in _.ij?_.ij[g]:_.ij[g]="on"+g,h);f=(0,_.lg)(f);_.hj[f]&&(h=_.hj[f],(0,_.rg)(h,c),0==h.length&&delete _.hj[f]);c.Cd=_.q;if(c=_.dj[g][l][f])c.nl=_.q,(0,_.kj)(g,l,f,c);delete _.gj[a];return _.q};
_.kj=function(a,c,f,g){if(!g.ug&&g.nl){for(var h=0,l=0;h<g.length;h++)g[h].Cd?g[h].d.src=_.s:(h!=l&&(g[l]=g[h]),l++);g.length=l;g.nl=_.t;0==l&&(delete _.dj[a][c][f],_.dj[a][c].V--,0==_.dj[a][c].V&&(delete _.dj[a][c],_.dj[a].V--),0==_.dj[a].V&&delete _.dj[a])}};_.lj=function(a,c,f){var g=_.dj;return c in g&&(g=g[c],f in g&&(g=g[f],a=(0,_.lg)(a),g[a]))?g[a]:_.s};
_.mj=function(a,c,f,g,h){var l=1;c=(0,_.lg)(c);if(a[c]){a.xb--;a=a[c];a.ug?a.ug++:a.ug=1;try{for(var n=a.length,r=0;r<n;r++){var u=a[r];u&&!u.Cd&&(l&=(0,_.nj)(u,h)!==_.t)}}finally{a.ug--,(0,_.kj)(f,g,c,a)}}return(0,window.Boolean)(l)};_.nj=function(a,c){a.Ff&&(0,_.jj)(a.key);return a.handleEvent(c)};
_.ej=function(a,c){if(!_.gj[a])return _.q;var f=_.gj[a],g=f.type,h=_.dj;if(!(g in h))return _.q;var h=h[g],l,n;if(!_.fj){l=c||(0,_.Ti)("window.event");var r=_.q in h,u=_.t in h;if(r){if(0>l.keyCode||l.returnValue!=_.p)return _.q;a:{var w=_.t;if(0==l.keyCode)try{l.keyCode=-1;break a}catch(x){w=_.q}if(w||l.returnValue==_.p)l.returnValue=_.q}}w=new _.aj;w.ea(l,this);l=_.q;try{if(r){for(var A=[],G=w.b;G;G=G.parentNode)A.push(G);n=h[_.q];n.xb=n.V;for(var J=A.length-1;!w.Ad&&0<=J&&n.xb;J--)w.b=A[J],l&= (0,_.mj)(n,A[J],g,_.q,w);if(u){n=h[_.t];n.xb=n.V;for(J=0;!w.Ad&&J<A.length&&n.xb;J++)w.b=A[J],l&=(0,_.mj)(n,A[J],g,_.t,w)}}else l=(0,_.nj)(f,w)}finally{A&&(A.length=0)}return l}g=new _.aj(c,this);return l=(0,_.nj)(f,g)};_.Wi=[];_.Yi=[];_.Xi=_.t;
_.Zi[" "]=_.Ui;_.oj=!_.S||(0,_.Ng)(9);_.fj=!_.S||(0,_.Ng)(9);_.pj=_.S&&!(0,_.Kg)("9");!_.Zg||(0,_.Kg)("528");_.Yg&&(0,_.Kg)("1.9b")||_.S&&(0,_.Kg)("8")||_.Xg&&(0,_.Kg)("9.5")||_.Zg&&(0,_.Kg)("528");_.Yg&&!(0,_.Kg)("8")||_.S&&(0,_.Kg)("9");_.B=_.$i.prototype;_.B.B=(0,_.v)();_.B.K=(0,_.v)();_.B.Ad=_.t;_.B.Kg=_.q;_.B.stopPropagation=function(){this.Ad=_.q};_.B.preventDefault=function(){this.Kg=_.t};(0,_.E)(_.aj,_.$i);_.B=_.aj.prototype;_.B.target=_.s;_.B.Wb=_.s;_.B.mk=0;_.B.nk=0;_.B.clientX=0;_.B.clientY=0;_.B.screenX=0;_.B.screenY=0;_.B.button=0;_.B.keyCode=0;_.B.charCode=0;_.B.ctrlKey=_.t;_.B.altKey=_.t;_.B.shiftKey=_.t;_.B.metaKey=_.t;_.B.Pi=_.t;_.B.Pa=_.s;
_.B.ea=function(a,c){var f=this.type=a.type;_.$i.call(this,f);this.target=a.target||a.srcElement;this.b=c;var g=a.relatedTarget;if(g){if(_.Yg){var h;a:{try{(0,_.Zi)(g.nodeName);h=_.q;break a}catch(l){}h=_.t}h||(g=_.s)}}else"mouseover"==f?g=a.fromElement:"mouseout"==f&&(g=a.toElement);this.Wb=g;this.mk=_.Zg||a.offsetX!==_.p?a.offsetX:a.layerX;this.nk=_.Zg||a.offsetY!==_.p?a.offsetY:a.layerY;this.clientX=a.clientX!==_.p?a.clientX:a.pageX;this.clientY=a.clientY!==_.p?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==f?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Pi=_.Ug?a.metaKey:a.ctrlKey;this.state=a.state;this.Pa=a;a.defaultPrevented&&this.preventDefault();delete this.Ad};_.B.stopPropagation=function(){_.aj.u.stopPropagation.call(this);this.Pa.stopPropagation?this.Pa.stopPropagation():this.Pa.cancelBubble=_.q};
_.B.preventDefault=function(){_.aj.u.preventDefault.call(this);var a=this.Pa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=_.t,_.pj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(c){}};_.B.Po=(0,_.y)("Pa");_.B.B=(0,_.v)();
_.qj=0;_.B=_.bj.prototype;_.B.key=0;_.B.Cd=_.t;_.B.Ff=_.t;_.B.ea=function(a,c,f,g,h,l){(0,_.ha)(a)?this.b=_.q:a&&a.handleEvent&&(0,_.ha)(a.handleEvent)?this.b=_.t:(0,_.m)((0,window.Error)("r"));this.bc=a;this.d=c;this.src=f;this.type=g;this.capture=!!h;this.xd=l;this.Ff=_.t;this.key=++_.qj;this.Cd=_.t};_.B.handleEvent=function(a){return this.b?this.bc.call(this.xd||this.src,a):this.bc.handleEvent.call(this.bc,a)};
_.gj={};_.dj={};_.hj={};_.ij={};(0,_.Vi)(function(a){_.ej=a(_.ej)});
_.rj=function(a){return"number"==typeof a};_.sj=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.sj)(a,c[l],f,g,h);return _.s}g=!!g;a=(0,_.lj)(a,c,g);if(!a)return _.t;for(l=0;l<a.length;l++)if(a[l].bc==f&&a[l].capture==g&&a[l].xd==h)return(0,_.jj)(a[l].key);return _.t};_.tj=function(a,c,f,g,h){if((0,_.ea)(c)){for(var l=0;l<c.length;l++)(0,_.tj)(a,c[l],f,g,h);return _.s}return(0,_.cj)(a,c,f,_.q,g,h)};_.uj=function(){};(0,_.E)(_.uj,_.Qi);_.B=_.uj.prototype;_.B.Rj=_.q;_.B.Cg=_.s;
_.B.aj=(0,_.ba)("Cg");_.B.addEventListener=function(a,c,f,g){(0,_.U)(this,a,c,f,g)};_.B.removeEventListener=function(a,c,f,g){(0,_.sj)(this,a,c,f,g)};
_.B.dispatchEvent=function(a){var c=a.type||a,f=_.dj;if(c in f){if((0,_.ga)(a))a=new _.$i(a,this);else if(a instanceof _.$i)a.target=a.target||this;else{var g=a;a=new _.$i(c,this);(0,_.mh)(a,g)}var g=1,h,f=f[c],c=_.q in f,l;if(c){h=[];for(l=this;l;l=l.Cg)h.push(l);l=f[_.q];l.xb=l.V;for(var n=h.length-1;!a.Ad&&0<=n&&l.xb;n--)a.b=h[n],g&=(0,_.mj)(l,h[n],a.type,_.q,a)&&a.Kg!=_.t}if(_.t in f)if(l=f[_.t],l.xb=l.V,c)for(n=0;!a.Ad&&n<h.length&&l.xb;n++)a.b=h[n],g&=(0,_.mj)(l,h[n],a.type,_.t,a)&&a.Kg!=_.t;
else for(h=this;!a.Ad&&h&&l.xb;h=h.Cg)a.b=h,g&=(0,_.mj)(l,h,a.type,_.t,a)&&a.Kg!=_.t;a=(0,window.Boolean)(g)}else a=_.q;return a};_.B.B=function(){_.uj.u.B.call(this);var a=_.p,c=0,f=this==_.s,g=a==_.s,a=!!a;if(f)(0,_.kh)(_.hj,function(f){for(var h=f.length-1;0<=h;h--){var l=f[h];if(g||a==l.capture)(0,_.jj)(l.key),c++}});else if(f=(0,_.lg)(this),_.hj[f])for(var f=_.hj[f],h=f.length-1;0<=h;h--){var l=f[h];if(g||a==l.capture)(0,_.jj)(l.key),c++}this.Cg=_.s};

_.vj=function(a){return new _.zi(a.top,a.left+a.width,a.top+a.height,a.left)};_.wj=function(a){this.v=a;this.b=a.la};
_.xj=function(a){var c=a.v.xa;if(a.b.anchorBox&&c&&c.ca())c=(0,_.ii)(c.ca()),a.b.anchorBox.left+=c.x,a.b.anchorBox.top+=c.y;else{c=a.b.anchor;if("_default"!=c&&"_iframe"!=c){var f=(0,_.rh)(c);if(f)a.b.anchorBox=(0,_.xi)(f);else{(0,_.ib)("Anchor not found in DOM: "+c+'. Falling back to "_default".');a.b.anchor="_default";return}}"_iframe"==c&&(c=(0,_.Yh)(),a.b.anchorBox=new _.wi(0,0,c.width,c.height))}a.b.anchor=""};_.yj=function(a){_.wj.call(this,a)};
_.zj=function(a){if(a.k)return a.k;var c=a.b;!c.anchorBox&&c.anchor&&(0,_.xj)(a);var f=a.v.xa;if("_default"==c.anchor&&f){var g=(0,_.xi)((0,_.rh)(f.T));c.anchorBox=g}if(!c.anchorBox)return(0,_.ib)("No anchor box defined."),_.s;g=new _.Sh(c.anchorBox.left,c.anchorBox.top);f&&(f=(0,_.ji)(f.ca(),window),a.C=new _.Sh,a.C.x=f.x,a.C.y=f.y,g.x+=f.x,g.y+=f.y,(0,_.Aj)(window,g));c={position:"absolute",background:"transparent",left:g.x+"px",top:g.y+"px",width:c.anchorBox.width+"px",height:c.anchorBox.height+
"px",zIndex:-1E4};a.k=window.document.createElement("ins");(0,_.yi)(a.k,c);window.document.body.appendChild(a.k);return a.k};
_.Bj=function(a,c){var f=0,g=0;if(c.pageX||c.pageY)f=c.pageX,g=c.pageY;else if(c.clientX||c.clientY){var g=c.target?c.target:c.srcElement,f=g.ownerDocument&&g.ownerDocument.parentWindow?g.ownerDocument.parentWindow:window,h=0,g=0;_.S?(h=f.document.documentElement.scrollLeft,g=f.document.documentElement.scrollTop):(h=f.pageXOffset,g=f.pageYOffset);f=c.clientX+h;g=c.clientY+g}g=new _.Sh(f,g);return(f=(0,_.vj)((0,_.xi)(a)))&&f.contains(g)};
_.Aj=function(a,c){var f=window.document.body,g=(0,_.ii)(f),f=f.currentStyle||a.getComputedStyle(f,"");f.position&&"static"!=f.position&&(c.x-=g.x,c.y-=g.y)};_.Cj=function(a){var c=a.v.xa&&a.v.xa.T,c=c&&c.style.zIndex?(0,window.parseInt)(c.style.zIndex,10)+1:0;return window.Math.min(2147483647,window.Math.max(2E9,a.b.zIndex||c))};
_.Dj=function(a,c,f,g,h){h=h||{x:0,y:0};if(_.Ej[c]){var l=(0,_.mi)(a).width/2;h.x="top-right"==g||"bottom-right"==g?h.x+l:h.x-l}_.Ej[g]&&(l=(0,_.mi)(f).width/2,h.x+=l);_.Fj[c]&&(l=(0,_.mi)(a).height/2,h.y="right-bottom"==g||"left-bottom"==g?h.y+l:h.y-l);_.Fj[g]&&(h.y+=(0,_.mi)(f).height/2);(0,_.Oi)(f,_.Gj[g],a,_.Gj[c],new _.Sh(h.x,h.y));a:{c=a;c=c.parentNode;for(f=0;c;){g=c==window.document?_.t:(g=(0,_.ei)(c))&&"static"!=g;if(g){g=c;break a}c=c.parentNode;f++}g=_.s}f=c=0;g&&(f=(0,_.ii)(g),c=-f.x,
f=-f.y);a=a.style;(0,window.parseInt)(a.left,10)<c&&(a.left=c+"px");(0,window.parseInt)(a.top,10)<f&&(a.top=f+"px")};_.Hj=function(a){_.wj.call(this,a.v);this.d=a;this.i=_.s};_.Ij=function(){this.b=[]};if("undefined"===typeof _.Jj)_.Jj={};_.wj.prototype.Y=function(){(0,_.xj)(this)};_.wj.prototype.onBeforeParentOpen=_.wj.prototype.Y;
(0,_.E)(_.yj,_.wj);_.yj.prototype.open=function(){var a=this.b,c=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(c);c.style.display="block";(0,_.yi)(c,a.containerCss);this.v.Ic(c);this.v.Ka(c)};_.yj.prototype.eb=function(){window.document.getElementById(this.v.id).style.height=this.v.height+"px"};_.yj.prototype.close=function(){(0,_.Ah)(this.v.T);(0,_.Ah)(this.k);this.k=_.s};
_.Gj={"bottom-center":1,"bottom-end":7,"bottom-left":1,"bottom-right":3,"bottom-start":5,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":3,"right-center":2,"right-top":2,"top-center":0,"top-end":6,"top-left":0,"top-right":2,"top-start":4};_.Ej={"bottom-center":_.q,"top-center":_.q};_.Fj={"left-center":_.q,"right-center":_.q};
(0,_.E)(_.Hj,_.yj);_.Hj.prototype.Y=function(){this.d.Y()};_.Hj.prototype.onBeforeParentOpen=_.Hj.prototype.Y;_.Hj.prototype.open=function(){this.d.open();if(this.b.closeClickDetection||this.b.hideClickDetection)this.i=(0,_.U)(window.document,"click",(0,_.D)(this.j,this),_.t)};_.Hj.prototype.open=_.Hj.prototype.open;_.Hj.prototype.eb=function(a){this.d.eb(a)};_.Hj.prototype.onready=_.Hj.prototype.eb;_.Hj.prototype.xl=function(a){this.d.onRenderStart&&this.d.onRenderStart(a)};
_.Hj.prototype.onRenderStart=_.Hj.prototype.xl;_.Hj.prototype.close=function(){if(this.b.closeClickDetection||this.b.hideClickDetection)(0,_.jj)(this.i),this.i=_.s;this.d.close()};_.Hj.prototype.close=_.Hj.prototype.close;_.Hj.prototype.j=function(a){(0,_.Bj)(this.v.T,a)||(this.b.hideClickDetection&&this.v.show?this.v.show(_.t):this.v.close())};
(0,_.E)(_.Ij,_.uj);_.Ij.prototype.B=function(){for(var a in this.b)(0,_.jj)(a);this.b=[];this.d=_.F.clearTimeout(this.d);_.Ij.u.B.call(this);this.dispatchEvent({type:"dispose"})};(0,_.I)("iframes.styles.createAnchor",function(){return new _.Ij(["email","oid","o","cid"])},_.p);

for(_.Mu="bubble circlepicker float hover hover-menu slide-menu".split(" "),_.i=0;_.i<_.Mu.length;_.i++)_.R.ia(_.Mu[_.i],function(a){return new _.wj(a)});
});

// Copyright 2002-2012 Google Inc.
