"undefined"==typeof gigya&&(gigya={});"undefined"==typeof gigya.global&&(gigya.global={});"undefined"==typeof gigya.services&&(gigya.services={});"undefined"==typeof gigya.services.socialize&&(gigya.services.socialize={});
gigya.pluginUtils={validation:{isEmailValid:function(a){return gigya.pluginUtils.validation.isEmailListValid(a)},isEmailListValid:function(a){return RegExp('^( *)?((("[^<]+<(([0-9a-zA-Z!#\\$%&\\\'\\*\\+\\-/=\\?\\^_`\\{\\|\\}\\~\\.]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4})))>")|(("[^"]*" *)?<(([0-9a-zA-Z!#\\$%&\\\'\\*\\+\\-/=\\?\\^_`\\{\\|\\}\\~\\.]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4})))>)|(([0-9a-zA-Z!#\\$%&\\\'\\*\\+\\-/=\\?\\^_`\\{\\|\\}\\~\\.]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4})))) *, *)*(("[^<]+<(([0-9a-zA-Z!#\\$%&\\\'\\*\\+\\-/=\\?\\^_`\\{\\|\\}\\~\\.]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4})))>")|(("[^"]*" *)?<(([0-9a-zA-Z!#\\$%&\\\'\\*\\+\\-/=\\?\\^_`\\{\\|\\}\\~\\.]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4})))>)|(([0-9a-zA-Z!#\\$%&\\\'\\*\\+\\-/=\\?\\^_`\\{\\|\\}\\~\\.]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{2,4}))))( *, *)?$').test(a)}},text:{normalizeLinebreaks:function(a){return a&&
a.replace?a.replace(/\r/,"").replace(/\n/g,"\r\n"):a}},animation:{slideDown:function(a){var c=gigya.global.getClassBordersAndPaddings(a.className),d=a.offsetHeight-c.h,b=a.style.transitionProperty;a.style.maxHeight="1px";a.style.transitionProperty=a.style.webkitTransitionProperty="max-height";window.setTimeout(function(){a.style.maxHeight=d+"px";a.style.transitionProperty=a.style.webkitTransitionProperty=b},100);var e=function(){a.style.maxHeight="999px";gigya.utils.DOM.removeEventListener(a,"transitionend",
e);gigya.utils.DOM.removeEventListener(a,"webkitTransitionEnd",e)};gigya.utils.DOM.addEventListener(a,"transitionend",e);gigya.utils.DOM.addEventListener(a,"webkitTransitionEnd",e);window.setTimeout(e,500)},fadeIn:function(a,c){"undefined"===typeof c&&(c=1);a.style.opacity="0";window.setTimeout(function(){a.style.opacity=c+""},10)}},css:{fixCss:function(a){if(gigya.localInfo.isIE7||gigya.localInfo.isIE&&gigya.localInfo.quirksMode)a=a.replace(/display:inline-block/g,"display:inline-block;zoom:1;*display:inline");
return a.replace(/gradient\((.*?),(.*?)\)/g,'filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="$1", endColorstr="$2");background: linear-gradient(top,  $1,  $2);background: -ms-linear-gradient(top left, $1, $2);background: -webkit-gradient(linear, left top, left bottom, from($1), to($2));background: -moz-linear-gradient(top,  $1,  $2)')}},DOM:{setTextboxSubmitButton:function(a,c){gigya.utils.DOM.addEventListener(a,"keyup",function(a){a&&a.which?a=a.which:(a=event,a=a.keyCode);13==
a&&c.click()})},getRelativePosition:function(a,c,d,b,e){var f={top:0,left:0,bottom:0,right:0};"bottom"===d?(f.top=a.bottom+b,f.left=e?a.right-c.w:a.left):"top"===d?(f.top=a.top-c.h-b,f.left=e?a.right-c.w:a.left):"left"===d?(f.top=e?a.bottom-c.h:a.top,f.left=a.left-c.w-b):(f.top=e?a.bottom-c.h:a.top,f.left=a.right+b);f.bottom=f.top+c.h;f.right=f.left+c.w;return f},placePopoverNearElement:function(a,c,d,b,e,f){a=gigya.utils.DOM.getElementPosition(a);size={w:c.offsetWidth,h:c.offsetHeight};var g=this.getRelativePosition(a,
size,d,b,e);f&&!gigya.utils.viewport.isRectFullyVisible(g)&&(f=this.getRelativePosition(a,size,{bottom:"top",left:"right",right:"left",top:"bottom"}[d],b),gigya.utils.viewport.isRectHorizontallyVisible(f)&&(g=f));gigya.utils.viewport.isRectHorizontallyVisible(g)||(f=this.getRelativePosition(a,size,d,b,!e),gigya.utils.viewport.isRectHorizontallyVisible(f)&&(g=f));c.style.left=""+g.left+"px";c.style.top=""+g.top+"px"},addPopoverNearElement:function(a,c,d,b,e,f,g,h,k){if(a&&c){d||(d="bottom");b||(b=
0);"undefined"===typeof f&&(f=!0);var l=document.createElement("div");l.appendChild(c);l.style.position="absolute";l.style.zIndex=(gigya.utils.DOM._nextZIndex++).toString();l.style.left="-1000px";document.body.appendChild(l);this.placePopoverNearElement(a,l,d,b,e,f);gigya.pluginUtils.DOM.removeElementOnDocClick(l,h,k);if(g&&"function"===typeof gigya.pluginUtils.animation[g])gigya.pluginUtils.animation[g](c);return l}},removeElementOnDocClick:function(a,c,d){if(a){var b=[a];d&&(b=b.concat(d));this.performOnDocClick(function(){a&&
a.parentNode&&a.parentNode.removeChild(a);c&&c()},b)}},hideElementOnDocClick:function(a,c,d){if(a){var b=[a];d&&b.concat(d);this.performOnDocClick(function(){a.style.display="none";c&&c()},b)}},performOnDocClick:function(a,c){var d=function(b){b=b.target||b.srcElement;for(var e=!1;b&&b.parentNode;){if(c&&-1!=c.indexOf(b)){e=!0;break}b=b.parentNode}e||(gigya.utils.DOM.removeEventListener(document,"mousedown",d),a&&a())};gigya.utils.DOM.addEventListener(document,"mousedown",d)}},layout:{measureText:function(a,
c,d){if(isNaN(d)||0>d)d=0;var b=document.getElementById("gigya_ruler"),e=document.getElementById("gigya_ruler_text");null==b&&(b=document.createElement("div"),e=document.createElement("span"),b.id="gigya_ruler",e.id="gigya_ruler_text",b.style.visibility="hidden",b.style.position="absolute",b.style.margin="0px",b.style.padding="0px",b.appendChild(e),gigya.utils.DOM.appendToBody(b));c&&(b.style.lineHeight=c.size+"px",b.style.fontFamily=c.font,b.style.fontSize=c.size+"px",b.style.fontWeight="true"==
(""+c.bold).toLowerCase()?"bold":"");d?(b.style.whiteSpace="",b.style.width=""+d+"px"):(b.style.whiteSpace="nowrap",b.style.width="auto");b.style.overflow="hidden";b.style.display="";e.innerHTML=a;a=e.offsetWidth;e=e.offsetHeight;if(0==a||0==e)a=b.offsetWidth,e=b.offsetHeight;b.style.display="none";return{w:a,h:e}}},domain:{isInDomain:function(a){if(a)return a="^"+a.replace(/\./g,"\\.").replace(/\*\\./g,"([a-zA-Z0-9]+\\.)*")+"$",RegExp(a).test(document.domain)}}};
gigya.pluginUtils.lang={getLocalizedText:function(a,c,d,b,e){if("te-st"==d)return"TEST_"+c.substring(0,10);d||(d="en");(a=gigya.i18n[a][d]?gigya.i18n[a][d][c]:gigya.i18n[a].en[c])&&b&&(a=a.replace(b,e));return a}};
gigya.utils.mouse.getPosition=function(){var a=0,c=0;if(document.body){var d=this._mouseEventObject;d||(d={clientX:0,clientY:0});if(d.pageX||d.pageY)a=d.pageX,c=d.pageY;else if(d.clientX||d.clientY)a=d.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=d.clientY+document.body.scrollTop+document.documentElement.scrollTop;return{x:a,y:c}}};
gigya.socialize._parseRID=function(a){var c=a.split("@"),d=document.getElementById(c[2]+"_"+c[1]),b;null==(b=gigya.utils.DOM._pseudoContainers[c[2]])&&(b=document.getElementById(c[2]));var e=null;null!=b&&(e=b.Reqs);var f=null;null!=e&&(f=e[parseInt(c[0])]);return{rid:a,container:b,Reqs:e,req:f,swf:d}};
gigya.socialize._closeComponent=function(a,c){var d=gigya.socialize._parseRID(a).req;gigya.socialize.GrayOut&&gigya.socialize.GrayOut(!1);var b=document.getElementById("gigya_ifr_"+d.container.id);null!=b&&(b.style.display="none");c&&gigya.events.dispatchForWidget({eventName:"close"},d.p);d.container.style.display="none"};
gigya.services.socialize._createJSPopup=function(a,c,d,b){var e=gigya.services.socialize._parseRID(a).req,f=e.p,g=e.c;gigya.utils.validation.isExplicitFalse(f.showCaption)&&(b=!0);var h=gigya.services.socialize,k=document.getElementById(f.containerID);e.container=k;e=c.Resolve("+/config/body/background");c=c.Resolve("+/config/body/captions");var l='<table style="'+h.getStyleString(e)+';empty-cells:show;" cellpadding="0" cellspacing="0" >';b?l+="<tr><td>":(l+='<tr style="'+h.getStyleString(c)+'"><td><table style="width:100%" width="100%" cellpadding="0" cellspacing="0"><tr id="'+
f.containerID+'_caption"><td style="vertical-align:middle"><div style="'+h.getStyleString(c)+';padding:7px">'+d+'</div></td><td style="vertical-align:middle">',l+='<div align="right" style="padding-right: 7px; cursor: pointer;'+h.getStyleString(c)+'"><img onclick="gigya.services.socialize._closeComponent(\''+a+'\', true);"  src="'+gigya.thisScript.base+'/gs/i/HTMLLogin/closeIcon.gif" alt="" /></div></td></tr></table></td></tr><tr><td colspan="2">');l+='<div id="'+f.containerID+'_container"></div></td></tr></table>';
k.innerHTML=l;a={};d={};for(var m in f)a[m]=f[m];for(m in g)d[m]=g[m];f=document.getElementById(a.containerID+"_caption");a.height-=2*e["frame-thickness"];b||(a.height-=f.offsetHeight);a.width-=2*e["frame-thickness"];gigya.utils.DOM._popupContainers[a.containerID]=k;a.containerID+="_container";return{c:d,p:a}};
gigya.services.socialize._createJSPopup2=function(a,c,d,b,e,f){var g=gigya.services.socialize._parseRID(a).req,h=g.p,k=g.c,l=gigya.services.socialize,m=document.getElementById(h.containerID);g.container=m;c=c.Resolve("+/config/body/captions");d||(d=10);b||(b=gigya.thisScript.base+"/gs/i/Dialog/DialogBg_");var g="width:"+d+"px;height:"+d+"px",p;f&&(p="1px solid #555555");f='<table style="font-size:1px;padding:0px;margin:0px;vertical-align:middle;font-size:1px;line-height:1px;empty-cells:show;" cellpadding="0" cellspacing="0" >'+
('<tr><td height="'+d+'" style="font-size:1px"><div style="height:'+d+'px"><img src="'+b+'TopLeft.png" style="'+g+'" alt="" /></div></td><td height="'+d+'" style="background-image:url(\''+b+'filler.png\');bakground-repeat:repeat"></td><td height="'+d+'" style="font-size:1px;"><div style="height:'+d+'px"><img style="'+g+'" src="'+b+'TopRight.png" alt="" /></div></td></tr>');e&&(f+="<tr><td style=\"background-image:url('"+b+'filler.png\');background-repeat:repeat"></td><td><table width="100%" cellspacing="0" cellpadding="0" style="border-top:'+
p+";border-left:"+p+";border-right:"+p+';width:100%;background-color:#FFFFFF"><tr><td style="padding-top:10px;padding-left:10px;'+l.getStyleString(c)+'">'+e+'</td><td align="right" valign="top" style="'+l.getStyleString(c)+'"><div style="padding-right:5px;padding-top:5px;text-align:right;"><img style="cursor:pointer" onclick="gigya.services.socialize._closeComponent(\''+a+'\', true);" src="'+b+'close.png" alt="" /></div></td></tr></table></td><td style="background-image:url(\''+b+"filler.png');background-repeat:repeat\"></td></tr>");
f+="<tr><td style=\"background-image:url('"+b+'filler.png\');background-repeat:repeat"></td><td><div style="border-bottom:'+p+";border-left:"+p+";border-right:"+p+';background-color:#FFFFFF" id="'+h.containerID+'_container"></div></td><td style="background-image:url(\''+b+"filler.png');background-repeat:repeat\"></td></tr>";m.innerHTML=f+('<tr><td height="'+d+'" style="font-size:1px;"><div style="height:'+d+'px"><img style="'+g+'" src="'+b+'BottomLeft.png" alt="" /></div></td><td height="'+d+'" style="background-image:url(\''+
b+'filler.png\');bakground-repeat:repeat"></td><td height="'+d+'" style="font-size:1px;"><div style="height:'+d+'px"><img style="'+g+'" src="'+b+'BottomRight.png" alt="" /></div></td></tr></table>');a={};b={};for(var n in h)a[n]=h[n];for(n in k)b[n]=k[n];gigya.utils.DOM._popupContainers[a.containerID]=m;a.containerID+="_container";a.height-=2*d;e&&(""==e.replace(/ /g,"")?a.height-=10:a.height-=gigya.pluginUtils.layout.measureText(e,c).h+10);a.width-=2*d;return{c:b,p:a}};
gigya.global.wbr=function(a,c){a=a.replace(/\n/g,"\n ");for(var d=a.split(" "),b=0;b<d.length;b++)if(d[b].length>c){for(var e=d[b].split(""),f=!1,g,h=-1,k=0;k<e.length;k+=1)f||h++,h==c&&(e.splice(k,0,"&#173;"),h=-1),"&"==e[k]?(f=!0,g=";"):"<"==e[k]&&(f=!0,g=">"),f&&e[k]==g&&(f=!1);d[b]=e.join("")}return d.join(" ").replace(/\n /g,"\n")};gigya.global.scrollToElement=function(a){a&&(a=gigya.global._GetElementPos(a),window.scrollTo(a.left,a.top))};
gigya.global.addCSS=function(a,c){if(a&&""!=a){a instanceof Array&&(a=a.join(" "));c&&(a=a.replace(/([^\s}]*\.gig)/g,c+" $1"));var d=document.createElement("style");d.type="text/css";var b=document.createTextNode(a);d.styleSheet?d.styleSheet.cssText=null!=b.value?b.value:b.nodeValue:d.appendChild(b);var b=document.getElementsByTagName("head"),e=document.body;(0<b.length?b[0]:e).appendChild(d)}};
gigya.global.setPlaceholder=function(a,c,d){a&&(a.onblur=function(){""==this.value&&(d?gigya.utils.DOM.addClassToElement(a,d):a.style.color="#585858",this.value=c,this.placeholderCleared=!1)},a.onfocus=function(){if(!this.placeholderCleared)if(d?gigya.utils.DOM.removeClassFromElement(a,d):a.style.color="",this.value="",this.placeholderCleared=!0,a.setSelectionRange)a.focus(),a.setSelectionRange(0,0);else if(a.createTextRange){var c=a.createTextRange();c.collapse(!0);c.moveEnd("character",0);c.moveStart("character",
0);c.select()}},a.onchange=a.onblur,a.onblur())};
gigya.global.scaleImageToContainer=function(a,c,d){c||(a.parentNode.style.textAlign="left",a.parentNode.style.verticalAlign="top");var b=function(c){for(var b=a.parentNode,d=gigya.global.getStyle(b,c);"auto"==d;)b=b.parentNode,d=gigya.global.getStyle(b,c);c=parseInt(d);isNaN(c)&&(c=0);return c},e=Math.min(b("width"),b("height"));if(gigya.localInfo.quirksMode)var f=gigya.global.getBordersAndPaddings(a.parentNode),e=b("width")-f.w,b=b("height")-f.h,e=Math.min(e,b);gigya.global.scaleImage(a,e,c,d)};
gigya.global.showLoader=function(a,c,d){a&&(c||(c=""),d||(d=parseInt(gigya.global.getStyle(a,"height"))),a.innerHTML='<div class="'+c+'" style="height:'+d+"px;background-image:url('"+gigya.thisScript.base+"/gs/i/gm/loader.gif'); background-repeat:no-repeat;background-position:center center\"></div>")};
gigya.global.getPhotoURL=function(a,c){return!c||a&&""!=a?a&&""!=a&&"https"==gigya.thisScript.protocol&&0==a.indexOf("http:")?gigya.thisScript.base+"/proxy/photos.ashx?u="+gigya.utils.URL.URLEncode(a):a:gigya.global.getPhotoURL(c)};
gigya.global.scaleImage=function(a,c,d,b){var e=a;a.width&&a.height||(e=new Image,e.src=a.src);var f=function(){0==e.width?window.setTimeout(f,100):(e.width>e.height?a.style.width=c+"px":a.style.height=c+"px",a.style.display="",b&&b(a),d||(a.style.marginTop=(c-a.offsetHeight)/2+"px",a.style.marginLeft=(c-a.offsetWidth)/2+"px"))};0<e.width?f():(a.style.display="none",e.onload=function(){window.setTimeout(f,50)})};
gigya.global.createGMBalloon=function(a,c,d,b,e,f,g,h,k){gigya.global.removeGMBalloon();var l="gig_gmBalloon_"+(new Date).getTime();h&&(l=h);a=gigya.global.getBalloonHTML(a,c,d,b,e,f,g,"gigya.global.removeGMBalloon()",l+"_frame");c=document.createElement("div");c.className="gig-balloon";c.style.position="absolute";c.style.zIndex=gigya.utils.DOM._nextZIndex++;c.innerHTML=a;c.id=l;gigya.global.fadeIn(c);gigya.utils.DOM.appendToBody(c);gigya.global.divGMBalloon=c;k||window.setTimeout(function(){document.attachEvent?
document.attachEvent("onclick",gigya.global.removeGMBalloon):document.addEventListener&&document.addEventListener("click",gigya.global.removeGMBalloon,!1)},50);return c};gigya.global.fadeIn=function(a){a.interval&&clearInterval(a.interval);a.style.opacity="0";a.interval=setInterval(function(){var c=parseFloat(a.style.opacity);1<=c&&clearInterval(a.interval);a.style.opacity=c+0.1},10)};
gigya.global.getBordersAndPaddings=function(a){var c=function(c){c=parseInt(gigya.global.getStyle(a,c));isNaN(c)&&(c=0);return c};return{w:c("border-left-width")+c("border-right-width")+c("padding-right")+c("padding-left"),h:c("border-top-width")+c("border-bottom-width")+c("padding-top")+c("padding-bottom")}};
gigya.global.getClassInnerSize=function(a,c,d){var b=document.createElement("div");b.className=a;gigya.utils.DOM.appendToBody(b);a=gigya.global.getBordersAndPaddings(b);c-=a.w;d-=a.h;b.parentNode.removeChild(b);return{w:c,h:d}};
gigya.global.applyEllipsis=function(a,c){for(var d="",b=[],e=/\<(\/)?([^ \/>]+)[ ]?[^>]*(\/)?\>/i,f=0,g=0;g<a.length&&(f<c||0==c);){var h=a.substr(g,1);if("<"==h){h=a.indexOf(">",g);h=a.substring(g,h+1);e.lastIndex=0;var h=e.exec(h),k=h[2].toLowerCase();"/"==h[1]?0<b.length&&b[b.length-1].tagname==k&&b.pop():"/"!=h[3]&&(k="</"+h[2]+">",0<b.length&&(k+=b[b.length-1].cl),b.push({tagname:h[2],cl:k}));d+=h[0];g+=h[0].length-1}else"&"==h?(h=a.indexOf(";",g),8<h-g?d+="&":(d+=a.substring(g,h+1),g=h)):d+=
h,f++;g++}return f<c?a:d+"&#133;"+(0<b.length?b[b.length-1].cl:"")};gigya.global.getClassBordersAndPaddings=function(a){var c=document.createElement("div");c.className=a;gigya.utils.DOM.appendToBody(c);a=gigya.global.getBordersAndPaddings(c);c.parentNode.removeChild(c);return a};
gigya.global.getBalloonHTML=function(a,c,d,b,e,f,g,h,k){gigya.global.addedBalloonCSS||(gigya.global.addCSS([".gig-balloons *, div.gig-balloons, .gig-balloons span, .gig-balloons a:hover, .gig-balloons a:visited, .gig-balloons a:link, .gig-balloons a:active{","border:none; line-height:normal;padding:0px;margin:0px;color:inherit;text-decoration:none;width:auto;float:none;-moz-border-radius:0;border-radius:0;","font-family:arial;font-size:10px;color:#797979;background:none;text-align:left}","div.gig-balloon-frame {",
"zoom:1;padding:15px 10px 10px 10px; border:1px solid #b4b4b4; min-height:80px; background-color:#FFFFFF; z-index:"+gigya.utils.DOM._nextZIndex++ +";","box-shadow:0 0 5px RGBA(0,0,0,0.6);-webkit-box-shadow:0 0 5px RGBA(0,0,0,0.6);-moz-box-shadow:0 0 5px RGBA(0,0,0,0.6);}",'div.gig-balloon-nub {left:1px; position:relative;background-image:url("'+gigya.thisScript.base+'/gs/i/gm/nub.png");width:13px;height:25px; z-index:'+gigya.utils.DOM._nextZIndex++ +" }",'div.gig-balloon-nub-right { left:-1px; position:relative;background-image:url("'+
gigya.thisScript.base+'/gs/i/gm/nub_right.png");width:13px;height:25px; z-index:'+gigya.utils.DOM._nextZIndex++ +" }",'span.gig-balloon-closeImage { cursor:pointer; float:right;background-image:url("'+gigya.thisScript.base+'/gs/i/gm/CloseButton.png"); width:14px;height:14px; margin:-7px -2px 0 0  }',"div.gig-balloon-caption {font-family:arial; font-size: 12px; font-weight:bold; color: #0b81c1; border-bottom: 1px solid #e8e8e8;padding-bottom:2px;}","span.gig-balloon-caption-text {float:left}"]),!gigya.localInfo.isIE||
!gigya.localInfo.quirksMode&&gigya.localInfo.isIE9||gigya.global.addCSS(["div.gig-balloon-frame {","-ms-filter: \"progid:DXImageTransform.Microsoft.Shadow(Strength=4, Direction=135, Color='#B4B4B4');\";","filter: progid:DXImageTransform.Microsoft.Shadow(Strength=4, Direction=135, Color='#B4B4B4');}","}","div.gig-balloon-nub-right { left:-5px;}"]),gigya.global.addedBalloonCSS=!0);var l="";if(gigya.localInfo.quirksMode){var m=gigya.global.getClassBordersAndPaddings("gig-balloon-frame");d&&(d+=m.w);
b&&(b+=m.h)}d&&(l+="width: "+d+"px;");b&&(l+="height: "+b+"px;");b="";e&&(b+="top: "+e+"px;");m="";m=c?m+('<div class="gig-balloon-caption"><span class="gig-balloon-caption-text" style="width:'+(d-20)+'px">'+c+"</span>"):m+'<div class="gig-balloon-caption" style="border-bottom:none">';!g&&h&&(m+='<span class="gig-balloon-closeImage" onclick="'+h+'"></span>');m+='<div style="clear:both;height:0;width:0;font-size:1px;">\x3c!-- empty divs=100% height IE --\x3e</div></div><div class="gig-balloon-body">'+
a+"</div>";e?(a='<table cellpadding="0" cellspacing="0" class="gig-balloon"><tr>',a=("right"==f?a+('<td style="vertical-align:top"><div id="'+k+'" class="gig-balloon-frame" style="'+l+'">'+m+'</div></td><td style="vertical-align:top"><div class="gig-balloon-nub-right" style="'+b+'"></div></td>'):a+('<td style="vertical-align:top"><div class="gig-balloon-nub" style="'+b+'"></div></td><td style="vertical-align:top"><div id="'+k+'" class="gig-balloon-frame" style="'+l+'">'+m+"</div></td>"))+"</tr></table>",
a+='<div style="clear:both;height:0;width:0;font-size:1px;">\x3c!-- empty divs=100% height IE --\x3e</div>'):a='<div class="gig-balloon gig-balloon-frame" style="'+l+'">'+m+"</div>";return a};
gigya.global.addIframeShim=function(a,c){if(!a.shim){var d=document.createElement("IFRAME");d.frameborder="0";d.frameBorder="0";d.allowtransparency=!0;d.style.position="absolute";d.update=function(b){if(d&&a){if(c)d.style.left=a.offsetLeft+"px",d.style.top=a.offsetTop+"px";else{var e=gigya.global._GetElementPos(a);d.style.left=e.left+"px";d.style.top=e.top+"px"}b&&(d.style.width=a.offsetWidth+"px",d.style.height=a.offsetHeight+"px")}};d.update(!0);c?(d.style.zIndex=gigya.utils.DOM._nextZIndex++,a.style.zIndex=
gigya.utils.DOM._nextZIndex++,c.appendChild(d)):gigya.utils.DOM.appendToBody(d);a.shim=d}};gigya.global.removeIframeShim=function(a){a&&(a.shim&&a.shim.parentNode)&&(a.shim.parentNode.removeChild(a.shim),a.shim=null)};gigya.global.fillUserActionTemplate=function(a,c){for(var d in a){var b=a[d];"string"==typeof b&&(a[d]=gigya.utils.templates.fill(a[d],c));if("mediaItems"==d)for(var e=0;e<b.length;e++)b[e].src&&(b[e].src=gigya.utils.templates.fill(b[e].src,c))}return a};
gigya.global.preloadImages=function(a,c){for(var d=[],b=0,e=function(){b++;b==a.length&&c()},f=0;f<a.length;f++)if(null==a[f])e();else{var g=new Image;g.onload=e;g.onerror=e;g.src=a[f];d.push(g)}};
gigya.global.putGMBalloonNextTo=function(a,c,d,b,e,f,g,h){gigya.global.createGMBalloon(c,d,b,e,47,"left",f,g,h);var k=gigya.global.divGMBalloon.offsetWidth,l=gigya.global.divGMBalloon.offsetHeight,m=gigya.global._GetElementPos(a),p=m.top+a.offsetHeight/2-47-12.5,n=document.documentElement,r=document.body,q=n.clientHeight;0==q&&(q=r.clientHeight);n=n.clientWidth;0==n&&(n=r.clientWidth);window.innerHeight&&(q=window.innerHeight,n=window.innerWidth);r=gigya.utils.viewport.getScroll();q=r.top+q;m.left+
a.offsetWidth+k+40>r.left+n?(a=m.left-k-5,gigya.global.createGMBalloon(c,d,b,e,47,"right",f,g,h)):(a=m.left+a.offsetWidth+5,gigya.global.createGMBalloon(c,d,b,e,47,"left",f,g,h));p+l>q&&(p=q-l-10);10>a&&(a=10);10>p&&(p=10);gigya.global.divGMBalloon.style.left=a+"px";gigya.global.divGMBalloon.style.top=p+"px";gigya.localInfo.isIE&&(c=document.getElementById(gigya.global.divGMBalloon.id+"_frame"))&&gigya.global.addIframeShim(c)};
gigya.global.removeGMBalloon=function(a){var c;if(a)for(c=a.target,c||(c=a.srcElement);null!=c&&c.offsetParent&&-1==c.id.indexOf(gigya.global.divGMBalloon.id);)c=c.offsetParent;if(!c||-1==c.id.indexOf(gigya.global.divGMBalloon.id))try{gigya.global.removeIframeShim(document.getElementById(gigya.global.divGMBalloon.id+"_frame")),gigya.global.divGMBalloon.parentNode.removeChild(gigya.global.divGMBalloon),document.detachEvent?document.detachEvent("onclick",gigya.global.removeGMBalloon):document.removeEventListener&&
document.removeEventListener("click",gigya.global.removeGMBalloon,!1)}catch(d){}};gigya.global._GetElementPos=function(a){a=gigya.global.getPos(a);return{left:a.x,top:a.y}};
gigya.global.getPos=function(a){var c=navigator.userAgent.toLowerCase();c.indexOf("opera");c.indexOf("msie");if(null===a.parentNode||"none"==a.style.display)return!1;var d=null,b=[];if(a.getBoundingClientRect)return c=a.getBoundingClientRect(),a=Math.max(document.documentElement.scrollTop,document.body.scrollTop),d=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),{x:c.left+d,y:c.top+a};if(document.getBoxObjectFor)c=document.getBoxObjectFor(a),d=a.style.borderLeftWidth?parseInt(a.style.borderLeftWidth):
0,b=a.style.borderTopWidth?parseInt(a.style.borderTopWidth):0,b=[c.x-d,c.y-b];else{b=[a.offsetLeft,a.offsetTop];d=a.offsetParent;if(d!=a)for(;d;)b[0]+=d.offsetLeft,b[1]+=d.offsetTop,d=d.offsetParent;if(-1!=c.indexOf("opera")||-1!=c.indexOf("safari")&&"absolute"==a.style.position)b[0]-=document.body.offsetLeft,b[1]-=document.body.offsetTop}for(d=a.parentNode?a.parentNode:null;d&&"BODY"!=d.tagName&&"HTML"!=d.tagName;)b[0]-=d.scrollLeft,b[1]-=d.scrollTop,d=d.parentNode?d.parentNode:null;return{x:b[0],
y:b[1]}};gigya.global.getStyle=function(a,c){if(a.currentStyle)return a.currentStyle[c];if(window.getComputedStyle)return document.defaultView.getComputedStyle(a,null).getPropertyValue(c)};
gigya.services.socialize.getStyleString=function(a,c){var d;d="line-height: normal;";c&&(d+="cursor:pointer;");a.underline&&(d+="text-decoration:underline;");a.font&&(d+="font-family:"+a.font+";");a.size&&(d+="font-size:"+a.size+"px;");a.color&&(d+="color:"+a.color+";");a.bold&&(d+="font-weight:bold;");a["frame-thickness"]&&(d+="border-style:solid; border-width:"+a["frame-thickness"]+"px;");a["frame-color"]&&(d+="border-color:"+a["frame-color"]+";");a["background-color"]&&(d+="background-color:"+
a["background-color"]+";");return d};
gigya.services.socialize.GrayOut=function(a,c,d){var b=c||{};c=b.zindex||50;d=b.opacity||70;var e=d/100,b=b.bgcolor||"#000000",f=document.getElementById("darkenScreenObject"),g=document.body;if(!f){var h=gigya.localInfo.isMobile||gigya.localInfo.isIE6||"BackCompat"==document.compatMode,f=document.documentElement.scrollTop;0==f&&(f=document.body.scrollTop);var k=document.createElement("div");h?(k.style.position="absolute",k.style.top=""+f+"px"):(k.style.position="fixed",k.style.top="0px");k.style.overflow=
"hidden";k.style.left="0px";k.style.display="none";k.id="darkenScreenObject";k.innerHTML="&#160;";g.appendChild(k);f=document.getElementById("darkenScreenObject");gigya.attachedFixGray||(gigya.attachedFixGray=!0,window.addEventListener&&window.addEventListener("resize",gigya.services.socialize._fixGraySize,!1),window.attachEvent&&window.attachEvent("onresize",gigya.services.socialize._fixGraySize),h&&(window.addEventListener&&window.addEventListener("scroll",gigya.services.socialize._fixGrayPosition,
!1),window.attachEvent&&window.attachEvent("onscroll",gigya.services.socialize._fixGrayPosition)))}if(a){var l,m;window.innerHeight&&(l=window.innerHeight,m=window.innerWidth);"undefined"==typeof l&&(a=document.documentElement,l=a.clientHeight,m=a.clientWidth);0==m&&(m=g.clientWidth);0==l&&(l=g.clientHeight);f.style.opacity=e;f.style.MozOpacity=e;f.style.width=""+m+"px";f.style.height=""+l+"px";f.style.filter="alpha(opacity="+d+")";f.style.zIndex=c;f.style.backgroundColor=b;f.style.display="block"}else g.removeChild(f)};
gigya.services.socialize._fixGrayPosition=function(){var a=document.getElementById("darkenScreenObject");if(a){var c=document.documentElement,d=document.body,b=c.scrollTop;0==b&&(b=d.scrollTop);c=c.scrollLeft;0==c&&(c=d.scrollLeft);a.style.top=b;a.style.left=c}};
gigya.services.socialize._fixGraySize=function(){var a=document.getElementById("darkenScreenObject");if(a){var c=document.documentElement,d=document.body,b=c.clientHeight;0==b&&(b=d.clientHeight);c=c.clientWidth;0==c&&(c=d.clientWidth);gigya.localInfo.isIE6&&(c-=1);a.style.width=""+c+"px";a.style.height=""+b+"px"}};
gigya.utils.DOM.createTopLevelDiv=function(a){var c;c=document.createElement("IFRAME");c.id="gigya_ifr_"+a;c.frameborder="0";c.frameBorder="0";c.allowtransparency=!0;c.style.position="absolute";c.style.width=gigya.localInfo.isChrome?"30px":"1px";c.style.height="1px";null!=c.style.zIndex&&(c.style.zIndex=gigya.utils.DOM._nextZIndex++);gigya.localInfo.isIE6&&(c.src=gigya.thisScript.base+"/gs/blank.htm");var d=document.createElement("div");d.style.position="absolute";null!=d.style.zIndex&&(d.style.zIndex=
gigya.utils.DOM._nextZIndex++);d.innerHTML="";a&&(d.id=a);document.body&&document.body.insertBefore&&(document.body.firstChild?(null!=c&&document.body.insertBefore(c,document.body.firstChild),document.body.insertBefore(d,document.body.firstChild)):document.body.appendChild&&(null!=c&&document.body.appendChild(c),document.body.appendChild(d)));return d};
gigya.services.socialize.hideUI=function(){var a=gigya.utils.object.merge([gigya.thisScript.globalConf,arguments]);gigya.services.socialize.GrayOut(!1);for(var c in gigya.utils.DOM._popupContainers){var d=gigya.utils.DOM._popupContainers[c];null!=d&&(d.innerHTML="",d.parentNode&&(d.style.display="none"));d=document.getElementById("gigya_ifr_"+c);null!=d&&(d.style.display="none")}if(c=document.getElementById("fb-root"))c.style.visibility="hidden";gigya.events.global.dispatch({eventName:"HideUIRequested"});
"function"==typeof a.callback&&a.callback({status:"OK",statusMessage:"",operation:"hideUI",context:a.context,errorMessage:"",errorCode:0})};gigya.global.isEmail=function(a){if(0<=a.indexOf(" "))return!1;a=a.split("@");if(2!=a.length||0==a[0].length||0==a[1].length)return!1;a=a[1].split(".");if(2>a.length)return!1;for(var c=0;c<a.length;c++)if(0==a[c].length||0<a[c].indexOf(" "))return!1;return!0};
gigya.socialize._AddJSRequest=function(a,c,d,b){if(document.body){b||(b={});gigya.log.logCall(c.split(".").pop(),b);var e=b.containerID,f=!1,g;d?"undefined"==typeof e||""==e?(e=gigya.utils.DOM.getCenteredDivID(c),b.containerID=e,f=!0,b.isPopup=!0,g=document.getElementById(e),null==g&&(g=gigya.utils.DOM.createTopLevelDiv(e))):g=document.getElementById(e):(null==gigya.utils.DOM._pseudoContainers[e]&&(gigya.utils.DOM._pseudoContainers[e]={}),g=gigya.utils.DOM._pseudoContainers[e]);if(g){var h=c.split(".").pop();
g.setAttribute&&g.setAttribute("gigid",(b.source&&b.source!=h?b.source+"_":"")+h);if(g.style){g.style.display="";g.style.visibility="";g.innerHTML="";if(h=document.getElementById("gigya_ifr_"+e))h.style.display="",h.style.visibility="";null!=h&&(gigya.utils.DOM.setSize(h,b.width,b.height,f),h.style.visibility="visible");gigya.utils.DOM.setSize(g,b.width,b.height,f)}f=g.Reqs?g.Reqs:g.Reqs=[];h=f.length+"@"+a+"@"+e;b.rid=h;var k=c;b._operation&&(k=b._operation);f[f.length]={rid:h,servicedBy:a,container:g,
method:c,context:b.context,c:b,p:b,i:b,operation:k,isHTML:!0};g=c.split(".");f=eval(g[0]);for(h=1;null!=(f=f[g[h]])&&++h<g.length;);gigya.utils.script.load(gigya.thisScript.base+"/js/"+a+".min.js"+(b.lang?"?lang="+b.lang:""),null,function(){gigya.reports.reportLoad(c,b);gigya.utils.functions.callFunction(c,[b,b,b])},!0);return e}gigya.events.dispatchInvalidParamError(b,"containerID")}else{var l=arguments;window.setTimeout(function(){gigya.socialize._AddJSRequest.apply(this,l)},300)}};
gigya.utils.object.add(gigya.utils.DOM,{enableSafeCopy:function(a){a.addedSafeCopy||(gigya.utils.DOM.addEventListener(a,"copy",function(a){a=a||window.event;var d=a.target||a.srcElement,d=d&&d.nodeName?d.nodeName.toLowerCase():"";if("textarea"!=d&&"input"!=d){var b=document.createElement("div");b.style.color=window.getComputedStyle?window.getComputedStyle(document.body).backgroundColor:"#FFFFFF";b.style.fontSize="0px";gigya.utils.DOM.appendToBody(b);d=RegExp("(&shy;|"+String.fromCharCode(173)+")",
"g");window.getSelection?(a.stopPropagation(),selection=window.getSelection(),range=selection.getRangeAt(0),b.appendChild(range.cloneContents()),b.innerHTML=b.innerHTML.replace(d,""),selection.selectAllChildren(b),fnRestore=function(){b.parentNode.removeChild(b);selection.removeAllRanges();selection.addRange(range)}):(a.cancelBubble=!0,selection=window.document.selection,range=selection.createRange(),b.innerHTML=range.htmlText,b.innerHTML=b.innerHTML.replace(d,""),range2=document.body.createTextRange(),
range2.moveToElementText(b),range2.select(),fnRestore=function(){b.parentNode.removeChild(b);""!==range.text&&range.select()});window.setTimeout(fnRestore,0)}}),a.addedSafeCopy=!0)}});
gigya.utils.object.add(gigya.pluginUtils.lang,{getDateString:function(a,c){if(a&&a.dateFormat){var d=a.dateFormat,b=c.getDate(),e=c.getMonth()+1,f="January February March April May June July August September October November December".split(" ")[c.getMonth()],g=c.getFullYear();return d.replace(/%dd/g,("0"+b).slice(-2)).replace(/%d/g,b).replace(/%MMMM/g,f).replace(/%MMM/g,f.substr(0,3)).replace(/%MM/g,("0"+e).slice(-2)).replace(/%M/g,e).replace(/%yyyy/g,g).replace(/%yy/g,g.toString().slice(-2))}}});
gigya.global.XMLUtils={CreateXMLFromString:function(a){var c=null;window.ActiveXObject?(c=new ActiveXObject("Microsoft.XMLDOM"),c.async="false",c.loadXML(a)):c=(new DOMParser).parseFromString(a,"text/xml");return c},CopyProperties:function(a,c,d,b){"undefined"==typeof d&&(d="");"undefined"==typeof c&&(c={});if(null!=b)for(var e in a)c[d+e]=b(e,a[e]);else for(var f in a)c[d+f]=a[f];return c},CollectAttributesFromXMLPathToObject:function(a,c,d,b,e){for(var f=0;f<c.length&&"undefined"!=typeof a;f++)a=
a.childNodes[c[f]],null!=a&&b&&this.CopyProperties(a.attributes,d,"",e);"undefined"!=typeof a&&this.CopyProperties(a.attributes,d,"",e)},mergeNodes:function(a,c){"undefined"==typeof c.attributes&&(c.attributes={});"undefined"==typeof c.childNodes&&(c.childNodes={});var d=c.attributes,b=a.attributes;if(b)for(var e=0;e<b.length;e++)d[b[e].nodeName]=null!=b[e].value?b[e].value:b[e].nodeValue;for(b=0;b<a.childNodes.length;b++)e=a.childNodes[b],d=c.childNodes[e.nodeName],"undefined"==typeof d&&(d=c.childNodes[e.nodeName]=
{attributes:{},childNodes:{}}),this.mergeNodes(e,d);return c}};
gigya.global.resolver=function(a){this.configurations=[];this.mergedConfig={};this.isMerged=!0;this._processor=a;this.merge=function(){if(!this.isMerged){this.mergedConfig={attributes:{},childNodes:{}};for(var a=0;a<this.configurations.length;a++)gigya.global.XMLUtils.mergeNodes(this.configurations[a],this.mergedConfig);this.isMerged=!0}};this.Resolve=function(){this.merge&&this.merge();var a={};"object"==typeof arguments[arguments.length-1]&&(a=arguments[arguments.length-1]);for(var d=0;d<arguments.length;d++){var b=
arguments[d],e=b.constructor;if(e==String)for(b=b.split("|"),e=b.length-1;0<=e;e--){var f=this.trimCharsAtSuffix(this.trimCharsAtPrefix(b[e]," \n\r\t")," \n\r\t"),g="+"==f.charAt(0),h=f.split("/").slice(1);g&&f.substring(1);gigya.global.XMLUtils.CollectAttributesFromXMLPathToObject(this.mergedConfig,h,a,g,this._processor)}else if(e==Array)for(e=0;e<b.length;e++)Resolve(b[e],a)}return a};this.trimCharsAtPrefix=function(a,d){var b=0;if("undefined"==typeof a||0==a.length)return"";for(var e=a.length;b<=
e&&-1<d.indexOf(a.charAt(b));)b++;return a.substring(b,e)};this.trimCharsAtSuffix=function(a,d){if("undefined"==typeof a||0==a.length)return"";for(var b=a.length-1;0<=b&&-1<d.indexOf(a.charAt(b));)b--;return a.substring(0,b+1)};this.addConfig=function(a){"string"==typeof a&&(this.configurations.push(gigya.global.XMLUtils.CreateXMLFromString(a)),this.isMerged=!1)};this.getTextFromKey=function(a){return this.Resolve("/config/lang/"+a).text}};
gigya.global.resolver.defaultProccessor=function(a,c){var d=a.toLowerCase(),b=d.indexOf("-");-1!=b&&(d=d.substring(b+1,d.length));switch(d){case "bold":case "italic":case "underline":return"true"==c.toString().toLowerCase();case "width":case "height":return c.replace("%","");case "size":return parseInt(c);default:return c}};
gigya.global.getSpriteRenderers=function(a){var c=[],d=0,b={},e;for(e in a){var f=a[e];c.push(f.path+"|"+f.w+","+f.h)}c=gigya.thisScript.base+"/gs/GetSprite.ashx?path="+encodeURIComponent(c.join("^").replace(/\[\]/,""));for(e in a){var f=a[e],g,h;g={};var k=[],l=0;h=gigya.thisScript.base+"/gs/i"+f.path.replace(/\[(.*?)\]/g,function(a,b){k.push(b.split(","));return"{"+l++ +"}"});var m=gigya.global.getCombination(k);0==m.length&&m.push([""]);for(var p=0;p<m.length;p++){var n=m[p].join("-");""==n&&(n=
"default");g[n]={groupId:e,id:n,x:d,w:f.w,h:f.h};d+=f.w}b[e]=new gigya.global.SpriteRenderer(c,h,g,f.w,f.h)}return b};gigya.global.SpriteRenderer=function(a,c,d,b,e){this.src=a;this.srcTemplate=c;this.spriteData=d;this.spriteW=b;this.spriteH=e};
gigya.global.SpriteRenderer.prototype={getSpriteData:function(a,c){if(this.spriteData[a]&&!c)return this.spriteData[a];var d=0,b=a.split("-");return{isSingleImage:!0,src:this.srcTemplate.replace(/\{(.*?)\}/g,function(a,c){var g=b[d++];return g?g:""})}},getStyleString:function(a,c){var d=this.getSpriteData(a),b=[];d&&(b.push("background-image:url('"+this.src+"');"),b.push("background-position:-"+d.x+"px 0px;"),c&&b.push("margin: 0 auto;"),b.push("width: "+this.spriteW+"px;"),b.push("height: "+this.spriteH+
"px;line-height: "+this.spriteH+"px;"),b.push("background-repeat:no-repeat;"),b.push("position:static;"));return b.join("")},getHTML:function(a,c,d,b){d=this.getSpriteData(a,d);var e=[];d&&(d.isSingleImage?e.push('<img src="'+d.src+'" style="width:'+this.spriteW+"px;height:"+this.spriteH+'px;position:static;margin:0" alt="" />'):(e.push('<div style="'),e.push(this.getStyleString(a,c)),e.push('"'),b&&e.push(' id="'+b+'"'),e.push("></div>")));return e.join("")}};
gigya.global.getCombination=function(a,c){c||(c=0);if(!a||0==a.length)return[];var d=a[c];if(c==a.length-1)for(var b=[],e=0;e<d.length;e++)b.push([d[e]]);else{var b=[],f=gigya.global.getCombination(a,c+1);if(d)for(e=0;e<d.length;e++)for(var g=0;g<f.length;g++)b.push([d[e]].concat(f[g]))}return b};
