function HaService(){var c;try{c=parent.window.innerWidth||parent.window.document.documentElement.clientWidth||parent.window.document.body.clientWidth}catch(G){c=-1}var e;try{e=parent.window.innerHeight||parent.window.document.documentElement.clientHeight||parent.window.document.body.clientHeight}catch(H){e=-1}var y=0,l="swfReady_"+$uid,q="sampleCallback"+$uid,b,m=0,n={},o=(new Date).getTime(),i=o,z=0,r=0,A=0,j=!1,s=!1,k=[],t=[],B=0,g=1,u=5;this.exec=function(){window.HaSettingsObj&&(g=window.HaSettingsObj.brid,
u=window.HaSettingsObj.numOfConsecutiveIterations);n.bucket_100=0;var a=window!=window.top,f=C(),d=D();a&&f&&d?(f=20*Math.random()+c/2-10,d=20*Math.random()+e/2-10,f==c/2&&(f=c/2+1),d==e/2&&(d=e/2+1),b=new E(f,d)):(a=$dv.tags[$uid].dv_protocol+"//"+$dv.tags[$uid].ServerPublicDns+"/event.gif?impid="+$uid+"&dvp_isFrmNested="+(a?1:0),a=a+("&dvp_isFlshSupported="+(f?1:0))+("&dvp_frmSize="+c+"x"+e),a=a+("&dvp_isValidFrmSize="+(d?1:0))+("&dvp_isHiddenSupprted="+("undefined"!==typeof document.hidden?1:0)),
$dv.domUtilities.addImage(a,$dv.tags[$uid].tagElement.parentElement))};$dv[q]=function(a){r++;"throttle"==a?b.isHdn=1:"resume"==a&&(b.isHdn=0);v();"throttle"==a&&k.push("t");"resume"==a&&k.push("r");t.push((new Date).getTime()-o);20<k.length&&(k.shift(),t.shift())};var v=function(){0==b.isHdn?(0!=i&&(m+=(new Date).getTime()-i),i=(new Date).getTime()):0==i};$dv[l]=function(){try{var a=$dv.tags[$uid].tagElement.parentElement.ownerDocument.getElementById("swfdetect_"+$uid);b?(b.swf=a,b.readyMs=(new Date).getTime()-
o,setTimeout(w,100)):200>y++&&setTimeout(function(){$dv[l]()},50)}catch(f){}};var w=function(){0==r?3>=++A?setTimeout(w,250):(b.isHdn=0,p()):p()},p=function(){z++;v();if(3==g){if(0==b.isHdn&&1E3<=m){h(["hdn=0"]);return}}else{var a=!0;if(window.$dv.tags[$uid].getViewabilityData&&"function"==typeof window.$dv.tags[$uid].getViewabilityData&&(F()?(1==b.isHdn?document.hidden?1==b.prevIsHdnAndPageHdn?b.consecutiveFraudHiddenIterationsAndPageHdn++:b.consecutiveFraudHiddenIterationsAndPageHdn=1:1==b.prevIsHdn?
b.consecutiveFraudHiddenIterations++:b.consecutiveFraudHiddenIterations=1:0==b.isHdn&&(j?h(["dvp_wasHdn=1","hdn=0"]):h(["hdn=0"]),a=!1,b.hide()),b.prevIsHdn=b.isHdn,b.prevIsHdnAndPageHdn=1==b.isHdn&&1==document.hidden?1:0):(b.consecutiveFraudHiddenIterations=0,b.consecutiveFraudHiddenIterationsAndPageHdn=0),b.consecutiveFraudHiddenIterations>=u&&!j&&(h(["hdn=1"]),j=!0),5<=b.consecutiveFraudHiddenIterationsAndPageHdn&&!s))h(["dvp_popU=1"]),s=j=!0;0==b.isHdn&&3<B++&&(a=!1,b.hide())}(a||3==g)&&setTimeout(function(){p()},
1E3)},E=function(a,b){var d="swfdetect_"+$uid,x=3==g?"transparent":"window",c=document.createElement("div");this.readyMs=-1;this.wasHidden=this.consecutiveFraudHiddenIterationsAndPageHdn=this.consecutiveFraudHiddenIterations=0;this.swf=null;this.isHdn=3==g?0:-1;this.prevIsHdnAndPageHdn=this.prevIsHdn=0;this.isVisible=!0;this.hide=function(){c.style.display="none"};c.id="swfDiv";c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.left=a+"px";c.style.top=b+"px";d='<object id="'+
d+'" data="'+$dv.tags[$uid].dv_protocol+'//cdn.doubleverify.com/dvdtc.swf"  type="application/x-shockwave-flash" bgcolor="#000000" width="1" height="1" allowScriptAccess="always" wmode="'+x+'">';d+='<param name="data" value="'+$dv.tags[$uid].dv_protocol+'//cdn.doubleverify.com/dvdtc.swf" />';d+='<param name="flashvars" value="swfCountTiming=1000&swfReadyCallbackName=$dv.'+l+"&swfSamplePixelStateCallbackName=$dv."+q+'" />';c.innerHTML=d+'<param name="quality" value="high"/><param name="bgcolor" value="#000000"/><param name="allowScriptAccess" value="always" />'+
('<param name="wmode" value="'+x+'" />')+"</object>";$dv.tags[$uid].tagElement.ownerDocument.body.appendChild(c)},h=function(a){var b=$dv.tags[$uid].dv_protocol+"//"+$dv.tags[$uid].ServerPublicDns+"/event.gif?impid="+$uid,d=[];d.push("dvp_hdnVer=2");if("undefined"!==typeof a)for(var c=0;c<a.length;c++)d.push(a[c]);b+="&"+d.join("&");$dv.domUtilities.addImage(b,$dv.tags[$uid].tagElement.parentElement)},C=function(){var a=0;try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.11"),!0}catch(b){}try{if(a=
navigator.plugins["Shockwave Flash"].description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1].split(",")[0],11<=a)return!0}catch(c){}return!1},F=function(){var a=!1;if(window.$dv.tags[$uid].getViewabilityData&&"function"==typeof window.$dv.tags[$uid].getViewabilityData)try{var b=window.$dv.tags[$uid].getViewabilityData().buckets;b.bucket_100>n.bucket_100&&(a=!0);n.bucket_100=b.bucket_100}catch(c){}return a},D=function(){var a=function(a,b,c){c*=b;return a<=b+c&&a>=b-c};return a(c,300,0.1)&&a(e,250,
0.1)||a(c,300,0.1)&&a(e,600,0.1)||a(c,728,0.1)&&a(e,90,0.1)||a(c,160,0.1)&&a(e,600,0.1)}}(new HaService).exec();
