// audienceinsights.net is a web application providing tools of analysis and statistics based on anonymous data collection.
// This service is provided by the French group Adthink-Media [http://www.adthink-media.com/].
// For more information on our service and our privacy policy, please contact contact@audienceinsights.net.

(function(){window._pusq=window._pusq||[];
window.PUS=window.PUS||function(){function W(){return{q:function(m){for(var e="",l=0;l<m.length;){var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(m.charAt(l++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(m.charAt(l++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(m.charAt(l++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(m.charAt(l++)),r=(h&15)<<4|d>>2,n=(d&3)<<6|
k,e=e+String.fromCharCode(p<<2|h>>4);64!=d&&(e+=String.fromCharCode(r));64!=k&&(e+=String.fromCharCode(n))}return e}}}function X(){return{A:function(m){function e(e,h){var d=(e&65535)+(h&65535);return(e>>16)+(h>>16)+(d>>16)<<16|d&65535}function l(e,h){return e>>>h|e<<32-h}return function(e){for(var h="",d=0;d<4*e.length;d++)h+="0123456789abcdef".charAt(e[d>>2]>>8*(3-d%4)+4&15)+"0123456789abcdef".charAt(e[d>>2]>>8*(3-d%4)&15);return h}(function(p,h){var d=[1116352408,1899447441,3049323471,3921009573,
961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,
883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298],k=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],r=Array(64),n,m,x,G,t,B,y,z,u,s;p[h>>5]|=128<<24-h%32;p[(h+64>>9<<4)+15]=h;for(var f=0;f<p.length;f+=16){n=k[0];m=k[1];x=k[2];G=k[3];t=k[4];B=k[5];y=k[6];z=k[7];for(var q=0;64>q;q++)16>q?u=p[q+f]:(u=r[q-15],s=r[q-2],u=e(e(e(l(s,17)^l(s,19)^s>>>10,r[q-7]),l(u,7)^l(u,18)^
u>>>3),r[q-16])),r[q]=u,u=e(e(e(e(z,l(t,6)^l(t,11)^l(t,25)),t&B^~t&y),d[q]),r[q]),s=e(l(n,2)^l(n,13)^l(n,22),n&m^n&x^m&x),z=y,y=B,B=t,t=e(G,u),G=x,x=m,m=n,n=e(u,s);k[0]=e(n,k[0]);k[1]=e(m,k[1]);k[2]=e(x,k[2]);k[3]=e(G,k[3]);k[4]=e(t,k[4]);k[5]=e(B,k[5]);k[6]=e(y,k[6]);k[7]=e(z,k[7])}return k}(function(e){for(var h=[],d=0;d<8*e.length;d+=8)h[d>>5]|=(e.charCodeAt(d/8)&255)<<24-d%32;return h}(m),8*m.length))}}}function K(){return{q:function(m){var e=[];m=m.split("&");for(var l=0;l<m.length;l++){var p=
m[l],h=p.indexOf("="),d;-1<h?(d=decodeURIComponent(p.substring(0,h)),p=decodeURIComponent(p.substring(h+1))):(d=decodeURIComponent(p),p=!0);for(var k=d,r=e;-1!=(h=d.indexOf("."));)k=d.substring(0,h),"object"!=typeof r[k]&&(r[k]=[]),r=r[k],d=d.substring(h+1);"undefined"==typeof r[d]?r[d]=p:"object"==typeof r[d]?r[d].push(p):r[d]=[r[d],p]}return e},A:function(m,e){var l="",p;for(p in m)if("$"!=p.charAt(0)){var h;h=e?e+"."+encodeURIComponent(p):encodeURI(p);var d=m[p];if("object"==typeof d){var k=!0,
r;for(r in d)if("$"!=r.charAt(0)&&r!=parseInt(r,10)){k=!1;break}if(!k){l+=K().A(d,h);continue}if("function"==typeof d.join&&"function"==typeof d.forEach){d.forEach(encodeURIComponent);l+="&"+h+"="+d.join("|").replace(/^\|+/g,"").replace(/\|+$/g,"");continue}}"function"!=typeof d&&(l+="&"+h+"="+encodeURIComponent(d))}return l}}}function N(){for(var m=0;m<arguments.length;m++){var e=arguments[m];if(e.shift){var l=e.shift();C[l].apply(C,e)}}}var C=function(){function m(){}function e(){}function l(a,
b){var c=[];if("object"!=typeof a)try{a=K().q(W().q(a))}catch(e){m("Impossible de d\u00e9coder les donn\u00e9es pass\u00e9es")}if("undefined"==typeof b)return a;for(var d in a)if(b[d]){var f=a[d];if("function"==typeof b[d][1])if(b[d][1](f))if("function"==typeof b[d][2])b[d][2](f,c);else c[b[d][0]]=f;else m("["+d+"] Value '"+f+"' doesn't match the expected type.");else c[b[d][0]]=l(f,b[d][1])}else m("["+d+"] Unknown key '"+d+"'.");return c}function p(a){var b=!1,c=v.a,d;for(d in c)H[d]||(c[d].l(),
H[d]=!1,b=!0);b?(F=setTimeout(h,2E3),e=a):a()}function h(a){var b=!0;if(a){H[a]=!0;for(var c in H)if(!H[c]){b=!1;break}}b&&(T=!0,clearTimeout(F),e())}function d(){var a=[],b=v.s,c;a:for(c in b){var d=b[c].r();if(d&&"string"==typeof d){for(var e in a)if(d==a[e])continue a;a.push(d)}}return a}function k(a){if(T)r(a);else{var b=v.s,c;for(c in b)b[c].w(a)}}function r(a){for(var b in v)for(var c in v[b])v[b][c].w(a)}function n(a){var b;b||(b=1);D[a]=a in D?D[a]+b:b}function C(){var a="",b;for(b in D)"number"==
typeof D[b]&&(a+="&metrics[]="+b+":"+D[b]+"|c");for(b in I)"number"==typeof I[b]&&(a+="&metrics[]="+b+":"+I[b]+"|ms");D=[];I=[];return a}function x(a){a=a.match(N);if(null!=a&&1<a.length){a=a[1];var b=a.match(Y);if(null!=b&&0<b.length)return a.replace(/^\s+|\s+$/g,"")}return null}function G(){function a(a){for(var c in a)"string"==typeof a[c]&&(q+="&idv[]="+a[c]);q+=C();t()}q="idp="+s+K().A(f);w&&a([w]);a(d())}function t(){var a,b;for(b in U)if(!a||b==a){a=null;try{U[b](z,q);break}catch(c){}}}function B(a){if(a.idv){w=
a.idv;if(a.flag){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.defer=!0;b.appendChild(document.createTextNode(a.flag));var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}a.cs&&(O=a.cs);a.gen?(a.old&&(v.a.old={r:function(){n("op_old.read");return window._pusOldIdv},w:function(){},c:function(){},l:function(){n("op_old.loaded");window._pusOldIdv=null;var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.defer=!0;b.src=
a.old+"?f=js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)},ok:function(){n("op_old.ready");h("old")}}),p(function(){if(!(3<L)){var a=[],b;for(b in v){var c;a:for(c in v[b]){var d=v[b][c].r();if(d&&"string"==typeof d){for(c in a)if(d==a[c])continue a;a.push(d)}}}q="idp="+s+"&nbp="+L;w&&(q+="&idv="+w);for(var e in a)"string"==typeof a[e]&&(q+="&idv[]="+a[e]);a.length?(q+=C(),t()):r(w)}})):a.op?p(function(){r(w)}):k(w);for(var d in J)if("function"==typeof J[d])J[d](w);
J=[];"tracker"in M&&(I["tracker.idvRetrieve"]=((new Date).getTime()-M.tracker)/1E3,delete M.tracker);O&&(b=document.createElement("script"),b.type="text/javascript",b.async=!0,b.defer=!0,b.src=O+"?i="+w,c=document.getElementsByTagName("script")[0],c.parentNode.insertBefore(b,c))}L++}function y(){if(null!=F){E*=1.5;try{setTimeout(y.bind(this),E)}catch(a){}}else{var b=C();if(0<b.length){q="idp="+s+"&nbp="+L;w&&(q+="&idv="+w);q+=b;t();E*=1.5;try{setTimeout(y.bind(this),E)}catch(c){}}}}var z="",u="",
s="",f={},q="",w,L=0,H={},F=null,T=!1,O=null,P=null,Q=null,D={},I={},M={},E=1E3,R={},A={},S=RegExp("^([0-9]{2,4})-([0][0-9]|1[0-2])-([0-2][0-9]|3[0-1])( ([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]))?$","i"),N=RegExp("(?:(?:(?:www.nicovideo.jp/search/)|(?:www.lespac.com/(?:[^/]+)/)|(?:recherche.lefigaro.fr/recherche/recherche.php\\?ecrivez=)|(?:(?:[^.]+.)?search.yahoo.com/search;(?:.+)?p=)|(?:www.wikio.[^/]+.+/s/)|(?:(?:[?&](?:q|k|qw|search|query|searchquery|oq|rdata|utm_term|gsc.q|s|search_query|_nkw|wd|kw|text|keywords|keyword|fulltext|field-keywords|recherche|tag|searchfor|SearchText|swords|searchword))=)))([^&/?]+)",
"i"),Y=/([^0-9-_+ ]{3,})/i,V=!1,J=[],g={j:function(a){return a==parseInt(a,10)||"object"==typeof a&&2==a.length&&a[0]==parseInt(a[0],10)&&a[1]==parseInt(a[1],10)?!0:!1},C:function(a){return!!a==a},B:function(a){a instanceof Date&&(a=a.getFullYear()+"-"+(a.getMonth()+1)+"-"+a.getDay()+" "+a.getHours()+":"+a.getMinutes()+":"+a.getSeconds());if(a.match(S)||"object"==typeof a&&2==a.length&&(a[0]instanceof Date&&(a[0]=a[0].getFullYear()+"-"+(a[0].getMonth()+1)+"-"+a[0].getDay()+" "+a[0].getHours()+":"+
a[0].getMinutes()+":"+a[0].getSeconds()),a[1]instanceof Date&&(a[1]=a[1].getFullYear()+"-"+(a[1].getMonth()+1)+"-"+a[1].getDay()+" "+a[1].getHours()+":"+a[1].getMinutes()+":"+a[1].getSeconds()),a[0].match(S)&&a[1].match(S)))return!0},g:function(a){return"string"==typeof a},multiple:function(a){return function(b){var c=!0;if("object"==typeof b)for(var d in b)c&=a(b[d]);c&&"object"==typeof b||(c=a(b));return c}}},Z={assets:["a",{salary:["s",g.j],family_income:["fi",g.j],landlord:["l",g.C],last_payment:["lp",
g.B]}],interests:["i",{hobbies:["h",g.multiple(g.g)],news:["n",g.multiple(g.g)],politics:["p",g.multiple(g.g)],religion:["r",g.g],tourism:["to",g.multiple(g.g)],economic:["e",g.multiple(g.g)]}],family:["f",{marital_status:["ms",function(a){return a in{single:1,in_relationship:1,married:1,divorced:1,widower:1}}],family_size:["fs",g.j],leaderships:["l",g.j]}],person:["p",{age:["ag",g.j,function(a,b){var c=new Date;c.setFullYear(c.getFullYear()-a);b.D=c.getFullYear()+"-"+(c.getMonth()+1)+"-"+c.getDay()+
" "+c.getHours()+":"+c.getMinutes()+":"+c.getSeconds()}],birthday:["b",g.B],gender:["g",function(a){return a in{m:1,f:1}}],nationality:["n",g.multiple(g.g)],aspect:["as",{height:["h",g.j],weight:["w",g.j],ethnie:["e",g.g]}],address:["a",{postal_code:["pc",g.g],city:["c",g.g],state:["s",g.g],country:["co",g.g]}],language:["l",g.multiple(g.g)],title:["t",g.g]}],career:["c",{industry:["i",g.g],organization:["o",{name:["n",g.g],size:["s",g.j]}],title:["t",g.multiple(g.g)]}]},$={email:["e",g.g],"facebook-numericid":["fni",
g.g],"facebook-name":["fn",g.g],twitter:["t",g.g],"google+":["g",g.g]},U={js:function(a,b){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.defer=!0;c.src=a+"?f=js&"+b;var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d)},img:function(a,b){(new Image(1,1)).src=a+"?f=gif&"+b},xhr:function(a,b){var c=!1;window.XDomainRequest?c=new window.XDomainRequest:window.XMLHttpRequest&&(c=new window.XMLHttpRequest);if(!c)throw"e";c.open("POST",a,!0);c.onreadystatechange=
function(){4===c.readyState&&200==c.status&&window.PUS.getTracker().setRawResponse(c.responseText)};if(!("withCredentials"in c))throw"e";c.withCredentials=!0;c.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");c.send("f=qs&"+b)}},v={s:{wn:{h:!1,r:function(){var a=window.name;if(null!=a&&0===a.indexOf("PUS"))return a=a.substr(3),n("op_wn.read"),a;n("op_wn.failed")},w:function(a){this.h||(n("op_wn.wrote"),window.name="PUS"+a,this.h=!0)},c:function(){n("op_wn.clean");
window.name=""}},cook:{h:!1,r:function(){var a=document.cookie.split(";"),b;for(b in a){var c=a[b];if("string"==typeof c){var d=c.indexOf("=");if("pus-idv"==c.substr(0,d).replace(/^\s+|\s+$/g,""))return a=unescape(c.substr(d+1)),n("op_cookie.read"),a}}n("op_cookie.failed")},w:function(a){if(!this.h){n("op_cookie.wrote");var b=new Date;b.setFullYear(b.getFullYear()+10);document.cookie="pus-idv="+escape(a)+";expires="+b.toUTCString()+";path=/";this.h=!0}},c:function(){n("op_cookie.cleaned");var a=new Date;
a.setFullYear(a.getFullYear()-1);document.cookie="pus-idv=;expires="+a.toUTCString()+";path=/"}}},a:{},a:{swf:{h:!1,r:function(){var a=document.getElementById("pus_swf_object");if("undefined"==typeof a||"function"!=typeof a.read)a=document.getElementById("pus_swf_object2");if("undefined"!=typeof a&&"function"==typeof a.read&&(a=a.read(),null!=a))return n("op_swf.read"),a;n("op_swf.read_failed")},w:function(a){if(!this.h){var b=document.getElementById("pus_swf_object");if("undefined"==typeof b||"function"!=
typeof b.write)b=document.getElementById("pus_swf_object2");"undefined"==typeof b||"function"!=typeof b.write?n("op_swf.wrote_failed"):(n("op_swf.wrote"),b.write(a),this.h=!0)}},c:function(){var a=document.getElementById("pus_swf_object");if("undefined"==typeof a||"function"!=typeof a.clean)a=document.getElementById("pus_swf_object2");"undefined"==typeof a||"function"!=typeof a.clean?n("op_swf.cleaned_failed"):(n("op_swf.cleaned"),a.clean())},l:function(){n("op_swf.loaded");var a=u+"op.swf",a='<div style="position:absolute; top:-1789px; left:-1789px; height:1px; width:1px;"><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="pus_swf_object" width="1" height="1"><param name="id" value="pus_swf_object"><param name="movie" value="'+
a+'" /><param name="play" value="true" /><param name="allowScriptAccess" value="always" /><param name="FlashVars" value="pusCookieName=pus" />\x3c!--[if !IE]>--\x3e<object type="application/x-shockwave-flash" id="pus_swf_object2" data="'+a+'" width="1" height="1"><param name="id" value="pus_swf_object2"><param name="movie" value="'+a+'" /><param name="play" value="true" /><param name="allowScriptAccess" value="always" /><param name="FlashVars" value="pusCookieName=pus" /></object>\x3c!--<![endif]--\x3e</object></div>',
b=document.createElement("div"),c=document.getElementsByTagName("body")[0];c||(c=document.documentElement);b.innerHTML=a;c.appendChild(b)},ok:function(){setTimeout(function(){n("op_swf.ready");h("swf")},50)}}}};M.tracker=(new Date).getTime();(function(){f.n=[];f.n.s=[];try{f.n.s.r=screen.width+"x"+screen.height,"undefined"!=typeof screen.pixelDepth&&(f.n.s.d=screen.pixelDepth),f.n.s.p=navigator.platform}catch(a){}f.n.b=[];try{f.n.b.a=navigator.userAgent,"undefined"!=typeof navigator.language&&(f.n.b.l=
navigator.language)}catch(b){}try{f.n.b.m=[];for(var c in navigator.mimeTypes)"undefined"!==typeof navigator.mimeTypes[c].type&&f.n.b.m.push(navigator.mimeTypes[c].type)}catch(d){}try{"boolean"===typeof navigator.cookieEnabled&&(f.n.b.c=+navigator.cookieEnabled)}catch(e){}f.n.v=[];try{f.n.v.u=document.location.href,f.n.v.t=(new Date).getTime()}catch(g){}c="";try{c=window.top.document.referrer}catch(h){}if(""===c)try{c=window.parent.document.referrer}catch(k){}if(""===c)try{c=document.referrer}catch(l){}""!=
c&&(f.n.v.r=c);try{"string"==typeof document.title&&(f.n.v.ti=document.title)}catch(m){}try{if(window.opener){f.n.v.p=[];f.n.v.p.i=1;f.n.v.p.u=window.opener.document.location.href;try{f.n.v.r=window.opener.document.referrer}catch(n){}window.opener.closed||(f.n.v.p.o=1)}}catch(q){}try{top.location!=window.location&&(f.n.v.i=[],f.n.v.i.i=1,"string"==typeof top.location.href&&(f.n.v.i.u=top.location.href))}catch(r){}if(!V){c=[];if("string"==typeof f.n.v.r){var p=x(f.n.v.r);null!=p&&c.push(p)}"string"==
typeof f.n.v.u&&(p=x(f.n.v.u),null!=p&&c.push(p));0<c.length&&(f.n.v.k=c)}P&&(f.n.v.c.u=P);Q&&(f.n.v.c.ot=Q)})();try{setTimeout(y.bind(this),E)}catch(aa){}return{setTrackerUrl:function(a){z=a},setTrackerStaticUrl:function(a){u=a},setIdp:function(a){s=a},setSiteUnderIdp:function(a){window.opener&&(s=a)},setRawResponse:function(a){B(K().q(a))},setVisitorData:function(a){a=l(a,Z);for(var b in a){f.v=a;break}},setCustomData:function(a){f.c=l(a)},setNetworkLink:function(a,b){""==s&&(s=a+"|"+b)},send:function(){for(var a in R){f.xi=
l(R,$);break}for(a in A){f.e=[];f.e[s]=A;break}n("hit.attempted");try{G()}catch(b){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.defer=!0;c.src=z.replace(/p$/,"e")+"?f=js";for(a in b)"string"==typeof b[a]&&(c.src+="&"+a+"="+b[a]);a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)}},setNr:function(){},setNk:function(a){V=a},onIdvRetrieve:function(a){J.push(a)},onError:function(a){m=a},clean:function(){},getOp:function(a){return v.a[a]||v.s[a]},
setProviderId:function(){},setExternalId:function(a,b){this.setHashedExternalId(a,X().A(b))},setHashedExternalId:function(a,b){R[a]=b},trackClick:function(a,b){P=a;b&&(b in{ad:1,email:1}?Q=b:m("[n.v.c.ot] Value '"+b+"' doesn't match the expected type."))},trackEvent:function(a,b,c){b||(b=0);c||(c="USD");a in A?A[a][c]=c in A[a]?A[a][c]+b:b:(A[a]=[],A[a][c]=b)}}}(),F=0;for(;F<window._pusq.length;F++)N(window._pusq[F]);return{getTracker:function(){return C},debug:function(){}}}();})();
