var TLpkg="tltrack.1.3.js",TrckServ="its.tradelab.fr";
tl_async_loader=function(a){function p(b,d){var c=a.createElement(b),m;for(m in d)d.hasOwnProperty(m)&&c.setAttribute(m,d[m]);return c}function d(){var d=navigator.userAgent;b={async:!0===a.createElement("script").async};(b.webkit=/AppleWebKit\//.test(d))||(b.ie=/MSIE|Trident/.test(d))||(b.opera=/Opera/.test(d))||(b.gecko=/Gecko\//.test(d))||(b.unknown=!0)}function c(t,h,k,m,A){var B=function(){var a=u[t],d,b;a&&(d=a.callback,b=a.urls,b.shift(),pollCount=0,b.length||(d&&d.call(a.context,a.obj),u[t]=
null,e[t].length&&c(t)))},C=[],l,r,x,z;b||d();if(h)if(h="string"===typeof h?[h]:h.concat(),b.async||b.gecko||b.opera)e[t].push({urls:h,callback:k,obj:m,context:A});else for(l=0,r=h.length;l<r;++l)e[t].push({urls:[h[l]],callback:l===r-1?k:null,obj:m,context:A});if(!u[t]&&(z=u[t]=e[t].shift())){q||(q=a.head||a.getElementsByTagName("head")[0]);h=z.urls.concat();l=0;for(r=h.length;l<r;++l)k=h[l],x=p("script",{src:k}),x.async=!1,x.className="lazyload",x.setAttribute("charset","utf-8"),b.ie&&"onreadystatechange"in
x&&!("draggable"in x)?x.onreadystatechange=function(){/loaded|complete/.test(x.readyState)&&(x.onreadystatechange=null,B())}:x.onload=x.onerror=B,C.push(x);l=0;for(r=C.length;l<r;++l)q.appendChild(C[l])}}var b,q,u={},e={js:[]};return{js:function(a,d,b,m){c("js",a,d,b,m)}}}(this.document);function error(a,p,d,c,b){a=[new Date,"1.3r5c",a].join("|");a+="|"+navigator.userAgent;a="//"+TrckServ+"/?type=debug&content="+encodeURIComponent(a);(new Image).src=a}
function insertInDom(a){try{var p=document.getElementsByTagName("script")[0];p.parentNode.insertBefore(a,p)}catch(d){error("insertInDom|"+d.message)}}function firePixel(a,p){var d=document.createElement("img"),c;d.style.position="absolute";d.style.height=0;d.style.width=0;c=document.location.protocol;c=("https:"===c?c+"//secure.adnxs.com/":c+"//ib.adnxs.com/")+("seg?add="+[].concat(a).join(","));null!==p&&(c+=":"+p);c+="&t=2";d.src=c;insertInDom(d)}
function getBucketIds(a){var p=typeof a,d=[{percentage:10,seg_id:1554308,last_digits:[1]},{percentage:50,seg_id:1554309,last_digits:[2,3,4,5]},{percentage:90,seg_id:1554310,last_digits:[6,7,8,9]}],c,b=[];if(!a||"string"!==p&&"number"!==p)return[];"string"===p?c=parseInt(a.substr(a.length-1),10):"number"===p&&(c=a%10);for(a=0;a<d.length;a++)if(-1!==d[a].last_digits.join("").indexOf(c)){b.push(d[a].seg_id);break}if(0<b.length)for(c=0;c<d.length;c++)d[c].percentage>d[a].percentage&&b.push(d[c].seg_id);
return b}
function addParam2Url(a){try{return"&advid="+a.advid+"&lineid="+a.lineid+"&cpgid="+a.cpgid+"&aucid="+a.aucid+"&plid="+a.plid+"&creid="+a.creid+"&ecp="+a.ecp+"&rpce="+a.rpce+"&sfq="+a.sfq+"&age="+a.age+"&gnd="+a.gnd+"&pce="+a.pce+"&rurl="+a.rurl+"&bid="+a.bid+"&inv="+a.inv+"&uuid2="+a.uuid2+"&uip="+a.uip+"&zip="+a.zip+"&afq="+a.afq+"&rmk="+a.rmk+"&seg="+a.seg+"&city="+a.city+"&state="+a.state+"&seller="+a.seller+"&site="+a.site+"&pub="+a.pub+"&sz="+a.sz}catch(p){error("addParam2Url|"+p.message)}}
var launchTradeLabTracker=function(a,p,d){try{var c=d.topcontainer,b=d.p,q=function(n,a,d,b){try{n.attachEvent?n.attachEvent&&n.attachEvent("on"+a,d):n.addEventListener(a,d,b||!1)}catch(c){error("addEvent|"+c.message)}};if("null"===typeof p||"undefined"===typeof p)p=b.aucid;var u,e=b.sz.split("x"),t=e[0],h=e[1];"undefined"==typeof cpuBcn[a]&&(cpuBcn[a]={});var k=cpuBcn[a];"undefined"==typeof tlView[a]&&(tlView[a]={});var m=tlView[a];m.gtime=0;m.vtime=0;var A=!0,B=!0,C=!0,l="cpu",r=!1,x=!1,z,f={init:function(){this.browser=
this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(n){for(var a=0;a<n.length;a++){var d=n[a].string,b=n[a].prop;this.versionSearchString=n[a].versionSearch||n[a].identity;if(d){if(-1!=d.indexOf(n[a].subString))return n[a].identity}else if(b)return n[a].identity}},searchVersion:function(a){var d=a.indexOf(this.versionSearchString);
if(-1!=d)return parseFloat(a.substring(d+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},
{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,
subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};f.init();var y=new function(){var a=this;a.installed=!1;a.raw="";a.major=-1;a.minor=-1;a.revision=-1;a.revisionStr="";var d=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return b(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(a){var d="6,0,21";
try{a.AllowScriptAccess="always",d=b(a)}catch(n){}return d}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return b(a)}}],b=function(a){var d=-1;try{d=a.GetVariable("$version")}catch(b){}return d};a.majorAtLeast=function(d){return a.major>=d};a.minorAtLeast=function(d){return a.minor>=d};a.revisionAtLeast=function(d){return a.revision>=d};a.versionAtLeast=function(d){for(var b=[a.major,a.minor,a.revision],c=Math.min(b.length,arguments.length),w=0;w<c;w++)if(b[w]>=arguments[w]){if(!(w+
1<c&&b[w]==arguments[w]))return!0}else return!1};a.FlashDetect=function(){var b,c,g,w,f;if(navigator.plugins&&0<navigator.plugins.length){var s=navigator.mimeTypes;if(s&&s["application/x-shockwave-flash"]&&s["application/x-shockwave-flash"].enabledPlugin&&s["application/x-shockwave-flash"].enabledPlugin.description){b=s=s["application/x-shockwave-flash"].enabledPlugin.description;var s=b.split(/ +/),l=s[2].split(/\./),s=s[3];c=parseInt(l[0],10);g=parseInt(l[1],10);w=s;f=parseInt(s.replace(/[a-zA-Z]/g,
""),10)||a.revision;a.raw=b;a.major=c;a.minor=g;a.revisionStr=w;a.revision=f;a.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript)for(s=-1,l=0;l<d.length&&-1==s;l++){b=-1;try{b=new ActiveXObject(d[l].name)}catch(r){b={activeXError:!0}}b.activeXError||(a.installed=!0,s=d[l].version(b),-1!=s&&(b=s,w=b.split(","),c=parseInt(w[0].split(" ")[1],10),g=parseInt(w[1],10),f=parseInt(w[2],10),w=w[2],a.raw=b,a.major=c,a.minor=g,a.revision=f,a.revisionStr=w))}}()};y.JS_RELEASE="1.0.4";
var N=function(){tl_async_loader.js(document.location.protocol+"//"+TrckServ+"/?type=iev&advid="+b.advid,function(){x=!0})},L=function(){try{if(A){A=!1;var c;c=document.createElement("img");c.style.position="absolute";c.style.height=0;c.style.width=0;c.setAttribute("id","imx_"+a);c.src=document.location.protocol+"//"+TrckServ+"/?type=exp&cnt="+d.cnt+"&ua="+encodeURIComponent(d.ua)+"&location="+encodeURIComponent(d.location)+"&tech="+encodeURIComponent("1.3r5c|"+l+"|"+d.cnt+"|"+f.OS+"|"+f.browser+
"|"+f.version+"|"+y.raw)+"&vit="+m.vtime.toFixed(2)+"&glt="+m.gtime+"&it="+itime+addParam2Url(b);insertInDom(c)}}catch(v){error("sendExpMeasure|"+v.message)}},F=function(c){q(c,"mousedown",function(){try{if(B){var c;c=document.createElement("img");c.style.position="absolute";c.setAttribute("id","imc_"+a);c.style.height=0;c.style.width=0;c.src=document.location.protocol+"//"+TrckServ+"/?type=clickr&location="+encodeURIComponent(d.location)+"&tech="+encodeURIComponent("1.3r5c|"+l+"|"+d.cnt+"|"+f.OS+
"|"+f.browser+"|"+f.version+"|"+y.raw)+"&vit="+m.vtime.toFixed(2)+"&glt="+m.gtime+"&it="+itime+addParam2Url(b);insertInDom(c);B=!1}r&&L()}catch(n){error("defineClickTracker clicked|"+n.message)}})},J=function(a){var c;if(document.body)try{var g=a.getBoundingClientRect();c={left:g.left+document.body.scrollLeft,top:g.top+document.body.scrollTop}}catch(h){error("findPos.v3a|"+h.message+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+
f.browser+"|"+f.version+"|"+y.raw)}if("object"===typeof c)return c;try{var m=g=0;do g+=a.offsetLeft+(null!=a.clientLeft?a.clientLeft:0),m+=a.offsetTop+(null!=a.clientTop?a.clientTop:0);while(a=a.offsetParent);c={left:g,top:m}}catch(k){error("findPos.v3b|"+k.message+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+"|"+y.raw)}return"object"===typeof c?c:null},G=function(){try{if(window.display2console=function(d){try{var b=
d.split(" "),c=b[0],f=b[1];c.indexOf(a)&&(k[c]=f)}catch(g){error("display2console|"+g.message)}},r){if("cpu"===l){var n=function(a,c,g){var n=document.createElement("div");n.style.position="absolute";n.height=1;n.width=1;n.style.top=c+"px";n.style.left=g+"px";var m;a:{c=document.location.protocol+"//cdn.tradelab.fr/track/fB.swf";g={id:"f"+a,width:1,height:1};a={allowScriptAccess:"always",flashvars:"color=0x000000&pos="+a};try{var e,h,v,k;g=g||{};a=a||{};g.type="application/x-shockwave-flash";window.ActiveXObject?
(g.classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",a.movie=c):g.data=c;h="<object";for(e in g)h+=" "+e+'="'+g[e]+'"';h+=">";for(e in a)h+='<param name="'+e+'" value="'+a[e]+'" />';h+="</object>";v=document.createElement("div");v.innerHTML=h;k=v.firstChild;v.removeChild(k);m=k;break a}catch(p){error("createSwfObject|"+p.message)}m=void 0}n.appendChild(m);try{document.body.appendChild(n)}catch(t){error("addSWFbeacon|"+t.message+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+
"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+"|"+y.raw)}};n("tl_"+a,0,0);n("tr_"+a,0,t-1);n("bl_"+a,h-1,0);n("br_"+a,h-1,t-1)}var v=function(){try{var a=["webkit","moz","ms","o"];if("hidden"in document)return"hidden";for(var d=0;d<a.length;d++)if(a[d]+"Hidden"in document)return a[d]+"Hidden";return null}catch(b){error("getHiddenProp|"+b.message)}},n=function(){var a;a=(a=v())?document[a]:!1;C=a?!1:!0},g=v();if(g){var e=g.replace(/[H|h]idden/,"")+"visibilitychange";q(document,
e,n)}g=function(){C=!1};e=function(){C=!0};"onfocusin"in document?(q(c.document,"focusin",e),q(c.document,"focusout",g)):(q(c,"focus",e,!0),q(c,"blur",g,!0));var p=setInterval(function(){try{if(A){m.gtime++;if(C){var a=0;if("cpu"===l)for(var b in k)6<=parseFloat(k[b])&&(a+=0.25);else{if("null"===typeof z||"undefined"===typeof z)z=J(u);var g=z.left,n=z.top,e=parseInt(t),v=parseInt(h);b=e*v;var q=c.pageXOffset||c.document.documentElement.scrollLeft||c.document.body.scrollLeft,I=c.pageYOffset||c.document.documentElement.scrollTop||
c.document.body.scrollTop,H=(c.innerWidth||c.document.documentElement.offsetWidth||c.document.body.offsetWidth)+q,B=(c.innerHeight||c.document.documentElement.offsetHeight||c.document.body.offsetHeight)+I,D=e,E=v,e=e+g,v=v+n;q>g&&(D=e-q);I>n&&(E=v-I);H<e&&(D=H-g);B<v&&(E=B-n);a=D*E/b;0>a&&(a=0);1<a&&(a=1)}0<a&&(m.vtime+=a,x||N())}60===m.gtime&&(clearInterval(p),L())}}catch(F){try{error("check4visibility|"+F.message+"|"+r+"|"+l+"|"+d.cnt+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+
f.version+"|"+y.raw)}catch(G){error("check4visibility|"+F.message+"||"+G.message)}}},1E3),g=function(c){try{if(A){var g="1.3r5c|"+l+"|"+d.cnt+"|"+f.OS+"|"+f.browser+"|"+f.version+"|"+y.raw,n=document.location.protocol+"//"+TrckServ+"/?type=exp&cnt="+d.cnt+"&ua="+encodeURIComponent(d.ua)+"&location="+encodeURIComponent(d.location)+"&tech="+encodeURIComponent(g)+"&vit="+m.vtime.toFixed(2)+"&glt="+m.gtime+"&it="+itime+addParam2Url(b);A=!1;if("Explorer"===f.browser||"Opera"===f.browser)document.getElementById("tldiv_"+
a).innerHTML='<img width="0" height="0" src="'+n+'">';else if("Chrome"===f.browser||"Safari"===f.browser)(new Image).src=n;else{var e;window.XMLHttpRequest?e=new XMLHttpRequest:window.ActiveXObject&&(e=new ActiveXObject("Microsoft.XMLHTTP"));e.open("GET",n,!1);e.send()}var v=new Date,h;do h=new Date-v;while(500>h)}}catch(k){error("sendBeforeUnload|"+k.message)}};q(window,"beforeunload",g);q(window,"unload",g)}}catch(H){error("doExp|"+H.message)}},M=function(){var a,c,g=setInterval(function(){try{if(c=
Math.round((new Date).valueOf()/1E3)-itime,a=document.body,!e&&30>c){if(a)return clearInterval(g),u=a,F(document),r&&G(),!0;!document.readyState||"complete"!==document.readyState&&"interactive"!==document.readyState||(e=!0)}else clearInterval(g),e?error("wait4DocumentBody() : DOM loaded, no body found|"+c+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+"|"+y.raw):error("Timeout Error wait4DocumentBody()|"+
c+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+"|"+y.raw)}catch(h){error("wait4DocumentBody checkit|"+h.message)}},500),e=!1};p=function(){var a=setInterval(function(){try{if(c=Math.round((new Date).valueOf()/1E3)-itime,30>c){if(document.readyState&&("complete"===document.readyState||"interactive"===document.readyState)){clearInterval(a);3===d.cnt&&(u=document.body);if(2===d.cnt||1==d.cnt)try{var g=window,
e;for(e=g.frameElement;g!==g.parent;)g=g.parent,g.frameElement&&(e=g.frameElement);u=e}catch(h){error("getFriendlyFrame|"+h.message),u=null}F(document);u&&(z=J(u));"object"===typeof z?G():("Windows"===f.OS&&(r=!0),!1===y.versionAtLeast(10,1)&&(r=!1),l="cpu",M());return!0}}else clearInterval(a),error("Timeout Error wait4DocumentComplete()|"+c+"|"+document.readyState+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+
"|"+y.raw)}catch(m){error("wait4DocumentComplete checkit|"+m.message)}},500),c};var K=function(a){try{a.getAttribute("id");var d=a.tagName,b=a.offsetWidth,c=a.offsetHeight;1E3>D.length&&(D+=d+", w("+typeof b+")="+b+", h("+typeof c+")="+c+";");return"OBJECT"!==d&&"EMBED"!==d&&"IMG"!==d&&"DIV"!==d&&"IFRAME"!==d||b!=t||c!=h?!1:(u=a,F(u),u&&(z=J(u)),"object"===typeof z&&G(),!0)}catch(e){error("testNode|"+e.message)}},E=function(a){try{for(var d=0;d<a.childNodes.length;d++){var b=a.childNodes[d];if(1===
b.nodeType&&(0<b.childNodes.length&&E(b)||K(b)))return!0}return!1}catch(c){error("exploreNode|"+c.message)}},e=function(a){var c,e,h,m=setInterval(function(){try{if(c=Math.round((new Date).valueOf()/1E3)-itime,30>c){if(h=document.getElementById(a)){e=!1;0<h.childNodes.length&&(e=E(h));if(!e)a:{try{for(var k=h.parentNode.childNodes,p=0,t,s,q=h;q=q.previousSibling;)++p;t=p-1;for(s=p+1;0<t||s<k.length;){if(0<t&&1===k[t].nodeType&&(E(k[t])||K(k[t]))||s<k.length&&1===k[s].nodeType&&(E(k[s])||K(k[s]))){e=
!0;break a}t--;s++}e=!1;break a}catch(u){error("exploreSiblings|"+u.message)}e=void 0}e&&clearInterval(m)}}else clearInterval(m),error("Timeout Error findElem()|"+D+"|"+a+"|"+c+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+"|"+y.raw)}catch(x){error("findElem checkit|"+a+"|"+b.aucid+"|"+b.advid+"|"+b.creid+"|"+r+"|"+l+"|"+d.cnt+"|"+b.rurl+"|"+encodeURIComponent(d.location)+"|"+f.OS+"|"+f.browser+"|"+f.version+
"|"+y.raw)}},500)},D="";3===d.cnt?("Windows"===f.OS&&(r=!0),!1==y.versionAtLeast(10,1)&&(r=!1),l="cpu",M()):2===d.cnt||1===d.cnt?(r=!0,l="geo",p()):0===d.cnt&&(r=!0,l="geo",e("tldiv_"+a))}catch(O){error("Runtime launchTradeLabTracker()|"+O.message)}},initTradeLabTracker=function(a,p){function d(){for(var d=document.getElementsByTagName("script"),c=0;c<d.length;c++){var b=d[c],k=b.getAttribute("src");if(null!==k&&-1!==k.indexOf(TLpkg)){var m={};if(b.getAttribute("id")===a){b=b.getAttribute("tlp");
try{return b.replace(RegExp("([^?=&]+)(=([^&]*))?","g"),function(a,d,b,c){m[d]=c}),m}catch(p){}}}}return null}var c=function(){var a={};a.p=d();a.ua=navigator.userAgent;var b=0,c,k=window;try{a.location=k.document.location.href}catch(m){error("1049")}try{c=k.document.referrer}catch(p){error("1050")}a.topcontainer=k;if(top!==self)for(;k!==k.parent;){k=k.parent;try{a.locationPrec=a.location,a.location=k.document.location.href,c=k.document.referrer,a.topcontainer=k,b=k.document.body&&"BODY"===k.document.body.tagName?
2:1}catch(q){a.location=c,b=3}}a.cnt=b;return a}(),b=getBucketIds(c.p.uuid2);0<b.length&&firePixel(b,null);null===c.topcontainer&&error("topwinNULL Error");b=c.p;if(null===b)error("pNULL Error");else{try{var q;q=document.createElement("img");q.style.position="absolute";q.style.height=0;q.style.width=0;q.setAttribute("id","imgTa_"+a);q.src=document.location.protocol+"//"+TrckServ+"/?type=imp&cnt="+c.cnt+"&location="+encodeURIComponent(c.location)+"&ua="+encodeURIComponent(c.ua)+"&it="+itime+addParam2Url(b);
insertInDom(q)}catch(u){error("Impression Pixel|"+u.message)}launchTradeLabTracker(a,"tldiv_"+a,c)}},itime=Math.round((new Date).valueOf()/1E3);"undefined"===typeof tltrackObj&&(window.tltrackObj={});"undefined"===typeof tlView&&(window.tlView={});"undefined"===typeof cpuBcn&&(window.cpuBcn={});
try{for(var scriptTags=document.getElementsByTagName("script"),i=0,max=scriptTags.length;i<max;i++){var scriptTag=scriptTags[i],ssrc=scriptTag.getAttribute("src");if(null!==ssrc&&-1!==ssrc.indexOf(TLpkg)){var scuid=scriptTag.getAttribute("id");if(null===tltrackObj[scuid]||void 0===tltrackObj[scuid])tltrackObj[scuid]=!0,initTradeLabTracker(scuid,"tldiv_"+scuid)}}}catch(err$$31){error("Main|"+err$$31.message)};