function SWFtoJS(c){this.m_oCallFuntions={};this.m_bDebug=!1;null!=c&&SWFtoJS.instance().parse(c)}SWFtoJS.m_oSWFtoJS=null;SWFtoJS.instance=function(c){null==SWFtoJS.m_oSWFtoJS&&(SWFtoJS.m_oSWFtoJS=new SWFtoJS,c&&(SWFtoJS.m_oSWFtoJS.m_bDebug=!0));return SWFtoJS.m_oSWFtoJS};SWFtoJS.prototype.addCallFunction=function(c,f){"function"==typeof f&&(this.m_oCallFuntions[c]=f)};
SWFtoJS.prototype.parse=function(c){try{if(c.call)switch(c.call){case "MULTI":for(i=0;i<p_oData.calls.length;i++)SWFtoJS(c.calls[i]);break;default:if(this.m_oCallFuntions[c.call])c.params||(c.params={}),this.m_oCallFuntions[c.call](c.params);else throw"call: "+c.call+" not found in call functions!";}else throw"call attribute not found in CallObject!";}catch(f){this.m_bDebug&&alert(f)}};/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIMonitor",deps:["SWP","GIController","JSLib","Net","Utils"],module:function(){var c,f=!1;if(!c)return c=function(c,r,y,g,k){var s=r.eventCodeMap,u={},d=function(b,a,e,c){"undefined"===typeof c&&(c=!0);k.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,e,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,e,!0]));var f=k.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),h=f?"ms":"c",f=f?e:1,d=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+d+"."+b+"."+a+"]="+f+h,n={};u.monitoring&&u.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+d+"."+u.monitoring.bucket+"."+b+"."+a+"]="+f+h,n.gameType=u.monitoring.bucket);0<f&&("c"===h?1===f:1)&&g.send({url:m,type:"GET"},k.emptyFn);y("tracker.event."+(c?"track":"express"),{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,
eventValue:parseInt(e,10),properties:n})},n={error:function(b){var a=s.error;b=b.data;switch(b.code){case a.USER_DATA_MISSING:d("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);d("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:d("error","missingBrowserFeature")}},warning:function(b){var a=s.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:d("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:d("warning",
"prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:d("warning","prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:d("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:d("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:d("warning","midrollTimeout",b.waited)}},update:function(b){var a=s.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&d("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&
d("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:d("update","initialized")}}};return{init:function(b){u=b;f||(f=!0,c.init("game"),b=window.publishingHost,void 0===b?d("update","publishingHostUndefined",b):"unknown"===b?d("update","publishingHostUnknown",b):d("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":n.error(a);break;case "gi.warning":n.warning(a);break;case "gi.update":n.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&
d("update","timeToPlay",a.timeToPlay);a.displayGame&&d("update","displayGame",a.displayGame,!1);a.prerollDisplayDuration&&d("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&d("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&d("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&d("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&d("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&d("update",
"progressBarStart",a.progressBarStart);a.progressBarDuration&&d("update","progressBarDuration",a.progressBarDuration);a.progressBarError&&d("warning","progressBarError",a.progressBarError);a.loadDuration&&d("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":d("warning","decodeAuthCookieFailure");break;case "appToken":d("error","appToken");break;case "getCurrentUser":d("error","getCurrentUser")}}},!0))}}}}()});/*
 2013, Spil Games
*/
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,f){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",f)},updateCache:function(c,f){f&&_SG.Settings.set("auth.uid",f);SpilGames.Events.publish("auth.login",{hash:c,uid:f,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(f){c.call(this,!0,f,null)},onfailure:function(f){c.call(this,!1,null,f)}})}}}});/*
: 2013, SpilGames
*/
SpilGames("spilgames.import",{name:"SpapiIntegration",deps:"RemoteEvent Game Utils JSLib SPAPI SWPEvent".split(" "),module:function(c,f){return function(c,r,y,g,k,s){return{enable:function(s,d){var n=f.getElementById(s.game.objectSettings.domId),b=s.game.objectSettings.url;c.subscribe(b);g.subscribe("remote.api.portal.*|remote.api.auth.getApplicationToken",function(a){var k=this.event.type,f=k.substring(7);"api.auth.getApplicationToken"===f?a={applicationId:s.portal.applicationId}:"api.portal.invite.friends"===
f&&d.System.emit("popup.social_invite.open");g(f,a,function(a){c.publish(k,{target:{frame:n,url:b},data:a})})});g.subscribe("api.event.*",function(a){c.publish(this.event.type,{target:{frame:n,url:b},data:a})});var a=g.messageBroker;a.addRule("api.portal.force.auth",function(a,b){g("api.user.get",{cache:!0},function(a){a.isError||"guest"==a.userInfo.level?(g("api.event.overlay.shown"),g("api.portal.overlay.show"),d.System.init(function(a){switch(a.name){case "popup.closed":g("api.event.overlay.hidden"),
g("api.portal.overlay.hide"),b({data:{state:k.STATE_LOGGEDOUT}})}}),d.System.emit("popup.login.open")):b({state:k.STATE_LOGGEDIN})})});a.addRule("api.portal.canvas.setSize",function(a,b){function c(b){/^[0-9]+$/.test(a[b])&&Number(a[b])<=g[b]&&("width"===b?(k.style.width=p+"px",f.style.width=p+"px",d.style.width=w+"px"):(k.style.height=a.height+"px",f.style.height=a.height+"px"),D=!0)}var g={width:1E3,height:2E3},k=document.getElementById("iframegame"),f=document.getElementById("theGame"),d=document.getElementById("layout-container"),
n=s.game.recommendedGames,p=parseInt(a.width,10),r=682,w,D=!1;n&&(r=891);w=p>r?960+p-r:960;960>w&&(w=960);y.isEmpty(a)?b({state:!1}):(c("width"),c("height"),D?b({state:!0}):b({state:!1}))})}}}}(window,document)});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Jeroen Reurings <jeroen.reurings@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,f){var p,r=!1;p||(p=function(p,g,k,s,u,d,n){var b={},a,e={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,INITIALIZED:11,
MIDROLL_ALIVE:12,MIDROLL_REQUESTED:19,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},B={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},q,h,t=!1,m=function(){var a=[],b=[],l=function(b,l){a[b]||(a[b]=[]);return a[b].push(l)-1},e=function(a){var x=!1;b[a]&&(x=!0);return x},c=function(b,l){a[b]&&a[b][l]&&(a[b][l]=null)},f=function(){k.System.init(function(l){var e=l.name;b[e]=l;(e=a[e])&&g.each(e,function(a){"function"===
typeof a&&a(l)})},!0);f=function(){}};return{subscribe:l,unsubscribe:c,unsubscribeAll:function(b){delete a[b]},waiton:function(a,x){if(e(a))x(b[a]);else{var g=l(a,function(a){c("eventName",g);x(a)});return g}},isFired:e,init:f}}(),v=function(a){p(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var l=!1;if(0<b.major||0<b.minor||0<b.release)l=!0;a(l)})},F=function(){var a=!1,b=h.game.requiredFeatures;g.isObject(b)&&0<g.size(b)&&g.each(b,function(b){!0===b&&(a=!0)});return a},A=function(){var b=
a.states,z;v(function(l){z=b.PRE_FETCHING_GAME;!1===l&&(z=b.PLUGIN_MISSING);a.transitionTo(z)})},C=function(){var b=a.states,z=b.LISTENING_TO_ADVERTISING,l;g.each(h.game.requiredFeatures,function(a,e){l=B[e];!0===a&&"function"===typeof n[l]&&!1===n[l]()&&(z=b.FEATURE_MISSING)});a.transitionTo(z)},w=function(){m.isFired("ad.preroll.finish")||p(["LightSWFObject"],function(a){var b=h.game.preloader,l={data:b.src+"?url="+encodeURIComponent(h.game.settings.movie),width:"1",height:"1"};p.subscribe("game.prefetcher.error",
function(a){k.System.emit("gi.warning",{code:e.warning.PRE_FETCH_ERROR,flashError:a})});a.createSWF(l,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},b.domId);t=!0});a.transitionTo(a.states.LISTENING_TO_ADVERTISING)},D=function(){var b=m.isFired("ad.preroll.heartbeat"),z=m.isFired("ad.preroll.start"),l=h.preroll.heartbeatTime,g=function(){k.System.emit("gi.update",{code:e.update.PREROLL_ALIVE,fetchTime:u.stop("prerollFetchTime")})},
f=function(){k.System.emit("gi.update",{code:e.update.PREROLL_FAKE_START})};!0===b&&g();!0===z&&f();u.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){f()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(q);b||(b=!0,g());q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.PREROLL_NO_HEARTBEAT,waited:l});a.transitionTo(a.states.WAITING_ON_USERDATA)},l)});m.waiton("ad.preroll.finish",function(){q&&c.clearTimeout(q);a.transitionTo(a.states.WAITING_ON_USERDATA)});
a.transitionTo(a.states.WAITING_ON_PRE_ROLL)},E=function(){var a=0,b=h.midroll.heartbeatTime,l=h.midroll.maxWaitingTime,g=!1,f=function(){c.clearTimeout(q);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");k.System.emit("gi.update",{code:e.update.MIDROLL_FINISHED,occurrence:a});k.System.emit("gi.update",{code:e.update.ABORT_MIDROLL});g=!1};m.subscribe("ad.midroll.start",function(){if(!g){var h=!1;g=!0;a+=1;u.start("midrollFetchTime");q=c.setTimeout(function(){k.System.emit("gi.warning",
{code:e.warning.MIDROLL_TIMEOUT,waited:l,occurrence:a});f()},l);k.System.emit("gi.update",{code:e.update.MIDROLL_REQUESTED,occurrence:a});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(q);h||(h=!0,k.System.emit("gi.update",{code:e.update.MIDROLL_ALIVE,fetchTime:u.stop("midrollFetchTime"),occurrence:a}));q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.MIDROLL_NO_HEARTBEAT,waited:b,occurrence:a});f()},b)});m.subscribe("ad.midroll.finish",function(){f()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var b=
h.preroll.maxWaitingTime;q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.PREROLL_TIMEOUT,waited:b});a.transitionTo(a.states.WAITING_ON_USERDATA)},b)}},H=function(){c.clearTimeout(q);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");m.unsubscribeAll("ad.preroll.finish");var x=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||k.System.emit("gi.update",{code:e.update.ABORT_PREROLL});
k.System.emit("gi.update",{code:e.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(e){var l=a.states,g=l.INTEGRATING_GAME;x&&c.clearTimeout(x);!e.data||e.data.isError?g=l.INTEGRATION_ERROR:b=e.data;a.transitionTo(g)})},I=function(){var x=a.states.GAME_INTEGRATED,z=b.auth,l=h.game.settings,f=h.game.preloader,d;if(z&&g.isObject(z)&&!z.isError)for(d in z)z.hasOwnProperty(d)&&(l.flashvars+="&"+d+"="+z[d]);h&&h.portal&&h.portal.appToken&&(l.flashvars+="&appToken="+h.portal.appToken);
p(["LightSWFObject"],function(b){var z={data:l.movie,width:l.width,height:l.height},g={base:l.base,quality:"autohigh",allowFullScreen:l.allowFullScreen,wmode:l.wmode,allowScriptAccess:l.allowScriptAccess,scale:l.scale,flashVars:l.flashvars,bgcolor:l.bgcolor,hasPriority:"true"},h=function(){b.createSWF(z,g,l.domId);k.System.emit("gi.update",{code:e.update.GAME_EMBEDDED});a.transitionTo(x)};t?(t=!1,b.removeSWF(f.domId),c.setTimeout(function(){h()},20)):h()})};a={states:{INITIALIZED:0,PLUGIN_DETECTION:1,
FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(b){k.Widget.emit(a.eventNamespace,{state:b})},flowController:function(x){var z,l,c,d;l=a.states;switch(x.data.state){case l.INITIALIZED:var q=a.states;x=q.LISTENING_TO_ADVERTISING;l=!1;var m,t,n;h&&(m=h.game,t=h.preroll,n=h.midroll);
g.isObject(h)&&g.isObject(m)&&g.isObject(t)&&g.isObject(n)&&g.isString(m.type)&&(g.contains(m.type,"DomObject")||g.contains(m.type,"iframe"))&&g.isNumber(t.maxWaitingTime)&&g.isNumber(n.maxWaitingTime)&&g.isNumber(t.heartbeatTime)&&g.isNumber(n.heartbeatTime)&&(l=!0);if(!l)throw q={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",eventLabel:"GameIntegration module, exception:"+
q.type+" - "+q.message,eventValue:1}),q;"DomObject"===h.game.type?x=q.PLUGIN_DETECTION:F()&&(x=q.FEATURE_DETECTION);a.transitionTo(x);break;case l.PLUGIN_DETECTION:A();break;case l.FEATURE_DETECTION:C();break;case l.PRE_FETCHING_GAME:w();break;case l.PLUGIN_MISSING:k.System.emit("gi.error",{code:e.error.PLUGIN_MISSING,pluginName:"flash"});k.System.emit("gi.update",{code:e.update.ABORT_PREROLL});break;case l.FEATURE_MISSING:k.System.emit("gi.error",{code:e.error.FEATURE_MISSING});k.System.emit("gi.update",
{code:e.update.ABORT_PREROLL});break;case l.LISTENING_TO_ADVERTISING:D();break;case l.WAITING_ON_PRE_ROLL:G();break;case l.WAITING_ON_USERDATA:H();break;case l.INTEGRATING_GAME:"DomObject"===h.game.type&&I();if("iframe"===h.game.type){m=a.states.GAME_INTEGRATED;l=h.game.settings;t=f.getElementById(l.domId);n={};g.isObject(b.auth)&&(n=g.combine(b.auth,n));g.isObject(h.portal)&&h.portal.siteId&&h.portal.channelId&&(n=g.combine({siteid:h.portal.siteId,channelid:h.portal.channelId,UID:h.portal.sgid||
""},n),n=h.portal.authenticated&&!0===h.portal.authenticated?g.combine({hash:h.portal.appToken||"",username:h.portal.username||""},n):g.combine({hash:"",username:""},n));g.isObject(b.other)&&(n=g.combine(b.other,n));t.width=l.width;t.height=l.height;x=n;n="";l=l.url.replace("###DOMAIN###",window.location.hostname);l=l.replace("###CACHE_PP###","");d=document.createElement("a");var p;d.href=l;p="/"===d.pathname.charAt(0)?d.pathname:"/"+d.pathname;z=d.protocol;l=d.search;c=d.hash;d=d.host;for(q in x)x.hasOwnProperty(q)&&
(n+="&"+q+"="+x[q]);q=z+"//"+d+p||"";q=0<l.length?q+encodeURI(l+n):q+("?"+encodeURI(n.substring(1)));t.src=q+(c||"");k.System.emit("gi.update",{code:e.update.GAME_EMBEDDED});a.transitionTo(m)}break;case l.INTEGRATION_ERROR:k.System.emit("gi.error",{code:e.error.USER_DATA_MISSING});break;case l.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),s.emit("gi.game.loaded")}},start:function(){k.Widget.init(a.flowController)}};return{init:function(b){h=b;h.game.objectSettings&&(h.game.settings=
h.game.objectSettings);if(r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;k.init("game");m.init();a.start();k.System.emit("gi.update",{code:e.update.INITIALIZED});a.transitionTo(a.states.INITIALIZED)},eventCodeMap:e}});return p}(window,document)});/*
: 2013, SpilGames
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;c||(c=function(c,p,r,y,g,k){return{launch:function(c){r.init(c);y.init(c);var f=c.hooks;if(p.isFunction(f.onPrerollFinish))g.onState("afterpreroll",function(){f.onPrerollFinish()});if(p.isFunction(f.onDisplayGame))g.onState("displaygame",function(){f.onDisplayGame()});if(p.isFunction(f.onMidroll))g.onState("onmidroll",function(){f.onMidroll()},!0);if(p.isFunction(f.afterMidroll))g.onState("aftermidroll",
function(){f.afterMidroll()},!0);g.init(c);k.init(c)}}});return c}(window,document)});SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,f){var p,r=!1;p||(p=function(p,g,k,s,u,d){var n={backgroundScreen:f.getElementById("backgroundScreen"),defaultScreen:f.getElementById("defaultLoadingScreen"),waitingForUserData:f.getElementById("waitingForUserData"),userDataNotResponding:f.getElementById("userDataNotResponding"),userDataMissing:f.getElementById("userDataMissing"),loadingDomObjectGame:f.getElementById("loadingDomObjectGame"),
loadingIframeGame:f.getElementById("loadingIframeGame"),errorLoadingGame:f.getElementById("errorLoadingGame"),missingPlugin:f.getElementById("missingPlugin"),missingFeature:f.getElementById("missingFeature"),displayGame:f.getElementById("theGame"),preRoll:f.getElementById("videoPreroll300x250"),midRoll:f.getElementById("sgAdOgGp300x250"),midrollLoading:f.getElementById("midrollLoadingScreen")},b=f.getElementById("game-integration"),a={},e=[],B=["displaygame","afterpreroll","onmidroll","aftermidroll"],
q=n.defaultScreen,h={},t,m=!1,v=function(a){q.className=q.className.replace("activeFeedbackScreen","");q=n[a];q.className+=" activeFeedbackScreen"},F=function(){u.subscribe("game.ad.accepted",function(a){p.isObject(a)&&!0===a.displayAd&&p.isString(a.bgImage)&&!p.isEmpty(a.bgImage)&&(t=a.bgImage)})},A=function(a){var b=e[a];b&&p.each(b,function(a,x){a.persistent&&!0===a.persistent||delete b[x];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),w=function(){if(!m){m=!0;v("displayGame");A("displaygame");try{F();g.System.emit("gi.portal.feedback",{displayGame:a.portal.contentarId});var b=C();b&&g.System.emit("gi.portal.feedback",{timeToPlay:k.now()-b});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),g.System.emit("gi.portal.feedback",
{timeToFirstPlay:k.now()-a.sessionStart}))})}catch(e){}}},D=function(){var b=f.getElementById(a.game.settings.domId),e=f.getElementById("progress-container"),c,x=function(){try{(c=k.stop("iframeLoadDuration"))&&g.System.emit("gi.portal.feedback",{loadDuration:c})}catch(a){}w()};k.start("iframeLoadDuration");b.completed?w():(e&&(e.style.display="none"),v("loadingIframeGame"),b.attachEvent?b.attachEvent("onload",function(){x()}):b.onload=function(){x()})},E=function(){var b=f.getElementById(a.game.settings.domId),
e=f.getElementById("progress-bar"),d=f.getElementById("progress-percentage"),x,z,l,h,q=0,n=function(){return b&&"function"===typeof b.PercentLoaded||c.attachEvent&&"number"===typeof b.PercentLoaded()},m=function(){l=b.PercentLoaded();if(98<l||0>l)w();else{v("loadingDomObjectGame");e.width=l+"%";d&&(d.innerHTML=l+"%");try{k.start("progressBarDuration"),g.System.emit("gi.portal.feedback",{progressBarStart:l})}catch(a){}x=c.setInterval(function(){l=n()?b.PercentLoaded():void 0;if("undefined"!==typeof l&&
-1<l&&100>l)d&&(d.innerHTML=l+"%"),e.style.width=l+"%";else{c.clearInterval(x);d&&(d.innerHTML="100%");e.style.width="99%";c.setTimeout(function(){w()},500);try{(z=k.stop("progressBarDuration"))&&g.System.emit("gi.portal.feedback",{progressBarDuration:z+500})}catch(a){}}},100)}};try{h=c.setInterval(function(){q+=1;n()&&(c.clearInterval(h),m());10<=q&&(c.clearInterval(h),w(),g.System.emit("gi.portal.feedback",{progressBarError:a.portal.contentarId}))},100)}catch(t){w(),g.System.emit("gi.portal.feedback",
{progressBarError:a.portal.contentarId})}};return{init:function(e){r||(r=!0,a=e,h=d.eventCodeMap,g.init("game"),g.System.init(function(e){switch(e.name){case "gi.update":var c=h.update;e=e.data;var x;switch(e.code){case c.WAITING_FOR_USER_DATA:v("waitingForUserData");try{var z=k.stop("prerollDisplayDuration");z&&g.System.emit("gi.portal.feedback",{prerollDisplayDuration:z})}catch(l){}A("afterpreroll");break;case c.PREROLL_FAKE_START:v("preRoll");break;case c.PREROLL_ALIVE:v("preRoll");try{(x=C())&&
g.System.emit("gi.portal.feedback",{timeToPreroll:k.now()-x}),k.start("prerollDisplayDuration")}catch(f){}break;case c.MIDROLL_REQUESTED:t&&(n.backgroundScreen.style.cssText="background-image: url("+t+");",491<parseInt(n.displayGame.style.height,10)&&(b.style.height=n.displayGame.style.height),n.backgroundScreen.style.display="block",t=void 0);v("midrollLoading");try{A("onmidroll")}catch(d){}break;case c.MIDROLL_ALIVE:v("midRoll");try{k.start("midrollDisplayDuration"),x=C(),e.occurrence&&1===e.occurrence&&
x&&g.System.emit("gi.portal.feedback",{timeToFirstMidroll:k.now()-x})}catch(q){}break;case c.MIDROLL_FINISHED:"block"===n.backgroundScreen.style.display&&(n.backgroundScreen.style.background="#FFF",n.backgroundScreen.style.display="none");v("displayGame");try{A("aftermidroll");var m=k.stop("midrollDisplayDuration");m&&g.System.emit("gi.portal.feedback",{midrollDisplayDuration:m})}catch(G){}break;case c.GAME_EMBEDDED:"DomObject"===a.game.type&&E(),"iframe"===a.game.type&&D()}break;case "gi.error":c=
h.error;switch(e.data.code){case c.USER_DATA_MISSING:v("userDataMissing");break;case c.PLUGIN_MISSING:v("missingPlugin");break;case c.FEATURE_MISSING:v("missingFeature")}break;case "gi.warning":e.data.code===h.warning.USER_DATA_NOT_RESPONDING&&v("userDataNotResponding")}},!0))},onState:function(a,b,c){0<=p.indexOf(B,a)&&(e[a]||(e[a]=[]),e[a].push({callback:b,persistent:c}))}}});return p}(window,window.document)});/*
: 2013, SpilGames
*/
SpilGames("spilgames.import",{name:"GameEvents",deps:["Import"],module:function(){var c,f;c||(c=function(c){return{init:function(r,y){c.file(["/wdg/game-"+r+"/js/SWFtoJS.js"],function(){f=SWFtoJS.instance();y.call(this)})},on:function(c,p){if(f)if(p)f.addCallFunction(c,p);else throw"no callback function defined for game event: "+c;else throw"no game event handler defined";}}});return c}(window,document)});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,f=!1;c||(c=function(c,r,y,g,k){var s,u=function(c){var b;y.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(a){a&&a.auth&&a.auth.token?r("api.user.get",{cache:!0},function(e){b=e&&e.userInfo?{username:e.userInfo.name,hash:a.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:e&&e.error||"unknown error"};c.call(this,b)}):(b={isError:!0,
message:"Failed to retrieve the user hash",error:a&&a.error||"unknown error"},c.call(this,b))})},d=function(c){var b={};r("api.account.getApplicationToken",{cache:!0,applicationId:(s.portal.applicationId||s.portal.contentarId).toString()},function(a){try{if(!a.appAuth||a.isError)SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:a.error});else{var e=a.appAuth.token;b.appToken=e;k.updateCache(e,s.portal.sgid);
k.getUserInfo(function(a,e,g){a?c(b):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:g})})}}catch(g){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:g})}})};return{init:function(g){s=g;if(!f)switch(f=!0,c.init("game"),s.game.needs){case "preliminaryAuth":u(function(b){c.System.emit("gi.userdata.ready",{auth:b})});break;case "auth":k.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);d(function(b){var a={auth:b},e;a:{e=window;
e=e.location.href.slice(e.location.href.indexOf("?")+1).split("&");var g=e.length,f,k,d;for(d=0;d<g;d+=1)if(f=e[d].split("="),k=f[0],f=f[1],"src"===k){e=f;break a}e=null}e&&(a.other={src:e});b.isError&&(a.isError=!0,c.System.emit("gi.userdata.failure",b));c.System.emit("gi.userdata.ready",a)});break;default:c.System.emit("gi.userdata.ready",{})}}}});return c}()});SpilGames({name:"wdg_game",waiton:"game.info.loaded"},"SWP SWPUtils SWPEvent JSLib GIBootstrap DOMSelect Cache GameEvents SpapiIntegration".split(" "),function(c,f,p,r,y,g,k,s,u){c.init("game");var d=r.get("current.game.integration.info"),n=g.get("#preroll-container"),b=!1,a="true"===r.get("spilgames.portal.user.authenticated")?!0:!1,e=document.getElementById("theGame"),B=function(a,b){var c=parseInt(d.game.objectSettings.height,10),e=parseInt(d.game.objectSettings.width,10),c=Math.floor(c*a/100),
e=Math.floor(e*a/100),f=g.get("#theGame object");f&&(f.setAttribute("height",c.toString()+"px"),f.setAttribute("width",e.toString()+"px"));b.call(this,c,e,a)},q=function(a,b){var c=[];k.getItem({key:"recent.played.games"},function(e){if(e&&0<e.length){c=e;f.each(e,function(b){"string"===typeof b&&(c=[a])});e=h(c,a);var g=0<=e;g&&(c.splice(e,1),c.unshift(a));g||(c.unshift(a),6<c.length&&c.pop())}else c.push(a);k.setItem({key:"recent.played.games",value:c,expires:315569259},b)})},h=function(a,b){for(var c in a)if(a[c].gid===
b.gid)return c;return-1};c.Widget.init(function(c){switch(c.name){case "recent.played.games.update":if(!b){var e=c.data.appid+"";c=d&&d.game&&d.game.info?f.combine(d.game.info,{gid:e}):{gid:e};q(c,function(c){a&&r("api.gameplay.log",{applicationId:e});b=c})}}});d.game.spapiIntegration?(u.enable(d,c),SpilGames("api.auth.getApplicationToken",{applicationId:d.portal.applicationId},function(a){-1===d.game.objectSettings.url.indexOf("?")&&(d.game.objectSettings.url+="?");d.game.objectSettings.url+="appToken="+
a.appAuth.token;d.game.objectSettings.url+="&o="+location.protocol+"//"+location.hostname;y.launch(d)})):(r.messageBroker.addRule("api.portal.force.auth",function(a,b){c.System.init(function(a){"login.finished"!==a.name&&"registration.finished"!=a.name||r("api.user.get",{cache:!0},function(a){b({data:{state:a&&a.userInfo&&"guest"!==a.userInfo.name?"logged-in":"logged-out"}})})});c.System.emit("popup.login.open",{force:!0})},r.messageBroker.FIRST|r.messageBroker.PROTECTED),y.launch(d));p.listen("gi.show.panel",
function(){c.System.emit("game.sidepanel.show")});p.listen("gi.show.zoombar",function(){c.System.emit("game.zoom.show")});SpilGames.Events&&SpilGames.Events.subscribe("portal.forceauthentication",function(){c.System.emit("popup.login.open")});p.listen("gi.game.loaded",function(){/Firefox/.test(navigator.userAgent)&&d.game.detailedType&&d.game.detailedType.social&&window.setTimeout(function(){g.get("#theGame #iframegame").style.height=(parseInt(d.game.objectSettings.height)+120).toString()+"px"},1500);
c.Widget.emit("recent.played.games.update",{appid:d.portal.applicationId});SpilGames.Events&&SpilGames.Events.subscribe("invitefriends.request",function(){a?c.System.emit("popup.social_invite.open"):c.System.emit("popup.register.open")})});c.System.init(function(a){switch(a.name){case "game.zoom.in":B(a.body.size,function(a,b,e){c.System.emit("game.area.increase",{ratio:e,game:{height:a,width:b}})});break;case "game.zoom.out":B(a.body.size,function(a,b,e){c.System.emit("game.area.decrease",{ratio:e,
game:{height:a,width:b}})});break;case "ad.preroll.finish":n&&(n.style.height=0,n.style.overflow="hidden");break;case "gi.game.show":f.hasClass(e,"activeFeedbackScreen")||f.addClass(e,"activeFeedbackScreen");break;case "gi.game.hide":f.hasClass(e,"activeFeedbackScreen")&&f.removeClass(e,"activeFeedbackScreen")}});(d.game.achievements||d.game.highscores)&&s.init(d.portal.vsn,function(){a?(s.on("UPDATE_HIGHSCORE",function(a){c.System.emit("game.update.highscore",a)}),s.on("UPDATE_ACHIEVEMENT",function(a){c.System.emit("game.update.achievement",
a)}),s.on("UPDATE_GALLERY",function(a){c.System.emit("game.update.gallery",a)})):(s.on("UPDATE_HIGHSCORE_FAILED",function(a){c.System.emit("game.update.highscore.failed",a)}),s.on("UPDATE_ACHIEVEMENT_FAILED",function(a){c.System.emit("game.update.achievement.failed",a)}),s.on("UPDATE_GALLERY_FAILED",function(a){c.System.emit("game.update.gallery.failed",a)}))});r.subscribe("api.portal.overlay.*",function(){switch(this.event.cleanType){case "api.portal.overlay.show":f.hasClass(e,"activeFeedbackScreen")&&
f.removeClass(e,"activeFeedbackScreen");break;case "api.portal.overlay.hide":f.hasClass(e,"activeFeedbackScreen")||f.addClass(e,"activeFeedbackScreen")}});r.subscribe("api.event.auth.changed",function(){d.portal.applicationId&&r("api.auth.getApplicationToken",{applicationId:d.portal.applicationId},function(){})});SpilGames.Events&&SpilGames.Events.subscribe("portal.adjustheight",function(a){var b=document.getElementById("iframegame");a&&a.height&&b&&(b.style.height=a.height+"px")})});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIMonitor",deps:["SWP","GIController","JSLib","Net","Utils"],module:function(){var c,f=!1;if(!c)return c=function(c,r,y,g,k){var s=r.eventCodeMap,u={},d=function(b,a,c,f){"undefined"===typeof f&&(f=!0);k.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,c,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,c,!0]));var d=k.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),h=d?"ms":"c",d=d?c:1,n=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+n+"."+b+"."+a+"]="+d+h;u.monitoring&&u.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+n+"."+u.monitoring.bucket+"."+b+"."+a+"]="+d+h);0<d&&("c"===h?1===d:1)&&g.send({url:m,type:"GET"},k.emptyFn);y("tracker.event."+(f?"track":"express"),{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,eventValue:c})},n={error:function(b){var a=
s.error;b=b.data;switch(b.code){case a.USER_DATA_MISSING:d("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);d("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:d("error","missingBrowserFeature")}},warning:function(b){var a=s.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:d("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:d("warning","prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:d("warning",
"prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:d("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:d("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:d("warning","midrollTimeout",b.waited)}},update:function(b){var a=s.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&d("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&d("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:d("update","initialized")}}};
return{init:function(b){u=b;f||(f=!0,c.init("game"),b=window.publishingHost,void 0===b?d("update","publishingHostUndefined",b):"unknown"===b?d("update","publishingHostUnknown",b):d("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":n.error(a);break;case "gi.warning":n.warning(a);break;case "gi.update":n.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&d("update","timeToPlay",a.timeToPlay);a.displayGame&&d("update","displayGame",a.displayGame,!1);
a.prerollDisplayDuration&&d("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&d("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&d("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&d("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&d("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&d("update","progressBarStart",a.progressBarStart);a.progressBarDuration&&d("update","progressBarDuration",
a.progressBarDuration);a.progressBarError&&d("warning","progressBarError",a.progressBarError);a.loadDuration&&d("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":d("warning","decodeAuthCookieFailure");break;case "appToken":d("error","appToken");break;case "getCurrentUser":d("error","getCurrentUser")}}},!0))}}}}()});/*
 2013, Spil Games
*/
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,f){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",f)},updateCache:function(c,f){f&&_SG.Settings.set("auth.uid",f);SpilGames.Events.publish("auth.login",{hash:c,uid:f,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(f){c.call(this,!0,f,null)},onfailure:function(f){c.call(this,!1,null,f)}})}}}});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Jeroen Reurings <jeroen.reurings@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,f){var p,r=!1;p||(p=function(p,g,k,s,u,d,n){var b={},a,e={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,INITIALIZED:11,
MIDROLL_ALIVE:12,MIDROLL_REQUESTED:19,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},B={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},q,h,t=!1,m=function(){var a=[],b=[],c=function(b,c){a[b]||(a[b]=[]);return a[b].push(c)-1},e=function(a){var c=!1;b[a]&&(c=!0);return c},f=function(b,c){a[b]&&a[b][c]&&(a[b][c]=null)},d=function(){k.System.init(function(c){var e=c.name;b[e]=c;(e=a[e])&&g.each(e,function(a){"function"===
typeof a&&a(c)})},!0);d=function(){}};return{subscribe:c,unsubscribe:f,unsubscribeAll:function(b){delete a[b]},waiton:function(a,x){if(e(a))x(b[a]);else{var g=c(a,function(a){f("eventName",g);x(a)});return g}},isFired:e,init:d}}(),v=function(a){p(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var c=!1;if(0<b.major||0<b.minor||0<b.release)c=!0;a(c)})},F=function(){var a=!1,b=h.game.requiredFeatures;g.isObject(b)&&0<g.size(b)&&g.each(b,function(b){!0===b&&(a=!0)});return a},A=function(){var b=
a.states,c;v(function(e){c=b.PRE_FETCHING_GAME;g.isObject(h.portal)&&h.portal.siteId&&(1===h.portal.siteId||16===h.portal.siteId||88===h.portal.siteId)&&(c=b.LISTENING_TO_ADVERTISING);!1===e&&(c=b.PLUGIN_MISSING);a.transitionTo(c)})},C=function(){var b=a.states,c=b.LISTENING_TO_ADVERTISING,e;g.each(h.game.requiredFeatures,function(a,g){e=B[g];!0===a&&"function"===typeof n[e]&&!1===n[e]()&&(c=b.FEATURE_MISSING)});a.transitionTo(c)},w=function(){m.isFired("ad.preroll.finish")||p(["LightSWFObject"],
function(a){var b=h.game.preloader,c={data:b.src+"?url="+encodeURIComponent(h.game.settings.movie),width:"1",height:"1"};p.subscribe("game.prefetcher.error",function(a){k.System.emit("gi.warning",{code:e.warning.PRE_FETCH_ERROR,flashError:a})});a.createSWF(c,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},b.domId);t=!0});a.transitionTo(a.states.LISTENING_TO_ADVERTISING)},D=function(){var b=m.isFired("ad.preroll.heartbeat"),g=
m.isFired("ad.preroll.start"),l=h.preroll.heartbeatTime,f=function(){k.System.emit("gi.update",{code:e.update.PREROLL_ALIVE,fetchTime:u.stop("prerollFetchTime")})},d=function(){k.System.emit("gi.update",{code:e.update.PREROLL_FAKE_START})};!0===b&&f();!0===g&&d();u.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){d()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(q);b||(b=!0,f());q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.PREROLL_NO_HEARTBEAT,
waited:l});a.transitionTo(a.states.WAITING_ON_USERDATA)},l)});m.waiton("ad.preroll.finish",function(){q&&c.clearTimeout(q);a.transitionTo(a.states.WAITING_ON_USERDATA)});a.transitionTo(a.states.WAITING_ON_PRE_ROLL)},E=function(){var a=0,b=h.midroll.heartbeatTime,l=h.midroll.maxWaitingTime,g=!1,f=function(){c.clearTimeout(q);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");k.System.emit("gi.update",{code:e.update.MIDROLL_FINISHED,occurrence:a});k.System.emit("gi.update",
{code:e.update.ABORT_MIDROLL});g=!1};m.subscribe("ad.midroll.start",function(){if(!g){var d=!1;g=!0;a+=1;u.start("midrollFetchTime");q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.MIDROLL_TIMEOUT,waited:l,occurrence:a});f()},l);k.System.emit("gi.update",{code:e.update.MIDROLL_REQUESTED,occurrence:a});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(q);d||(d=!0,k.System.emit("gi.update",{code:e.update.MIDROLL_ALIVE,fetchTime:u.stop("midrollFetchTime"),occurrence:a}));
q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.MIDROLL_NO_HEARTBEAT,waited:b,occurrence:a});f()},b)});m.subscribe("ad.midroll.finish",function(){f()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var b=h.preroll.maxWaitingTime;q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.PREROLL_TIMEOUT,waited:b});a.transitionTo(a.states.WAITING_ON_USERDATA)},b)}},H=function(){c.clearTimeout(q);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");
m.unsubscribeAll("ad.preroll.finish");var g=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||k.System.emit("gi.update",{code:e.update.ABORT_PREROLL});k.System.emit("gi.update",{code:e.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(e){var l=a.states,f=l.INTEGRATING_GAME;g&&c.clearTimeout(g);!e.data||e.data.isError?f=l.INTEGRATION_ERROR:b=e.data;a.transitionTo(f)})},I=function(){var f=a.states.GAME_INTEGRATED,
d=b.auth,l=h.game.settings,q=h.game.preloader,n;if(d&&g.isObject(d)&&!d.isError)for(n in d)d.hasOwnProperty(n)&&(l.flashvars+="&"+n+"="+d[n]);h&&h.portal&&h.portal.appToken&&(l.flashvars+="&appToken="+h.portal.appToken);p(["LightSWFObject"],function(b){var g={data:l.movie,width:l.width,height:l.height},d={base:l.base,quality:"autohigh",allowFullScreen:l.allowFullScreen,wmode:l.wmode,allowScriptAccess:l.allowScriptAccess,scale:l.scale,flashVars:l.flashvars,bgcolor:l.bgcolor,hasPriority:"true"},z=function(){b.createSWF(g,
d,l.domId);k.System.emit("gi.update",{code:e.update.GAME_EMBEDDED});a.transitionTo(f)};t?(t=!1,b.removeSWF(q.domId),c.setTimeout(function(){z()},20)):z()})};a={states:{INITIALIZED:0,PLUGIN_DETECTION:1,FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(b){k.Widget.emit(a.eventNamespace,
{state:b})},flowController:function(c){var d=a.states;switch(c.data.state){case d.INITIALIZED:var l=a.states;c=l.LISTENING_TO_ADVERTISING;var d=!1,q,n,m;h&&(q=h.game,n=h.preroll,m=h.midroll);g.isObject(h)&&g.isObject(q)&&g.isObject(n)&&g.isObject(m)&&g.isString(q.type)&&(g.contains(q.type,"DomObject")||g.contains(q.type,"iframe"))&&g.isNumber(n.maxWaitingTime)&&g.isNumber(m.maxWaitingTime)&&g.isNumber(n.heartbeatTime)&&g.isNumber(m.heartbeatTime)&&(d=!0);if(!d)throw l={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},
SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",eventLabel:"GameIntegration module, exception:"+l.type+" - "+l.message,eventValue:1}),l;"DomObject"===h.game.type?c=l.PLUGIN_DETECTION:F()&&(c=l.FEATURE_DETECTION);a.transitionTo(c);break;case d.PLUGIN_DETECTION:A();break;case d.FEATURE_DETECTION:C();break;case d.PRE_FETCHING_GAME:w();break;case d.PLUGIN_MISSING:k.System.emit("gi.error",{code:e.error.PLUGIN_MISSING,pluginName:"flash"});k.System.emit("gi.update",
{code:e.update.ABORT_PREROLL});break;case d.FEATURE_MISSING:k.System.emit("gi.error",{code:e.error.FEATURE_MISSING});k.System.emit("gi.update",{code:e.update.ABORT_PREROLL});break;case d.LISTENING_TO_ADVERTISING:D();break;case d.WAITING_ON_PRE_ROLL:G();break;case d.WAITING_ON_USERDATA:H();break;case d.INTEGRATING_GAME:"DomObject"===h.game.type&&I();if("iframe"===h.game.type){q=a.states.GAME_INTEGRATED;d=h.game.settings;n=f.getElementById(d.domId);m={};g.isObject(b.auth)&&(m=g.combine(b.auth,m));g.isObject(h.portal)&&
h.portal.siteId&&h.portal.channelId&&(m=g.combine({siteid:h.portal.siteId,channelid:h.portal.channelId,UID:h.portal.sgid||""},m),m=h.portal.authenticated&&!0===h.portal.authenticated?g.combine({hash:h.portal.appToken||"",username:h.portal.username||""},m):g.combine({hash:"",username:""},m));g.isObject(b.other)&&(m=g.combine(b.other,m));n.width=d.width;n.height=d.height;c=m;var p,u,t;m="";d=d.url.replace("###DOMAIN###",window.location.hostname);d=d.replace("###CACHE_PP###","");t=document.createElement("a");
var r;t.href=d;r="/"===t.pathname.charAt(0)?t.pathname:"/"+t.pathname;p=t.protocol;d=t.search;u=t.hash;t=t.host;for(l in c)c.hasOwnProperty(l)&&(m+="&"+l+"="+c[l]);l=p+"//"+t+r||"";l=0<d.length?l+encodeURI(d+m):l+("?"+encodeURI(m.substring(1)));n.src=l+(u||"");k.System.emit("gi.update",{code:e.update.GAME_EMBEDDED});a.transitionTo(q)}break;case d.INTEGRATION_ERROR:k.System.emit("gi.error",{code:e.error.USER_DATA_MISSING});break;case d.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),
s.emit("gi.game.loaded")}},start:function(){k.Widget.init(a.flowController)}};return{init:function(b){h=b;h.game.objectSettings&&(h.game.settings=h.game.objectSettings);if(r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;k.init("game");m.init();a.start();k.System.emit("gi.update",{code:e.update.INITIALIZED});a.transitionTo(a.states.INITIALIZED)},eventCodeMap:e}});return p}(window,document)});/*
: 2013, SpilGames
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;c||(c=function(c,p,r,y,g,k){return{launch:function(c){r.init(c);y.init(c);var f=c.hooks;if(p.isFunction(f.onPrerollFinish))g.onState("afterpreroll",function(){f.onPrerollFinish()});if(p.isFunction(f.onDisplayGame))g.onState("displaygame",function(){f.onDisplayGame()});if(p.isFunction(f.onMidroll))g.onState("onmidroll",function(){f.onMidroll()},!0);if(p.isFunction(f.afterMidroll))g.onState("aftermidroll",
function(){f.afterMidroll()},!0);g.init(c);k.init(c)}}});return c}(window,document)});SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,f){var p,r=!1;p||(p=function(p,g,k,s,u,d){var n={backgroundScreen:f.getElementById("backgroundScreen"),defaultScreen:f.getElementById("defaultLoadingScreen"),waitingForUserData:f.getElementById("waitingForUserData"),userDataNotResponding:f.getElementById("userDataNotResponding"),userDataMissing:f.getElementById("userDataMissing"),loadingDomObjectGame:f.getElementById("loadingDomObjectGame"),
loadingIframeGame:f.getElementById("loadingIframeGame"),errorLoadingGame:f.getElementById("errorLoadingGame"),missingPlugin:f.getElementById("missingPlugin"),missingFeature:f.getElementById("missingFeature"),displayGame:f.getElementById("theGame"),preRoll:f.getElementById("videoPreroll300x250"),midRoll:f.getElementById("sgAdOgGp300x250"),midrollLoading:f.getElementById("midrollLoadingScreen")},b=f.getElementById("game-integration"),a={},e=[],B=["displaygame","afterpreroll","onmidroll","aftermidroll"],
q=n.defaultScreen,h={},t,m=!1,v=function(a){q.className=q.className.replace("activeFeedbackScreen","");q=n[a];q.className+=" activeFeedbackScreen"},F=function(){u.subscribe("game.ad.accepted",function(a){p.isObject(a)&&!0===a.displayAd&&p.isString(a.bgImage)&&!p.isEmpty(a.bgImage)&&(t=a.bgImage)})},A=function(a){var b=e[a];b&&p.each(b,function(a,e){a.persistent&&!0===a.persistent||delete b[e];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),w=function(){if(!m){m=!0;v("displayGame");A("displaygame");try{F();g.System.emit("gi.portal.feedback",{displayGame:a.portal.contentarId});var b=C();b&&g.System.emit("gi.portal.feedback",{timeToPlay:k.now()-b});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),g.System.emit("gi.portal.feedback",
{timeToFirstPlay:k.now()-a.sessionStart}))})}catch(c){}}},D=function(){var b=f.getElementById(a.game.settings.domId),c=f.getElementById("progress-container"),e,d=function(){try{(e=k.stop("iframeLoadDuration"))&&g.System.emit("gi.portal.feedback",{loadDuration:e})}catch(a){}w()};k.start("iframeLoadDuration");b.completed?w():(c&&(c.style.display="none"),v("loadingIframeGame"),b.attachEvent?b.attachEvent("onload",function(){d()}):b.onload=function(){d()})},E=function(){var b=f.getElementById(a.game.settings.domId),
e=f.getElementById("progress-bar"),d=f.getElementById("progress-percentage"),x,h,l,q,n=0,m=function(){return b&&"function"===typeof b.PercentLoaded||c.attachEvent&&"number"===typeof b.PercentLoaded()},p=function(){l=b.PercentLoaded();if(98<l||0>l)w();else{v("loadingDomObjectGame");e.width=l+"%";d&&(d.innerHTML=l+"%");try{k.start("progressBarDuration"),g.System.emit("gi.portal.feedback",{progressBarStart:l})}catch(a){}x=c.setInterval(function(){l=m()?b.PercentLoaded():void 0;if("undefined"!==typeof l&&
-1<l&&100>l)d&&(d.innerHTML=l+"%"),e.style.width=l+"%";else{c.clearInterval(x);d&&(d.innerHTML="100%");e.style.width="99%";c.setTimeout(function(){w()},500);try{(h=k.stop("progressBarDuration"))&&g.System.emit("gi.portal.feedback",{progressBarDuration:h+500})}catch(a){}}},100)}};try{q=c.setInterval(function(){n+=1;m()&&(c.clearInterval(q),p());10<=n&&(c.clearInterval(q),w(),g.System.emit("gi.portal.feedback",{progressBarError:a.portal.contentarId}))},100)}catch(s){w(),g.System.emit("gi.portal.feedback",
{progressBarError:a.portal.contentarId})}};return{init:function(c){r||(r=!0,a=c,h=d.eventCodeMap,g.init("game"),g.System.init(function(c){switch(c.name){case "gi.update":var e=h.update;c=c.data;var d;switch(c.code){case e.WAITING_FOR_USER_DATA:v("waitingForUserData");try{var f=k.stop("prerollDisplayDuration");f&&g.System.emit("gi.portal.feedback",{prerollDisplayDuration:f})}catch(l){}A("afterpreroll");break;case e.PREROLL_FAKE_START:v("preRoll");break;case e.PREROLL_ALIVE:v("preRoll");try{(d=C())&&
g.System.emit("gi.portal.feedback",{timeToPreroll:k.now()-d}),k.start("prerollDisplayDuration")}catch(q){}break;case e.MIDROLL_REQUESTED:t&&(n.backgroundScreen.style.cssText="background-image: url("+t+");",491<parseInt(n.displayGame.style.height,10)&&(b.style.height=n.displayGame.style.height),n.backgroundScreen.style.display="block",t=void 0);v("midrollLoading");try{A("onmidroll")}catch(m){}break;case e.MIDROLL_ALIVE:v("midRoll");try{k.start("midrollDisplayDuration"),d=C(),c.occurrence&&1===c.occurrence&&
d&&g.System.emit("gi.portal.feedback",{timeToFirstMidroll:k.now()-d})}catch(p){}break;case e.MIDROLL_FINISHED:"block"===n.backgroundScreen.style.display&&(n.backgroundScreen.style.background="#FFF",n.backgroundScreen.style.display="none");v("displayGame");try{A("aftermidroll");var s=k.stop("midrollDisplayDuration");s&&g.System.emit("gi.portal.feedback",{midrollDisplayDuration:s})}catch(G){}break;case e.GAME_EMBEDDED:"DomObject"===a.game.type&&E(),"iframe"===a.game.type&&D()}break;case "gi.error":e=
h.error;switch(c.data.code){case e.USER_DATA_MISSING:v("userDataMissing");break;case e.PLUGIN_MISSING:v("missingPlugin");break;case e.FEATURE_MISSING:v("missingFeature")}break;case "gi.warning":c.data.code===h.warning.USER_DATA_NOT_RESPONDING&&v("userDataNotResponding")}},!0))},onState:function(a,b,c){0<=p.indexOf(B,a)&&(e[a]||(e[a]=[]),e[a].push({callback:b,persistent:c}))}}});return p}(window,window.document)});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,f=!1;c||(c=function(c,r,y,g,k){var s,u=function(c){var b;y.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(a){a&&a.auth&&a.auth.token?r("api.user.get",{cache:!0},function(e){b=e&&e.userInfo?{username:e.userInfo.name,hash:a.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:e&&e.error||"unknown error"};c.call(this,b)}):(b={isError:!0,
message:"Failed to retrieve the user hash",error:a&&a.error||"unknown error"},c.call(this,b))})},d=function(c){var b={};r("api.account.getApplicationToken",{cache:!0,applicationId:(s.portal.applicationId||s.portal.contentarId).toString()},function(a){try{if(!a.appAuth||a.isError)SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:a.error});else{var e=a.appAuth.token;b.appToken=e;k.updateCache(e,s.portal.sgid);
k.getUserInfo(function(a,e,d){a?c(b):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:d})})}}catch(d){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:d})}})};return{init:function(g){s=g;if(!f)switch(f=!0,c.init("game"),s.game.needs){case "preliminaryAuth":u(function(b){c.System.emit("gi.userdata.ready",{auth:b})});break;case "auth":k.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);d(function(b){var a={auth:b},e;a:{e=window;
e=e.location.href.slice(e.location.href.indexOf("?")+1).split("&");var d=e.length,g,f,k;for(k=0;k<d;k+=1)if(g=e[k].split("="),f=g[0],g=g[1],"src"===f){e=g;break a}e=null}e&&(a.other={src:e});b.isError&&(a.isError=!0,c.System.emit("gi.userdata.failure",b));c.System.emit("gi.userdata.ready",a)});break;default:c.System.emit("gi.userdata.ready",{})}}}});return c}()});/*
: 2013, SpilGames
 @author Laurens van Hees <performance@spilgames.com>
 2013, Spil Games
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Jeroen Reurings <jeroen.reurings@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;c||(c=function(c,p,r,y,g,k){return{launch:function(c){r.init(c);y.init(c);var f=c.hooks;if(p.isFunction(f.onPrerollFinish))g.onState("afterpreroll",function(){f.onPrerollFinish()});if(p.isFunction(f.onDisplayGame))g.onState("displaygame",function(){f.onDisplayGame()});if(p.isFunction(f.onMidroll))g.onState("onmidroll",function(){f.onMidroll()},!0);if(p.isFunction(f.afterMidroll))g.onState("aftermidroll",
function(){f.afterMidroll()},!0);g.init(c);k.init(c)}}});return c}(window,document)});
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,f){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",f)},updateCache:function(c,f){f&&_SG.Settings.set("auth.uid",f);SpilGames.Events.publish("auth.login",{hash:c,uid:f,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(f){c.call(this,!0,f,null)},onfailure:function(f){c.call(this,!1,null,f)}})}}}});
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,f){var p,r=!1;p||(p=function(p,g,k,s,u,d,n){var b={},a,e={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,INITIALIZED:11,
MIDROLL_ALIVE:12,MIDROLL_REQUESTED:19,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},B={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},q,h,t=!1,m=function(){var a=[],b=[],c=function(b,c){a[b]||(a[b]=[]);return a[b].push(c)-1},e=function(a){var c=!1;b[a]&&(c=!0);return c},d=function(b,c){a[b]&&a[b][c]&&(a[b][c]=null)},f=function(){k.System.init(function(c){var e=c.name;b[e]=c;(e=a[e])&&g.each(e,function(a){"function"===
typeof a&&a(c)})},!0);f=function(){}};return{subscribe:c,unsubscribe:d,unsubscribeAll:function(b){delete a[b]},waiton:function(a,f){if(e(a))f(b[a]);else{var g=c(a,function(a){d("eventName",g);f(a)});return g}},isFired:e,init:f}}(),v=function(a){p(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var c=!1;if(0<b.major||0<b.minor||0<b.release)c=!0;a(c)})},F=function(){var a=!1,b=h.game.requiredFeatures;g.isObject(b)&&0<g.size(b)&&g.each(b,function(b){!0===b&&(a=!0)});return a},A=function(){var b=
a.states,c;v(function(e){c=b.PRE_FETCHING_GAME;g.isObject(h.portal)&&h.portal.siteId&&(1===h.portal.siteId||16===h.portal.siteId||88===h.portal.siteId)&&(c=b.LISTENING_TO_ADVERTISING);!1===e&&(c=b.PLUGIN_MISSING);a.transitionTo(c)})},C=function(){var b=a.states,c=b.LISTENING_TO_ADVERTISING,e;g.each(h.game.requiredFeatures,function(a,d){e=B[d];!0===a&&"function"===typeof n[e]&&!1===n[e]()&&(c=b.FEATURE_MISSING)});a.transitionTo(c)},w=function(){m.isFired("ad.preroll.finish")||p(["LightSWFObject"],
function(a){var b=h.game.preloader,c={data:b.src+"?url="+encodeURIComponent(h.game.settings.movie),width:"1",height:"1"};p.subscribe("game.prefetcher.error",function(a){k.System.emit("gi.warning",{code:e.warning.PRE_FETCH_ERROR,flashError:a})});a.createSWF(c,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},b.domId);t=!0});a.transitionTo(a.states.LISTENING_TO_ADVERTISING)},D=function(){var b=m.isFired("ad.preroll.heartbeat"),d=
m.isFired("ad.preroll.start"),f=h.preroll.heartbeatTime,g=function(){k.System.emit("gi.update",{code:e.update.PREROLL_ALIVE,fetchTime:u.stop("prerollFetchTime")})},n=function(){k.System.emit("gi.update",{code:e.update.PREROLL_FAKE_START})};!0===b&&g();!0===d&&n();u.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){n()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(q);b||(b=!0,g());q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.PREROLL_NO_HEARTBEAT,
waited:f});a.transitionTo(a.states.WAITING_ON_USERDATA)},f)});m.waiton("ad.preroll.finish",function(){q&&c.clearTimeout(q);a.transitionTo(a.states.WAITING_ON_USERDATA)});a.transitionTo(a.states.WAITING_ON_PRE_ROLL)},E=function(){var a=0,b=h.midroll.heartbeatTime,d=h.midroll.maxWaitingTime,f=!1,g=function(){c.clearTimeout(q);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");k.System.emit("gi.update",{code:e.update.MIDROLL_FINISHED,occurrence:a});k.System.emit("gi.update",
{code:e.update.ABORT_MIDROLL});f=!1};m.subscribe("ad.midroll.start",function(){if(!f){var h=!1;f=!0;a+=1;u.start("midrollFetchTime");q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.MIDROLL_TIMEOUT,waited:d,occurrence:a});g()},d);k.System.emit("gi.update",{code:e.update.MIDROLL_REQUESTED,occurrence:a});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(q);h||(h=!0,k.System.emit("gi.update",{code:e.update.MIDROLL_ALIVE,fetchTime:u.stop("midrollFetchTime"),occurrence:a}));
q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.MIDROLL_NO_HEARTBEAT,waited:b,occurrence:a});g()},b)});m.subscribe("ad.midroll.finish",function(){g()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var b=h.preroll.maxWaitingTime;q=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.PREROLL_TIMEOUT,waited:b});a.transitionTo(a.states.WAITING_ON_USERDATA)},b)}},H=function(){c.clearTimeout(q);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");
m.unsubscribeAll("ad.preroll.finish");var d=c.setTimeout(function(){k.System.emit("gi.warning",{code:e.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||k.System.emit("gi.update",{code:e.update.ABORT_PREROLL});k.System.emit("gi.update",{code:e.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(e){var f=a.states,g=f.INTEGRATING_GAME;d&&c.clearTimeout(d);!e.data||e.data.isError?g=f.INTEGRATION_ERROR:b=e.data;a.transitionTo(g)})},I=function(){var d=a.states.GAME_INTEGRATED,
f=b.auth,l=h.game.settings,q=h.game.preloader,m;if(f&&g.isObject(f)&&!f.isError)for(m in f)f.hasOwnProperty(m)&&(l.flashvars+="&"+m+"="+f[m]);h&&h.portal&&h.portal.appToken&&(l.flashvars+="&appToken="+h.portal.appToken);p(["LightSWFObject"],function(b){var f={data:l.movie,width:l.width,height:l.height},g={base:l.base,quality:"autohigh",allowFullScreen:l.allowFullScreen,wmode:l.wmode,allowScriptAccess:l.allowScriptAccess,scale:l.scale,flashVars:l.flashvars,bgcolor:l.bgcolor,hasPriority:"true"},h=function(){b.createSWF(f,
g,l.domId);k.System.emit("gi.update",{code:e.update.GAME_EMBEDDED});a.transitionTo(d)};t?(t=!1,b.removeSWF(q.domId),c.setTimeout(function(){h()},20)):h()})};a={states:{INITIALIZED:0,PLUGIN_DETECTION:1,FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(b){k.Widget.emit(a.eventNamespace,
{state:b})},flowController:function(c){var d=a.states;switch(c.data.state){case d.INITIALIZED:var l=a.states;c=l.LISTENING_TO_ADVERTISING;var d=!1,m,q,n;h&&(m=h.game,q=h.preroll,n=h.midroll);g.isObject(h)&&g.isObject(m)&&g.isObject(q)&&g.isObject(n)&&g.isString(m.type)&&(g.contains(m.type,"DomObject")||g.contains(m.type,"iframe"))&&g.isNumber(q.maxWaitingTime)&&g.isNumber(n.maxWaitingTime)&&g.isNumber(q.heartbeatTime)&&g.isNumber(n.heartbeatTime)&&(d=!0);if(!d)throw l={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},
SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",eventLabel:"GameIntegration module, exception:"+l.type+" - "+l.message,eventValue:1}),l;"DomObject"===h.game.type?c=l.PLUGIN_DETECTION:F()&&(c=l.FEATURE_DETECTION);a.transitionTo(c);break;case d.PLUGIN_DETECTION:A();break;case d.FEATURE_DETECTION:C();break;case d.PRE_FETCHING_GAME:w();break;case d.PLUGIN_MISSING:k.System.emit("gi.error",{code:e.error.PLUGIN_MISSING,pluginName:"flash"});k.System.emit("gi.update",
{code:e.update.ABORT_PREROLL});break;case d.FEATURE_MISSING:k.System.emit("gi.error",{code:e.error.FEATURE_MISSING});k.System.emit("gi.update",{code:e.update.ABORT_PREROLL});break;case d.LISTENING_TO_ADVERTISING:D();break;case d.WAITING_ON_PRE_ROLL:G();break;case d.WAITING_ON_USERDATA:H();break;case d.INTEGRATING_GAME:"DomObject"===h.game.type&&I();if("iframe"===h.game.type){m=a.states.GAME_INTEGRATED;d=h.game.settings;q=f.getElementById(d.domId);n={};g.isObject(b.auth)&&(n=g.combine(b.auth,n));g.isObject(h.portal)&&
h.portal.siteId&&h.portal.channelId&&(n=g.combine({siteid:h.portal.siteId,channelid:h.portal.channelId,UID:h.portal.sgid||""},n),n=h.portal.authenticated&&!0===h.portal.authenticated?g.combine({hash:h.portal.appToken||"",username:h.portal.username||""},n):g.combine({hash:"",username:""},n));g.isObject(b.other)&&(n=g.combine(b.other,n));q.width=d.width;q.height=d.height;c=n;var p,t,r;n="";d=d.url.replace("###DOMAIN###",window.location.hostname);d=d.replace("###CACHE_PP###","");r=document.createElement("a");
var u;r.href=d;u="/"===r.pathname.charAt(0)?r.pathname:"/"+r.pathname;p=r.protocol;d=r.search;t=r.hash;r=r.host;for(l in c)c.hasOwnProperty(l)&&(n+="&"+l+"="+c[l]);l=p+"//"+r+u||"";l=0<d.length?l+encodeURI(d+n):l+("?"+encodeURI(n.substring(1)));q.src=l+(t||"");k.System.emit("gi.update",{code:e.update.GAME_EMBEDDED});a.transitionTo(m)}break;case d.INTEGRATION_ERROR:k.System.emit("gi.error",{code:e.error.USER_DATA_MISSING});break;case d.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),
s.emit("gi.game.loaded")}},start:function(){k.Widget.init(a.flowController)}};return{init:function(b){h=b;h.game.objectSettings&&(h.game.settings=h.game.objectSettings);if(r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;k.init("game");m.init();a.start();k.System.emit("gi.update",{code:e.update.INITIALIZED});a.transitionTo(a.states.INITIALIZED)},eventCodeMap:e}});return p}(window,document)});
SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,f){var p,r=!1;p||(p=function(p,g,k,s,u,d){var n={backgroundScreen:f.getElementById("backgroundScreen"),defaultScreen:f.getElementById("defaultLoadingScreen"),waitingForUserData:f.getElementById("waitingForUserData"),userDataNotResponding:f.getElementById("userDataNotResponding"),userDataMissing:f.getElementById("userDataMissing"),loadingDomObjectGame:f.getElementById("loadingDomObjectGame"),
loadingIframeGame:f.getElementById("loadingIframeGame"),errorLoadingGame:f.getElementById("errorLoadingGame"),missingPlugin:f.getElementById("missingPlugin"),missingFeature:f.getElementById("missingFeature"),displayGame:f.getElementById("theGame"),preRoll:f.getElementById("videoPreroll300x250"),midRoll:f.getElementById("sgAdOgGp300x250"),midrollLoading:f.getElementById("midrollLoadingScreen")},b=f.getElementById("game-integration"),a={},e=[],B=["displaygame","afterpreroll","onmidroll","aftermidroll"],
q=n.defaultScreen,h={},t,m=!1,v=function(a){q.className=q.className.replace("activeFeedbackScreen","");q=n[a];q.className+=" activeFeedbackScreen"},F=function(){u.subscribe("game.ad.accepted",function(a){p.isObject(a)&&!0===a.displayAd&&p.isString(a.bgImage)&&!p.isEmpty(a.bgImage)&&(t=a.bgImage)})},A=function(a){var b=e[a];b&&p.each(b,function(a,e){a.persistent&&!0===a.persistent||delete b[e];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),w=function(){if(!m){m=!0;v("displayGame");A("displaygame");try{F();g.System.emit("gi.portal.feedback",{displayGame:a.portal.contentarId});var b=C();b&&g.System.emit("gi.portal.feedback",{timeToPlay:k.now()-b});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),g.System.emit("gi.portal.feedback",
{timeToFirstPlay:k.now()-a.sessionStart}))})}catch(c){}}},D=function(){var b=f.getElementById(a.game.settings.domId),c=f.getElementById("progress-container"),e,d=function(){try{(e=k.stop("iframeLoadDuration"))&&g.System.emit("gi.portal.feedback",{loadDuration:e})}catch(a){}w()};k.start("iframeLoadDuration");b.completed?w():(c&&(c.style.display="none"),v("loadingIframeGame"),b.attachEvent?b.attachEvent("onload",function(){d()}):b.onload=function(){d()})},E=function(){var b=f.getElementById(a.game.settings.domId),
e=f.getElementById("progress-bar"),d=f.getElementById("progress-percentage"),h,n,l,m,q=0,p=function(){return b&&"function"===typeof b.PercentLoaded||c.attachEvent&&"number"===typeof b.PercentLoaded()},s=function(){l=b.PercentLoaded();if(98<l||0>l)w();else{v("loadingDomObjectGame");e.width=l+"%";d&&(d.innerHTML=l+"%");try{k.start("progressBarDuration"),g.System.emit("gi.portal.feedback",{progressBarStart:l})}catch(a){}h=c.setInterval(function(){l=p()?b.PercentLoaded():void 0;if("undefined"!==typeof l&&
-1<l&&100>l)d&&(d.innerHTML=l+"%"),e.style.width=l+"%";else{c.clearInterval(h);d&&(d.innerHTML="100%");e.style.width="99%";c.setTimeout(function(){w()},500);try{(n=k.stop("progressBarDuration"))&&g.System.emit("gi.portal.feedback",{progressBarDuration:n+500})}catch(a){}}},100)}};try{m=c.setInterval(function(){q+=1;p()&&(c.clearInterval(m),s());10<=q&&(c.clearInterval(m),w(),g.System.emit("gi.portal.feedback",{progressBarError:a.portal.contentarId}))},100)}catch(r){w(),g.System.emit("gi.portal.feedback",
{progressBarError:a.portal.contentarId})}};return{init:function(c){r||(r=!0,a=c,h=d.eventCodeMap,g.init("game"),g.System.init(function(c){switch(c.name){case "gi.update":var e=h.update;c=c.data;var d;switch(c.code){case e.WAITING_FOR_USER_DATA:v("waitingForUserData");try{var f=k.stop("prerollDisplayDuration");f&&g.System.emit("gi.portal.feedback",{prerollDisplayDuration:f})}catch(l){}A("afterpreroll");break;case e.PREROLL_FAKE_START:v("preRoll");break;case e.PREROLL_ALIVE:v("preRoll");try{(d=C())&&
g.System.emit("gi.portal.feedback",{timeToPreroll:k.now()-d}),k.start("prerollDisplayDuration")}catch(m){}break;case e.MIDROLL_REQUESTED:t&&(n.backgroundScreen.style.cssText="background-image: url("+t+");",491<parseInt(n.displayGame.style.height,10)&&(b.style.height=n.displayGame.style.height),n.backgroundScreen.style.display="block",t=void 0);v("midrollLoading");try{A("onmidroll")}catch(q){}break;case e.MIDROLL_ALIVE:v("midRoll");try{k.start("midrollDisplayDuration"),d=C(),c.occurrence&&1===c.occurrence&&
d&&g.System.emit("gi.portal.feedback",{timeToFirstMidroll:k.now()-d})}catch(p){}break;case e.MIDROLL_FINISHED:"block"===n.backgroundScreen.style.display&&(n.backgroundScreen.style.background="#FFF",n.backgroundScreen.style.display="none");v("displayGame");try{A("aftermidroll");var s=k.stop("midrollDisplayDuration");s&&g.System.emit("gi.portal.feedback",{midrollDisplayDuration:s})}catch(r){}break;case e.GAME_EMBEDDED:"DomObject"===a.game.type&&E(),"iframe"===a.game.type&&D()}break;case "gi.error":e=
h.error;switch(c.data.code){case e.USER_DATA_MISSING:v("userDataMissing");break;case e.PLUGIN_MISSING:v("missingPlugin");break;case e.FEATURE_MISSING:v("missingFeature")}break;case "gi.warning":c.data.code===h.warning.USER_DATA_NOT_RESPONDING&&v("userDataNotResponding")}},!0))},onState:function(a,b,c){0<=p.indexOf(B,a)&&(e[a]||(e[a]=[]),e[a].push({callback:b,persistent:c}))}}});return p}(window,window.document)});
SpilGames("spilgames.import",{name:"GIMonitor",deps:["SWP","GIController","JSLib","Net","Utils"],module:function(){var c,f=!1;if(!c)return c=function(c,r,y,g,k){var s=r.eventCodeMap,u={},d=function(b,a,c,d){"undefined"===typeof d&&(d=!0);k.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,c,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,c,!0]));var f=k.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),h=f?"ms":"c",f=f?c:1,n=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+n+"."+b+"."+a+"]="+f+h;u.monitoring&&u.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+n+"."+u.monitoring.bucket+"."+b+"."+a+"]="+f+h);0<f&&("c"===h?1===f:1)&&g.send({url:m,type:"GET"},k.emptyFn);y("tracker.event."+(d?"track":"express"),{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,eventValue:c})},n={error:function(b){var a=
s.error;b=b.data;switch(b.code){case a.USER_DATA_MISSING:d("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);d("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:d("error","missingBrowserFeature")}},warning:function(b){var a=s.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:d("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:d("warning","prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:d("warning",
"prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:d("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:d("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:d("warning","midrollTimeout",b.waited)}},update:function(b){var a=s.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&d("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&d("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:d("update","initialized")}}};
return{init:function(b){u=b;f||(f=!0,c.init("game"),b=window.publishingHost,void 0===b?d("update","publishingHostUndefined",b):"unknown"===b?d("update","publishingHostUnknown",b):d("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":n.error(a);break;case "gi.warning":n.warning(a);break;case "gi.update":n.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&d("update","timeToPlay",a.timeToPlay);a.displayGame&&d("update","displayGame",a.displayGame,!1);
a.prerollDisplayDuration&&d("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&d("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&d("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&d("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&d("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&d("update","progressBarStart",a.progressBarStart);a.progressBarDuration&&d("update","progressBarDuration",
a.progressBarDuration);a.progressBarError&&d("warning","progressBarError",a.progressBarError);a.loadDuration&&d("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":d("warning","decodeAuthCookieFailure");break;case "appToken":d("error","appToken");break;case "getCurrentUser":d("error","getCurrentUser")}}},!0))}}}}()});
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,f=!1;c||(c=function(c,r,y,g,k){var s,u=function(c){var b;y.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(a){a&&a.auth&&a.auth.token?r("api.user.get",{cache:!0},function(e){b=e&&e.userInfo?{username:e.userInfo.name,hash:a.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:e&&e.error||"unknown error"};c.call(this,b)}):(b={isError:!0,
message:"Failed to retrieve the user hash",error:a&&a.error||"unknown error"},c.call(this,b))})},d=function(c){var b={};r("api.account.getApplicationToken",{cache:!0,applicationId:(s.portal.applicationId||s.portal.contentarId).toString()},function(a){try{if(!a.appAuth||a.isError)SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:a.error});else{var e=a.appAuth.token;b.appToken=e;k.updateCache(e,s.portal.sgid);
k.getUserInfo(function(a,e,d){a?c(b):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:d})})}}catch(d){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:d})}})};return{init:function(g){s=g;if(!f)switch(f=!0,c.init("game"),s.game.needs){case "preliminaryAuth":u(function(b){c.System.emit("gi.userdata.ready",{auth:b})});break;case "auth":k.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);d(function(b){var a={auth:b},e;a:{e=window;
e=e.location.href.slice(e.location.href.indexOf("?")+1).split("&");var d=e.length,f,g,k;for(k=0;k<d;k+=1)if(f=e[k].split("="),g=f[0],f=f[1],"src"===g){e=f;break a}e=null}e&&(a.other={src:e});b.isError&&(a.isError=!0,c.System.emit("gi.userdata.failure",b));c.System.emit("gi.userdata.ready",a)});break;default:c.System.emit("gi.userdata.ready",{})}}}});return c}()});SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;return c||(c=function(c,p,r,y,g,k){return{launch:function(c){r.init(c);y.init(c);var f=c.hooks;p.isFunction(f.onPrerollFinish)&&g.onState("afterpreroll",function(){f.onPrerollFinish()});p.isFunction(f.onDisplayGame)&&g.onState("displaygame",function(){f.onDisplayGame()});p.isFunction(f.onMidroll)&&g.onState("onmidroll",function(){f.onMidroll()},!0);p.isFunction(f.afterMidroll)&&
g.onState("aftermidroll",function(){f.afterMidroll()},!0);g.init(c);k.init(c)}}}),c}(window,document)});
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,f){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",f)},updateCache:function(c,f){f&&_SG.Settings.set("auth.uid",f);SpilGames.Events.publish("auth.login",{hash:c,uid:f,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(f){c.call(this,!0,f,null)},onfailure:function(f){c.call(this,!1,null,f)}})}}}});
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,f){var p,r=!1;return p||(p=function(p,g,k,s,u,d,n){var b,a,e,B={},q={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,
INITIALIZED:11,MIDROLL_ALIVE:12,MIDROLL_REQUESTED:19,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},h={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},t=!1,m=function(){var a=[],b=[],c=function(b,c){return a[b]||(a[b]=[]),a[b].push(c)-1},e=function(a){var c=!1;return b[a]&&(c=!0),c},d=function(b,c){a[b]&&a[b][c]&&(a[b][c]=null)},f=function(){k.System.init(function(c){var e;e=c.name;b[e]=c;(e=a[e])&&
g.each(e,function(a){"function"==typeof a&&a(c)})},!0);f=function(){}};return{subscribe:c,unsubscribe:d,unsubscribeAll:function(b){delete a[b]},waiton:function(a,f){if(!e(a)){var g=c(a,function(a){d("eventName",g);f(a)});return g}f(b[a])},isFired:e,init:f}}(),v=function(a){p(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var c=!1;(0<b.major||0<b.minor||0<b.release)&&(c=!0);a(c)})},F=function(){var a=!1,b=e.game.requiredFeatures;return g.isObject(b)&&0<g.size(b)&&g.each(b,function(b){!0===
b&&(a=!0)}),a},A=function(){var a,c=b.states;v(function(d){a=c.PRE_FETCHING_GAME;g.isObject(e.portal)&&e.portal.siteId&&(1===e.portal.siteId||16===e.portal.siteId||88===e.portal.siteId)&&(a=c.LISTENING_TO_ADVERTISING);!1===d&&(a=c.PLUGIN_MISSING);b.transitionTo(a)})},C=function(){var a,c=b.states,d=c.LISTENING_TO_ADVERTISING;g.each(e.game.requiredFeatures,function(b,e){a=h[e];!0===b&&"function"==typeof n[a]&&!1===n[a]()&&(d=c.FEATURE_MISSING)});b.transitionTo(d)},w=function(){!m.isFired("ad.preroll.finish")&&
p(["LightSWFObject"],function(a){var b=e.game.preloader,c={data:b.src+"?url="+encodeURIComponent(e.game.settings.movie),width:"1",height:"1"};p.subscribe("game.prefetcher.error",function(a){k.System.emit("gi.warning",{code:q.warning.PRE_FETCH_ERROR,flashError:a})});a.createSWF(c,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},b.domId);t=!0});b.transitionTo(b.states.LISTENING_TO_ADVERTISING)},D=function(){var d=m.isFired("ad.preroll.heartbeat"),
f=m.isFired("ad.preroll.start"),g=e.preroll.heartbeatTime,h=function(){k.System.emit("gi.update",{code:q.update.PREROLL_ALIVE,fetchTime:u.stop("prerollFetchTime")})},n=function(){k.System.emit("gi.update",{code:q.update.PREROLL_FAKE_START})};!0===d&&h();!0===f&&n();u.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){n()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(a);d||(d=!0,h());a=c.setTimeout(function(){k.System.emit("gi.warning",{code:q.warning.PREROLL_NO_HEARTBEAT,
waited:g});b.transitionTo(b.states.WAITING_ON_USERDATA)},g)});m.waiton("ad.preroll.finish",function(){a&&c.clearTimeout(a);b.transitionTo(b.states.WAITING_ON_USERDATA)});b.transitionTo(b.states.WAITING_ON_PRE_ROLL)},E=function(){var b=0,d=e.midroll.heartbeatTime,f=e.midroll.maxWaitingTime,g=!1,h=function(){c.clearTimeout(a);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");k.System.emit("gi.update",{code:q.update.MIDROLL_FINISHED,occurrence:b});k.System.emit("gi.update",
{code:q.update.ABORT_MIDROLL});g=!1};m.subscribe("ad.midroll.start",function(){if(!g){var e=!1;g=!0;b+=1;u.start("midrollFetchTime");a=c.setTimeout(function(){k.System.emit("gi.warning",{code:q.warning.MIDROLL_TIMEOUT,waited:f,occurrence:b});h()},f);k.System.emit("gi.update",{code:q.update.MIDROLL_REQUESTED,occurrence:b});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(a);e||(e=!0,k.System.emit("gi.update",{code:q.update.MIDROLL_ALIVE,fetchTime:u.stop("midrollFetchTime"),occurrence:b}));
a=c.setTimeout(function(){k.System.emit("gi.warning",{code:q.warning.MIDROLL_NO_HEARTBEAT,waited:d,occurrence:b});h()},d)});m.subscribe("ad.midroll.finish",function(){h()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var d=e.preroll.maxWaitingTime;a=c.setTimeout(function(){k.System.emit("gi.warning",{code:q.warning.PREROLL_TIMEOUT,waited:d});b.transitionTo(b.states.WAITING_ON_USERDATA)},d)}},H=function(){c.clearTimeout(a);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");
m.unsubscribeAll("ad.preroll.finish");var e=c.setTimeout(function(){k.System.emit("gi.warning",{code:q.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||k.System.emit("gi.update",{code:q.update.ABORT_PREROLL});k.System.emit("gi.update",{code:q.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(a){var d=b.states,f=d.INTEGRATING_GAME;e&&c.clearTimeout(e);!a.data||a.data.isError?f=d.INTEGRATION_ERROR:B=a.data;b.transitionTo(f)})},I=function(){var a,d=b.states.GAME_INTEGRATED,
f=B.auth,h=e.game.settings,n=e.game.preloader;if(f&&g.isObject(f)&&!f.isError)for(a in f)f.hasOwnProperty(a)&&(h.flashvars+="&"+a+"="+f[a]);e&&e.portal&&e.portal.appToken&&(h.flashvars+="&appToken="+e.portal.appToken);p(["LightSWFObject"],function(a){var e={data:h.movie,width:h.width,height:h.height},f={base:h.base,quality:"autohigh",allowFullScreen:h.allowFullScreen,wmode:h.wmode,allowScriptAccess:h.allowScriptAccess,scale:h.scale,flashVars:h.flashvars,bgcolor:h.bgcolor,hasPriority:"true"},g=function(){a.createSWF(e,
f,h.domId);k.System.emit("gi.update",{code:q.update.GAME_EMBEDDED});b.transitionTo(d)};t?(t=!1,a.removeSWF(n.domId),c.setTimeout(function(){g()},20)):g()})};return b={states:{INITIALIZED:0,PLUGIN_DETECTION:1,FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(a){k.Widget.emit(b.eventNamespace,
{state:a})},flowController:function(a){var c=b.states;switch(a.data.state){case c.INITIALIZED:var d,h=b.states,n=h.LISTENING_TO_ADVERTISING,m,p,r,t=!1;if(e&&(m=e.game,p=e.preroll,r=e.midroll),g.isObject(e)&&g.isObject(m)&&g.isObject(p)&&g.isObject(r)&&g.isString(m.type)&&(g.contains(m.type,"DomObject")||g.contains(m.type,"iframe"))&&g.isNumber(p.maxWaitingTime)&&g.isNumber(r.maxWaitingTime)&&g.isNumber(p.heartbeatTime)&&g.isNumber(r.heartbeatTime)&&(t=!0),!t)throw d={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},
SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",eventLabel:"GameIntegration module, exception:"+d.type+" - "+d.message,eventValue:1}),d;"DomObject"===e.game.type?n=h.PLUGIN_DETECTION:F()&&(n=h.FEATURE_DETECTION);b.transitionTo(n);break;case c.PLUGIN_DETECTION:A();break;case c.FEATURE_DETECTION:C();break;case c.PRE_FETCHING_GAME:w();break;case c.PLUGIN_MISSING:k.System.emit("gi.error",{code:q.error.PLUGIN_MISSING,pluginName:"flash"});k.System.emit("gi.update",
{code:q.update.ABORT_PREROLL});break;case c.FEATURE_MISSING:k.System.emit("gi.error",{code:q.error.FEATURE_MISSING});k.System.emit("gi.update",{code:q.update.ABORT_PREROLL});break;case c.LISTENING_TO_ADVERTISING:D();break;case c.WAITING_ON_PRE_ROLL:G();break;case c.WAITING_ON_USERDATA:H();break;case c.INTEGRATING_GAME:"DomObject"===e.game.type&&I();if("iframe"===e.game.type){d=b.states.GAME_INTEGRATED;a=e.game.settings;m=f.getElementById(a.domId);p={};g.isObject(B.auth)&&(p=g.combine(B.auth,p));g.isObject(e.portal)&&
e.portal.siteId&&e.portal.channelId&&(p=g.combine({siteid:e.portal.siteId,channelid:e.portal.channelId,UID:e.portal.sgid||""},p),p=e.portal.authenticated&&!0===e.portal.authenticated?g.combine({hash:e.portal.appToken||"",username:e.portal.username||""},p):g.combine({hash:"",username:""},p));g.isObject(B.other)&&(p=g.combine(B.other,p));m.width=a.width;m.height=a.height;r="";a=a.url.replace("###DOMAIN###",window.location.hostname);a=a.replace("###CACHE_PP###","");c=document.createElement("a");a=(c.href=
a,t="/"===c.pathname.charAt(0)?c.pathname:"/"+c.pathname,{protocol:c.protocol,hostname:c.hostname,port:c.port,pathname:t,search:c.search,hash:c.hash,host:c.host});for(n in p)p.hasOwnProperty(n)&&(r+="&"+n+"="+p[n]);n=(h=a.protocol+"//"+a.host+a.pathname||"",h+=0<a.search.length?encodeURI(a.search+r):"?"+encodeURI(r.substring(1)),h+(a.hash||""));m.src=n;k.System.emit("gi.update",{code:q.update.GAME_EMBEDDED});b.transitionTo(d)}break;case c.INTEGRATION_ERROR:k.System.emit("gi.error",{code:q.error.USER_DATA_MISSING});
break;case c.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),s.emit("gi.game.loaded")}},start:function(){k.Widget.init(b.flowController)}},{init:function(a){if(e=a,e.game.objectSettings&&(e.game.settings=e.game.objectSettings),r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;k.init("game");m.init();b.start();k.System.emit("gi.update",{code:q.update.INITIALIZED});b.transitionTo(b.states.INITIALIZED)},
eventCodeMap:q}}),p}(window,document)});
SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,f){var p,r=!1;return p||(p=function(p,g,k,s,u,d){var n,b={backgroundScreen:f.getElementById("backgroundScreen"),defaultScreen:f.getElementById("defaultLoadingScreen"),waitingForUserData:f.getElementById("waitingForUserData"),userDataNotResponding:f.getElementById("userDataNotResponding"),userDataMissing:f.getElementById("userDataMissing"),loadingDomObjectGame:f.getElementById("loadingDomObjectGame"),
loadingIframeGame:f.getElementById("loadingIframeGame"),errorLoadingGame:f.getElementById("errorLoadingGame"),missingPlugin:f.getElementById("missingPlugin"),missingFeature:f.getElementById("missingFeature"),displayGame:f.getElementById("theGame"),preRoll:f.getElementById("videoPreroll300x250"),midRoll:f.getElementById("sgAdOgGp300x250"),midrollLoading:f.getElementById("midrollLoadingScreen")},a=f.getElementById("game-integration"),e={},B=[],q=["displaygame","afterpreroll","onmidroll","aftermidroll"],
h=b.defaultScreen,t={},m=!1,v=function(a){h.className=h.className.replace("activeFeedbackScreen","");h=b[a];h.className+=" activeFeedbackScreen"},F=function(){u.subscribe("game.ad.accepted",function(a){p.isObject(a)&&!0===a.displayAd&&p.isString(a.bgImage)&&!p.isEmpty(a.bgImage)&&(n=a.bgImage)})},A=function(a){var b=B[a];b&&p.each(b,function(a,e){a.persistent&&!0===a.persistent||delete b[e];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),w=function(){if(!m){m=!0;v("displayGame");A("displaygame");try{F();g.System.emit("gi.portal.feedback",{displayGame:e.portal.contentarId});var a=C();a&&g.System.emit("gi.portal.feedback",{timeToPlay:k.now()-a});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),g.System.emit("gi.portal.feedback",
{timeToFirstPlay:k.now()-a.sessionStart}))})}catch(b){}}},D=function(){var a,b=f.getElementById(e.game.settings.domId),c=f.getElementById("progress-container"),d=function(){try{(a=k.stop("iframeLoadDuration"))&&g.System.emit("gi.portal.feedback",{loadDuration:a})}catch(b){}w()};k.start("iframeLoadDuration");b.completed?w():(c&&(c.style.display="none"),v("loadingIframeGame"),b.attachEvent?b.attachEvent("onload",function(){d()}):b.onload=function(){d()})},E=function(){var a,b,d,h,n=f.getElementById(e.game.settings.domId),
l=f.getElementById("progress-bar"),m=f.getElementById("progress-percentage"),p=0,q=function(){return n&&"function"==typeof n.PercentLoaded||c.attachEvent&&"number"==typeof n.PercentLoaded()},r=function(){if(d=n.PercentLoaded(),98<d||0>d)w();else{v("loadingDomObjectGame");l.width=d+"%";m&&(m.innerHTML=d+"%");try{k.start("progressBarDuration"),g.System.emit("gi.portal.feedback",{progressBarStart:d})}catch(e){}a=c.setInterval(function(){if(d=q()?n.PercentLoaded():void 0,void 0!==d&&-1<d&&100>d)m&&(m.innerHTML=
d+"%"),l.style.width=d+"%";else{c.clearInterval(a);m&&(m.innerHTML="100%");l.style.width="99%";c.setTimeout(function(){w()},500);try{(b=k.stop("progressBarDuration"))&&g.System.emit("gi.portal.feedback",{progressBarDuration:b+500})}catch(e){}}},100)}};try{h=c.setInterval(function(){p+=1;q()&&(c.clearInterval(h),r());10<=p&&(c.clearInterval(h),w(),g.System.emit("gi.portal.feedback",{progressBarError:e.portal.contentarId}))},100)}catch(s){w(),g.System.emit("gi.portal.feedback",{progressBarError:e.portal.contentarId})}};
return{init:function(c){r||(r=!0,e=c,t=d.eventCodeMap,g.init("game"),g.System.init(function(c){switch(c.name){case "gi.update":var d,f=t.update;c=c.data;switch(c.code){case f.WAITING_FOR_USER_DATA:v("waitingForUserData");try{var h=k.stop("prerollDisplayDuration");h&&g.System.emit("gi.portal.feedback",{prerollDisplayDuration:h})}catch(l){}A("afterpreroll");break;case f.PREROLL_FAKE_START:v("preRoll");break;case f.PREROLL_ALIVE:v("preRoll");try{(d=C())&&g.System.emit("gi.portal.feedback",{timeToPreroll:k.now()-
d}),k.start("prerollDisplayDuration")}catch(m){}break;case f.MIDROLL_REQUESTED:n&&(b.backgroundScreen.style.cssText="background-image: url("+n+");",491<parseInt(b.displayGame.style.height,10)&&(a.style.height=b.displayGame.style.height),b.backgroundScreen.style.display="block",n=void 0);v("midrollLoading");try{A("onmidroll")}catch(p){}break;case f.MIDROLL_ALIVE:v("midRoll");try{k.start("midrollDisplayDuration"),d=C(),c.occurrence&&1===c.occurrence&&d&&g.System.emit("gi.portal.feedback",{timeToFirstMidroll:k.now()-
d})}catch(q){}break;case f.MIDROLL_FINISHED:"block"===b.backgroundScreen.style.display&&(b.backgroundScreen.style.background="#FFF",b.backgroundScreen.style.display="none");v("displayGame");try{A("aftermidroll");var r=k.stop("midrollDisplayDuration");r&&g.System.emit("gi.portal.feedback",{midrollDisplayDuration:r})}catch(s){}break;case f.GAME_EMBEDDED:"DomObject"===e.game.type&&E(),"iframe"===e.game.type&&D()}break;case "gi.error":d=t.error;switch(c.data.code){case d.USER_DATA_MISSING:v("userDataMissing");
break;case d.PLUGIN_MISSING:v("missingPlugin");break;case d.FEATURE_MISSING:v("missingFeature")}break;case "gi.warning":c.data.code===t.warning.USER_DATA_NOT_RESPONDING&&v("userDataNotResponding")}},!0))},onState:function(a,b,c){0<=p.indexOf(q,a)&&(B[a]||(B[a]=[]),B[a].push({callback:b,persistent:c}))}}}),p}(window,window.document)});
SpilGames("spilgames.import",{name:"GIMonitor",deps:["SWP","GIController","JSLib","Net","Utils"],module:function(){var c,f=!1;return c?void 0:c=function(c,r,y,g,k){var s=r.eventCodeMap,u={},d=function(b,a,c,d){void 0===d&&(d=!0);k.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,c,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,c,!0]));var f=k.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),h=f?"ms":"c",f=f?c:1,n=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+n+"."+b+"."+a+"]="+f+h;u.monitoring&&u.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+n+"."+u.monitoring.bucket+"."+b+"."+a+"]="+f+h);0<f&&("c"===h?1===f:1)&&g.send({url:m,type:"GET"},k.emptyFn);y("tracker.event."+(d?"track":"express"),{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,eventValue:c})},n={error:function(b){var a=
s.error;b=b.data;switch(b.code){case a.USER_DATA_MISSING:d("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);d("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:d("error","missingBrowserFeature")}},warning:function(b){var a=s.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:d("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:d("warning","prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:d("warning",
"prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:d("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:d("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:d("warning","midrollTimeout",b.waited)}},update:function(b){var a=s.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&d("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&d("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:d("update","initialized")}}};
return{init:function(b){(u=b,f)||(f=!0,c.init("game"),b=window.publishingHost,void 0===b?d("update","publishingHostUndefined",b):"unknown"===b?d("update","publishingHostUnknown",b):d("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":n.error(a);break;case "gi.warning":n.warning(a);break;case "gi.update":n.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&d("update","timeToPlay",a.timeToPlay);a.displayGame&&d("update","displayGame",a.displayGame,
!1);a.prerollDisplayDuration&&d("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&d("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&d("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&d("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&d("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&d("update","progressBarStart",a.progressBarStart);a.progressBarDuration&&d("update","progressBarDuration",
a.progressBarDuration);a.progressBarError&&d("warning","progressBarError",a.progressBarError);a.loadDuration&&d("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":d("warning","decodeAuthCookieFailure");break;case "appToken":d("error","appToken");break;case "getCurrentUser":d("error","getCurrentUser")}}},!0))}}}}()});
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,f=!1;return c||(c=function(c,r,y,g,k){var s,u=function(c){var b;y.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(a){a&&a.auth&&a.auth.token?r("api.user.get",{cache:!0},function(d){b=d&&d.userInfo?{username:d.userInfo.name,hash:a.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:d&&d.error||"unknown error"};c.call(this,b)}):(b=
{isError:!0,message:"Failed to retrieve the user hash",error:a&&a.error||"unknown error"},c.call(this,b))})},d=function(c){var b={};r("api.account.getApplicationToken",{cache:!0,applicationId:""+(s.portal.applicationId||s.portal.contentarId)},function(a){try{if(!a.appAuth||a.isError)return SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:a.error}),void 0;var d=a.appAuth.token;b.appToken=d;k.updateCache(d,
s.portal.sgid);k.getUserInfo(function(a,d,e){a?c(b):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:e})})}catch(f){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:f})}})};return{init:function(g){if(s=g,!f)switch(f=!0,c.init("game"),s.game.needs){case "preliminaryAuth":u(function(b){c.System.emit("gi.userdata.ready",{auth:b})});break;case "auth":k.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);d(function(b){var a={auth:b},
d;a:{var f,g,h;f=window;var k=f.location.href.slice(f.location.href.indexOf("?")+1).split("&"),m=k.length;for(h=0;m>h;h+=1)if(d=k[h].split("="),g=d[0],f=d[1],"src"===g){d=f;break a}d=null}d&&(a.other={src:d});b.isError&&(a.isError=!0,c.System.emit("gi.userdata.failure",b));c.System.emit("gi.userdata.ready",a)});break;default:c.System.emit("gi.userdata.ready",{})}}}}),c}()});
//# sourceMappingURL=wdg_game-1545bf082cd3773f77bdefbb094bbbdc97e55bae.js.map
