function SWFtoJS(c){this.m_oCallFuntions={};this.m_bDebug=!1;null!=c&&SWFtoJS.instance().parse(c)}SWFtoJS.m_oSWFtoJS=null;SWFtoJS.instance=function(c){null==SWFtoJS.m_oSWFtoJS&&(SWFtoJS.m_oSWFtoJS=new SWFtoJS,c&&(SWFtoJS.m_oSWFtoJS.m_bDebug=!0));return SWFtoJS.m_oSWFtoJS};SWFtoJS.prototype.addCallFunction=function(c,e){"function"==typeof e&&(this.m_oCallFuntions[c]=e)};
SWFtoJS.prototype.parse=function(c){try{if(c.call)switch(c.call){case "MULTI":for(i=0;i<p_oData.calls.length;i++)SWFtoJS(c.calls[i]);break;default:if(this.m_oCallFuntions[c.call])c.params||(c.params={}),this.m_oCallFuntions[c.call](c.params);else throw"call: "+c.call+" not found in call functions!";}else throw"call attribute not found in CallObject!";}catch(e){this.m_bDebug&&alert(e)}};/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIMonitor",deps:["SWP","GIController","JSLib","Net","Utils"],module:function(){var c,e=!1;if(!c)return c=function(c,r,z,d,h){var s=r.eventCodeMap,v={},n=function(c,b,a,f){"undefined"===typeof f&&(f=!0);h.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",c,b,a,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",c,b,a,!0]));var e=h.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
b),g=e?"ms":"c",e=e?a:1,t=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+t+"."+c+"."+b+"]="+e+g;v.monitoring&&v.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+t+"."+v.monitoring.bucket+"."+c+"."+b+"]="+e+g);0<e&&("c"===g?1===e:1)&&d.send({url:m,type:"GET"},h.emptyFn);z("tracker.event."+(f?"track":"express"),{eventCategory:"gameIntegration",eventAction:c,eventLabel:b,eventValue:a})},f={error:function(c){var b=
s.error;c=c.data;switch(c.code){case b.USER_DATA_MISSING:n("error","userDataMissing");break;case b.PLUGIN_MISSING:b=c.pluginName.charAt(0).toUpperCase()+c.pluginName.slice(1);n("error","missing"+b+"Plugin");break;case b.FEATURE_MISSING:n("error","missingBrowserFeature")}},warning:function(c){var b=s.warning;c=c.data;switch(c.code){case b.USER_DATA_NOT_RESPONDING:n("warning","userDataNotResponding",5E3);break;case b.PRE_FETCH_ERROR:n("warning","prefetchError",c.flashError.code);break;case b.PREROLL_NO_HEARTBEAT:n("warning",
"prerollNoHeartbeat",c.waited);break;case b.PREROLL_TIMEOUT:n("warning","prerollTimeout",c.waited);break;case b.MIDROLL_NO_HEARTBEAT:n("warning","midrollNoHeartbeat",c.waited);break;case b.MIDROLL_TIMEOUT:n("warning","midrollTimeout",c.waited)}},update:function(c){var b=s.update;c=c.data;switch(c.code){case b.PREROLL_ALIVE:c.fetchTime&&n("update","prerollFetchTime",c.fetchTime);break;case b.MIDROLL_ALIVE:c.fetchTime&&n("update","midrollFetchTime",c.fetchTime);break;case b.INITIALIZED:n("update","initialized")}}};
return{init:function(d){v=d;e||(e=!0,c.init("game"),d=window.publishingHost,void 0===d?n("update","publishingHostUndefined",d):"unknown"===d?n("update","publishingHostUnknown",d):n("update","publishingHostOk",d),c.System.init(function(b){switch(b.name){case "gi.error":f.error(b);break;case "gi.warning":f.warning(b);break;case "gi.update":f.update(b);break;case "gi.portal.feedback":b=b.data;b.timeToPlay&&n("update","timeToPlay",b.timeToPlay);b.displayGame&&n("update","displayGame",b.displayGame,!1);
b.prerollDisplayDuration&&n("update","prerollDisplayDuration",b.prerollDisplayDuration);b.timeToPreroll&&n("update","timeToPreroll",b.timeToPreroll);b.midrollDisplayDuration&&n("update","midrollDisplayDuration",b.midrollDisplayDuration);b.timeToFirstMidroll&&n("update","timeToFirstMidroll",b.timeToFirstMidroll);b.timeToFirstPlay&&n("update","timeToFirstPlay",b.timeToFirstPlay);b.progressBarStart&&n("update","progressBarStart",b.progressBarStart);b.progressBarDuration&&n("update","progressBarDuration",
b.progressBarDuration);b.progressBarError&&n("warning","progressBarError",b.progressBarError);b.loadDuration&&n("update","loadingScreenDuration",b.loadDuration);break;case "gi.userdata.failure":if(b.data&&b.data.action)switch(b.data.action){case "decodeCookie":n("warning","decodeAuthCookieFailure");break;case "appToken":n("error","appToken");break;case "getCurrentUser":n("error","getCurrentUser")}}},!0))}}}}()});/*
 2013, Spil Games
*/
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,e){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",e)},updateCache:function(c,e){e&&_SG.Settings.set("auth.uid",e);SpilGames.Events.publish("auth.login",{hash:c,uid:e,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(e){c.call(this,!0,e,null)},onfailure:function(e){c.call(this,!1,null,e)}})}}}});/*
: 2013, SpilGames
*/
SpilGames("spilgames.import",{name:"SpapiIntegration",deps:"RemoteEvent Game Utils JSLib SPAPI SWPEvent".split(" "),module:function(c,e){return function(c,r,z,d,h,s){return{enable:function(s,n){var f=e.getElementById(s.game.objectSettings.domId),q=s.game.objectSettings.url;c.subscribe(q);d.subscribe("remote.api.portal.*|remote.api.auth.getApplicationToken",function(a){var b=this.event.type,h=b.substring(7);"api.auth.getApplicationToken"===h?a={applicationId:s.portal.applicationId}:"api.portal.invite.friends"===
h&&n.System.emit("popup.social_invite.open");d(h,a,function(a){c.publish(b,{target:{frame:f,url:q},data:a})})});d.subscribe("api.event.*",function(a){c.publish(this.event.type,{target:{frame:f,url:q},data:a})});var b=d.messageBroker;b.addRule("api.portal.force.auth",function(a,b){d("api.user.get",{cache:!0},function(a){a.isError||"guest"==a.userInfo.level?(d("api.event.overlay.shown"),d("api.portal.overlay.show"),n.System.init(function(a){switch(a.name){case "popup.closed":d("api.event.overlay.hidden"),
d("api.portal.overlay.hide"),b({data:{state:h.STATE_LOGGEDOUT}})}}),n.System.emit("popup.login.open")):b({state:h.STATE_LOGGEDIN})})});b.addRule("api.portal.canvas.setSize",function(a,b){function c(b){/^[0-9]+$/.test(a[b])&&Number(a[b])<=d[b]&&("width"===b?(h.style.width=n+"px",f.style.width=n+"px",e.style.width=r+"px"):(h.style.height=a.height+"px",f.style.height=a.height+"px"),D=!0)}var d={width:1E3,height:2E3},h=document.getElementById("iframegame"),f=document.getElementById("theGame"),e=document.getElementById("layout-container"),
q=s.game.recommendedGames,n=parseInt(a.width,10),l=682,r,D=!1;q&&(l=891);r=n>l?960+n-l:960;960>r&&(r=960);z.isEmpty(a)?b({state:!1}):(c("width"),c("height"),D?b({state:!0}):b({state:!1}))})}}}}(window,document)});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Jeroen Reurings <jeroen.reurings@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,e){var l,r=!1;l||(l=function(l,d,h,s,v,n,f){var q={},b,a={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,INITIALIZED:11,
MIDROLL_ALIVE:12,MIDROLL_REQUESTED:19,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},B={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},p,g,t=!1,m=function(){var a=[],b=[],k=function(b,k){a[b]||(a[b]=[]);return a[b].push(k)-1},c=function(a){var w=!1;b[a]&&(w=!0);return w},f=function(b,k){a[b]&&a[b][k]&&(a[b][k]=null)},e=function(){h.System.init(function(k){var c=k.name;b[c]=k;(c=a[c])&&d.each(c,function(a){"function"===
typeof a&&a(k)})},!0);e=function(){}};return{subscribe:k,unsubscribe:f,unsubscribeAll:function(b){delete a[b]},waiton:function(a,w){if(c(a))w(b[a]);else{var d=k(a,function(a){f("eventName",d);w(a)});return d}},isFired:c,init:e}}(),u=function(a){l(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var k=!1;if(0<b.major||0<b.minor||0<b.release)k=!0;a(k)})},F=function(){var a=!1,b=g.game.requiredFeatures;d.isObject(b)&&0<d.size(b)&&d.each(b,function(b){!0===b&&(a=!0)});return a},A=function(){var a=
b.states,c;u(function(k){c=a.PRE_FETCHING_GAME;!1===k&&(c=a.PLUGIN_MISSING);b.transitionTo(c)})},C=function(){var a=b.states,c=a.LISTENING_TO_ADVERTISING,k;d.each(g.game.requiredFeatures,function(b,d){k=B[d];!0===b&&"function"===typeof f[k]&&!1===f[k]()&&(c=a.FEATURE_MISSING)});b.transitionTo(c)},x=function(){m.isFired("ad.preroll.finish")||l(["LightSWFObject"],function(b){var c=g.game.preloader,k={data:c.src+"?url="+encodeURIComponent(g.game.settings.movie),width:"1",height:"1"};l.subscribe("game.prefetcher.error",
function(b){h.System.emit("gi.warning",{code:a.warning.PRE_FETCH_ERROR,flashError:b})});b.createSWF(k,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},c.domId);t=!0});b.transitionTo(b.states.LISTENING_TO_ADVERTISING)},D=function(){var w=m.isFired("ad.preroll.heartbeat"),y=m.isFired("ad.preroll.start"),k=g.preroll.heartbeatTime,d=function(){h.System.emit("gi.update",{code:a.update.PREROLL_ALIVE,fetchTime:v.stop("prerollFetchTime")})},
f=function(){h.System.emit("gi.update",{code:a.update.PREROLL_FAKE_START})};!0===w&&d();!0===y&&f();v.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){f()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(p);w||(w=!0,d());p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.PREROLL_NO_HEARTBEAT,waited:k});b.transitionTo(b.states.WAITING_ON_USERDATA)},k)});m.waiton("ad.preroll.finish",function(){p&&c.clearTimeout(p);b.transitionTo(b.states.WAITING_ON_USERDATA)});
b.transitionTo(b.states.WAITING_ON_PRE_ROLL)},E=function(){var b=0,y=g.midroll.heartbeatTime,k=g.midroll.maxWaitingTime,d=!1,f=function(){c.clearTimeout(p);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");h.System.emit("gi.update",{code:a.update.MIDROLL_FINISHED,occurrence:b});h.System.emit("gi.update",{code:a.update.ABORT_MIDROLL});d=!1};m.subscribe("ad.midroll.start",function(){if(!d){var e=!1;d=!0;b+=1;v.start("midrollFetchTime");p=c.setTimeout(function(){h.System.emit("gi.warning",
{code:a.warning.MIDROLL_TIMEOUT,waited:k,occurrence:b});f()},k);h.System.emit("gi.update",{code:a.update.MIDROLL_REQUESTED,occurrence:b});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(p);e||(e=!0,h.System.emit("gi.update",{code:a.update.MIDROLL_ALIVE,fetchTime:v.stop("midrollFetchTime"),occurrence:b}));p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.MIDROLL_NO_HEARTBEAT,waited:y,occurrence:b});f()},y)});m.subscribe("ad.midroll.finish",function(){f()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var w=
g.preroll.maxWaitingTime;p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.PREROLL_TIMEOUT,waited:w});b.transitionTo(b.states.WAITING_ON_USERDATA)},w)}},H=function(){c.clearTimeout(p);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");m.unsubscribeAll("ad.preroll.finish");var w=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});
h.System.emit("gi.update",{code:a.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(a){var k=b.states,d=k.INTEGRATING_GAME;w&&c.clearTimeout(w);!a.data||a.data.isError?d=k.INTEGRATION_ERROR:q=a.data;b.transitionTo(d)})},I=function(){var w=b.states.GAME_INTEGRATED,y=q.auth,k=g.game.settings,f=g.game.preloader,e;if(y&&d.isObject(y)&&!y.isError)for(e in y)y.hasOwnProperty(e)&&(k.flashvars+="&"+e+"="+y[e]);g&&g.portal&&g.portal.appToken&&(k.flashvars+="&appToken="+g.portal.appToken);
l(["LightSWFObject"],function(y){var d={data:k.movie,width:k.width,height:k.height},e={base:k.base,quality:"autohigh",allowFullScreen:k.allowFullScreen,wmode:k.wmode,allowScriptAccess:k.allowScriptAccess,scale:k.scale,flashVars:k.flashvars,bgcolor:k.bgcolor,hasPriority:"true"},g=function(){y.createSWF(d,e,k.domId);h.System.emit("gi.update",{code:a.update.GAME_EMBEDDED});b.transitionTo(w)};t?(t=!1,y.removeSWF(f.domId),c.setTimeout(function(){g()},20)):g()})};b={states:{INITIALIZED:0,PLUGIN_DETECTION:1,
FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(a){h.Widget.emit(b.eventNamespace,{state:a})},flowController:function(c){var y,k,f,p;k=b.states;switch(c.data.state){case k.INITIALIZED:var m=b.states;c=m.LISTENING_TO_ADVERTISING;k=!1;var t,n,l;g&&(t=g.game,n=g.preroll,l=g.midroll);
d.isObject(g)&&d.isObject(t)&&d.isObject(n)&&d.isObject(l)&&d.isString(t.type)&&(d.contains(t.type,"DomObject")||d.contains(t.type,"iframe"))&&d.isNumber(n.maxWaitingTime)&&d.isNumber(l.maxWaitingTime)&&d.isNumber(n.heartbeatTime)&&d.isNumber(l.heartbeatTime)&&(k=!0);if(!k)throw m={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",eventLabel:"GameIntegration module, exception:"+
m.type+" - "+m.message,eventValue:1}),m;"DomObject"===g.game.type?c=m.PLUGIN_DETECTION:F()&&(c=m.FEATURE_DETECTION);b.transitionTo(c);break;case k.PLUGIN_DETECTION:A();break;case k.FEATURE_DETECTION:C();break;case k.PRE_FETCHING_GAME:x();break;case k.PLUGIN_MISSING:h.System.emit("gi.error",{code:a.error.PLUGIN_MISSING,pluginName:"flash"});h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});break;case k.FEATURE_MISSING:h.System.emit("gi.error",{code:a.error.FEATURE_MISSING});h.System.emit("gi.update",
{code:a.update.ABORT_PREROLL});break;case k.LISTENING_TO_ADVERTISING:D();break;case k.WAITING_ON_PRE_ROLL:G();break;case k.WAITING_ON_USERDATA:H();break;case k.INTEGRATING_GAME:"DomObject"===g.game.type&&I();if("iframe"===g.game.type){t=b.states.GAME_INTEGRATED;k=g.game.settings;n=e.getElementById(k.domId);l={};d.isObject(q.auth)&&(l=d.combine(q.auth,l));d.isObject(g.portal)&&g.portal.siteId&&g.portal.channelId&&(l=d.combine({siteid:g.portal.siteId,channelid:g.portal.channelId,UID:g.portal.sgid||
""},l),l=g.portal.authenticated&&!0===g.portal.authenticated?d.combine({hash:g.portal.appToken||"",username:g.portal.username||""},l):d.combine({hash:"",username:""},l));d.isObject(q.other)&&(l=d.combine(q.other,l));n.width=k.width;n.height=k.height;c=l;l="";k=k.url.replace("###DOMAIN###",window.location.hostname);k=k.replace("###CACHE_PP###","");p=document.createElement("a");var u;p.href=k;u="/"===p.pathname.charAt(0)?p.pathname:"/"+p.pathname;y=p.protocol;k=p.search;f=p.hash;p=p.host;for(m in c)c.hasOwnProperty(m)&&
(l+="&"+m+"="+c[m]);m=y+"//"+p+u||"";m=0<k.length?m+encodeURI(k+l):m+("?"+encodeURI(l.substring(1)));n.src=m+(f||"");h.System.emit("gi.update",{code:a.update.GAME_EMBEDDED});b.transitionTo(t)}break;case k.INTEGRATION_ERROR:h.System.emit("gi.error",{code:a.error.USER_DATA_MISSING});break;case k.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),s.emit("gi.game.loaded")}},start:function(){h.Widget.init(b.flowController)}};return{init:function(c){g=c;g.game.objectSettings&&(g.game.settings=
g.game.objectSettings);if(r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;h.init("game");m.init();b.start();h.System.emit("gi.update",{code:a.update.INITIALIZED});b.transitionTo(b.states.INITIALIZED)},eventCodeMap:a}});return l}(window,document)});/*
: 2013, SpilGames
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;c||(c=function(c,l,r,z,d,h){return{launch:function(c){r.init(c);z.init(c);var e=c.hooks;if(l.isFunction(e.onPrerollFinish))d.onState("afterpreroll",function(){e.onPrerollFinish()});if(l.isFunction(e.onDisplayGame))d.onState("displaygame",function(){e.onDisplayGame()});if(l.isFunction(e.onMidroll))d.onState("onmidroll",function(){e.onMidroll()},!0);if(l.isFunction(e.afterMidroll))d.onState("aftermidroll",
function(){e.afterMidroll()},!0);d.init(c);h.init(c)}}});return c}(window,document)});SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,e){var l,r=!1;l||(l=function(l,d,h,s,v,n){var f={backgroundScreen:e.getElementById("backgroundScreen"),defaultScreen:e.getElementById("defaultLoadingScreen"),waitingForUserData:e.getElementById("waitingForUserData"),userDataNotResponding:e.getElementById("userDataNotResponding"),userDataMissing:e.getElementById("userDataMissing"),loadingDomObjectGame:e.getElementById("loadingDomObjectGame"),
loadingIframeGame:e.getElementById("loadingIframeGame"),errorLoadingGame:e.getElementById("errorLoadingGame"),missingPlugin:e.getElementById("missingPlugin"),missingFeature:e.getElementById("missingFeature"),displayGame:e.getElementById("theGame"),preRoll:e.getElementById("videoPreroll300x250"),midRoll:e.getElementById("sgAdOgGp300x250"),midrollLoading:e.getElementById("midrollLoadingScreen")},q=e.getElementById("game-integration"),b={},a=[],B=["displaygame","afterpreroll","onmidroll","aftermidroll"],
p=f.defaultScreen,g={},t,m=!1,u=function(a){p.className=p.className.replace("activeFeedbackScreen","");p=f[a];p.className+=" activeFeedbackScreen"},F=function(){v.subscribe("game.ad.accepted",function(a){l.isObject(a)&&!0===a.displayAd&&l.isString(a.bgImage)&&!l.isEmpty(a.bgImage)&&(t=a.bgImage)})},A=function(b){var d=a[b];d&&l.each(d,function(a,b){a.persistent&&!0===a.persistent||delete d[b];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),x=function(){if(!m){m=!0;u("displayGame");A("displaygame");try{F();d.System.emit("gi.portal.feedback",{displayGame:b.portal.contentarId});var a=C();a&&d.System.emit("gi.portal.feedback",{timeToPlay:h.now()-a});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),d.System.emit("gi.portal.feedback",
{timeToFirstPlay:h.now()-a.sessionStart}))})}catch(c){}}},D=function(){var a=e.getElementById(b.game.settings.domId),c=e.getElementById("progress-container"),f,w=function(){try{(f=h.stop("iframeLoadDuration"))&&d.System.emit("gi.portal.feedback",{loadDuration:f})}catch(a){}x()};h.start("iframeLoadDuration");a.completed?x():(c&&(c.style.display="none"),u("loadingIframeGame"),a.attachEvent?a.attachEvent("onload",function(){w()}):a.onload=function(){w()})},E=function(){var a=e.getElementById(b.game.settings.domId),
f=e.getElementById("progress-bar"),g=e.getElementById("progress-percentage"),w,y,k,q,p=0,m=function(){return a&&"function"===typeof a.PercentLoaded||c.attachEvent&&"number"===typeof a.PercentLoaded()},l=function(){k=a.PercentLoaded();if(98<k||0>k)x();else{u("loadingDomObjectGame");f.width=k+"%";g&&(g.innerHTML=k+"%");try{h.start("progressBarDuration"),d.System.emit("gi.portal.feedback",{progressBarStart:k})}catch(b){}w=c.setInterval(function(){k=m()?a.PercentLoaded():void 0;if("undefined"!==typeof k&&
-1<k&&100>k)g&&(g.innerHTML=k+"%"),f.style.width=k+"%";else{c.clearInterval(w);g&&(g.innerHTML="100%");f.style.width="99%";c.setTimeout(function(){x()},500);try{(y=h.stop("progressBarDuration"))&&d.System.emit("gi.portal.feedback",{progressBarDuration:y+500})}catch(b){}}},100)}};try{q=c.setInterval(function(){p+=1;m()&&(c.clearInterval(q),l());10<=p&&(c.clearInterval(q),x(),d.System.emit("gi.portal.feedback",{progressBarError:b.portal.contentarId}))},100)}catch(t){x(),d.System.emit("gi.portal.feedback",
{progressBarError:b.portal.contentarId})}};return{init:function(a){r||(r=!0,b=a,g=n.eventCodeMap,d.init("game"),d.System.init(function(a){switch(a.name){case "gi.update":var c=g.update;a=a.data;var w;switch(a.code){case c.WAITING_FOR_USER_DATA:u("waitingForUserData");try{var y=h.stop("prerollDisplayDuration");y&&d.System.emit("gi.portal.feedback",{prerollDisplayDuration:y})}catch(k){}A("afterpreroll");break;case c.PREROLL_FAKE_START:u("preRoll");break;case c.PREROLL_ALIVE:u("preRoll");try{(w=C())&&
d.System.emit("gi.portal.feedback",{timeToPreroll:h.now()-w}),h.start("prerollDisplayDuration")}catch(e){}break;case c.MIDROLL_REQUESTED:t&&(f.backgroundScreen.style.cssText="background-image: url("+t+");",491<parseInt(f.displayGame.style.height,10)&&(q.style.height=f.displayGame.style.height),f.backgroundScreen.style.display="block",t=void 0);u("midrollLoading");try{A("onmidroll")}catch(p){}break;case c.MIDROLL_ALIVE:u("midRoll");try{h.start("midrollDisplayDuration"),w=C(),a.occurrence&&1===a.occurrence&&
w&&d.System.emit("gi.portal.feedback",{timeToFirstMidroll:h.now()-w})}catch(m){}break;case c.MIDROLL_FINISHED:"block"===f.backgroundScreen.style.display&&(f.backgroundScreen.style.background="#FFF",f.backgroundScreen.style.display="none");u("displayGame");try{A("aftermidroll");var l=h.stop("midrollDisplayDuration");l&&d.System.emit("gi.portal.feedback",{midrollDisplayDuration:l})}catch(G){}break;case c.GAME_EMBEDDED:"DomObject"===b.game.type&&E(),"iframe"===b.game.type&&D()}break;case "gi.error":c=
g.error;switch(a.data.code){case c.USER_DATA_MISSING:u("userDataMissing");break;case c.PLUGIN_MISSING:u("missingPlugin");break;case c.FEATURE_MISSING:u("missingFeature")}break;case "gi.warning":a.data.code===g.warning.USER_DATA_NOT_RESPONDING&&u("userDataNotResponding")}},!0))},onState:function(b,c,d){0<=l.indexOf(B,b)&&(a[b]||(a[b]=[]),a[b].push({callback:c,persistent:d}))}}});return l}(window,window.document)});/*
: 2013, SpilGames
*/
SpilGames("spilgames.import",{name:"GameEvents",deps:["Import"],module:function(){var c,e;c||(c=function(c){return{init:function(r,z){c.file(["/wdg/game-"+r+"/js/SWFtoJS.js"],function(){e=SWFtoJS.instance();z.call(this)})},on:function(c,l){if(e)if(l)e.addCallFunction(c,l);else throw"no callback function defined for game event: "+c;else throw"no game event handler defined";}}});return c}(window,document)});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,e=!1;c||(c=function(c,r,z,d,h){var s,v=function(c){var d;z.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(b){b&&b.auth&&b.auth.token?r("api.user.get",{cache:!0},function(a){d=a&&a.userInfo?{username:a.userInfo.name,hash:b.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:a&&a.error||"unknown error"};c.call(this,d)}):(d={isError:!0,
message:"Failed to retrieve the user hash",error:b&&b.error||"unknown error"},c.call(this,d))})},n=function(c){var d={};r("api.account.getApplicationToken",{cache:!0,applicationId:(s.portal.applicationId||s.portal.contentarId).toString()},function(b){try{if(!b.appAuth||b.isError)SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:b.error});else{var a=b.appAuth.token;d.appToken=a;h.updateCache(a,s.portal.sgid);
h.getUserInfo(function(a,b,e){a?c(d):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:e})})}}catch(e){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:e})}})};return{init:function(d){s=d;if(!e)switch(e=!0,c.init("game"),s.game.needs){case "preliminaryAuth":v(function(d){c.System.emit("gi.userdata.ready",{auth:d})});break;case "auth":h.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);n(function(d){var b={auth:d},a;a:{a=window;
a=a.location.href.slice(a.location.href.indexOf("?")+1).split("&");var e=a.length,h,f,t;for(t=0;t<e;t+=1)if(h=a[t].split("="),f=h[0],h=h[1],"src"===f){a=h;break a}a=null}a&&(b.other={src:a});d.isError&&(b.isError=!0,c.System.emit("gi.userdata.failure",d));c.System.emit("gi.userdata.ready",b)});break;default:c.System.emit("gi.userdata.ready",{})}}}});return c}()});SpilGames({name:"wdg_game",waiton:"game.info.loaded"},"SWP SWPUtils SWPEvent JSLib GIBootstrap DOMSelect Cache GameEvents SpapiIntegration".split(" "),function(c,e,l,r,z,d,h,s,v){c.init("game");var n=r.get("current.game.integration.info"),f=d.get("#preroll-container"),q=!1,b="true"===r.get("spilgames.portal.user.authenticated")?!0:!1,a=document.getElementById("theGame"),B=function(a,b){var c=parseInt(n.game.objectSettings.height,10),e=parseInt(n.game.objectSettings.width,10),c=Math.floor(c*a/100),
e=Math.floor(e*a/100),h=d.get("#theGame object");h&&(h.setAttribute("height",c.toString()+"px"),h.setAttribute("width",e.toString()+"px"));b.call(this,c,e,a)},p=function(a,b){var c=[];h.getItem({key:"recent.played.games"},function(d){if(d&&0<d.length){c=d;e.each(d,function(b){"string"===typeof b&&(c=[a])});d=g(c,a);var f=0<=d;f&&(c.splice(d,1),c.unshift(a));f||(c.unshift(a),6<c.length&&c.pop())}else c.push(a);h.setItem({key:"recent.played.games",value:c,expires:315569259},b)})},g=function(a,b){for(var c in a)if(a[c].gid===
b.gid)return c;return-1};c.Widget.init(function(a){switch(a.name){case "recent.played.games.update":if(!q){var c=a.data.appid+"";a=n&&n.game&&n.game.info?e.combine(n.game.info,{gid:c}):{gid:c};p(a,function(a){b&&r("api.gameplay.log",{applicationId:c});q=a})}}});n.game.spapiIntegration?(v.enable(n,c),SpilGames("api.auth.getApplicationToken",{applicationId:n.portal.applicationId},function(a){-1===n.game.objectSettings.url.indexOf("?")&&(n.game.objectSettings.url+="?");n.game.objectSettings.url+="appToken="+
a.appAuth.token;n.game.objectSettings.url+="&o="+location.protocol+"//"+location.hostname;z.launch(n)})):(r.messageBroker.addRule("api.portal.force.auth",function(a,b){c.System.init(function(a){"login.finished"!==a.name&&"registration.finished"!=a.name||r("api.user.get",{cache:!0},function(a){b({data:{state:a&&a.userInfo&&"guest"!==a.userInfo.name?"logged-in":"logged-out"}})})});c.System.emit("popup.login.open",{force:!0})},r.messageBroker.FIRST|r.messageBroker.PROTECTED),z.launch(n));l.listen("gi.show.panel",
function(){c.System.emit("game.sidepanel.show")});l.listen("gi.show.zoombar",function(){c.System.emit("game.zoom.show")});SpilGames.Events&&SpilGames.Events.subscribe("portal.forceauthentication",function(){c.System.emit("popup.login.open")});l.listen("gi.game.loaded",function(){/Firefox/.test(navigator.userAgent)&&n.game.detailedType&&n.game.detailedType.social&&window.setTimeout(function(){d.get("#theGame #iframegame").style.height=(parseInt(n.game.objectSettings.height)+120).toString()+"px"},1500);
c.Widget.emit("recent.played.games.update",{appid:n.portal.applicationId});SpilGames.Events&&SpilGames.Events.subscribe("invitefriends.request",function(){b?c.System.emit("popup.social_invite.open"):c.System.emit("popup.register.open")})});c.System.init(function(b){switch(b.name){case "game.zoom.in":B(b.body.size,function(a,b,d){c.System.emit("game.area.increase",{ratio:d,game:{height:a,width:b}})});break;case "game.zoom.out":B(b.body.size,function(a,b,d){c.System.emit("game.area.decrease",{ratio:d,
game:{height:a,width:b}})});break;case "ad.preroll.finish":f&&(f.style.height=0,f.style.overflow="hidden");break;case "gi.game.show":e.hasClass(a,"activeFeedbackScreen")||e.addClass(a,"activeFeedbackScreen");break;case "gi.game.hide":e.hasClass(a,"activeFeedbackScreen")&&e.removeClass(a,"activeFeedbackScreen")}});(n.game.achievements||n.game.highscores)&&s.init(n.portal.vsn,function(){b?(s.on("UPDATE_HIGHSCORE",function(a){c.System.emit("game.update.highscore",a)}),s.on("UPDATE_ACHIEVEMENT",function(a){c.System.emit("game.update.achievement",
a)}),s.on("UPDATE_GALLERY",function(a){c.System.emit("game.update.gallery",a)})):(s.on("UPDATE_HIGHSCORE_FAILED",function(a){c.System.emit("game.update.highscore.failed",a)}),s.on("UPDATE_ACHIEVEMENT_FAILED",function(a){c.System.emit("game.update.achievement.failed",a)}),s.on("UPDATE_GALLERY_FAILED",function(a){c.System.emit("game.update.gallery.failed",a)}))});r.subscribe("api.portal.overlay.*",function(){switch(this.event.cleanType){case "api.portal.overlay.show":e.hasClass(a,"activeFeedbackScreen")&&
e.removeClass(a,"activeFeedbackScreen");break;case "api.portal.overlay.hide":e.hasClass(a,"activeFeedbackScreen")||e.addClass(a,"activeFeedbackScreen")}});r.subscribe("api.event.auth.changed",function(){n.portal.applicationId&&r("api.auth.getApplicationToken",{applicationId:n.portal.applicationId},function(){})});SpilGames.Events&&SpilGames.Events.subscribe("portal.adjustheight",function(a){var b=document.getElementById("iframegame");a&&a.height&&b&&(b.style.height=a.height+"px")})});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIMonitor",deps:"SWP EventTracker GIController JSLib Net Utils".split(" "),module:function(){var c,e=!1;if(!c)return c=function(c,r,z,d,h,s){var v=z.eventCodeMap,n={},f=function(b,a,c){s.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,c,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,c,!0]));var e=s.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),f=e?"ms":"c",e=e?c:1,q=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+q+"."+b+"."+a+"]="+e+f;n.monitoring&&n.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+q+"."+n.monitoring.bucket+"."+b+"."+a+"]="+e+f);0<e&&("c"===f?1===e:1)&&h.send({url:m,type:"GET"},s.emptyFn);d("tracker.event.track",{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,eventValue:c})},q={error:function(b){var a=v.error;
b=b.data;switch(b.code){case a.USER_DATA_MISSING:f("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);f("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:f("error","missingBrowserFeature")}},warning:function(b){var a=v.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:f("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:f("warning","prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:f("warning",
"prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:f("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:f("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:f("warning","midrollTimeout",b.waited)}},update:function(b){var a=v.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&f("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&f("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:f("update","initialized")}}};
return{init:function(b){n=b;e||(e=!0,c.init("game"),b=window.publishingHost,void 0===b?f("update","publishingHostUndefined",b):"unknown"===b?f("update","publishingHostUnknown",b):f("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":q.error(a);break;case "gi.warning":q.warning(a);break;case "gi.update":q.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&f("update","timeToPlay",a.timeToPlay);a.displayGame&&f("update","displayGame",a.displayGame);a.prerollDisplayDuration&&
f("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&f("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&f("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&f("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&f("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&f("update","progressBarStart",a.progressBarStart);a.progressBarDuration&&f("update","progressBarDuration",a.progressBarDuration);
a.progressBarError&&f("warning","progressBarError",a.progressBarError);a.loadDuration&&f("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":f("warning","decodeAuthCookieFailure");break;case "appToken":f("error","appToken");break;case "getCurrentUser":f("error","getCurrentUser")}}},!0))}}}}()});/*
 2013, Spil Games
*/
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,e){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",e)},updateCache:function(c,e){e&&_SG.Settings.set("auth.uid",e);SpilGames.Events.publish("auth.login",{hash:c,uid:e,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(e){c.call(this,!0,e,null)},onfailure:function(e){c.call(this,!1,null,e)}})}}}});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Jeroen Reurings <jeroen.reurings@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,e){var l,r=!1;l||(l=function(l,d,h,s,v,n,f){var q={},b,a={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,INITIALIZED:11,
MIDROLL_ALIVE:12,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},B={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},p,g,t=!1,m=function(){var a=[],b=[],c=function(b,c){a[b]||(a[b]=[]);return a[b].push(c)-1},e=function(a){var c=!1;b[a]&&(c=!0);return c},f=function(b,c){a[b]&&a[b][c]&&(a[b][c]=null)},g=function(){h.System.init(function(c){var k=c.name;b[k]=c;(k=a[k])&&d.each(k,function(a){"function"===
typeof a&&a(c)})},!0);g=function(){}};return{subscribe:c,unsubscribe:f,unsubscribeAll:function(b){delete a[b]},waiton:function(a,d){if(e(a))d(b[a]);else{var w=c(a,function(a){f("eventName",w);d(a)});return w}},isFired:e,init:g}}(),u=function(a){l(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var c=!1;if(0<b.major||0<b.minor||0<b.release)c=!0;a(c)})},F=function(){var a=!1,b=g.game.requiredFeatures;d.isObject(b)&&0<d.size(b)&&d.each(b,function(b){!0===b&&(a=!0)});return a},A=function(){var a=
b.states,c;u(function(k){c=a.PRE_FETCHING_GAME;!1===k&&(c=a.PLUGIN_MISSING);b.transitionTo(c)})},C=function(){var a=b.states,c=a.LISTENING_TO_ADVERTISING,k;d.each(g.game.requiredFeatures,function(b,d){k=B[d];!0===b&&"function"===typeof f[k]&&!1===f[k]()&&(c=a.FEATURE_MISSING)});b.transitionTo(c)},x=function(){m.isFired("ad.preroll.finish")||l(["LightSWFObject"],function(b){var c=g.game.preloader,d={data:c.src+"?url="+encodeURIComponent(g.game.settings.movie),width:"1",height:"1"};l.subscribe("game.prefetcher.error",
function(b){h.System.emit("gi.warning",{code:a.warning.PRE_FETCH_ERROR,flashError:b})});b.createSWF(d,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},c.domId);t=!0});b.transitionTo(b.states.LISTENING_TO_ADVERTISING)},D=function(){var d=m.isFired("ad.preroll.heartbeat"),e=m.isFired("ad.preroll.start"),k=g.preroll.heartbeatTime,f=function(){h.System.emit("gi.update",{code:a.update.PREROLL_ALIVE,fetchTime:v.stop("prerollFetchTime")})},
q=function(){h.System.emit("gi.update",{code:a.update.PREROLL_FAKE_START})};!0===d&&f();!0===e&&q();v.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){q()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(p);d||(d=!0,f());p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.PREROLL_NO_HEARTBEAT,waited:k});b.transitionTo(b.states.WAITING_ON_USERDATA)},k)});m.waiton("ad.preroll.finish",function(){p&&c.clearTimeout(p);b.transitionTo(b.states.WAITING_ON_USERDATA)});
b.transitionTo(b.states.WAITING_ON_PRE_ROLL)},E=function(){var b=0,d=g.midroll.heartbeatTime,k=g.midroll.maxWaitingTime,e=!1,f=function(){c.clearTimeout(p);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");h.System.emit("gi.update",{code:a.update.MIDROLL_FINISHED,occurrence:b});h.System.emit("gi.update",{code:a.update.ABORT_MIDROLL});e=!1};m.subscribe("ad.midroll.start",function(){if(!e){var g=!1;e=!0;b+=1;v.start("midrollFetchTime");p=c.setTimeout(function(){h.System.emit("gi.warning",
{code:a.warning.MIDROLL_TIMEOUT,waited:k,occurrence:b});f()},k);h.System.emit("gi.update",{code:a.update.MIDROLL_REQUESTED,occurrence:b});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(p);g||(g=!0,h.System.emit("gi.update",{code:a.update.MIDROLL_ALIVE,fetchTime:v.stop("midrollFetchTime"),occurrence:b}));p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.MIDROLL_NO_HEARTBEAT,waited:d,occurrence:b});f()},d)});m.subscribe("ad.midroll.finish",function(){f()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var d=
g.preroll.maxWaitingTime;p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.PREROLL_TIMEOUT,waited:d});b.transitionTo(b.states.WAITING_ON_USERDATA)},d)}},H=function(){c.clearTimeout(p);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");m.unsubscribeAll("ad.preroll.finish");var d=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});
h.System.emit("gi.update",{code:a.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(a){var k=b.states,e=k.INTEGRATING_GAME;d&&c.clearTimeout(d);!a.data||a.data.isError?e=k.INTEGRATION_ERROR:q=a.data;b.transitionTo(e)})},I=function(){var e=b.states.GAME_INTEGRATED,f=q.auth,k=g.game.settings,p=g.game.preloader,m;if(f&&d.isObject(f)&&!f.isError)for(m in f)f.hasOwnProperty(m)&&(k.flashvars+="&"+m+"="+f[m]);g&&g.portal&&g.portal.appToken&&(k.flashvars+="&appToken="+g.portal.appToken);
l(["LightSWFObject"],function(d){var f={data:k.movie,width:k.width,height:k.height},y={base:k.base,quality:"autohigh",allowFullScreen:k.allowFullScreen,wmode:k.wmode,allowScriptAccess:k.allowScriptAccess,scale:k.scale,flashVars:k.flashvars,bgcolor:k.bgcolor,hasPriority:"true"},g=function(){d.createSWF(f,y,k.domId);h.System.emit("gi.update",{code:a.update.GAME_EMBEDDED});b.transitionTo(e)};k.allowNetworking&&(y.allowNetworking=k.allowNetworking);t?(t=!1,d.removeSWF(p.domId),c.setTimeout(function(){g()},
20)):g()})};b={states:{INITIALIZED:0,PLUGIN_DETECTION:1,FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(a){h.Widget.emit(b.eventNamespace,{state:a})},flowController:function(c){var f=b.states;switch(c.data.state){case f.INITIALIZED:var k=b.states;c=k.LISTENING_TO_ADVERTISING;
var f=!1,p,m,l;g&&(p=g.game,m=g.preroll,l=g.midroll);d.isObject(g)&&d.isObject(p)&&d.isObject(m)&&d.isObject(l)&&d.isString(p.type)&&(d.contains(p.type,"DomObject")||d.contains(p.type,"iframe"))&&d.isNumber(m.maxWaitingTime)&&d.isNumber(l.maxWaitingTime)&&d.isNumber(m.heartbeatTime)&&d.isNumber(l.heartbeatTime)&&(f=!0);if(!f)throw k={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",
eventLabel:"GameIntegration module, exception:"+k.type+" - "+k.message,eventValue:1}),k;"DomObject"===g.game.type?c=k.PLUGIN_DETECTION:F()&&(c=k.FEATURE_DETECTION);b.transitionTo(c);break;case f.PLUGIN_DETECTION:A();break;case f.FEATURE_DETECTION:C();break;case f.PRE_FETCHING_GAME:x();break;case f.PLUGIN_MISSING:h.System.emit("gi.error",{code:a.error.PLUGIN_MISSING,pluginName:"flash"});h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});break;case f.FEATURE_MISSING:h.System.emit("gi.error",{code:a.error.FEATURE_MISSING});
h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});break;case f.LISTENING_TO_ADVERTISING:D();break;case f.WAITING_ON_PRE_ROLL:G();break;case f.WAITING_ON_USERDATA:H();break;case f.INTEGRATING_GAME:"DomObject"===g.game.type&&I();if("iframe"===g.game.type){p=b.states.GAME_INTEGRATED;f=g.game.settings;m=e.getElementById(f.domId);l={};d.isObject(q.auth)&&(l=d.combine(q.auth,l));d.isObject(g.portal)&&g.portal.siteId&&g.portal.channelId&&(l=d.combine({siteid:g.portal.siteId,channelid:g.portal.channelId,
UID:g.portal.sgid||""},l),l=g.portal.authenticated&&!0===g.portal.authenticated?d.combine({hash:g.portal.appToken||"",username:g.portal.username||""},l):d.combine({hash:"",username:""},l));d.isObject(q.other)&&(l=d.combine(q.other,l));m.width=f.width;m.height=f.height;c=l;var n,v,t;l="";f=f.url.replace("###DOMAIN###",window.location.hostname);f=f.replace("###CACHE_PP###","");t=document.createElement("a");var r;t.href=f;r="/"===t.pathname.charAt(0)?t.pathname:"/"+t.pathname;n=t.protocol;f=t.search;
v=t.hash;t=t.host;for(k in c)c.hasOwnProperty(k)&&(l+="&"+k+"="+c[k]);k=n+"//"+t+r||"";k=0<f.length?k+encodeURI(f+l):k+("?"+encodeURI(l.substring(1)));m.src=k+(v||"");h.System.emit("gi.update",{code:a.update.GAME_EMBEDDED});b.transitionTo(p)}break;case f.INTEGRATION_ERROR:h.System.emit("gi.error",{code:a.error.USER_DATA_MISSING});break;case f.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),s.emit("gi.game.loaded")}},start:function(){h.Widget.init(b.flowController)}};return{init:function(c){g=
c;g.game.objectSettings&&(g.game.settings=g.game.objectSettings);if(r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;h.init("game");m.init();b.start();h.System.emit("gi.update",{code:a.update.INITIALIZED});b.transitionTo(b.states.INITIALIZED)},eventCodeMap:a}});return l}(window,document)});/*
: 2013, SpilGames
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;c||(c=function(c,l,r,z,d,h){return{launch:function(c){r.init(c);z.init(c);var e=c.hooks;if(l.isFunction(e.onPrerollFinish))d.onState("afterpreroll",function(){e.onPrerollFinish()});if(l.isFunction(e.onDisplayGame))d.onState("displaygame",function(){e.onDisplayGame()});if(l.isFunction(e.onMidroll))d.onState("onmidroll",function(){e.onMidroll()},!0);if(l.isFunction(e.afterMidroll))d.onState("aftermidroll",
function(){e.afterMidroll()},!0);d.init(c);h.init(c)}}});return c}(window,document)});SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,e){var l,r=!1;l||(l=function(l,d,h,s,v,n){var f={backgroundScreen:e.getElementById("backgroundScreen"),defaultScreen:e.getElementById("defaultLoadingScreen"),waitingForUserData:e.getElementById("waitingForUserData"),userDataNotResponding:e.getElementById("userDataNotResponding"),userDataMissing:e.getElementById("userDataMissing"),loadingDomObjectGame:e.getElementById("loadingDomObjectGame"),
loadingIframeGame:e.getElementById("loadingIframeGame"),errorLoadingGame:e.getElementById("errorLoadingGame"),missingPlugin:e.getElementById("missingPlugin"),missingFeature:e.getElementById("missingFeature"),displayGame:e.getElementById("theGame"),preRoll:e.getElementById("videoPreroll300x250"),midRoll:e.getElementById("sgAdOgGp300x250"),midrollLoading:e.getElementById("midrollLoadingScreen")},q=e.getElementById("game-integration"),b={},a=[],B=["displaygame","afterpreroll","onmidroll","aftermidroll"],
p=f.defaultScreen,g={},t,m=!1,u=function(a){p.className=p.className.replace("activeFeedbackScreen","");p=f[a];p.className+=" activeFeedbackScreen"},F=function(){v.subscribe("game.ad.accepted",function(a){l.isObject(a)&&!0===a.displayAd&&l.isString(a.bgImage)&&!l.isEmpty(a.bgImage)&&(t=a.bgImage)})},A=function(b){var d=a[b];d&&l.each(d,function(a,b){a.persistent&&!0===a.persistent||delete d[b];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),x=function(){if(!m){m=!0;u("displayGame");A("displaygame");try{F();d.System.emit("gi.portal.feedback",{displayGame:b.portal.contentarId});var a=C();a&&d.System.emit("gi.portal.feedback",{timeToPlay:h.now()-a});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),d.System.emit("gi.portal.feedback",
{timeToFirstPlay:h.now()-a.sessionStart}))})}catch(c){}}},D=function(){var a=e.getElementById(b.game.settings.domId),c=e.getElementById("progress-container"),f,w=function(){try{(f=h.stop("iframeLoadDuration"))&&d.System.emit("gi.portal.feedback",{loadDuration:f})}catch(a){}x()};h.start("iframeLoadDuration");a.completed?x():(c&&(c.style.display="none"),u("loadingIframeGame"),a.attachEvent?a.attachEvent("onload",function(){w()}):a.onload=function(){w()})},E=function(){var a=e.getElementById(b.game.settings.domId),
f=e.getElementById("progress-bar"),g=e.getElementById("progress-percentage"),w,y,k,l,p=0,q=function(){return a&&"function"===typeof a.PercentLoaded||c.attachEvent&&"number"===typeof a.PercentLoaded()},m=function(){k=a.PercentLoaded();if(98<k||0>k)x();else{u("loadingDomObjectGame");f.width=k+"%";g&&(g.innerHTML=k+"%");try{h.start("progressBarDuration"),d.System.emit("gi.portal.feedback",{progressBarStart:k})}catch(b){}w=c.setInterval(function(){k=q()?a.PercentLoaded():void 0;if("undefined"!==typeof k&&
-1<k&&100>k)g&&(g.innerHTML=k+"%"),f.style.width=k+"%";else{c.clearInterval(w);g&&(g.innerHTML="100%");f.style.width="99%";c.setTimeout(function(){x()},500);try{(y=h.stop("progressBarDuration"))&&d.System.emit("gi.portal.feedback",{progressBarDuration:y+500})}catch(b){}}},100)}};try{l=c.setInterval(function(){p+=1;q()&&(c.clearInterval(l),m());10<=p&&(c.clearInterval(l),x(),d.System.emit("gi.portal.feedback",{progressBarError:b.portal.contentarId}))},100)}catch(n){x(),d.System.emit("gi.portal.feedback",
{progressBarError:b.portal.contentarId})}};return{init:function(a){r||(r=!0,b=a,g=n.eventCodeMap,d.init("game"),d.System.init(function(a){switch(a.name){case "gi.update":var c=g.update;a=a.data;var e;switch(a.code){case c.WAITING_FOR_USER_DATA:u("waitingForUserData");try{var y=h.stop("prerollDisplayDuration");y&&d.System.emit("gi.portal.feedback",{prerollDisplayDuration:y})}catch(k){}A("afterpreroll");break;case c.PREROLL_FAKE_START:u("preRoll");break;case c.PREROLL_ALIVE:u("preRoll");try{(e=C())&&
d.System.emit("gi.portal.feedback",{timeToPreroll:h.now()-e}),h.start("prerollDisplayDuration")}catch(l){}break;case c.MIDROLL_REQUESTED:t&&(f.backgroundScreen.style.cssText="background-image: url("+t+");",491<parseInt(f.displayGame.style.height,10)&&(q.style.height=f.displayGame.style.height),f.backgroundScreen.style.display="block",t=void 0);u("midrollLoading");try{A("onmidroll")}catch(p){}break;case c.MIDROLL_ALIVE:u("midRoll");try{h.start("midrollDisplayDuration"),e=C(),a.occurrence&&1===a.occurrence&&
e&&d.System.emit("gi.portal.feedback",{timeToFirstMidroll:h.now()-e})}catch(m){}break;case c.MIDROLL_FINISHED:"block"===f.backgroundScreen.style.display&&(f.backgroundScreen.style.background="#FFF",f.backgroundScreen.style.display="none");q.style.height="auto";u("displayGame");try{A("aftermidroll");var n=h.stop("midrollDisplayDuration");n&&d.System.emit("gi.portal.feedback",{midrollDisplayDuration:n})}catch(s){}break;case c.GAME_EMBEDDED:"DomObject"===b.game.type&&E(),"iframe"===b.game.type&&D()}break;
case "gi.error":c=g.error;switch(a.data.code){case c.USER_DATA_MISSING:u("userDataMissing");break;case c.PLUGIN_MISSING:u("missingPlugin");break;case c.FEATURE_MISSING:u("missingFeature")}break;case "gi.warning":a.data.code===g.warning.USER_DATA_NOT_RESPONDING&&u("userDataNotResponding")}},!0))},onState:function(b,c,d){0<=l.indexOf(B,b)&&(a[b]||(a[b]=[]),a[b].push({callback:c,persistent:d}))}}});return l}(window,window.document)});/*
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,e=!1;c||(c=function(c,r,z,d,h){var s,v=function(c){var d;z.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(b){b&&b.auth&&b.auth.token?r("api.user.get",{cache:!0},function(a){d=a&&a.userInfo?{username:a.userInfo.name,hash:b.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:a&&a.error||"unknown error"};c.call(this,d)}):(d={isError:!0,
message:"Failed to retrieve the user hash",error:b&&b.error||"unknown error"},c.call(this,d))})},n=function(c){var d={};r("api.account.getApplicationToken",{cache:!0,applicationId:(s.portal.applicationId||s.portal.contentarId).toString()},function(b){try{if(!b.appAuth||b.isError)SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:b.error});else{var a=b.appAuth.token;d.appToken=a;h.updateCache(a,s.portal.sgid);
h.getUserInfo(function(a,b,e){a?c(d):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:e})})}}catch(e){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:e})}})};return{init:function(d){s=d;if(!e)switch(e=!0,c.init("game"),s.game.needs){case "preliminaryAuth":v(function(d){c.System.emit("gi.userdata.ready",{auth:d})});break;case "auth":h.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);n(function(d){var b={auth:d},a;a:{a=window;
a=a.location.href.slice(a.location.href.indexOf("?")+1).split("&");var e=a.length,f,h,n;for(n=0;n<e;n+=1)if(f=a[n].split("="),h=f[0],f=f[1],"src"===h){a=f;break a}a=null}a&&(b.other={src:a});d.isError&&(b.isError=!0,c.System.emit("gi.userdata.failure",d));c.System.emit("gi.userdata.ready",b)});break;default:c.System.emit("gi.userdata.ready",{})}}}});return c}()});/*
: 2013, SpilGames
 @author Laurens van Hees <performance@spilgames.com>
 2013, Spil Games
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Jeroen Reurings <jeroen.reurings@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
: 2013, SpilGames
 @author Robby de Rijk <robby.derijk@spilgames.com>
 @author Laurens van Hees <performance@spilgames.com>
*/
SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;c||(c=function(c,l,r,z,d,h){return{launch:function(c){r.init(c);z.init(c);var e=c.hooks;if(l.isFunction(e.onPrerollFinish))d.onState("afterpreroll",function(){e.onPrerollFinish()});if(l.isFunction(e.onDisplayGame))d.onState("displaygame",function(){e.onDisplayGame()});if(l.isFunction(e.onMidroll))d.onState("onmidroll",function(){e.onMidroll()},!0);if(l.isFunction(e.afterMidroll))d.onState("aftermidroll",
function(){e.afterMidroll()},!0);d.init(c);h.init(c)}}});return c}(window,document)});
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,e){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",e)},updateCache:function(c,e){e&&_SG.Settings.set("auth.uid",e);SpilGames.Events.publish("auth.login",{hash:c,uid:e,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(e){c.call(this,!0,e,null)},onfailure:function(e){c.call(this,!1,null,e)}})}}}});
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,e){var l,r=!1;l||(l=function(l,d,h,s,v,n,f){var q={},b,a={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,INITIALIZED:11,
MIDROLL_ALIVE:12,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},B={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},p,g,t=!1,m=function(){var a=[],b=[],c=function(b,c){a[b]||(a[b]=[]);return a[b].push(c)-1},e=function(a){var c=!1;b[a]&&(c=!0);return c},f=function(b,c){a[b]&&a[b][c]&&(a[b][c]=null)},g=function(){h.System.init(function(c){var e=c.name;b[e]=c;(e=a[e])&&d.each(e,function(a){"function"===
typeof a&&a(c)})},!0);g=function(){}};return{subscribe:c,unsubscribe:f,unsubscribeAll:function(b){delete a[b]},waiton:function(a,d){if(e(a))d(b[a]);else{var h=c(a,function(a){f("eventName",h);d(a)});return h}},isFired:e,init:g}}(),u=function(a){l(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var c=!1;if(0<b.major||0<b.minor||0<b.release)c=!0;a(c)})},F=function(){var a=!1,b=g.game.requiredFeatures;d.isObject(b)&&0<d.size(b)&&d.each(b,function(b){!0===b&&(a=!0)});return a},A=function(){var a=
b.states,c;u(function(d){c=a.PRE_FETCHING_GAME;!1===d&&(c=a.PLUGIN_MISSING);b.transitionTo(c)})},C=function(){var a=b.states,c=a.LISTENING_TO_ADVERTISING,e;d.each(g.game.requiredFeatures,function(b,d){e=B[d];!0===b&&"function"===typeof f[e]&&!1===f[e]()&&(c=a.FEATURE_MISSING)});b.transitionTo(c)},x=function(){m.isFired("ad.preroll.finish")||l(["LightSWFObject"],function(b){var c=g.game.preloader,d={data:c.src+"?url="+encodeURIComponent(g.game.settings.movie),width:"1",height:"1"};l.subscribe("game.prefetcher.error",
function(b){h.System.emit("gi.warning",{code:a.warning.PRE_FETCH_ERROR,flashError:b})});b.createSWF(d,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},c.domId);t=!0});b.transitionTo(b.states.LISTENING_TO_ADVERTISING)},D=function(){var d=m.isFired("ad.preroll.heartbeat"),e=m.isFired("ad.preroll.start"),f=g.preroll.heartbeatTime,l=function(){h.System.emit("gi.update",{code:a.update.PREROLL_ALIVE,fetchTime:v.stop("prerollFetchTime")})},
q=function(){h.System.emit("gi.update",{code:a.update.PREROLL_FAKE_START})};!0===d&&l();!0===e&&q();v.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){q()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(p);d||(d=!0,l());p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.PREROLL_NO_HEARTBEAT,waited:f});b.transitionTo(b.states.WAITING_ON_USERDATA)},f)});m.waiton("ad.preroll.finish",function(){p&&c.clearTimeout(p);b.transitionTo(b.states.WAITING_ON_USERDATA)});
b.transitionTo(b.states.WAITING_ON_PRE_ROLL)},E=function(){var b=0,d=g.midroll.heartbeatTime,e=g.midroll.maxWaitingTime,f=!1,l=function(){c.clearTimeout(p);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");h.System.emit("gi.update",{code:a.update.MIDROLL_FINISHED,occurrence:b});h.System.emit("gi.update",{code:a.update.ABORT_MIDROLL});f=!1};m.subscribe("ad.midroll.start",function(){if(!f){var g=!1;f=!0;b+=1;v.start("midrollFetchTime");p=c.setTimeout(function(){h.System.emit("gi.warning",
{code:a.warning.MIDROLL_TIMEOUT,waited:e,occurrence:b});l()},e);h.System.emit("gi.update",{code:a.update.MIDROLL_REQUESTED,occurrence:b});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(p);g||(g=!0,h.System.emit("gi.update",{code:a.update.MIDROLL_ALIVE,fetchTime:v.stop("midrollFetchTime"),occurrence:b}));p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.MIDROLL_NO_HEARTBEAT,waited:d,occurrence:b});l()},d)});m.subscribe("ad.midroll.finish",function(){l()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var d=
g.preroll.maxWaitingTime;p=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.PREROLL_TIMEOUT,waited:d});b.transitionTo(b.states.WAITING_ON_USERDATA)},d)}},H=function(){c.clearTimeout(p);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");m.unsubscribeAll("ad.preroll.finish");var d=c.setTimeout(function(){h.System.emit("gi.warning",{code:a.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});
h.System.emit("gi.update",{code:a.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(a){var e=b.states,f=e.INTEGRATING_GAME;d&&c.clearTimeout(d);!a.data||a.data.isError?f=e.INTEGRATION_ERROR:q=a.data;b.transitionTo(f)})},I=function(){var e=b.states.GAME_INTEGRATED,f=q.auth,k=g.game.settings,m=g.game.preloader,p;if(f&&d.isObject(f)&&!f.isError)for(p in f)f.hasOwnProperty(p)&&(k.flashvars+="&"+p+"="+f[p]);g&&g.portal&&g.portal.appToken&&(k.flashvars+="&appToken="+g.portal.appToken);
l(["LightSWFObject"],function(d){var f={data:k.movie,width:k.width,height:k.height},g={base:k.base,quality:"autohigh",allowFullScreen:k.allowFullScreen,wmode:k.wmode,allowScriptAccess:k.allowScriptAccess,scale:k.scale,flashVars:k.flashvars,bgcolor:k.bgcolor,hasPriority:"true"},l=function(){d.createSWF(f,g,k.domId);h.System.emit("gi.update",{code:a.update.GAME_EMBEDDED});b.transitionTo(e)};k.allowNetworking&&(g.allowNetworking=k.allowNetworking);t?(t=!1,d.removeSWF(m.domId),c.setTimeout(function(){l()},
20)):l()})};b={states:{INITIALIZED:0,PLUGIN_DETECTION:1,FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(a){h.Widget.emit(b.eventNamespace,{state:a})},flowController:function(c){var f=b.states;switch(c.data.state){case f.INITIALIZED:var k=b.states;c=k.LISTENING_TO_ADVERTISING;
var f=!1,l,m,p;g&&(l=g.game,m=g.preroll,p=g.midroll);d.isObject(g)&&d.isObject(l)&&d.isObject(m)&&d.isObject(p)&&d.isString(l.type)&&(d.contains(l.type,"DomObject")||d.contains(l.type,"iframe"))&&d.isNumber(m.maxWaitingTime)&&d.isNumber(p.maxWaitingTime)&&d.isNumber(m.heartbeatTime)&&d.isNumber(p.heartbeatTime)&&(f=!0);if(!f)throw k={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",
eventLabel:"GameIntegration module, exception:"+k.type+" - "+k.message,eventValue:1}),k;"DomObject"===g.game.type?c=k.PLUGIN_DETECTION:F()&&(c=k.FEATURE_DETECTION);b.transitionTo(c);break;case f.PLUGIN_DETECTION:A();break;case f.FEATURE_DETECTION:C();break;case f.PRE_FETCHING_GAME:x();break;case f.PLUGIN_MISSING:h.System.emit("gi.error",{code:a.error.PLUGIN_MISSING,pluginName:"flash"});h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});break;case f.FEATURE_MISSING:h.System.emit("gi.error",{code:a.error.FEATURE_MISSING});
h.System.emit("gi.update",{code:a.update.ABORT_PREROLL});break;case f.LISTENING_TO_ADVERTISING:D();break;case f.WAITING_ON_PRE_ROLL:G();break;case f.WAITING_ON_USERDATA:H();break;case f.INTEGRATING_GAME:"DomObject"===g.game.type&&I();if("iframe"===g.game.type){l=b.states.GAME_INTEGRATED;f=g.game.settings;m=e.getElementById(f.domId);p={};d.isObject(q.auth)&&(p=d.combine(q.auth,p));d.isObject(g.portal)&&g.portal.siteId&&g.portal.channelId&&(p=d.combine({siteid:g.portal.siteId,channelid:g.portal.channelId,
UID:g.portal.sgid||""},p),p=g.portal.authenticated&&!0===g.portal.authenticated?d.combine({hash:g.portal.appToken||"",username:g.portal.username||""},p):d.combine({hash:"",username:""},p));d.isObject(q.other)&&(p=d.combine(q.other,p));m.width=f.width;m.height=f.height;c=p;var n,t,r;p="";f=f.url.replace("###DOMAIN###",window.location.hostname);f=f.replace("###CACHE_PP###","");r=document.createElement("a");var v;r.href=f;v="/"===r.pathname.charAt(0)?r.pathname:"/"+r.pathname;n=r.protocol;f=r.search;
t=r.hash;r=r.host;for(k in c)c.hasOwnProperty(k)&&(p+="&"+k+"="+c[k]);k=n+"//"+r+v||"";k=0<f.length?k+encodeURI(f+p):k+("?"+encodeURI(p.substring(1)));m.src=k+(t||"");h.System.emit("gi.update",{code:a.update.GAME_EMBEDDED});b.transitionTo(l)}break;case f.INTEGRATION_ERROR:h.System.emit("gi.error",{code:a.error.USER_DATA_MISSING});break;case f.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),s.emit("gi.game.loaded")}},start:function(){h.Widget.init(b.flowController)}};return{init:function(c){g=
c;g.game.objectSettings&&(g.game.settings=g.game.objectSettings);if(r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;h.init("game");m.init();b.start();h.System.emit("gi.update",{code:a.update.INITIALIZED});b.transitionTo(b.states.INITIALIZED)},eventCodeMap:a}});return l}(window,document)});
SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,e){var l,r=!1;l||(l=function(l,d,h,s,v,n){var f={backgroundScreen:e.getElementById("backgroundScreen"),defaultScreen:e.getElementById("defaultLoadingScreen"),waitingForUserData:e.getElementById("waitingForUserData"),userDataNotResponding:e.getElementById("userDataNotResponding"),userDataMissing:e.getElementById("userDataMissing"),loadingDomObjectGame:e.getElementById("loadingDomObjectGame"),
loadingIframeGame:e.getElementById("loadingIframeGame"),errorLoadingGame:e.getElementById("errorLoadingGame"),missingPlugin:e.getElementById("missingPlugin"),missingFeature:e.getElementById("missingFeature"),displayGame:e.getElementById("theGame"),preRoll:e.getElementById("videoPreroll300x250"),midRoll:e.getElementById("sgAdOgGp300x250"),midrollLoading:e.getElementById("midrollLoadingScreen")},q=e.getElementById("game-integration"),b={},a=[],B=["displaygame","afterpreroll","onmidroll","aftermidroll"],
p=f.defaultScreen,g={},t,m=!1,u=function(a){p.className=p.className.replace("activeFeedbackScreen","");p=f[a];p.className+=" activeFeedbackScreen"},F=function(){v.subscribe("game.ad.accepted",function(a){l.isObject(a)&&!0===a.displayAd&&l.isString(a.bgImage)&&!l.isEmpty(a.bgImage)&&(t=a.bgImage)})},A=function(b){var d=a[b];d&&l.each(d,function(a,b){a.persistent&&!0===a.persistent||delete d[b];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),x=function(){if(!m){m=!0;u("displayGame");A("displaygame");try{F();d.System.emit("gi.portal.feedback",{displayGame:b.portal.contentarId});var a=C();a&&d.System.emit("gi.portal.feedback",{timeToPlay:h.now()-a});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),d.System.emit("gi.portal.feedback",
{timeToFirstPlay:h.now()-a.sessionStart}))})}catch(c){}}},D=function(){var a=e.getElementById(b.game.settings.domId),c=e.getElementById("progress-container"),f,g=function(){try{(f=h.stop("iframeLoadDuration"))&&d.System.emit("gi.portal.feedback",{loadDuration:f})}catch(a){}x()};h.start("iframeLoadDuration");a.completed?x():(c&&(c.style.display="none"),u("loadingIframeGame"),a.attachEvent?a.attachEvent("onload",function(){g()}):a.onload=function(){g()})},E=function(){var a=e.getElementById(b.game.settings.domId),
f=e.getElementById("progress-bar"),g=e.getElementById("progress-percentage"),l,p,k,m,q=0,n=function(){return a&&"function"===typeof a.PercentLoaded||c.attachEvent&&"number"===typeof a.PercentLoaded()},s=function(){k=a.PercentLoaded();if(98<k||0>k)x();else{u("loadingDomObjectGame");f.width=k+"%";g&&(g.innerHTML=k+"%");try{h.start("progressBarDuration"),d.System.emit("gi.portal.feedback",{progressBarStart:k})}catch(b){}l=c.setInterval(function(){k=n()?a.PercentLoaded():void 0;if("undefined"!==typeof k&&
-1<k&&100>k)g&&(g.innerHTML=k+"%"),f.style.width=k+"%";else{c.clearInterval(l);g&&(g.innerHTML="100%");f.style.width="99%";c.setTimeout(function(){x()},500);try{(p=h.stop("progressBarDuration"))&&d.System.emit("gi.portal.feedback",{progressBarDuration:p+500})}catch(b){}}},100)}};try{m=c.setInterval(function(){q+=1;n()&&(c.clearInterval(m),s());10<=q&&(c.clearInterval(m),x(),d.System.emit("gi.portal.feedback",{progressBarError:b.portal.contentarId}))},100)}catch(t){x(),d.System.emit("gi.portal.feedback",
{progressBarError:b.portal.contentarId})}};return{init:function(a){r||(r=!0,b=a,g=n.eventCodeMap,d.init("game"),d.System.init(function(a){switch(a.name){case "gi.update":var c=g.update;a=a.data;var e;switch(a.code){case c.WAITING_FOR_USER_DATA:u("waitingForUserData");try{var l=h.stop("prerollDisplayDuration");l&&d.System.emit("gi.portal.feedback",{prerollDisplayDuration:l})}catch(k){}A("afterpreroll");break;case c.PREROLL_FAKE_START:u("preRoll");break;case c.PREROLL_ALIVE:u("preRoll");try{(e=C())&&
d.System.emit("gi.portal.feedback",{timeToPreroll:h.now()-e}),h.start("prerollDisplayDuration")}catch(p){}break;case c.MIDROLL_REQUESTED:t&&(f.backgroundScreen.style.cssText="background-image: url("+t+");",491<parseInt(f.displayGame.style.height,10)&&(q.style.height=f.displayGame.style.height),f.backgroundScreen.style.display="block",t=void 0);u("midrollLoading");try{A("onmidroll")}catch(m){}break;case c.MIDROLL_ALIVE:u("midRoll");try{h.start("midrollDisplayDuration"),e=C(),a.occurrence&&1===a.occurrence&&
e&&d.System.emit("gi.portal.feedback",{timeToFirstMidroll:h.now()-e})}catch(n){}break;case c.MIDROLL_FINISHED:"block"===f.backgroundScreen.style.display&&(f.backgroundScreen.style.background="#FFF",f.backgroundScreen.style.display="none");q.style.height="auto";u("displayGame");try{A("aftermidroll");var s=h.stop("midrollDisplayDuration");s&&d.System.emit("gi.portal.feedback",{midrollDisplayDuration:s})}catch(r){}break;case c.GAME_EMBEDDED:"DomObject"===b.game.type&&E(),"iframe"===b.game.type&&D()}break;
case "gi.error":c=g.error;switch(a.data.code){case c.USER_DATA_MISSING:u("userDataMissing");break;case c.PLUGIN_MISSING:u("missingPlugin");break;case c.FEATURE_MISSING:u("missingFeature")}break;case "gi.warning":a.data.code===g.warning.USER_DATA_NOT_RESPONDING&&u("userDataNotResponding")}},!0))},onState:function(b,c,d){0<=l.indexOf(B,b)&&(a[b]||(a[b]=[]),a[b].push({callback:c,persistent:d}))}}});return l}(window,window.document)});
SpilGames("spilgames.import",{name:"GIMonitor",deps:"SWP EventTracker GIController JSLib Net Utils".split(" "),module:function(){var c,e=!1;if(!c)return c=function(c,r,z,d,h,s){var v=z.eventCodeMap,n={},f=function(b,a,c){s.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,c,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,c,!0]));var f=s.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),e=f?"ms":"c",f=f?c:1,l=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+l+"."+b+"."+a+"]="+f+e;n.monitoring&&n.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+l+"."+n.monitoring.bucket+"."+b+"."+a+"]="+f+e);0<f&&("c"===e?1===f:1)&&h.send({url:m,type:"GET"},s.emptyFn);d("tracker.event.track",{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,eventValue:c})},q={error:function(b){var a=v.error;
b=b.data;switch(b.code){case a.USER_DATA_MISSING:f("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);f("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:f("error","missingBrowserFeature")}},warning:function(b){var a=v.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:f("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:f("warning","prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:f("warning",
"prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:f("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:f("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:f("warning","midrollTimeout",b.waited)}},update:function(b){var a=v.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&f("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&f("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:f("update","initialized")}}};
return{init:function(b){n=b;e||(e=!0,c.init("game"),b=window.publishingHost,void 0===b?f("update","publishingHostUndefined",b):"unknown"===b?f("update","publishingHostUnknown",b):f("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":q.error(a);break;case "gi.warning":q.warning(a);break;case "gi.update":q.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&f("update","timeToPlay",a.timeToPlay);a.displayGame&&f("update","displayGame",a.displayGame);a.prerollDisplayDuration&&
f("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&f("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&f("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&f("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&f("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&f("update","progressBarStart",a.progressBarStart);a.progressBarDuration&&f("update","progressBarDuration",a.progressBarDuration);
a.progressBarError&&f("warning","progressBarError",a.progressBarError);a.loadDuration&&f("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":f("warning","decodeAuthCookieFailure");break;case "appToken":f("error","appToken");break;case "getCurrentUser":f("error","getCurrentUser")}}},!0))}}}}()});
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,e=!1;c||(c=function(c,r,z,d,h){var s,v=function(c){var d;z.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(b){b&&b.auth&&b.auth.token?r("api.user.get",{cache:!0},function(a){d=a&&a.userInfo?{username:a.userInfo.name,hash:b.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:a&&a.error||"unknown error"};c.call(this,d)}):(d={isError:!0,
message:"Failed to retrieve the user hash",error:b&&b.error||"unknown error"},c.call(this,d))})},n=function(c){var d={};r("api.account.getApplicationToken",{cache:!0,applicationId:(s.portal.applicationId||s.portal.contentarId).toString()},function(b){try{if(!b.appAuth||b.isError)SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:b.error});else{var a=b.appAuth.token;d.appToken=a;h.updateCache(a,s.portal.sgid);
h.getUserInfo(function(a,b,e){a?c(d):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:e})})}}catch(e){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:e})}})};return{init:function(d){s=d;if(!e)switch(e=!0,c.init("game"),s.game.needs){case "preliminaryAuth":v(function(d){c.System.emit("gi.userdata.ready",{auth:d})});break;case "auth":h.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);n(function(d){var b={auth:d},a;a:{a=window;
a=a.location.href.slice(a.location.href.indexOf("?")+1).split("&");var f=a.length,e,h,n;for(n=0;n<f;n+=1)if(e=a[n].split("="),h=e[0],e=e[1],"src"===h){a=e;break a}a=null}a&&(b.other={src:a});d.isError&&(b.isError=!0,c.System.emit("gi.userdata.failure",d));c.System.emit("gi.userdata.ready",b)});break;default:c.System.emit("gi.userdata.ready",{})}}}});return c}()});SpilGames("spilgames.import",{name:"GIBootstrap",deps:"JSLib Utils GIUserData GIMonitor GIFeedback GIController".split(" "),module:function(){var c;return c||(c=function(c,l,r,z,d,h){return{launch:function(c){r.init(c);z.init(c);var e=c.hooks;l.isFunction(e.onPrerollFinish)&&d.onState("afterpreroll",function(){e.onPrerollFinish()});l.isFunction(e.onDisplayGame)&&d.onState("displaygame",function(){e.onDisplayGame()});l.isFunction(e.onMidroll)&&d.onState("onmidroll",function(){e.onMidroll()},!0);l.isFunction(e.afterMidroll)&&
d.onState("aftermidroll",function(){e.afterMidroll()},!0);d.init(c);h.init(c)}}}),c}(window,document)});
SpilGames("spilgames.import",{fullName:"SocialGateway",deps:[],module:function(){return{setSocialGatewayInfo:function(c,e){_SG.Settings.set("portal.site_id",c);_SG.Settings.set("portal.channel_id",e)},updateCache:function(c,e){e&&_SG.Settings.set("auth.uid",e);SpilGames.Events.publish("auth.login",{hash:c,uid:e,status:"success"})},getUserInfo:function(c){SpilGames.Users.getCurrentUser({onsuccess:function(e){c.call(this,!0,e,null)},onfailure:function(e){c.call(this,!1,null,e)}})}}}});
SpilGames("spilgames.import",{name:"GIController",deps:"JSLib Utils SWP SWPEvent StopWatch SocialGateway FeatureDetector".split(" "),module:function(c,e){var l,r=!1;return l||(l=function(l,d,h,s,v,n,f){var q,b,a,B={},p={error:{USER_DATA_MISSING:1,PLUGIN_MISSING:2,FEATURE_MISSING:17},warning:{USER_DATA_NOT_RESPONDING:3,PRE_FETCH_ERROR:4,PREROLL_NO_HEARTBEAT:9,PREROLL_TIMEOUT:10,MIDROLL_NO_HEARTBEAT:14,MIDROLL_TIMEOUT:15},update:{WAITING_FOR_USER_DATA:5,GAME_EMBEDDED:6,ABORT_PREROLL:7,PREROLL_ALIVE:8,
INITIALIZED:11,MIDROLL_ALIVE:12,MIDROLL_FINISHED:13,ABORT_MIDROLL:16,PREROLL_FAKE_START:18}},g={flexboxlegacy:"flexboxLegacy",canvas:"canvas",canvastext:"canvasText",localstorage:"localStorage",applicationcache:"applicationCache"},t=!1,m=function(){var a=[],b=[],c=function(b,c){return a[b]||(a[b]=[]),a[b].push(c)-1},e=function(a){var c=!1;return b[a]&&(c=!0),c},f=function(b,c){a[b]&&a[b][c]&&(a[b][c]=null)},g=function(){h.System.init(function(c){var e;e=c.name;b[e]=c;(e=a[e])&&d.each(e,function(a){"function"==
typeof a&&a(c)})},!0);g=function(){}};return{subscribe:c,unsubscribe:f,unsubscribeAll:function(b){delete a[b]},waiton:function(a,d){if(!e(a)){var h=c(a,function(a){f("eventName",h);d(a)});return h}d(b[a])},isFired:e,init:g}}(),u=function(a){l(["LightSWFObject"],function(b){b=b.getFlashPlayerVersion();var c=!1;(0<b.major||0<b.minor||0<b.release)&&(c=!0);a(c)})},F=function(){var b=!1,c=a.game.requiredFeatures;return d.isObject(c)&&0<d.size(c)&&d.each(c,function(a){!0===a&&(b=!0)}),b},A=function(){var a,
b=q.states;u(function(c){a=b.PRE_FETCHING_GAME;!1===c&&(a=b.PLUGIN_MISSING);q.transitionTo(a)})},C=function(){var b,c=q.states,e=c.LISTENING_TO_ADVERTISING;d.each(a.game.requiredFeatures,function(a,d){b=g[d];!0===a&&"function"==typeof f[b]&&!1===f[b]()&&(e=c.FEATURE_MISSING)});q.transitionTo(e)},x=function(){!m.isFired("ad.preroll.finish")&&l(["LightSWFObject"],function(b){var c=a.game.preloader,d={data:c.src+"?url="+encodeURIComponent(a.game.settings.movie),width:"1",height:"1"};l.subscribe("game.prefetcher.error",
function(a){h.System.emit("gi.warning",{code:p.warning.PRE_FETCH_ERROR,flashError:a})});b.createSWF(d,{quality:"low",flashvars:"debug=false",allowFullScreen:!1,wmode:"direct",allowScriptAccess:"always",hasPriority:"true"},c.domId);t=!0});q.transitionTo(q.states.LISTENING_TO_ADVERTISING)},D=function(){var d=m.isFired("ad.preroll.heartbeat"),e=m.isFired("ad.preroll.start"),f=a.preroll.heartbeatTime,g=function(){h.System.emit("gi.update",{code:p.update.PREROLL_ALIVE,fetchTime:v.stop("prerollFetchTime")})},
l=function(){h.System.emit("gi.update",{code:p.update.PREROLL_FAKE_START})};!0===d&&g();!0===e&&l();v.start("prerollFetchTime");m.subscribe("ad.preroll.start",function(){l()});m.subscribe("ad.preroll.heartbeat",function(){c.clearTimeout(b);d||(d=!0,g());b=c.setTimeout(function(){h.System.emit("gi.warning",{code:p.warning.PREROLL_NO_HEARTBEAT,waited:f});q.transitionTo(q.states.WAITING_ON_USERDATA)},f)});m.waiton("ad.preroll.finish",function(){b&&c.clearTimeout(b);q.transitionTo(q.states.WAITING_ON_USERDATA)});
q.transitionTo(q.states.WAITING_ON_PRE_ROLL)},E=function(){var d=0,e=a.midroll.heartbeatTime,f=a.midroll.maxWaitingTime,g=!1,l=function(){c.clearTimeout(b);m.unsubscribeAll("ad.midroll.heartbeat");m.unsubscribeAll("ad.midroll.finish");h.System.emit("gi.update",{code:p.update.MIDROLL_FINISHED,occurrence:d});h.System.emit("gi.update",{code:p.update.ABORT_MIDROLL});g=!1};m.subscribe("ad.midroll.start",function(){if(!g){var a=!1;g=!0;d+=1;v.start("midrollFetchTime");b=c.setTimeout(function(){h.System.emit("gi.warning",
{code:p.warning.MIDROLL_TIMEOUT,waited:f,occurrence:d});l()},f);h.System.emit("gi.update",{code:p.update.MIDROLL_REQUESTED,occurrence:d});m.subscribe("ad.midroll.heartbeat",function(){c.clearTimeout(b);a||(a=!0,h.System.emit("gi.update",{code:p.update.MIDROLL_ALIVE,fetchTime:v.stop("midrollFetchTime"),occurrence:d}));b=c.setTimeout(function(){h.System.emit("gi.warning",{code:p.warning.MIDROLL_NO_HEARTBEAT,waited:e,occurrence:d});l()},e)});m.subscribe("ad.midroll.finish",function(){l()})}})},G=function(){if(!m.isFired("ad.preroll.finish")){var d=
a.preroll.maxWaitingTime;b=c.setTimeout(function(){h.System.emit("gi.warning",{code:p.warning.PREROLL_TIMEOUT,waited:d});q.transitionTo(q.states.WAITING_ON_USERDATA)},d)}},H=function(){c.clearTimeout(b);m.unsubscribeAll("ad.preroll.start");m.unsubscribeAll("ad.preroll.heartbeat");m.unsubscribeAll("ad.preroll.finish");var a=c.setTimeout(function(){h.System.emit("gi.warning",{code:p.warning.USER_DATA_NOT_RESPONDING})},5E3);m.isFired("ad.preroll.finish")||h.System.emit("gi.update",{code:p.update.ABORT_PREROLL});
h.System.emit("gi.update",{code:p.update.WAITING_FOR_USER_DATA});m.waiton("gi.userdata.ready",function(b){var d=q.states,e=d.INTEGRATING_GAME;a&&c.clearTimeout(a);!b.data||b.data.isError?e=d.INTEGRATION_ERROR:B=b.data;q.transitionTo(e)})},I=function(){var b,e=q.states.GAME_INTEGRATED,f=B.auth,g=a.game.settings,m=a.game.preloader;if(f&&d.isObject(f)&&!f.isError)for(b in f)f.hasOwnProperty(b)&&(g.flashvars+="&"+b+"="+f[b]);a&&a.portal&&a.portal.appToken&&(g.flashvars+="&appToken="+a.portal.appToken);
l(["LightSWFObject"],function(a){var b={data:g.movie,width:g.width,height:g.height},d={base:g.base,quality:"autohigh",allowFullScreen:g.allowFullScreen,wmode:g.wmode,allowScriptAccess:g.allowScriptAccess,scale:g.scale,flashVars:g.flashvars,bgcolor:g.bgcolor,hasPriority:"true"},f=function(){a.createSWF(b,d,g.domId);h.System.emit("gi.update",{code:p.update.GAME_EMBEDDED});q.transitionTo(e)};g.allowNetworking&&(d.allowNetworking=g.allowNetworking);t?(t=!1,a.removeSWF(m.domId),c.setTimeout(function(){f()},
20)):f()})};return q={states:{INITIALIZED:0,PLUGIN_DETECTION:1,FEATURE_DETECTION:10,PLUGIN_MISSING:2,FEATURE_MISSING:11,PRE_FETCHING_GAME:3,LISTENING_TO_ADVERTISING:4,WAITING_ON_PRE_ROLL:5,WAITING_ON_USERDATA:6,INTEGRATING_GAME:7,INTEGRATION_ERROR:8,GAME_INTEGRATED:9,UNKNOWN:9999},eventNamespace:"FSM.transition",transitionTo:function(a){h.Widget.emit(q.eventNamespace,{state:a})},flowController:function(b){var c=q.states;switch(b.data.state){case c.INITIALIZED:var f,g=q.states,l=g.LISTENING_TO_ADVERTISING,
m,n,r,t=!1;if(a&&(m=a.game,n=a.preroll,r=a.midroll),d.isObject(a)&&d.isObject(m)&&d.isObject(n)&&d.isObject(r)&&d.isString(m.type)&&(d.contains(m.type,"DomObject")||d.contains(m.type,"iframe"))&&d.isNumber(n.maxWaitingTime)&&d.isNumber(r.maxWaitingTime)&&d.isNumber(n.heartbeatTime)&&d.isNumber(r.heartbeatTime)&&(t=!0),!t)throw f={type:"InvalidArgument",message:"The provided integration configuration does not match the criteria."},SpilGames("tracker.event.track",{eventCategory:"jserror",eventAction:"game.integration.config.validation",
eventLabel:"GameIntegration module, exception:"+f.type+" - "+f.message,eventValue:1}),f;"DomObject"===a.game.type?l=g.PLUGIN_DETECTION:F()&&(l=g.FEATURE_DETECTION);q.transitionTo(l);break;case c.PLUGIN_DETECTION:A();break;case c.FEATURE_DETECTION:C();break;case c.PRE_FETCHING_GAME:x();break;case c.PLUGIN_MISSING:h.System.emit("gi.error",{code:p.error.PLUGIN_MISSING,pluginName:"flash"});h.System.emit("gi.update",{code:p.update.ABORT_PREROLL});break;case c.FEATURE_MISSING:h.System.emit("gi.error",{code:p.error.FEATURE_MISSING});
h.System.emit("gi.update",{code:p.update.ABORT_PREROLL});break;case c.LISTENING_TO_ADVERTISING:D();break;case c.WAITING_ON_PRE_ROLL:G();break;case c.WAITING_ON_USERDATA:H();break;case c.INTEGRATING_GAME:"DomObject"===a.game.type&&I();if("iframe"===a.game.type){f=q.states.GAME_INTEGRATED;b=a.game.settings;m=e.getElementById(b.domId);n={};d.isObject(B.auth)&&(n=d.combine(B.auth,n));d.isObject(a.portal)&&a.portal.siteId&&a.portal.channelId&&(n=d.combine({siteid:a.portal.siteId,channelid:a.portal.channelId,
UID:a.portal.sgid||""},n),n=a.portal.authenticated&&!0===a.portal.authenticated?d.combine({hash:a.portal.appToken||"",username:a.portal.username||""},n):d.combine({hash:"",username:""},n));d.isObject(B.other)&&(n=d.combine(B.other,n));m.width=b.width;m.height=b.height;r="";b=b.url.replace("###DOMAIN###",window.location.hostname);b=b.replace("###CACHE_PP###","");c=document.createElement("a");b=(c.href=b,t="/"===c.pathname.charAt(0)?c.pathname:"/"+c.pathname,{protocol:c.protocol,hostname:c.hostname,
port:c.port,pathname:t,search:c.search,hash:c.hash,host:c.host});for(l in n)n.hasOwnProperty(l)&&(r+="&"+l+"="+n[l]);l=(g=b.protocol+"//"+b.host+b.pathname||"",g+=0<b.search.length?encodeURI(b.search+r):"?"+encodeURI(r.substring(1)),g+(b.hash||""));m.src=l;h.System.emit("gi.update",{code:p.update.GAME_EMBEDDED});q.transitionTo(f)}break;case c.INTEGRATION_ERROR:h.System.emit("gi.error",{code:p.error.USER_DATA_MISSING});break;case c.GAME_INTEGRATED:document.getElementById("sgAdOgGp300x250")&&E(),s.emit("gi.game.loaded")}},
start:function(){h.Widget.init(q.flowController)}},{init:function(b){if(a=b,a.game.objectSettings&&(a.game.settings=a.game.objectSettings),r)throw{type:"IllegalOperation",message:"It is not allowed to start the game integration more than once, as there can only be one game per page"};r=!0;h.init("game");m.init();q.start();h.System.emit("gi.update",{code:p.update.INITIALIZED});q.transitionTo(q.states.INITIALIZED)},eventCodeMap:p}}),l}(window,document)});
SpilGames("spilgames.import",{name:"GIFeedback",deps:"Utils SWP StopWatch Cache JSLib GIController".split(" "),module:function(c,e){var l,r=!1;return l||(l=function(l,d,h,s,v,n){var f,q={backgroundScreen:e.getElementById("backgroundScreen"),defaultScreen:e.getElementById("defaultLoadingScreen"),waitingForUserData:e.getElementById("waitingForUserData"),userDataNotResponding:e.getElementById("userDataNotResponding"),userDataMissing:e.getElementById("userDataMissing"),loadingDomObjectGame:e.getElementById("loadingDomObjectGame"),
loadingIframeGame:e.getElementById("loadingIframeGame"),errorLoadingGame:e.getElementById("errorLoadingGame"),missingPlugin:e.getElementById("missingPlugin"),missingFeature:e.getElementById("missingFeature"),displayGame:e.getElementById("theGame"),preRoll:e.getElementById("videoPreroll300x250"),midRoll:e.getElementById("sgAdOgGp300x250"),midrollLoading:e.getElementById("midrollLoadingScreen")},b=e.getElementById("game-integration"),a={},B=[],p=["displaygame","afterpreroll","onmidroll","aftermidroll"],
g=q.defaultScreen,t={},m=!1,u=function(a){g.className=g.className.replace("activeFeedbackScreen","");g=q[a];g.className+=" activeFeedbackScreen"},F=function(){v.subscribe("game.ad.accepted",function(a){l.isObject(a)&&!0===a.displayAd&&l.isString(a.bgImage)&&!l.isEmpty(a.bgImage)&&(f=a.bgImage)})},A=function(a){var b=B[a];b&&l.each(b,function(a,d){a.persistent&&!0===a.persistent||delete b[d];c.setTimeout(function(){a.callback()},0)})},C=function(){var a=c.performance||c.msPerformance||c.webkitPerformance||
c.mozPerformance||!1;return a&&a.timing&&a.timing.navigationStart?function(){return a.timing.navigationStart}:function(){return null}}(),x=function(){if(!m){m=!0;u("displayGame");A("displaygame");try{F();d.System.emit("gi.portal.feedback",{displayGame:a.portal.contentarId});var b=C();b&&d.System.emit("gi.portal.feedback",{timeToPlay:h.now()-b});s.getItem("ttfp",function(a){a&&!1===a.send&&(s.setItem({key:"ttfp",value:{sessionStart:a.sessionStart,send:!0},expires:0}),d.System.emit("gi.portal.feedback",
{timeToFirstPlay:h.now()-a.sessionStart}))})}catch(c){}}},D=function(){var b,c=e.getElementById(a.game.settings.domId),f=e.getElementById("progress-container"),g=function(){try{(b=h.stop("iframeLoadDuration"))&&d.System.emit("gi.portal.feedback",{loadDuration:b})}catch(a){}x()};h.start("iframeLoadDuration");c.completed?x():(f&&(f.style.display="none"),u("loadingIframeGame"),c.attachEvent?c.attachEvent("onload",function(){g()}):c.onload=function(){g()})},E=function(){var b,f,g,l,m=e.getElementById(a.game.settings.domId),
k=e.getElementById("progress-bar"),n=e.getElementById("progress-percentage"),p=0,q=function(){return m&&"function"==typeof m.PercentLoaded||c.attachEvent&&"number"==typeof m.PercentLoaded()},r=function(){if(g=m.PercentLoaded(),98<g||0>g)x();else{u("loadingDomObjectGame");k.width=g+"%";n&&(n.innerHTML=g+"%");try{h.start("progressBarDuration"),d.System.emit("gi.portal.feedback",{progressBarStart:g})}catch(a){}b=c.setInterval(function(){if(g=q()?m.PercentLoaded():void 0,void 0!==g&&-1<g&&100>g)n&&(n.innerHTML=
g+"%"),k.style.width=g+"%";else{c.clearInterval(b);n&&(n.innerHTML="100%");k.style.width="99%";c.setTimeout(function(){x()},500);try{(f=h.stop("progressBarDuration"))&&d.System.emit("gi.portal.feedback",{progressBarDuration:f+500})}catch(a){}}},100)}};try{l=c.setInterval(function(){p+=1;q()&&(c.clearInterval(l),r());10<=p&&(c.clearInterval(l),x(),d.System.emit("gi.portal.feedback",{progressBarError:a.portal.contentarId}))},100)}catch(s){x(),d.System.emit("gi.portal.feedback",{progressBarError:a.portal.contentarId})}};
return{init:function(c){r||(r=!0,a=c,t=n.eventCodeMap,d.init("game"),d.System.init(function(c){switch(c.name){case "gi.update":var e,g=t.update;c=c.data;switch(c.code){case g.WAITING_FOR_USER_DATA:u("waitingForUserData");try{var l=h.stop("prerollDisplayDuration");l&&d.System.emit("gi.portal.feedback",{prerollDisplayDuration:l})}catch(k){}A("afterpreroll");break;case g.PREROLL_FAKE_START:u("preRoll");break;case g.PREROLL_ALIVE:u("preRoll");try{(e=C())&&d.System.emit("gi.portal.feedback",{timeToPreroll:h.now()-
e}),h.start("prerollDisplayDuration")}catch(m){}break;case g.MIDROLL_REQUESTED:f&&(q.backgroundScreen.style.cssText="background-image: url("+f+");",491<parseInt(q.displayGame.style.height,10)&&(b.style.height=q.displayGame.style.height),q.backgroundScreen.style.display="block",f=void 0);u("midrollLoading");try{A("onmidroll")}catch(n){}break;case g.MIDROLL_ALIVE:u("midRoll");try{h.start("midrollDisplayDuration"),e=C(),c.occurrence&&1===c.occurrence&&e&&d.System.emit("gi.portal.feedback",{timeToFirstMidroll:h.now()-
e})}catch(p){}break;case g.MIDROLL_FINISHED:"block"===q.backgroundScreen.style.display&&(q.backgroundScreen.style.background="#FFF",q.backgroundScreen.style.display="none");b.style.height="auto";u("displayGame");try{A("aftermidroll");var r=h.stop("midrollDisplayDuration");r&&d.System.emit("gi.portal.feedback",{midrollDisplayDuration:r})}catch(s){}break;case g.GAME_EMBEDDED:"DomObject"===a.game.type&&E(),"iframe"===a.game.type&&D()}break;case "gi.error":e=t.error;switch(c.data.code){case e.USER_DATA_MISSING:u("userDataMissing");
break;case e.PLUGIN_MISSING:u("missingPlugin");break;case e.FEATURE_MISSING:u("missingFeature")}break;case "gi.warning":c.data.code===t.warning.USER_DATA_NOT_RESPONDING&&u("userDataNotResponding")}},!0))},onState:function(a,b,c){0<=l.indexOf(p,a)&&(B[a]||(B[a]=[]),B[a].push({callback:b,persistent:c}))}}}),l}(window,window.document)});
SpilGames("spilgames.import",{name:"GIMonitor",deps:"SWP EventTracker GIController JSLib Net Utils".split(" "),module:function(){var c,e=!1;return c?void 0:c=function(c,r,z,d,h,s){var v=z.eventCodeMap,n={},f=function(b,a,c){s.isObject(window._gaq)&&window._gaq.push&&(window._gaq.push(["_trackEvent","gameIntegration",b,a,c,!0]),window._gaq.push(["aggregated._trackEvent","gameIntegration",b,a,c,!0]));var e=s.contains("timeToPlay timeToFirstPlay timeToPreroll prerollFetchTime prerollDisplayDuration progressBarStart progressBarDuration loadingScreenDuration midrollDisplayDuration timeToFirstMidroll midrollFetchTime".split(" "),
a),f=e?"ms":"c",e=e?c:1,l=document.location.host.replace("www.","").replace(RegExp(/\./g),"-"),m="/gc/pb/?data[prod.syseng.performance.gameIntegration."+l+"."+b+"."+a+"]="+e+f;n.monitoring&&n.monitoring.bucket&&(m+="&data[prod.syseng.performance.gameIntegration."+l+"."+n.monitoring.bucket+"."+b+"."+a+"]="+e+f);0<e&&("c"===f?1===e:1)&&h.send({url:m,type:"GET"},s.emptyFn);d("tracker.event.track",{eventCategory:"gameIntegration",eventAction:b,eventLabel:a,eventValue:c})},q={error:function(b){var a=v.error;
b=b.data;switch(b.code){case a.USER_DATA_MISSING:f("error","userDataMissing");break;case a.PLUGIN_MISSING:a=b.pluginName.charAt(0).toUpperCase()+b.pluginName.slice(1);f("error","missing"+a+"Plugin");break;case a.FEATURE_MISSING:f("error","missingBrowserFeature")}},warning:function(b){var a=v.warning;b=b.data;switch(b.code){case a.USER_DATA_NOT_RESPONDING:f("warning","userDataNotResponding",5E3);break;case a.PRE_FETCH_ERROR:f("warning","prefetchError",b.flashError.code);break;case a.PREROLL_NO_HEARTBEAT:f("warning",
"prerollNoHeartbeat",b.waited);break;case a.PREROLL_TIMEOUT:f("warning","prerollTimeout",b.waited);break;case a.MIDROLL_NO_HEARTBEAT:f("warning","midrollNoHeartbeat",b.waited);break;case a.MIDROLL_TIMEOUT:f("warning","midrollTimeout",b.waited)}},update:function(b){var a=v.update;b=b.data;switch(b.code){case a.PREROLL_ALIVE:b.fetchTime&&f("update","prerollFetchTime",b.fetchTime);break;case a.MIDROLL_ALIVE:b.fetchTime&&f("update","midrollFetchTime",b.fetchTime);break;case a.INITIALIZED:f("update","initialized")}}};
return{init:function(b){(n=b,e)||(e=!0,c.init("game"),b=window.publishingHost,void 0===b?f("update","publishingHostUndefined",b):"unknown"===b?f("update","publishingHostUnknown",b):f("update","publishingHostOk",b),c.System.init(function(a){switch(a.name){case "gi.error":q.error(a);break;case "gi.warning":q.warning(a);break;case "gi.update":q.update(a);break;case "gi.portal.feedback":a=a.data;a.timeToPlay&&f("update","timeToPlay",a.timeToPlay);a.displayGame&&f("update","displayGame",a.displayGame);
a.prerollDisplayDuration&&f("update","prerollDisplayDuration",a.prerollDisplayDuration);a.timeToPreroll&&f("update","timeToPreroll",a.timeToPreroll);a.midrollDisplayDuration&&f("update","midrollDisplayDuration",a.midrollDisplayDuration);a.timeToFirstMidroll&&f("update","timeToFirstMidroll",a.timeToFirstMidroll);a.timeToFirstPlay&&f("update","timeToFirstPlay",a.timeToFirstPlay);a.progressBarStart&&f("update","progressBarStart",a.progressBarStart);a.progressBarDuration&&f("update","progressBarDuration",
a.progressBarDuration);a.progressBarError&&f("warning","progressBarError",a.progressBarError);a.loadDuration&&f("update","loadingScreenDuration",a.loadDuration);break;case "gi.userdata.failure":if(a.data&&a.data.action)switch(a.data.action){case "decodeCookie":f("warning","decodeAuthCookieFailure");break;case "appToken":f("error","appToken");break;case "getCurrentUser":f("error","getCurrentUser")}}},!0))}}}}()});
SpilGames("spilgames.import",{name:"GIUserData",deps:["SWP","JSLib","Utils","Cache","SocialGateway"],module:function(){var c,e=!1;return c||(c=function(c,r,z,d,h){var s,v=function(c){var d;z.isObject(s.portal);SpilGames("api.account.getToken",{cache:!0},function(b){b&&b.auth&&b.auth.token?r("api.user.get",{cache:!0},function(a){d=a&&a.userInfo?{username:a.userInfo.name,hash:b.auth.token}:{isError:!0,message:"Failed to retrieve the user's name",error:a&&a.error||"unknown error"};c.call(this,d)}):(d=
{isError:!0,message:"Failed to retrieve the user hash",error:b&&b.error||"unknown error"},c.call(this,d))})},n=function(c){var d={};r("api.account.getApplicationToken",{cache:!0,applicationId:""+(s.portal.applicationId||s.portal.contentarId)},function(b){try{if(!b.appAuth||b.isError)return SpilGames.Events.publish("auth.login",{status:"failed"}),c({isError:!0,action:"appToken",error:"Failed to retrieve application token",realError:b.error}),void 0;var a=b.appAuth.token;d.appToken=a;h.updateCache(a,
s.portal.sgid);h.getUserInfo(function(a,b,e){a?c(d):c({isError:!0,action:"getCurrentUser",error:"Failed to retrieve user data (from SG)",realError:e})})}catch(e){c({isError:!0,action:"appToken",error:"Get app token JS error",realError:e})}})};return{init:function(d){if(s=d,!e)switch(e=!0,c.init("game"),s.game.needs){case "preliminaryAuth":v(function(d){c.System.emit("gi.userdata.ready",{auth:d})});break;case "auth":h.setSocialGatewayInfo(s.portal.siteId,s.portal.channelId);n(function(d){var b={auth:d},
a;a:{var e,f,g;e=window;var h=e.location.href.slice(e.location.href.indexOf("?")+1).split("&"),m=h.length;for(g=0;m>g;g+=1)if(a=h[g].split("="),f=a[0],e=a[1],"src"===f){a=e;break a}a=null}a&&(b.other={src:a});d.isError&&(b.isError=!0,c.System.emit("gi.userdata.failure",d));c.System.emit("gi.userdata.ready",b)});break;default:c.System.emit("gi.userdata.ready",{})}}}}),c}()});
//# sourceMappingURL=wdg_game-c740f0f40f78b938e62aa4edd1477bf06a5f9841.js.map
