/*
 2013, SpilGames
*/
SpilGames("spilgames.import",{fullName:"GameComments",deps:"SWPUtils DOMSelect DOMEvent JSLib TimeAgo Emoticons".split(" "),module:function(c,b,a,e,C,u){function y(a,d){var b=Array.prototype.slice.call(arguments,2);return function(){a.apply(d,b.concat(arguments))}}function D(a,d,c){e("api.user.get",{username:b.get(l.user).innerHTML.toString()},function(b){f&&(f.innerHTML="");q.value="";x.innerHTML=s;z(a.messageId,d,c,b.userInfo)})}function z(a,d,c,n,g){g=g||!1;m=b.get(l.commentsList);var e=m.getElementsByTagName("li")[0],
h=A.cloneNode(!0),f=Date.parse(new Date)/1E3;h.id="comment-"+a;b.get(".comments-first",m)&&(e.style.display="none");"0"==n.guid?n.avatarUrl="http://static1.spilcdn.com/tw/img/_/profile/dummy_small.png":(h.setAttribute("data-username",n.name),b.get(".friend-request",h).setAttribute("data-toadd",n.name));u.init(b.get("#emoticon-base-url").value);b.get(".media-thumb img",h).src=n.avatarUrl;if(e=b.get(".media-thumb .hoverHidden img",h))e.src=n.avatarLargeUrl;b.get(".game-comments-title",h).innerHTML=
n.name;b.get(".game-comments-content",h).innerHTML=u.insert(d);b.get(".game-comments-time-units",h).setAttribute("data-timestamp",f);b.get(".game-comments-time-units",h).innerHTML=c;if(g){d=b.get(".game-comments-time .report-btn",h);d.setAttribute("data-commentid",a);d.setAttribute("href","#comment-"+a);var k=b.get(".game-comments-time .reported-txt",h);B([d],function(a,d){d.style.display="none";k.style.display="block"});a=b.get(".media-thumb",h);d=b.get(".game-comments-title",h);n=a.getAttribute("href").replace("##USER##",
n.name);a.setAttribute("href",n);d.setAttribute("href",n);h.className=b.get(".odd-row:last-child",m)?"media":"media odd-row";m.insertBefore(h,m.lastChild)}else m.scrollTop=0,h.className=b.get(".odd-row:first-child",m)?"media":"media odd-row",m.insertBefore(h,m.firstChild);return h}function B(b,d){b&&0<b.length&&c.each(b,function(b,c){a.add(b,"click",y(function(b,c,p){a.preventDefault(p);e("api.comment.report",{messageId:b.getAttribute("data-commentid")},function(a){d(a,b,c)})},void 0,b,c))})}var r,
l,v,m,A,f,q,x,s=160,k,w,t=1,g;return{init:function(a){r=this;l=a;v=b.get(a.frm);m=b.get(a.commentsList);A=b.get(a.sampleItem);f=b.get(a.txtArea);q=b.get(a.HidTxtArea);x=b.get(a.charDisplay);b.get(a.user);k=a.totItems;w=a.itemsPerBatch;g=b.get(a.getBatchButton);return r},limitChars:function(){f?(a.add(l.txtArea,"keydown",function(b){var d=f.innerText||f.textContent,c=f.getElementsByTagName("img"),c="undefined"===typeof c?0:c.length;if("undefined"===typeof d||null===d)d=" ";c+d.length>=s&&8!==b.keyCode&&
46!==b.keyCode&&(a.preventDefault(b),a.stopPropagation())}),a.add(l.txtArea,"keyup",function(a){a=f.innerText||f.textContent;var b=f.getElementsByTagName("img"),b="undefined"===typeof b?0:b.length;if("undefined"===typeof a||null===a)a=" ";x.innerHTML=s-(a.length+b)})):q&&(a.add(l.HidTxtArea,"keydown",function(b){q.value.length>=s&&8!==b.keyCode&&46!==b.keyCode&&a.preventDefault(b)}),a.add(l.HidTxtArea,"keyup",function(a){x.innerHTML=s-q.value.length}))},postComment:function(b){v&&a.add(l.frm,"submit",
function(d){a.preventDefault(d);if(f){var c=f.getElementsByTagName("img");d=f.innerHTML;for(c=c.length-1;0<=c;c--){var n=/<img[^>]*alt="([^"]+)"[^>]*>/,g=n.exec(d);"undefined"!==typeof g[1]&&null!==g[1]&&(d=d.replace(n,g[1]))}f.innerHTML=d;d=f.textContent;void 0===d&&(d=f.innerText);v.comment.value=d}var k=v.comment.value,h=v.appid.value;e("api.comment.application",{applicationId:h,message:k},function(a){b.call(this,a,k,h)})})},insertSmilie:function(a,b){var c=f.innerText||f.textContent,g=f.getElementsByTagName("img"),
g="undefined"===typeof g?0:g.length;if(g+c.length<=s){var e=document.createElement("img");e.src=a;e.alt=b;e.title=b;e.className="com-smile";f.appendChild(e);q.value+=b;x.innerHTML=s-(c.length+g)}},refreshList:function(a,b,c){D(a,b,c)},getFriends:function(a){e("api.friend.list",function(b){e("api.friend.pending",function(c){b&&b.friendList&&c&&c.sentList?a.call(this,b.friendList,c.sentList):a.call(this,[],[])})})},updateFriendStatus:function(a,d,g,e){c.each(a,function(a,f){var h=a.getAttribute("data-username"),
p=!1,k=!1,m=!1,l=!1;-1!==c.indexOf(g,h)&&(p=!0);-1!==c.indexOf(e,h)&&(k=!0);h===d&&(l=!0);"unknown"==h&&(m=!0);l||p||k||m?l||p||!k||(h=b.get(".friend-request-sent",a),p=b.get(".friend-request",a),h&&(h.style.display="block"),p&&(p.style.display="none")):(h=b.get(".friend-request-sent",a),p=b.get(".friend-request",a),h&&(h.style.display="none"),p&&(p.style.display="block"))})},sendFriendRequest:function(a,b){e("api.user.get",{username:a},function(a){a&&a.userInfo&&a.userInfo.guid?e("api.friend.request",
{guid:a.userInfo.guid},function(a){a&&a.friendStatus&&"sent"===a.friendStatus?b.call(!0,"friend request sent successfully"):b.call(!1,"could not send friend request")}):b.call(this,!1,"could not retrieve user info")})},getNextBatch:function(a){c.addClass(g,"processing");var b={applicationId:v.appid.value,pageControl:{page:++t,pageSize:w}},f=0;e("api.application.comments",b,function(b){var d=[];if(b&&b.messageList){b&&b.pageControl&&(k=b.pageControl.totalItems);var e=!0,h;for(f=0;f<b.messageList.length;f++){var l=
z(b.messageList[f].messageId,b.messageList[f].message,C.timeDifference(1E3*b.messageList[f].created),b.messageList[f].userInfo,!0);d.push(l);e&&(h=l);e=!1}h.scrollIntoView()}c.removeClass(g,"processing");(50<=t||w*t>=k)&&c.addClass(g,"hidden");a(d)})},reportComment:function(a,b){B(a,b)}}}});/*
 2013, SpilGames
*/
SpilGames("spilgames.import",{fullName:"Emoticons",deps:[],module:function(){var c="",b=[{targets:[":d",":D",":-d",":-D"],replacement:"kolobok_biggrin.gif"},{targets:[":)",":-)"],replacement:"kolobok_smile.gif"},{targets:[";)",";-)"],replacement:"kolobok_wink.gif"},{targets:[":(",":-("],replacement:"kolobok_sad.gif"},{targets:[":O",":-o",":-O"],replacement:"kolobok_surprised.gif"},{targets:[":0",":-0"],replacement:"kolobok_eek.gif"},{targets:[":?",":-?"],replacement:"kolobok_confused.gif"},{targets:["8)",
"8-)"],replacement:"kolobok_cool.gif"},{targets:[":x",":X",":-x",":-X"],replacement:"kolobok_mad.gif"},{targets:[":p",":P",":-p",":-P"],replacement:"kolobok_razz.gif"},{targets:[":oops:"],replacement:"kolobok_redface.gif"},{targets:[":|",":-|"],replacement:"kolobok_neutral.gif"},{targets:[":lol:"],replacement:"kolobok_lol.gif"},{targets:[":cry:"],replacement:"kolobok_cry.gif"},{targets:[":evil:"],replacement:"kolobok_evil.gif"},{targets:[":twisted:"],replacement:"kolobok_twisted.gif"},{targets:[":roll:"],
replacement:"kolobok_rolleyes.gif"},{targets:[":!:"],replacement:"kolobok_exclaim.gif"},{targets:[":ask:"],replacement:"kolobok_question.gif"},{targets:[":idea:"],replacement:"kolobok_idea.gif"},{targets:[":arrow:"],replacement:"kolobok_arrow.gif"},{targets:[":mrgreen:"],replacement:"kolobok_mrgreen.gif"},{targets:[":geek:"],replacement:"kolobok_geek.gif"},{targets:[":ugeek:"],replacement:"kolobok_ugeek.gif"}];return{init:function(a){c=a},insert:function(a){var e=a;b.map(function(a){a.targets.map(function(b){RegExp.quote=
function(a){return a.replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")};var y=RegExp(RegExp.quote(b),"g");e=e.replace(y,'<img src="'+c+"/"+a.replacement+'" alt="'+b+'" title="'+b+'" style="display: inline;" />')})});return e}}}});/*
 2013, SpilGames
*/
SpilGames("spilgames.import",{fullName:"TimeAgo",deps:[],module:function(){return{timeDifference:function(c){var b=(new Date).getTime()-c;c="";c="undefined"===typeof spilgames_api.siteid?79:spilgames_api.siteid;var a=[,["seconden","minuten","uur","uren","dag","dagen","maand","jaar","geleden",0],,,,["sekunden","minuten","stunde","stunden","tag","tagen","monat","jahr","vor",1]];a[11]=["secondes","minutes","heure","heures","jour","jours","mois","ann\u00e9e","Il y a",1];a[15]=["secondi","minuti","ora",
"ore","giorni","giorni","mese","anno","fa",0];a[16]=["sekund","minut","godzin\u0119","godzin","dzie\u0144","dni","miesi\u0105ce","rok","temu",0];a[44]=["sekunder","minuter","timme","timmar","dag","dagar","m\u00e5nad","\u00e5r","sedan",0];a[50]=["segundos","minutos","hora","horas","d\u00eda","d\u00edas","m\u00eas","ano","atr\u00e1s",0];a[86]=["segundos","minutos","hora","horas","d\u00eda","d\u00edas","mes","a\u00f1o","hace",1];a[88]=["seconds","minutes","hour","hours","day","days","month","year","ago",
0];a[103]=["\u0441\u0435\u043a\u0443\u043d\u0434","\u043c\u0438\u043d\u0443\u0442","\u0447\u0430\u0441","\u0447\u0430\u0441\u043e\u0432","\u0434\u0435\u043d\u044c","\u0434\u043d\u0435\u0439","\u043c\u0435\u0441\u044f\u0446\u0435\u0432","\u0433\u043e\u0434","\u043d\u0430\u0437\u0430\u0434",0];a[140]=["detik","menit","jam","jam","hari","hari","bulan","tahun","yang lalu",0];a[157]=["saniye","dakika","saat","saat","g\u00fcn","g\u00fcnler","ay","y\u0131l","evvel",0];a[25]=a[1];a[26]=a[5];a[138]=a[15];
a[108]=a[44];a[87]=a[50];a[97]=a[86];a[105]=a[103];a[12]=a[11];a[79]=a[88];a[92]=a[88];a[55]=a[140];void 0===typeof a[c]&&(a[c]=a[88]);if(6E4>b)c=1==a[c][9]?a[c][8]+" "+Math.round(b/1E3)+" "+a[c][0]:Math.round(b/1E3)+" "+a[c][0]+" "+a[c][8];else if(36E5>b)c=1==a[c][9]?a[c][8]+" "+Math.round(b/6E4)+" "+a[c][1]:Math.round(b/6E4)+" "+a[c][1]+" "+a[c][8];else if(864E5>b){var b=Math.round(b/36E5),e=1==b?a[c][2]:a[c][3];c=1==a[c][9]?a[c][8]+" "+b+" "+e:b+" "+e+" "+a[c][8]}else 2592E6>b?(b=Math.round(b/
864E5),e=1==b?a[c][4]:a[c][5],c=1==a[c][9]?a[c][8]+" "+b+" "+e:b+" "+e+" "+a[c][8]):c=31536E6>b?1==a[c][9]?a[c][8]+" "+Math.round(b/2592E6)+" "+a[c][6]:Math.round(b/2592E6)+" "+a[c][6]+" "+a[c][8]:1==a[c][9]?a[c][8]+" "+Math.round(b/31536E6)+" "+a[c][7]:Math.round(b/31536E6)+" "+a[c][7]+" "+a[c][8];return c}}}});SpilGames({name:"wdg_game_comments",waiton:"spilgames.loaded"},"SWPUtils SWP DOMSelect DOMEvent JSLib GameComments TimeAgo Emoticons".split(" "),function(c,b,a,e,C,u,y,D){b.init("game_comments");var z,B,r=a.getAll("#comments-list li.media"),l=a.getAll("#tot_items").value||0,v=a.getAll("#items_per_batch").value||5,m=a.getAll("#comments-list .report-btn"),A=a.getAll("#comments-list .reported-txt"),f=a.getAll(".friend-request"),q=a.get("#current-user").value||"",x=a.get("#comments-default-timestamp")?
a.get("#comments-default-timestamp").value:"Just now";y=a.getAll(".game-comments-time-units");var s="true"===C.get("spilgames.portal.user.authenticated")?!0:!1,k=u.init({frm:"form#game-comments-form",txtArea:"div#div-msg-box",HidTxtArea:"textarea#msg-box",charDisplay:"div.chars-left em",sampleItem:"ul#comments-list-sample li",commentsList:"ul#comments-list",user:"span.game-comments-username",totItems:l,itemsPerBatch:v,getBatchButton:"#more_comments"}),w=[],t=[];D.init(a.get("#emoticon-base-url").value);
for(u=0;u<r.length;u++)l=a.get(".game-comments-content",r[u]),l.innerHTML=D.insert(l.innerHTML);C.subscribe("wdg_game_comments.ready",function(){z=a.get("#comments-join-button-nav");B=a.get("#comments-login-button-nav");z&&B&&(e.add("#comments-login-button-nav","click",function(a){e.preventDefault(a);b.System.emit("popup.login.open")}),e.add("#comments-join-button-nav","click",function(a){e.preventDefault(a);b.System.emit("popup.register.open")}));e.add("#more_comments","click",function(g){e.preventDefault(g);
k.getNextBatch(function(g){r=a.getAll("#comments-list li.media");m=a.getAll("#comments-list .report-btn");A=a.getAll("#comments-list .reported-txt");s&&(k.updateFriendStatus(r,q,w,t),c.each(g,function(c){a.get(".friend-request",c).onclick=function(a){e.preventDefault(a);a=this.getAttribute("data-toadd");b.Widget.emit("friend.request.send",{toadd:a})}}))})});var g=a.get("#icons");if(g)for(var g=g.getElementsByTagName("img"),f=0;f<g.length;f++)e.add("#"+g[f].id,"click",function(a){k.insertSmilie(this.src,
this.title)});document.addEventListener||(g=document.getElementById("more_comments"),null!==g&&(g.className="hideMe"));if(Object.hasOwnProperty.call(window,"ActiveXObject")||window.ActiveXObject)g=document.getElementById("showicons"),null!==g&&(g.className="hideMe")});c.each(y,function(a){var b=a.getAttribute("data-timestamp");a.innerHTML=(new Date(1E3*b)).toLocaleString()});s&&0<r.length&&k.getFriends(function(a,l){var d;for(d=0;d<a.length;d++)w.push(a[d].name);for(d=0;d<l.length;d++)t.push(l[d].name);
k.updateFriendStatus(r,q,w,t);c.each(f,function(a){a.onclick=function(a){e.preventDefault(a);a=this.getAttribute("data-toadd");b.Widget.emit("friend.request.send",{toadd:a})}})});0<r.length&&k.reportComment(m,function(a,b,c){b.style.display="none";A[c].style.display="block"});k.limitChars();k.postComment(function(a,c,d){a&&a.result?b.Widget.emit("game.comments.refresh",{res:a,message:c,label:x}):b.Widget.emit("game.comments.postfailed")});b.Widget.init(function(b){switch(b.name){case "game.comments.refresh":k.refreshList(b.data.res,
b.data.message,b.data.label);break;case "game.comments.postfailed":a.get("#post-comment-error").style.display="";break;case "friend.request.send":b.data&&b.data.toadd&&k.sendFriendRequest(b.data.toadd,function(a,c){a&&(t.push(b.data.toadd),k.updateFriendStatus(r,q,w,t))})}});b.System.init(function(a){c.debug("wdg_game_comments received system event ",a)})});
//# sourceMappingURL=/wdg/game_comments-active/js/minified/wdg_game_comments.js.map
