
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /><meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate,max-age=-1" /><meta http-equiv="Pragma" content="no-cache" /><meta http-equiv="Expires" content="-1" /><meta name="description" content="Bella Sara is a magical world where children can play games, activate trading cards, and take care of horses online." /><meta name="keywords" content="collectable card game, trading cards, online children's games, magical horses, fantasy horses, equines, magical world, horses, horseshoes, interact with online horses, girl games, Bella Sara, magical friends, safe online children's games, play online, bellasara.com.mx, bellasara.com, bellasara.ch, bellasara.co.uk, bellasara.cz, bellasara.ca, bellasara.hr, bellasara.za, bellasara.se, bellasara.au, bellasara.fr, bellasara.de, bellasara.it, bellasara.com.au, bellasara.be, bellasara.sl, bellasara.cl, bellasara.fi, bellasara.dk, bellasara.no, bellasara.nl" /><meta name="robots" content="Index, Follow" /><meta name="revisit-after" content="7 days" /><title>
	Welcome to the World of Bella Sara
</title>
    <script src="" type="text/javascript"></script>
	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /><link href="App_Themes/q4/activation.css" type="text/css" rel="stylesheet" /><link href="App_Themes/q4/dropdown-EN.css" type="text/css" rel="stylesheet" /><link href="App_Themes/q4/global.css" type="text/css" rel="stylesheet" /><link href="App_Themes/q4/reset.css" type="text/css" rel="stylesheet" /><link href="App_Themes/q4/signup.css" type="text/css" rel="stylesheet" /><link href="App_Themes/q4/store.css" type="text/css" rel="stylesheet" /></head>
<body>
    <div id="flash-container">
        <form name="aspnetForm" method="post" action="login.aspx?ReturnUrl=%2fcottageentry.aspx" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJNDc3NDk0MzY2D2QWAmYPZBYCAgEPZBYGAgMPZBYEAgMPDxYCHgRUZXh0BSNZb3UgbXVzdCBsb2cgaW4gdG8gdmlzaXQgdGhpcyBwYWdlIWRkAg0PZBYCZg9kFgYCAQ8PFgIfAAUJVXNlciBOYW1lFgQeB29uZm9jdXMFQGlmICh0aGlzLnZhbHVlID09ICdVc2VyIE5hbWUnKSB7IHRoaXMudmFsdWUgPSAnJzsgfSByZXR1cm4gdHJ1ZTseBm9uYmx1cgVAaWYgKHRoaXMudmFsdWUgPT0gJycpIHsgdGhpcy52YWx1ZSA9ICdVc2VyIE5hbWUnOyB9IHJldHVybiB0cnVlO2QCAw8PZBYGHwEFP2lmICh0aGlzLnZhbHVlID09ICdQYXNzd29yZCcpIHsgdGhpcy52YWx1ZSA9ICcnOyB9IHJldHVybiB0cnVlOx8CBT9pZiAodGhpcy52YWx1ZSA9PSAnJykgeyB0aGlzLnZhbHVlID0gJ1Bhc3N3b3JkJzsgfSByZXR1cm4gdHJ1ZTseBXZhbHVlBQhQYXNzd29yZGQCCQ8PZBYEHgtvbm1vdXNlb3ZlcgUjdGhpcy5jbGFzc05hbWU9J3NpZ25pbi1jaGVjay1ob3ZlciceCm9ubW91c2VvdXQFHXRoaXMuY2xhc3NOYW1lPSdzaWduaW4tY2hlY2snZAIFDxYCHgdWaXNpYmxlaGQCCQ9kFhRmDxYCHwAFIyZjb3B5OyAyMDA4IEhpZGRlbiBDaXR5IEdhbWVzLCBJbmMuZAIBDxYCHwAFqAFBbGwgUmlnaHRzIFJlc2VydmVkLiBBbGwgdHJhZGVtYXJrcyBhbmQgDQoJICAgICAgICAgICAgICAgICAgICBjaGFyYWN0ZXIgbmFtZXMgYW5kIHRoZWlyIGRpc3RpbmN0aXZlIGxpa2VuZXNzZXMgYXJlIHByb3BlcnRpZXMgb2YgY29uY2VwdGNhcmQsIGluIERlbm1hcmsgYW5kIGVsc2V3aGVyZS5kAgIPZBYCZg8WAh8ABRFEYWlseSBUaW1lIExpbWl0OmQCAw8WAh8ABWY8YSBjbGFzcz0iZ2xvYmFsLWxvd2VybmF2LWxpbmsiIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vcHJlc3Nyb29tLmJlbGxhc2FyYS5jb20iPlByZXNzcm9vbTwvYT4gfCBkAgQPFgIfAAUHUHJvZmlsZWQCBQ8WAh8ABQNGQVFkAgYPFgIfAAUHUGFyZW50c2QCBw8WAh8ABQVMZWdhbGQCCA8WAh8ABQRIZWxwZAIJDxYCHwAFBkxvZyBJbmRkfrpcHJb6zrLJawnBigHEsSnxQ7s=" />


<script src="Utility/loadFlash.js" type="text/javascript"></script>
<script src="Utility/swfobject.js" type="text/javas